/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DesafioDiarioRouteImport } from './routes/desafio-diario'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiSolveQuestionRouteImport } from './routes/api/solve-question'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardAdminFinanceRouteImport } from './routes/dashboard/admin-finance'
import { Route as DashboardAdminMediaRouteImport } from './routes/dashboard/admin-media'
import { Route as DashboardAdminMetricsRouteImport } from './routes/dashboard/admin-metrics'
import { Route as DashboardAdminQuestionsRouteImport } from './routes/dashboard/admin-questions'
import { Route as DashboardAdminSignupsRouteImport } from './routes/dashboard/admin-signups'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard/admin-students'
import { Route as DashboardAiSolverRouteImport } from './routes/dashboard/ai-solver'
import { Route as DashboardCareersRouteImport } from './routes/dashboard/careers'
import { Route as DashboardEditalRouteImport } from './routes/dashboard/edital'
import { Route as DashboardEditalRadarRouteImport } from './routes/dashboard/edital-radar'
import { Route as DashboardEnemRouteImport } from './routes/dashboard/enem'
import { Route as DashboardErrorsRouteImport } from './routes/dashboard/errors'
import { Route as DashboardEssaysRouteImport } from './routes/dashboard/essays'
import { Route as DashboardExamPanoramaRouteImport } from './routes/dashboard/exam-panorama'
import { Route as DashboardFlashcardsRouteImport } from './routes/dashboard/flashcards'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard/library'
import { Route as DashboardMedalsRouteImport } from './routes/dashboard/medals'
import { Route as DashboardMediaRouteImport } from './routes/dashboard/media'
import { Route as DashboardMockExamsRouteImport } from './routes/dashboard/mock-exams'
import { Route as DashboardMyContestRouteImport } from './routes/dashboard/my-contest'
import { Route as DashboardNotebooksRouteImport } from './routes/dashboard/notebooks'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard/performance'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardQuestionBankRouteImport } from './routes/dashboard/question-bank'
import { Route as DashboardQuestionTrainerRouteImport } from './routes/dashboard/question-trainer'
import { Route as DashboardQuestionsRouteImport } from './routes/dashboard/questions'
import { Route as DashboardRankingRouteImport } from './routes/dashboard/ranking'
import { Route as DashboardStudentExamsRouteImport } from './routes/dashboard/student-exams'
import { Route as DashboardStudyCoachRouteImport } from './routes/dashboard/study-coach'
import { Route as DashboardStudyPlanRouteImport } from './routes/dashboard/study-plan'
import { Route as DashboardStudyRoomRouteImport } from './routes/dashboard/study-room'
import { Route as DashboardStudyToolsRouteImport } from './routes/dashboard/study-tools'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard/subscriptions'
import { Route as DashboardTimerRouteImport } from './routes/dashboard/timer'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as DashboardAdminStudentIdRouteImport } from './routes/dashboard/admin-student.$id'
import { Route as DashboardEditalIndexRouteImport } from './routes/dashboard/edital.index'
import { Route as DashboardEditalTopicIdRouteImport } from './routes/dashboard/edital.$topicId'
import { Route as DashboardLibraryIndexRouteImport } from './routes/dashboard/library.index'
import { Route as DashboardLibrarySlugRouteImport } from './routes/dashboard/library.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioDiarioRoute = DesafioDiarioRouteImport.update({
  id: '/desafio-diario',
  path: '/desafio-diario',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolveQuestionRoute = ApiSolveQuestionRouteImport.update({
  id: '/api/solve-question',
  path: '/api/solve-question',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminFinanceRoute = DashboardAdminFinanceRouteImport.update({
  id: '/admin-finance',
  path: '/admin-finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMediaRoute = DashboardAdminMediaRouteImport.update({
  id: '/admin-media',
  path: '/admin-media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMetricsRoute = DashboardAdminMetricsRouteImport.update({
  id: '/admin-metrics',
  path: '/admin-metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminQuestionsRoute = DashboardAdminQuestionsRouteImport.update({
  id: '/admin-questions',
  path: '/admin-questions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSignupsRoute = DashboardAdminSignupsRouteImport.update({
  id: '/admin-signups',
  path: '/admin-signups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/admin-students',
  path: '/admin-students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiSolverRoute = DashboardAiSolverRouteImport.update({
  id: '/ai-solver',
  path: '/ai-solver',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareersRoute = DashboardCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditalRoute = DashboardEditalRouteImport.update({
  id: '/edital',
  path: '/edital',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditalRadarRoute = DashboardEditalRadarRouteImport.update({
  id: '/edital-radar',
  path: '/edital-radar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnemRoute = DashboardEnemRouteImport.update({
  id: '/enem',
  path: '/enem',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardErrorsRoute = DashboardErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEssaysRoute = DashboardEssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamPanoramaRoute = DashboardExamPanoramaRouteImport.update({
  id: '/exam-panorama',
  path: '/exam-panorama',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlashcardsRoute = DashboardFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedalsRoute = DashboardMedalsRouteImport.update({
  id: '/medals',
  path: '/medals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMockExamsRoute = DashboardMockExamsRouteImport.update({
  id: '/mock-exams',
  path: '/mock-exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyContestRoute = DashboardMyContestRouteImport.update({
  id: '/my-contest',
  path: '/my-contest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotebooksRoute = DashboardNotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionBankRoute = DashboardQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionTrainerRoute =
  DashboardQuestionTrainerRouteImport.update({
    id: '/question-trainer',
    path: '/question-trainer',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionsRoute = DashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRankingRoute = DashboardRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentExamsRoute = DashboardStudentExamsRouteImport.update({
  id: '/student-exams',
  path: '/student-exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyCoachRoute = DashboardStudyCoachRouteImport.update({
  id: '/study-coach',
  path: '/study-coach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyPlanRoute = DashboardStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyRoomRoute = DashboardStudyRoomRouteImport.update({
  id: '/study-room',
  path: '/study-room',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyToolsRoute = DashboardStudyToolsRouteImport.update({
  id: '/study-tools',
  path: '/study-tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimerRoute = DashboardTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminStudentIdRoute = DashboardAdminStudentIdRouteImport.update({
  id: '/admin-student/$id',
  path: '/admin-student/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditalIndexRoute = DashboardEditalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEditalRoute,
} as any)
const DashboardEditalTopicIdRoute = DashboardEditalTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => DashboardEditalRoute,
} as any)
const DashboardLibraryIndexRoute = DashboardLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLibraryRoute,
} as any)
const DashboardLibrarySlugRoute = DashboardLibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/desafio-diario': typeof DesafioDiarioRoute
  '/privacy': typeof PrivacyRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/terms': typeof TermsRoute
  '/api/solve-question': typeof ApiSolveQuestionRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/admin-finance': typeof DashboardAdminFinanceRoute
  '/dashboard/admin-media': typeof DashboardAdminMediaRoute
  '/dashboard/admin-metrics': typeof DashboardAdminMetricsRoute
  '/dashboard/admin-questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/admin-signups': typeof DashboardAdminSignupsRoute
  '/dashboard/admin-students': typeof DashboardAdminStudentsRoute
  '/dashboard/ai-solver': typeof DashboardAiSolverRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/edital': typeof DashboardEditalRouteWithChildren
  '/dashboard/edital-radar': typeof DashboardEditalRadarRoute
  '/dashboard/enem': typeof DashboardEnemRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/exam-panorama': typeof DashboardExamPanoramaRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/library': typeof DashboardLibraryRouteWithChildren
  '/dashboard/medals': typeof DashboardMedalsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/mock-exams': typeof DashboardMockExamsRoute
  '/dashboard/my-contest': typeof DashboardMyContestRoute
  '/dashboard/notebooks': typeof DashboardNotebooksRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/question-bank': typeof DashboardQuestionBankRoute
  '/dashboard/question-trainer': typeof DashboardQuestionTrainerRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/ranking': typeof DashboardRankingRoute
  '/dashboard/student-exams': typeof DashboardStudentExamsRoute
  '/dashboard/study-coach': typeof DashboardStudyCoachRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/study-room': typeof DashboardStudyRoomRoute
  '/dashboard/study-tools': typeof DashboardStudyToolsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/timer': typeof DashboardTimerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/admin-student/$id': typeof DashboardAdminStudentIdRoute
  '/dashboard/edital/$topicId': typeof DashboardEditalTopicIdRoute
  '/dashboard/library/$slug': typeof DashboardLibrarySlugRoute
  '/dashboard/edital/': typeof DashboardEditalIndexRoute
  '/dashboard/library/': typeof DashboardLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/desafio-diario': typeof DesafioDiarioRoute
  '/privacy': typeof PrivacyRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/terms': typeof TermsRoute
  '/api/solve-question': typeof ApiSolveQuestionRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/admin-finance': typeof DashboardAdminFinanceRoute
  '/dashboard/admin-media': typeof DashboardAdminMediaRoute
  '/dashboard/admin-metrics': typeof DashboardAdminMetricsRoute
  '/dashboard/admin-questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/admin-signups': typeof DashboardAdminSignupsRoute
  '/dashboard/admin-students': typeof DashboardAdminStudentsRoute
  '/dashboard/ai-solver': typeof DashboardAiSolverRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/edital-radar': typeof DashboardEditalRadarRoute
  '/dashboard/enem': typeof DashboardEnemRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/exam-panorama': typeof DashboardExamPanoramaRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/medals': typeof DashboardMedalsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/mock-exams': typeof DashboardMockExamsRoute
  '/dashboard/my-contest': typeof DashboardMyContestRoute
  '/dashboard/notebooks': typeof DashboardNotebooksRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/question-bank': typeof DashboardQuestionBankRoute
  '/dashboard/question-trainer': typeof DashboardQuestionTrainerRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/ranking': typeof DashboardRankingRoute
  '/dashboard/student-exams': typeof DashboardStudentExamsRoute
  '/dashboard/study-coach': typeof DashboardStudyCoachRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/study-room': typeof DashboardStudyRoomRoute
  '/dashboard/study-tools': typeof DashboardStudyToolsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/timer': typeof DashboardTimerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/admin-student/$id': typeof DashboardAdminStudentIdRoute
  '/dashboard/edital/$topicId': typeof DashboardEditalTopicIdRoute
  '/dashboard/library/$slug': typeof DashboardLibrarySlugRoute
  '/dashboard/edital': typeof DashboardEditalIndexRoute
  '/dashboard/library': typeof DashboardLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/desafio-diario': typeof DesafioDiarioRoute
  '/privacy': typeof PrivacyRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/terms': typeof TermsRoute
  '/api/solve-question': typeof ApiSolveQuestionRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/admin-finance': typeof DashboardAdminFinanceRoute
  '/dashboard/admin-media': typeof DashboardAdminMediaRoute
  '/dashboard/admin-metrics': typeof DashboardAdminMetricsRoute
  '/dashboard/admin-questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/admin-signups': typeof DashboardAdminSignupsRoute
  '/dashboard/admin-students': typeof DashboardAdminStudentsRoute
  '/dashboard/ai-solver': typeof DashboardAiSolverRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/edital': typeof DashboardEditalRouteWithChildren
  '/dashboard/edital-radar': typeof DashboardEditalRadarRoute
  '/dashboard/enem': typeof DashboardEnemRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/exam-panorama': typeof DashboardExamPanoramaRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/library': typeof DashboardLibraryRouteWithChildren
  '/dashboard/medals': typeof DashboardMedalsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/mock-exams': typeof DashboardMockExamsRoute
  '/dashboard/my-contest': typeof DashboardMyContestRoute
  '/dashboard/notebooks': typeof DashboardNotebooksRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/question-bank': typeof DashboardQuestionBankRoute
  '/dashboard/question-trainer': typeof DashboardQuestionTrainerRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/ranking': typeof DashboardRankingRoute
  '/dashboard/student-exams': typeof DashboardStudentExamsRoute
  '/dashboard/study-coach': typeof DashboardStudyCoachRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/study-room': typeof DashboardStudyRoomRoute
  '/dashboard/study-tools': typeof DashboardStudyToolsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/timer': typeof DashboardTimerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/admin-student/$id': typeof DashboardAdminStudentIdRoute
  '/dashboard/edital/$topicId': typeof DashboardEditalTopicIdRoute
  '/dashboard/library/$slug': typeof DashboardLibrarySlugRoute
  '/dashboard/edital/': typeof DashboardEditalIndexRoute
  '/dashboard/library/': typeof DashboardLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/desafio-diario'
    | '/privacy'
    | '/sobre'
    | '/suporte'
    | '/terms'
    | '/api/solve-question'
    | '/checkout/$planId'
    | '/dashboard/admin'
    | '/dashboard/admin-finance'
    | '/dashboard/admin-media'
    | '/dashboard/admin-metrics'
    | '/dashboard/admin-questions'
    | '/dashboard/admin-signups'
    | '/dashboard/admin-students'
    | '/dashboard/ai-solver'
    | '/dashboard/careers'
    | '/dashboard/edital'
    | '/dashboard/edital-radar'
    | '/dashboard/enem'
    | '/dashboard/errors'
    | '/dashboard/essays'
    | '/dashboard/exam-panorama'
    | '/dashboard/flashcards'
    | '/dashboard/history'
    | '/dashboard/library'
    | '/dashboard/medals'
    | '/dashboard/media'
    | '/dashboard/mock-exams'
    | '/dashboard/my-contest'
    | '/dashboard/notebooks'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/question-bank'
    | '/dashboard/question-trainer'
    | '/dashboard/questions'
    | '/dashboard/ranking'
    | '/dashboard/student-exams'
    | '/dashboard/study-coach'
    | '/dashboard/study-plan'
    | '/dashboard/study-room'
    | '/dashboard/study-tools'
    | '/dashboard/subscriptions'
    | '/dashboard/timer'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
    | '/dashboard/admin-student/$id'
    | '/dashboard/edital/$topicId'
    | '/dashboard/library/$slug'
    | '/dashboard/edital/'
    | '/dashboard/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/desafio-diario'
    | '/privacy'
    | '/sobre'
    | '/suporte'
    | '/terms'
    | '/api/solve-question'
    | '/checkout/$planId'
    | '/dashboard/admin'
    | '/dashboard/admin-finance'
    | '/dashboard/admin-media'
    | '/dashboard/admin-metrics'
    | '/dashboard/admin-questions'
    | '/dashboard/admin-signups'
    | '/dashboard/admin-students'
    | '/dashboard/ai-solver'
    | '/dashboard/careers'
    | '/dashboard/edital-radar'
    | '/dashboard/enem'
    | '/dashboard/errors'
    | '/dashboard/essays'
    | '/dashboard/exam-panorama'
    | '/dashboard/flashcards'
    | '/dashboard/history'
    | '/dashboard/medals'
    | '/dashboard/media'
    | '/dashboard/mock-exams'
    | '/dashboard/my-contest'
    | '/dashboard/notebooks'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/question-bank'
    | '/dashboard/question-trainer'
    | '/dashboard/questions'
    | '/dashboard/ranking'
    | '/dashboard/student-exams'
    | '/dashboard/study-coach'
    | '/dashboard/study-plan'
    | '/dashboard/study-room'
    | '/dashboard/study-tools'
    | '/dashboard/subscriptions'
    | '/dashboard/timer'
    | '/dashboard'
    | '/api/public/stripe-webhook'
    | '/dashboard/admin-student/$id'
    | '/dashboard/edital/$topicId'
    | '/dashboard/library/$slug'
    | '/dashboard/edital'
    | '/dashboard/library'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/desafio-diario'
    | '/privacy'
    | '/sobre'
    | '/suporte'
    | '/terms'
    | '/api/solve-question'
    | '/checkout/$planId'
    | '/dashboard/admin'
    | '/dashboard/admin-finance'
    | '/dashboard/admin-media'
    | '/dashboard/admin-metrics'
    | '/dashboard/admin-questions'
    | '/dashboard/admin-signups'
    | '/dashboard/admin-students'
    | '/dashboard/ai-solver'
    | '/dashboard/careers'
    | '/dashboard/edital'
    | '/dashboard/edital-radar'
    | '/dashboard/enem'
    | '/dashboard/errors'
    | '/dashboard/essays'
    | '/dashboard/exam-panorama'
    | '/dashboard/flashcards'
    | '/dashboard/history'
    | '/dashboard/library'
    | '/dashboard/medals'
    | '/dashboard/media'
    | '/dashboard/mock-exams'
    | '/dashboard/my-contest'
    | '/dashboard/notebooks'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/question-bank'
    | '/dashboard/question-trainer'
    | '/dashboard/questions'
    | '/dashboard/ranking'
    | '/dashboard/student-exams'
    | '/dashboard/study-coach'
    | '/dashboard/study-plan'
    | '/dashboard/study-room'
    | '/dashboard/study-tools'
    | '/dashboard/subscriptions'
    | '/dashboard/timer'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
    | '/dashboard/admin-student/$id'
    | '/dashboard/edital/$topicId'
    | '/dashboard/library/$slug'
    | '/dashboard/edital/'
    | '/dashboard/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DesafioDiarioRoute: typeof DesafioDiarioRoute
  PrivacyRoute: typeof PrivacyRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermsRoute: typeof TermsRoute
  ApiSolveQuestionRoute: typeof ApiSolveQuestionRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio-diario': {
      id: '/desafio-diario'
      path: '/desafio-diario'
      fullPath: '/desafio-diario'
      preLoaderRoute: typeof DesafioDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/solve-question': {
      id: '/api/solve-question'
      path: '/api/solve-question'
      fullPath: '/api/solve-question'
      preLoaderRoute: typeof ApiSolveQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-finance': {
      id: '/dashboard/admin-finance'
      path: '/admin-finance'
      fullPath: '/dashboard/admin-finance'
      preLoaderRoute: typeof DashboardAdminFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-media': {
      id: '/dashboard/admin-media'
      path: '/admin-media'
      fullPath: '/dashboard/admin-media'
      preLoaderRoute: typeof DashboardAdminMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-metrics': {
      id: '/dashboard/admin-metrics'
      path: '/admin-metrics'
      fullPath: '/dashboard/admin-metrics'
      preLoaderRoute: typeof DashboardAdminMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-questions': {
      id: '/dashboard/admin-questions'
      path: '/admin-questions'
      fullPath: '/dashboard/admin-questions'
      preLoaderRoute: typeof DashboardAdminQuestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-signups': {
      id: '/dashboard/admin-signups'
      path: '/admin-signups'
      fullPath: '/dashboard/admin-signups'
      preLoaderRoute: typeof DashboardAdminSignupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-students': {
      id: '/dashboard/admin-students'
      path: '/admin-students'
      fullPath: '/dashboard/admin-students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-solver': {
      id: '/dashboard/ai-solver'
      path: '/ai-solver'
      fullPath: '/dashboard/ai-solver'
      preLoaderRoute: typeof DashboardAiSolverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/careers': {
      id: '/dashboard/careers'
      path: '/careers'
      fullPath: '/dashboard/careers'
      preLoaderRoute: typeof DashboardCareersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edital': {
      id: '/dashboard/edital'
      path: '/edital'
      fullPath: '/dashboard/edital'
      preLoaderRoute: typeof DashboardEditalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edital-radar': {
      id: '/dashboard/edital-radar'
      path: '/edital-radar'
      fullPath: '/dashboard/edital-radar'
      preLoaderRoute: typeof DashboardEditalRadarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enem': {
      id: '/dashboard/enem'
      path: '/enem'
      fullPath: '/dashboard/enem'
      preLoaderRoute: typeof DashboardEnemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/errors': {
      id: '/dashboard/errors'
      path: '/errors'
      fullPath: '/dashboard/errors'
      preLoaderRoute: typeof DashboardErrorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/essays': {
      id: '/dashboard/essays'
      path: '/essays'
      fullPath: '/dashboard/essays'
      preLoaderRoute: typeof DashboardEssaysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exam-panorama': {
      id: '/dashboard/exam-panorama'
      path: '/exam-panorama'
      fullPath: '/dashboard/exam-panorama'
      preLoaderRoute: typeof DashboardExamPanoramaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flashcards': {
      id: '/dashboard/flashcards'
      path: '/flashcards'
      fullPath: '/dashboard/flashcards'
      preLoaderRoute: typeof DashboardFlashcardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medals': {
      id: '/dashboard/medals'
      path: '/medals'
      fullPath: '/dashboard/medals'
      preLoaderRoute: typeof DashboardMedalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mock-exams': {
      id: '/dashboard/mock-exams'
      path: '/mock-exams'
      fullPath: '/dashboard/mock-exams'
      preLoaderRoute: typeof DashboardMockExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-contest': {
      id: '/dashboard/my-contest'
      path: '/my-contest'
      fullPath: '/dashboard/my-contest'
      preLoaderRoute: typeof DashboardMyContestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notebooks': {
      id: '/dashboard/notebooks'
      path: '/notebooks'
      fullPath: '/dashboard/notebooks'
      preLoaderRoute: typeof DashboardNotebooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/question-bank': {
      id: '/dashboard/question-bank'
      path: '/question-bank'
      fullPath: '/dashboard/question-bank'
      preLoaderRoute: typeof DashboardQuestionBankRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/question-trainer': {
      id: '/dashboard/question-trainer'
      path: '/question-trainer'
      fullPath: '/dashboard/question-trainer'
      preLoaderRoute: typeof DashboardQuestionTrainerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/questions': {
      id: '/dashboard/questions'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof DashboardQuestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ranking': {
      id: '/dashboard/ranking'
      path: '/ranking'
      fullPath: '/dashboard/ranking'
      preLoaderRoute: typeof DashboardRankingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student-exams': {
      id: '/dashboard/student-exams'
      path: '/student-exams'
      fullPath: '/dashboard/student-exams'
      preLoaderRoute: typeof DashboardStudentExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-coach': {
      id: '/dashboard/study-coach'
      path: '/study-coach'
      fullPath: '/dashboard/study-coach'
      preLoaderRoute: typeof DashboardStudyCoachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-plan': {
      id: '/dashboard/study-plan'
      path: '/study-plan'
      fullPath: '/dashboard/study-plan'
      preLoaderRoute: typeof DashboardStudyPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-room': {
      id: '/dashboard/study-room'
      path: '/study-room'
      fullPath: '/dashboard/study-room'
      preLoaderRoute: typeof DashboardStudyRoomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-tools': {
      id: '/dashboard/study-tools'
      path: '/study-tools'
      fullPath: '/dashboard/study-tools'
      preLoaderRoute: typeof DashboardStudyToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timer': {
      id: '/dashboard/timer'
      path: '/timer'
      fullPath: '/dashboard/timer'
      preLoaderRoute: typeof DashboardTimerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin-student/$id': {
      id: '/dashboard/admin-student/$id'
      path: '/admin-student/$id'
      fullPath: '/dashboard/admin-student/$id'
      preLoaderRoute: typeof DashboardAdminStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edital/': {
      id: '/dashboard/edital/'
      path: '/'
      fullPath: '/dashboard/edital/'
      preLoaderRoute: typeof DashboardEditalIndexRouteImport
      parentRoute: typeof DashboardEditalRoute
    }
    '/dashboard/edital/$topicId': {
      id: '/dashboard/edital/$topicId'
      path: '/$topicId'
      fullPath: '/dashboard/edital/$topicId'
      preLoaderRoute: typeof DashboardEditalTopicIdRouteImport
      parentRoute: typeof DashboardEditalRoute
    }
    '/dashboard/library/': {
      id: '/dashboard/library/'
      path: '/'
      fullPath: '/dashboard/library/'
      preLoaderRoute: typeof DashboardLibraryIndexRouteImport
      parentRoute: typeof DashboardLibraryRoute
    }
    '/dashboard/library/$slug': {
      id: '/dashboard/library/$slug'
      path: '/$slug'
      fullPath: '/dashboard/library/$slug'
      preLoaderRoute: typeof DashboardLibrarySlugRouteImport
      parentRoute: typeof DashboardLibraryRoute
    }
  }
}

interface DashboardEditalRouteChildren {
  DashboardEditalTopicIdRoute: typeof DashboardEditalTopicIdRoute
  DashboardEditalIndexRoute: typeof DashboardEditalIndexRoute
}

const DashboardEditalRouteChildren: DashboardEditalRouteChildren = {
  DashboardEditalTopicIdRoute: DashboardEditalTopicIdRoute,
  DashboardEditalIndexRoute: DashboardEditalIndexRoute,
}

const DashboardEditalRouteWithChildren = DashboardEditalRoute._addFileChildren(
  DashboardEditalRouteChildren,
)

interface DashboardLibraryRouteChildren {
  DashboardLibrarySlugRoute: typeof DashboardLibrarySlugRoute
  DashboardLibraryIndexRoute: typeof DashboardLibraryIndexRoute
}

const DashboardLibraryRouteChildren: DashboardLibraryRouteChildren = {
  DashboardLibrarySlugRoute: DashboardLibrarySlugRoute,
  DashboardLibraryIndexRoute: DashboardLibraryIndexRoute,
}

const DashboardLibraryRouteWithChildren =
  DashboardLibraryRoute._addFileChildren(DashboardLibraryRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAdminFinanceRoute: typeof DashboardAdminFinanceRoute
  DashboardAdminMediaRoute: typeof DashboardAdminMediaRoute
  DashboardAdminMetricsRoute: typeof DashboardAdminMetricsRoute
  DashboardAdminQuestionsRoute: typeof DashboardAdminQuestionsRoute
  DashboardAdminSignupsRoute: typeof DashboardAdminSignupsRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAiSolverRoute: typeof DashboardAiSolverRoute
  DashboardCareersRoute: typeof DashboardCareersRoute
  DashboardEditalRoute: typeof DashboardEditalRouteWithChildren
  DashboardEditalRadarRoute: typeof DashboardEditalRadarRoute
  DashboardEnemRoute: typeof DashboardEnemRoute
  DashboardErrorsRoute: typeof DashboardErrorsRoute
  DashboardEssaysRoute: typeof DashboardEssaysRoute
  DashboardExamPanoramaRoute: typeof DashboardExamPanoramaRoute
  DashboardFlashcardsRoute: typeof DashboardFlashcardsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardLibraryRoute: typeof DashboardLibraryRouteWithChildren
  DashboardMedalsRoute: typeof DashboardMedalsRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardMockExamsRoute: typeof DashboardMockExamsRoute
  DashboardMyContestRoute: typeof DashboardMyContestRoute
  DashboardNotebooksRoute: typeof DashboardNotebooksRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuestionBankRoute: typeof DashboardQuestionBankRoute
  DashboardQuestionTrainerRoute: typeof DashboardQuestionTrainerRoute
  DashboardQuestionsRoute: typeof DashboardQuestionsRoute
  DashboardRankingRoute: typeof DashboardRankingRoute
  DashboardStudentExamsRoute: typeof DashboardStudentExamsRoute
  DashboardStudyCoachRoute: typeof DashboardStudyCoachRoute
  DashboardStudyPlanRoute: typeof DashboardStudyPlanRoute
  DashboardStudyRoomRoute: typeof DashboardStudyRoomRoute
  DashboardStudyToolsRoute: typeof DashboardStudyToolsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardTimerRoute: typeof DashboardTimerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminStudentIdRoute: typeof DashboardAdminStudentIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAdminFinanceRoute: DashboardAdminFinanceRoute,
  DashboardAdminMediaRoute: DashboardAdminMediaRoute,
  DashboardAdminMetricsRoute: DashboardAdminMetricsRoute,
  DashboardAdminQuestionsRoute: DashboardAdminQuestionsRoute,
  DashboardAdminSignupsRoute: DashboardAdminSignupsRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAiSolverRoute: DashboardAiSolverRoute,
  DashboardCareersRoute: DashboardCareersRoute,
  DashboardEditalRoute: DashboardEditalRouteWithChildren,
  DashboardEditalRadarRoute: DashboardEditalRadarRoute,
  DashboardEnemRoute: DashboardEnemRoute,
  DashboardErrorsRoute: DashboardErrorsRoute,
  DashboardEssaysRoute: DashboardEssaysRoute,
  DashboardExamPanoramaRoute: DashboardExamPanoramaRoute,
  DashboardFlashcardsRoute: DashboardFlashcardsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardLibraryRoute: DashboardLibraryRouteWithChildren,
  DashboardMedalsRoute: DashboardMedalsRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardMockExamsRoute: DashboardMockExamsRoute,
  DashboardMyContestRoute: DashboardMyContestRoute,
  DashboardNotebooksRoute: DashboardNotebooksRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuestionBankRoute: DashboardQuestionBankRoute,
  DashboardQuestionTrainerRoute: DashboardQuestionTrainerRoute,
  DashboardQuestionsRoute: DashboardQuestionsRoute,
  DashboardRankingRoute: DashboardRankingRoute,
  DashboardStudentExamsRoute: DashboardStudentExamsRoute,
  DashboardStudyCoachRoute: DashboardStudyCoachRoute,
  DashboardStudyPlanRoute: DashboardStudyPlanRoute,
  DashboardStudyRoomRoute: DashboardStudyRoomRoute,
  DashboardStudyToolsRoute: DashboardStudyToolsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardTimerRoute: DashboardTimerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminStudentIdRoute: DashboardAdminStudentIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DesafioDiarioRoute: DesafioDiarioRoute,
  PrivacyRoute: PrivacyRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermsRoute: TermsRoute,
  ApiSolveQuestionRoute: ApiSolveQuestionRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
