-- Auditoria jurídica: PF 2014 (Agente), itens 105 e 115. Textos oficiais do Planalto conferidos em 27/09/2026.

update public.official_exam_questions set review_note=$q$Conferido no texto compilado do CPP (Planalto, 27/09/2026): art. 6º, VII (determinar exame de corpo de delito e outras perícias) e VI (proceder a acareações). Gabarito C confere.$q$, question_text=$q$Comando: Logo que tiver conhecimento da prática de infração penal, a autoridade policial deverá:

Item: determinar, se for caso, a realização das perícias que se mostrarem necessárias e proceder a acareações.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Direito Penal e Processual Penal$q$ and t.topic_order=3 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Código de Processo Penal – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm$q$)), law_version_checked_at=now() where exam_year=2014 and career_name=$q$Agente de Polícia Federal$q$ and item_number=105 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido (Planalto, 27/09/2026): CF, art. 5º, XI (entrada sem consentimento, durante o dia, por determinação judicial) e CPP, arts. 245 e 246 (regras da busca domiciliar aplicam-se ao compartimento não aberto ao público onde alguém exerce profissão). Gabarito C confere.$q$, question_text=$q$Comando: Um agente da Polícia Federal foi escalado para atuar em operação para cumprimento de mandado judicial de prisão e de busca e apreensão, durante o dia, de documentos no escritório profissional do investigado. A respeito da atuação do agente na situação descrita acima, julgue os itens a seguir.

Item: Mesmo sem o consentimento do proprietário, é permitido ao agente entrar no escritório profissional onde se encontrem os objetos de busca e apreensão.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Direito Penal e Processual Penal$q$ and t.topic_order=4 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, subject=$q$Direito Penal e Processual Penal$q$, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Constituição Federal de 1988 – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm$q$),jsonb_build_object('title',$q$Código de Processo Penal – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm$q$)), law_version_checked_at=now() where exam_year=2014 and career_name=$q$Agente de Polícia Federal$q$ and item_number=115 and content_status='under_review';
-- @@
