-- Catálogo de questões da prova Especialista da Fazenda Estadual, SEFAZ/AC,
-- Edital SEAD/SEFAZ nº 001/2023 (CEBRASPE, aplicação 02/06/2024), conferida
-- contra os gabaritos oficiais definitivos publicados pelo CEBRASPE
-- (946_SEFAZ_AC_CG2_01.PDF e 946_SEFAZ_AC_003_01.PDF).
--
-- 59 das 60 questões foram transcritas das fotos da própria prova do
-- candidato. A questão 57 não foi cadastrada: um trecho do enunciado fica
-- sob a dobra física da folha na foto e ficou ilegível — nenhum texto foi
-- inventado para completá-la.

insert into public.content_sources (source_type,title,issuer,url,published_on,status,notes) values
('edital','Edital nº 1 – SEAD/SEFAZ – 2023','Secretaria de Estado da Fazenda do Acre / CEBRASPE','https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/ED_1_SEFAZ_AC_23_ABERTURA.PDF','2023-12-22','vigente','Edital do concurso para os cargos de Auditor, Contador, Especialista e Técnico da Fazenda Estadual.'),
('outro','Gabarito Oficial Definitivo - Conhecimentos Gerais (Cargos 2 e 3) - SEFAZ/AC 2023','CEBRASPE','https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/GAB_DEFINITIVO_946_SEFAZ_AC_CG2_01.PDF','2024-06-28','vigente','Gabarito oficial definitivo, questões 1 a 30.'),
('outro','Gabarito Oficial Definitivo - Conhecimentos Específicos (Cargo 3) - SEFAZ/AC 2023','CEBRASPE','https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/GAB_DEFINITIVO_946_SEFAZ_AC_003_01.PDF','2024-06-28','vigente','Gabarito oficial definitivo, questões 31 a 60. Sem itens anulados para o Cargo 3.')
on conflict (url) do update set checked_at=now(), status=excluded.status, notes=excluded.notes;

insert into public.syllabus_editions (contest_name,role_name,contest_year,exam_board,source_id,status)
select 'SEFAZ/AC - Secretaria de Estado da Fazenda do Acre','Especialista da Fazenda Estadual',2023,'CEBRASPE',id,'active'
from public.content_sources where url='https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/ED_1_SEFAZ_AC_23_ABERTURA.PDF'
on conflict (contest_name,role_name,contest_year) do update set source_id=excluded.source_id, status='active';

with edition as (
  select id from public.syllabus_editions
  where contest_name='SEFAZ/AC - Secretaria de Estado da Fazenda do Acre' and role_name='Especialista da Fazenda Estadual' and contest_year=2023
)
insert into public.syllabus_topics (edition_id,block_name,discipline,topic_order,topic_text)
select edition.id, data.block_name, data.discipline, 1, data.topic_text from edition cross join (values
('Conhecimentos Gerais','Língua Portuguesa','Compreensão e interpretação textual; coesão e coerência; correção gramatical; substituição vocabular — questões 1 a 7 do caderno.'),
('Conhecimentos Gerais','Matemática Financeira','Juros simples e compostos, desconto racional simples, valor presente e futuro — questões 8 a 10 do caderno.'),
('Conhecimentos Gerais','Raciocínio Lógico','Lógica proposicional, argumentos válidos, sequências numéricas — questões 11 a 15 do caderno.'),
('Conhecimentos Gerais','Informática','Edição de documentos acessíveis, ferramentas de busca, armazenamento em nuvem, LGPD (Lei nº 13.709/2018) — questões 16 a 19 do caderno.'),
('Conhecimentos Gerais','Realidade do Acre','História, geografia, cultura e economia do estado do Acre — questões 20 a 30 do caderno.'),
('Conhecimentos Específicos','Administração Pública','Orçamento participativo, indicadores de desempenho, OSCIP, descentralização, Lei de Acesso à Informação, improbidade administrativa, processo administrativo — questões 31 a 44 do caderno.'),
('Conhecimentos Específicos','Direito Tributário','Substituição tributária, IPI, ICMS (diferencial de alíquota, monofásico) — questões 45 a 48 do caderno.'),
('Conhecimentos Específicos','Direito Constitucional','Ações constitucionais, intervenção federal, Poder Judiciário, ADI, direitos indígenas e quilombolas, Constituição do Estado do Acre — questões 49 a 54 do caderno.'),
('Conhecimentos Específicos','Orçamento Público','LDO, PPA, LOA, sistema de controle interno e externo — questões 55 a 60 do caderno.')
) as data(block_name,discipline,topic_text)
on conflict (edition_id,discipline,topic_order) do update set topic_text=excluded.topic_text, content_status='current';

with sources as (
  select
    (select id from public.content_sources where url='https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/ED_1_SEFAZ_AC_23_ABERTURA.PDF') as prova_id,
    (select id from public.content_sources where url='https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/GAB_DEFINITIVO_946_SEFAZ_AC_CG2_01.PDF') as gab_gerais_id,
    (select id from public.content_sources where url='https://cdn.cebraspe.org.br/concursos/sefaz_ac_23/arquivos/GAB_DEFINITIVO_946_SEFAZ_AC_003_01.PDF') as gab_especificos_id
),
topics as (
  select t.discipline, t.id as topic_id
  from public.syllabus_topics t
  join public.syllabus_editions e on e.id = t.edition_id
  where e.contest_name='SEFAZ/AC - Secretaria de Estado da Fazenda do Acre' and e.role_name='Especialista da Fazenda Estadual' and e.contest_year=2023
),
imported(item_number,subject,question_text,official_answer,source_page,is_specifico) as (values
(1,'Língua Portuguesa','Texto CG2A1 (Tatiana Roque, "História da matemática: uma visão crítica, desfazendo mitos e lendas", 2012, sobre a origem grega/mesopotâmica da matemática). No primeiro parágrafo do texto CG2A1, a autora: A) descreve o relato tradicional da evolução da matemática, ratifica um aspecto de seus primórdios e defende a ideia de uma história da evolução de diversas práticas consideradas matemáticas; B) enaltece a história da matemática, ainda que corrija o relato tradicional de seus primórdios e proponha uma revisão das práticas que devem ser consideradas matemáticas; C) critica a evolução da matemática, refutando o relato tradicional de suas origens, e se propõe a uma revisão dos critérios definidores das práticas que devem ser consideradas matemáticas; D) apresenta o relato tradicional da história da matemática e critica a premissa que o embasa, defendendo a proposta de uma história da evolução de diversas práticas consideradas matemáticas; E) valoriza a história da matemática, porém retifica uma de suas premissas tradicionais e defende a proposta de uma revisão da evolução de diversas práticas consideradas matemáticas.','D',1,false),
(2,'Língua Portuguesa','Texto CG2A1. No texto CG2A1, a referência ao desaparecimento da matemática mesopotâmica e a menção aos primeiros registros da matemática grega integram o argumento de que: A) a matemática grega suplantou a matemática mesopotâmica; B) a origem da matemática ocorreu na Mesopotâmia; C) a origem da notação matemática é grega; D) a história da matemática deve ser entendida de forma linear; E) a história da matemática é plural e descontínua.','A',1,false),
(3,'Língua Portuguesa','Texto CG2A1. Com base nas ideias veiculadas no texto CG2A1, julgue os itens: I De acordo com a perspectiva defendida pela autora, não há evidências que amparem o entendimento segundo o qual a matemática mesopotâmica tenha sido precursora da matemática grega. II A data de origem da matemática europeia é incerta, situando-se em algum momento entre os séculos XIII e XV, conforme as informações do primeiro parágrafo. III Infere-se do texto que a suposta herança grega da matemática é considerada um mito porque propaga uma história eurocêntrica da matemática. Assinale a opção correta: A) Apenas o item I está certo; B) Apenas o item II está certo; C) Apenas os itens I e III estão certos; D) Apenas os itens II e III estão certos; E) Todos os itens estão certos.','E',1,false),
(4,'Língua Portuguesa','Texto CG2A1. No último parágrafo do texto CG2A1, a forma pronominal "sua" (último período), em suas duas ocorrências, reporta-se, respectivamente, a: A) "o mito da herança grega" (penúltimo período) e "história" (último período); B) "demandas identitárias" (penúltimo período) e "história" (último período); C) "o mito da herança grega" (penúltimo período) e "formação de uma imagem da matemática" (último período); D) "demandas identitárias" (penúltimo período) e "formação de uma imagem da matemática" (último período); E) "o mito da herança grega" (penúltimo período) e "matemática" (último período).','C',1,false),
(5,'Língua Portuguesa','Texto CG2A1. A correção gramatical e a coerência das ideias do texto CG2A1 seriam mantidas caso o vocábulo "Ora" (terceiro período do primeiro parágrafo) fosse substituído por: A) Então; B) Ainda; C) Logo; D) Além disso; E) No entanto.','D',1,false),
(6,'Língua Portuguesa','Assinale a opção em que é apresentado um verbo que poderia substituir "responder" no segundo período do último parágrafo do texto CG2A1, sem prejuízo da sua correção gramatical e do seu sentido: A) retribuir; B) atentar; C) resolver; D) replicar; E) atender.','E',2,false),
(7,'Língua Portuguesa','A precisão, um dos atributos da redação oficial, caracteriza-se: A) pelo favorecimento da conexão harmônica entre os elementos do texto, utilizando-se mecanismos de referenciação e substituição; B) pela articulação da linguagem para a perfeita compreensão da ideia veiculada, evitando-se expressões que confiram ambiguidade ao texto; C) pela transmissão do máximo de informações com o mínimo de palavras, evitando-se a prolixidade e o jargão técnico; D) pela abordagem direta e objetiva, respeitando-se a hierarquia entre ideias primárias e secundárias; E) pelo emprego de frases curtas e bem estruturadas, preferencialmente apresentadas na ordem sintática direta.','B',2,false),
(8,'Matemática Financeira','Carlos tem uma dívida que deve ser paga em três prestações iguais de R$ 3.600,00, em três meses consecutivos, com o vencimento da primeira prestação daqui a um mês; na negociação, foi usada uma taxa de 20% ao mês no regime de juros compostos. Nessa situação, se Carlos resolver quitar a dívida total no dia do pagamento da primeira prestação, então o valor a ser pago será igual a: A) R$ 8.208,00; B) R$ 8.640,00; C) R$ 9.100,00; D) R$ 9.360,00; E) R$ 10.800,00.','D',2,true),
(9,'Matemática Financeira','A quantia de R$ 2.000,00 foi emprestada a uma taxa de 4% ao mês no regime de juros compostos. Se a dívida total for paga em uma única parcela 2 anos após o empréstimo, então, considerando que 1,04^24 = 1,6, o valor pago será igual a: A) R$ 2.160,00; B) R$ 3.200,00; C) R$ 3.920,00; D) R$ 5.120,00; E) R$ 6.400,00.','C',2,true),
(10,'Matemática Financeira','Uma nota promissória com valor nominal igual a R$ 3.500,00 foi paga 8 meses antes de seu vencimento. Ao seu pagamento foi aplicado um desconto racional simples à taxa de 5% ao mês. Nessa situação, o valor da nota promissória após o desconto foi igual a: A) R$ 1.400,00; B) R$ 2.100,00; C) R$ 2.500,00; D) R$ 2.800,00; E) R$ 3.325,00.','C',2,true),
(11,'Raciocínio Lógico','Para que uma taxa anual de juros simples gere, em um prazo de 8 meses, um juro de R$ 700,00 sobre um capital de R$ 2.500,00, essa taxa deve ser igual a: A) 28%; B) 42%; C) 72%; D) 75%; E) 92%.','A',2,true),
(12,'Raciocínio Lógico','Texto CG2A3-I (proposições P1 a P4 sobre crise no mercado consumidor, demanda, preço, faturamento e lucro de uma companhia). Assinale a opção em que é apresentada uma proposição que, sob o ponto de vista lógico, expressa o exato significado da proposição P2 do texto CG2A3-I: A) "Se, no novo equilíbrio de mercado, diminui o preço ou a quantidade demandada do produto vendido pela companhia, sua demanda sofre retração."; B) "Se a demanda pelo produto vendido pela companhia não sofre retração, no novo equilíbrio de mercado, não diminuem seu preço nem sua quantidade demandada."; C) "A demanda pelo produto vendido pela companhia sofre retração e, no novo equilíbrio de mercado, diminuem seu preço e sua quantidade demandada."; D) "A demanda pelo produto vendido pela companhia não sofre retração ou, no novo equilíbrio de mercado, diminuem seu preço e sua quantidade demandada."; E) "Se, no novo equilíbrio de mercado, diminuem o preço e a quantidade demandada do produto vendido pela companhia, sua demanda sofre retração."','E',2,true),
(13,'Raciocínio Lógico','Texto CG2A3-I. Assinale a opção em que é apresentado um argumento válido cujas premissas são as proposições P1 a P4 do texto CG2A3-I: A) "O lucro da companhia é afetado."; B) "A ação da empresa fica volátil."; C) "Se há uma crise no principal mercado consumidor do produto vendido, a ação da empresa fica volátil."; D) "Se a demanda pelo produto vendido pela companhia não sofre retração, seu faturamento não cai."; E) "O investidor fica receoso."','C',2,true),
(14,'Raciocínio Lógico','Texto CG2A3-II: uma sequência numérica crescente e infinita foi criada com o seguinte padrão: 0, 1, 3, 7, 15, 31, 63... No texto CG2A3-II, o primeiro termo da sequência com valor superior a 30.000 será o: A) 13.º termo; B) 14.º termo; C) 15.º termo; D) 16.º termo; E) 17.º termo.','C',2,true),
(15,'Raciocínio Lógico','Texto CG2A3-II. Assinale a opção em que é corretamente indicado o décimo termo da sequência numérica apresentada no texto CG2A3-II: A) 255; B) 511; C) 1.023; D) 1.024; E) 2.047.','B',2,true),
(16,'Informática','A fim de facilitar a leitura e a edição do conteúdo de um arquivo para pessoa com deficiência, o Microsoft Word 365 disponibiliza o recurso denominado: A) Editor; B) Traduzir; C) Previsões de Texto; D) Verificar Acessibilidade; E) Controlar alterações.','D',3,false),
(17,'Informática','Assinale a opção em que está apresentado corretamente o comando a ser utilizado caso se queira localizar, por meio da pesquisa do Google, os termos SEFAZ AC no título de uma página: A) top SEFAZ AC; B) + SEFAZ AC; C) ~ SEFAZ AC; D) SEFAZ AC in caption; E) allintitle: SEFAZ AC.','E',3,false),
(18,'Informática','Para o armazenamento de arquivos diversos em nuvem, é correto o uso do: A) OneDrive; B) NordVPN; C) Mozila Thunderbird; D) Spotify; E) Google Chrome.','A',3,false),
(19,'Informática','Segundo a Lei n.º 13.709/2018 (Lei Geral de Proteção de Dados Pessoais), o dado relativo a titular que não possa ser identificado, considerando a utilização de meios técnicos razoáveis e disponíveis na ocasião de seu tratamento, é definido como dado: A) pessoal sensível; B) secreto; C) pessoal; D) do controlador; E) anonimizado.','E',3,false),
(20,'Realidade do Acre','Assinale a opção em que é mencionado importante acontecimento destacado pela historiografia do Acre ocorrido em janeiro de 1903 e integrante do processo que culminou com a incorporação da região ao território brasileiro: A) assinatura do Tratado de Petrópolis, que não previa qualquer forma de compensação à Bolívia; B) afastamento da Anglo-Bolivian Syndicate da região, sem recebimento de qualquer indenização; C) início da arbitragem norte-americana solicitada pelo Barão do Rio Branco para solucionar o impasse com a Bolívia; D) aclamação de Plácido de Castro como governador do estado independente do Acre; E) arrendamento do Acre a um consórcio anglo-americano sediado em Nova Iorque.','D',3,false),
(21,'Realidade do Acre','Em 1962, quando a Presidência da República era exercida por João Goulart, houve uma importante mudança na configuração político-administrativa do estado do Acre ao se determinar, por lei, a: A) transformação do antigo território em estado dentro da estrutura federativa do Brasil; B) proibição definitiva da chegada de novas levas de imigrantes para a região; C) permissão para que o estado do Acre assinasse acordos e tratados internacionais; D) oficialização das cores da bandeira do Acre, alterando-se as que vigoravam anteriormente; E) conclusão das obras da ferrovia Madeira-Mamoré, iniciadas nas primeiras décadas do século XX.','A',3,false),
(22,'Realidade do Acre','Tendo em vista o cenário geográfico, econômico, étnico e cultural do Acre, assinale a opção correta: A) O Acre está situado nos limites da região Centro-Oeste, porém pertence ao bioma amazônico e seu clima é predominantemente temperado; B) Produtos primários praticamente desapareceram da pauta das exportações do Acre desde o fim da Segunda Guerra Mundial; C) A taxa de urbanização do Acre é bastante reduzida, e Rio Branco, apesar de ser a capital do estado, tem população inferior à de cidades do interior do estado, como Cruzeiro do Sul; D) Até a segunda metade do século XIX, o Acre era habitado por populações indígenas, bolivianos, peruanos e brasileiros que ali chegaram e disputaram o território; E) Apesar da forte pressão de grupos culturais locais, ainda não houve o tombamento de nenhum bem como patrimônio material do estado.','D',3,false),
(23,'Realidade do Acre','Acerca de características culturais do estado do Acre, assinale a opção correta: A) A cultura das populações originárias foi obliterada a tal ponto de ser imperceptível na atual configuração cultural do estado; B) Diferentemente do restante da região Norte, no Acre a culinária típica praticamente não faz uso de preparos à base de peixe; C) O artesanato, especialmente a produção de peças em madeira, é bastante desenvolvido e consiste em fonte de renda para a população local; D) Apesar da forte migração nordestina para o estado, sobretudo de cearenses, dela não restaram resquícios na cultura estadual; E) Inspirado na cultura dos seringais, o Arraial Cultural, em Rio Branco, deixou de ocorrer para evitar grandes aglomerações e pelo alto custo da festa.','C',3,false),
(24,'Realidade do Acre','Acerca do contexto primordial da ocupação das terras acreanas, assinale a opção correta: A) Os pioneiros no Acre tiveram sua subsistência econômica fornecida pela Amazônia boliviana, em Puerto Alonso, cidade fundada no início do século XIX pelos seringueiros; B) A formação econômica do Acre está relacionada ao avanço de imigrantes nordestinos pelo território acreano, que ocorreu através de vias hidrográficas, principalmente pelo vale do rio Purus; C) Após o Tratado de Petrópolis, o Brasil teve de desenvolver a engenharia civil para que as empresas internas executassem a construção da ferrovia Madeira-Mamoré; D) Apesar de o Peru ser um país vizinho do Brasil, os problemas do comando brasileiro pela delimitação de fronteiras territoriais deram-se exclusivamente com os bolivianos; E) Apesar da assinatura do Tratado de Petrópolis, os conflitos territoriais entre seringueiros brasileiros e bolivianos continuaram ocorrendo.','B',4,false),
(25,'Realidade do Acre','No que se refere ao processo de anexação do Acre ao Brasil, assinale a opção correta: A) As proibições do governo boliviano acerca da instalação da aduaneira boliviana no rio Adquiri e da fundação de um posto alfandegário em Puerto Alonso foram ações que oficializaram a soberania brasileira sobre as fronteiras que definiram o estado do Acre; B) Em 1899, os seringalistas brasileiros executaram um levante contra a taxação da extração do látex e, no mesmo ano, após a revolta, o espanhol Luís Gálvez Rodríguez de Arias proclamou os limites do Estado Independente do Acre; C) A ocupação das terras acreanas por brasileiros teve início na década de 1890, com o desbravamento do rio Amazonas e do rio Acre, que efetivou a presença dos brasileiros em solo acreano, delineando os limites estatais pelo uti possidetis; D) As tensões territoriais findaram quando a Bolívia decidiu conceder, em 1901, através de um tratado, o direito de exploração das riquezas naturais da região por um período de trinta anos ao conglomerado anglo-americano Bolivian Syndicate; E) Em 1867, Brasil, Peru e Bolívia assinaram o Tratado de Ayacucho, momento em que o Brasil incorporou o Acreano, território até então pertencente à Bolívia e com população predominantemente composta por seringalistas brasileiros.','B',4,false),
(26,'Realidade do Acre','O rio nasce em território peruano, em cotas planálticas da ordem de 400 metros, e corre na direção oeste-leste, atuando como divisa entre o Brasil e o Peru, e depois como divisa entre o Brasil e a Bolívia. Percorre mais de 1.190 km desde suas nascentes até a sua desembocadura, na margem direita do Rio Purus. Drena um substrato formado, em grande parte, por unidades geológicas muito jovens — a Formação Solimões e terraços aluvionares antigos. O texto precedente sobre a Bacia Amazônica se refere ao rio: A) Juruá; B) Tarauacá; C) Abunã; D) Purus; E) Acre.','A',4,false),
(27,'Realidade do Acre','Em relação aos aspectos físicos do Acre, que envolvem características de relevo, do solo e da rede hidrográfica do estado, assinale a opção correta: A) A planície amazônica envolve os afluentes mais próximos ao rio Amazonas, por isso só envolve a regional de Cruzeiro do Sul, no norte do estado do Acre; B) A principal unidade geomorfológica do estado é a bacia sedimentar do Acre, composta por material cristalino erodido dos Andes; C) No centro do estado, predominam os cambissolos, os quais envolvem terras das microrregiões de Tarauacá e Sena Madureira; D) A rede hidrográfica do Acre se concentra no centro-norte do estado, e seus rios correm no sentido nordeste/sul; E) A variação altimétrica expressiva faz todo o território do estado do Acre ter predominância de planaltos seguidos de depressões angulares.','A',4,false),
(28,'Realidade do Acre','A balança comercial do estado do Acre registrou superávit de US$ 38,3 milhões nos primeiros 11 meses de 2023. As exportações somaram US$ 43,1 milhões, e as importações, US$ 4,8 milhões. Em referência à balança comercial do estado do Acre, assinale a opção que apresenta dois dos produtos que esse estado mais exporta na atualidade: A) castanha-do-pará e madeiras e seus derivados; B) madeira compensada e resíduos de ferro e aço; C) soja e cortes suínos congelados; D) castanha seca fresca com casca e milho para semeadura; E) milho e leite de seringueira coagulado.','A',4,false),
(29,'Realidade do Acre','No Plano Estratégico de Governo (2023-2026), as necessidades voltadas para o crescimento econômico do estado do Acre correspondem: A) à promoção do desenvolvimento social com o uso sustentável dos recursos naturais e ao aumento do desenvolvimento humano e da equidade de gênero; B) ao desenvolvimento dos serviços voltados para a administração pública e aos investimentos para tornar a indústria siderúrgica forte; C) à dinamização da economia local por meio de intercâmbios internacionais e à formalização de empresas e postos de trabalho; D) ao controle estatal nos serviços de saúde e educação e a maiores subsídios para o agronegócio expandir a produção de soja; E) ao fomento da extração da borracha para a exportação e ao aumento na produção de madeira de lenha para a energia produtiva interna.','E',4,false),
(30,'Realidade do Acre','A balança comercial do estado do Acre vem alcançando recordes, e em 2022 houve um saldo positivo de US$ 49,12 milhões. O Acre exporta em torno de 10 vezes mais do que importa. Com relação à balança comercial do estado do Acre, assinale a opção que indica um dos produtos que tiveram mais participação percentual nas importações desse estado nos últimos cinco anos: A) pneus novos de borracha; B) madeiras tropicais; C) minério de ferro em resíduos; D) miudezas comestíveis de animais; E) soja e milho, exceto para semeadura.','A',4,true),
(31,'Administração Pública','A respeito do orçamento participativo municipal, assinale a opção correta: A) O orçamento participativo começou a ser praticado no Brasil após a promulgação da Carta Magna de 1988; B) O citado orçamento participativo prevê a participação aberta apenas aos representantes de organizações civis do município; C) A decisão de alocação do investimento municipal está sob o poder dos representantes de organizações civis, independentemente de critérios técnicos e orçamentários; D) As discussões públicas acerca do orçamento participativo municipal podem ocorrer somente por meio de consultas públicas; E) Comumente, as discussões públicas do orçamento participativo municipal, no primeiro momento, ocorrem de forma direta, e, em momento posterior, mediante uma forma de representação.','D',5,true),
(32,'Administração Pública','Assinale a opção que apresenta a propriedade dos indicadores de desempenho que diz respeito à qualidade dos dados, primários ou não, utilizados no âmbito do indicador de desempenho, refletindo-se na significância estatística de planos amostrais, imparcialidade dos questionários aplicados em pesquisas de opinião e precisão dos registros administrativos: A) factibilidade dos custos de aquisição; B) historicidade; C) relevância social; D) sensibilidade; E) confiabilidade.','A',5,true),
(33,'Administração Pública','Em relação às organizações da sociedade civil de interesse público (OSCIP), assinale a opção correta: A) A outorga da qualificação de uma organização como OSCIP constitui ato discricionário no deferimento pela administração pública; B) As OSCIP, conceituadas como pessoas jurídicas de direito privado, podem ter fins lucrativos, visando à prestação de serviços sociais não exclusivos do Estado; C) A execução do objeto do contrato de gestão da OSCIP deve ser acompanhada e fiscalizada por órgão do poder público da área de atuação pertinente à atividade fomentada; D) Assistência social, cultura, defesa e conservação do patrimônio histórico e artístico são exemplos de áreas de atuação de OSCIP; E) As instituições hospitalares privadas não gratuitas são passíveis de qualificação como OSCIP.','D',5,true),
(34,'Administração Pública','Assinale a opção que corresponde ao tipo de descentralização que se refere à delegação pela transferência de competências e de funções entre unidades administrativas, entre esferas de governo ou entre órgãos e entidades governamentais e que é defendida como estratégia para obter maior eficácia e eficiência na gestão pública, por meio da eliminação dos níveis burocráticos intermediários: A) descentralização política; B) descentralização orçamentária; C) descentralização administrativa; D) descentralização social; E) descentralização jurídica.','C',5,true),
(35,'Administração Pública','Assinale a opção que corresponde à espécie de critério utilizado na avaliação de políticas públicas e associado à homogeneidade da distribuição de benefícios entre os cidadãos favorecidos: A) equidade; B) eficiência administrativa; C) eficácia; D) eficiência econômica; E) economicidade.','C',5,true),
(36,'Administração Pública','Uma das diretrizes dispostas na Lei n.º 12.527/2011 (Lei de Acesso à Informação) é: A) o fomento ao desenvolvimento da cultura de confidencialidade na administração pública; B) a divulgação de informações de interesse público, independentemente de solicitações; C) a observância do sigilo como preceito geral e da publicidade como exceção; D) o aplacamento do controle social da administração pública; E) a garantia da quebra irrestrita do sigilo das informações públicas.','C',5,true),
(37,'Administração Pública','Segundo a lei de improbidade administrativa, quando determinada autoridade pública, atuando em nome do poder público, causa efetivo e comprovado desvio de recursos com a liberação dolosa de verba pública sem a estrita observância das normas pertinentes, isso: A) configura ato de improbidade que atenta contra os princípios da administração pública; B) configura ato de improbidade que causa lesão ao erário; C) não configura ato de improbidade por ausência de disposição expressa na lei; D) configura ato de improbidade, mesmo que o agente público tenha agido sem intenção; E) configura ato de improbidade que importa enriquecimento ilícito.','E',5,true),
(38,'Administração Pública','Caio, servidor público civil do estado do Acre, atuou como intermediário junto à repartição onde é lotado para fins de agilizar o andamento do pedido administrativo de um vizinho. Nessa situação hipotética, de acordo com o Estatuto dos Servidores Públicos Civis do Estado do Acre, caso aberto processo administrativo disciplinar, Caio: A) poderá ser punido com a pena de advertência; B) poderá ser punido com a pena de demissão; C) poderá ser punido com a pena de suspensão de até 30 dias; D) poderá ser punido com a pena de suspensão de até 90 dias; E) não poderá ser punido, pois a conduta praticada não está prevista em lei.','B',5,true),
(39,'Administração Pública','A lei que regulamenta processos administrativos prevê que nestes será observado, entre outros, o critério de indicação dos pressupostos de fato e de direito que determinarem a decisão. Esse critério corresponde ao princípio da: A) finalidade; B) publicidade; C) motivação; D) legalidade; E) razoabilidade.','D',5,true),
(40,'Administração Pública','Acerca do regime de concessão e permissão da prestação de serviços públicos, julgue os itens a seguir: I A delegação da prestação do serviço público por concessão pode ser feita pelo poder concedente mediante licitação na modalidade concorrência ou diálogo competitivo. II A encampação é uma forma de extinção da concessão pela retomada do serviço público pelo poder concedente durante o prazo da concessão, por motivo de interesse público, mediante lei autorizativa específica e após prévio pagamento de indenização. III A permissão de serviço público é formalizada mediante contrato de adesão e tem como característica a precariedade e a revogabilidade unilateral do contrato pelo poder concedente. Assinale a opção correta: A) Apenas o item I está certo; B) Apenas o item III está certo; C) Apenas os itens I e II estão certos; D) Apenas os itens II e III estão certos; E) Todos os itens estão certos.','E',6,true),
(41,'Administração Pública','Caso a administração pública pretenda adquirir bem ou serviço comum cujo critério de julgamento possa ser o de menor preço ou o de maior desconto, ela deverá se valer da modalidade de licitação: A) pregão; B) leilão; C) concurso; D) concorrência; E) diálogo competitivo.','C',6,true),
(42,'Administração Pública','Determinado órgão de controle fiscalizará o uso de dinheiro público de uma entidade dotada de personalidade jurídica de direito privado, que teve a criação autorizada por lei, tem patrimônio próprio e cujo capital social é integralmente público. Nessa situação hipotética, o órgão de controle fiscalizará uma: A) autarquia; B) empresa pública; C) sociedade de economia mista; D) organização social; E) fundação pública.','E',6,true),
(43,'Administração Pública','Uma sociedade empresária que tenha iniciado suas atividades em 1.º/7/2023 e auferido receita bruta de R$ 200 mil e lucro líquido de R$ 150 mil no ano de 2023 é considerada uma: A) microempresa, com base em seu lucro líquido; B) empresa de pequeno porte, com base em sua receita bruta; C) empresa de pequeno porte, com base em seu lucro líquido; D) microempresa, com base em sua receita bruta; E) empresa que não pode ser abarcada pelo regime da Lei Complementar n.º 123/2006.','B',6,true),
(44,'Administração Pública','De acordo com a Constituição Federal de 1988, a contribuição fixada pela assembleia-geral para custeio do sistema confederativo do respectivo sindicato: A) tem natureza jurídica tributária de contribuição social sindical; B) não tem natureza jurídica de tributo; C) é cobrada de todos os trabalhadores, incluídos os não filiados; D) depende de instituição por lei; E) é compulsória.','A',6,true),
(45,'Direito Tributário','Quando uma indústria de alimentos é obrigada, por lei, a recolher os tributos decorrentes de fatos geradores anteriores à cadeia produtiva rural, essa obrigação decorre da: A) antecipação do pagamento do tributo em relação ao fato gerador; B) responsabilidade tributária por solidariedade; C) responsabilidade tributária por sucessão; D) substituição tributária concomitante; E) substituição tributária regressiva.','A',6,true),
(46,'Direito Tributário','O imposto sobre produtos industrializados (IPI) tem como característica: A) o impacto preponderante sobre bens de capital pelo contribuinte do imposto; B) a possibilidade de fiscalização pelos municípios que assim optarem; C) a seletividade em função da essencialidade do produto; D) a progressividade das alíquotas; E) a incidência sobre produtos destinados ao consumo interno e externo.','E',6,true),
(47,'Direito Tributário','De acordo com a Constituição Federal de 1988, o recolhimento do imposto correspondente à diferença entre a alíquota interna e a interestadual de ICMS cabe: A) ao remetente, quando o destinatário não for contribuinte do imposto; B) ao responsável previsto na legislação tributária do ente de residência do destinatário; C) ao remetente, quando nenhuma das partes for contribuinte; D) ao destinatário, quando nenhuma das partes for contribuinte; E) tanto ao destinatário quanto ao remetente, sendo glosada pela metade no caso em que ambos forem contribuintes.','C',6,true),
(48,'Direito Tributário','Conforme a Constituição Federal de 1988, o ICMS monofásico incidente nas operações com lubrificantes derivados de petróleo caberá ao(s) estado(s): A) onde ocorrer o consumo; B) onde ocorrer o refino do produto; C) titular dos royalties de exploração da matéria-prima; D) de origem e de destino, mediante repartição; E) de domicílio do produtor.','C',6,true),
(49,'Direito Constitucional','Acerca das ações constitucionais de proteção dos direitos fundamentais, assinale a opção correta: A) A ação de habeas corpus surgiu, no direito brasileiro, com a promulgação da Constituição Federal de 1988; B) Pode-se formular pedido de habeas corpus em favor de indivíduo mesmo antes que ele sofra restrição ilegal de sua liberdade de locomoção; C) A ação de mandado de segurança deve ser proposta contra o órgão ou ente público do qual tenha surgido o ato ilegal; D) A finalidade da ação de habeas data limita-se a permitir o acesso de alguém a informações que lhe digam respeito; E) Não cabe mandado de segurança contra ato omissivo.','D',6,true),
(50,'Direito Constitucional','No que se refere à intervenção federal e à intervenção dos estados nos municípios, assinale a opção correta: A) Um dos mecanismos previstos expressamente na legislação brasileira para situações de crise é a intervenção militar constitucional; B) A intervenção pode ser decretada pelo presidente da República, pelos governadores e pelos prefeitos municipais; C) Os motivos constitucionais para intervenção têm cunho político, de modo que não é cabível intervenção com a finalidade de executar ordem judicial; D) Uma vez decretada a intervenção, a autoridade deve justificá-la ao Poder Legislativo no prazo de até seis meses; E) A intervenção federal somente pode ser decretada nos casos definidos de forma expressa na Constituição Federal de 1988.','D',7,true),
(51,'Direito Constitucional','Em relação ao Poder Judiciário, assinale a opção correta: A) A garantia de vitaliciedade assegura que os integrantes do Poder Judiciário não percam o cargo em hipótese alguma; B) A função exclusiva do Poder Judiciário consiste em julgar litígios concretos entre pessoas físicas e jurídicas, bem como entre órgãos e entes da administração pública; C) O ingresso como membro do Poder Judiciário requer necessariamente aprovação em concurso público de provas e títulos; D) O Conselho Nacional de Justiça representa um dos mecanismos de controle externo do Poder Judiciário; E) Todos os processos a serem julgados pelo Supremo Tribunal Federal devem chegar lá por meio de recursos específicos, com requisitos especiais.','E',7,true),
(52,'Direito Constitucional','A ação direta de inconstitucionalidade: A) é uma via processual para controle de qualquer ato que possa haver ferido a Constituição; B) somente pode ser proposta pelo presidente da República ou pelo procurador-geral da República; C) não admite concessão de medida liminar; D) é cabível para questionamento acerca da constitucionalidade de emenda constitucional; E) produz decisões cuja observância é obrigatória apenas para as partes do processo.','B',7,true),
(53,'Direito Constitucional','No que se refere aos direitos das populações indígenas e das comunidades remanescentes de quilombos, julgue os itens: I As terras ocupadas tradicionalmente pelas comunidades indígenas não podem ser vendidas. II Os indígenas têm direito às terras que tradicionalmente ocupam, ainda que não estejam demarcadas. III A Constituição Federal de 1988 considera objeto de tombamento os locais onde haja reminiscências históricas de antigos quilombos. IV As comunidades remanescentes de quilombos têm o direito de se autoidentificarem dessa maneira. Assinale a opção correta: A) Apenas os itens I e II estão certos; B) Apenas os itens I e IV estão certos; C) Apenas os itens II e III estão certos; D) Apenas os itens III e IV estão certos; E) Todos os itens estão certos.','E',7,true),
(54,'Direito Constitucional','À luz do que estabelece a Constituição do Estado do Acre, assinale a opção correta: A) No território do Acre, apenas a Assembleia Legislativa pode produzir leis; B) No caso de vacância dos cargos de governador e vice-governador, o presidente do Tribunal de Justiça do Estado será chamado a exercer essas funções; C) Sempre que aberta vaga de deputado estadual, deve-se realizar eleição para preenchê-la; D) Os juízes do estado do Acre podem exercer atividade partidária, nos casos autorizados pela Constituição do Estado; E) O governador que, durante o mandato, tomar posse em outro cargo público em razão de concurso não necessariamente perderá o cargo de governador.','B',7,true),
(55,'Orçamento Público','Acerca do orçamento público, assinale a opção correta: A) A lei de diretrizes orçamentárias (LDO) estabelecerá as metas, as diretrizes e os objetivos da administração pública, levando em consideração a região em que forem feitas as despesas de capital e as despesas relativas aos programas de duração continuada; B) O PPA conterá reserva de contingência, cuja forma de utilização e montante, definido com base na receita corrente líquida, serão estabelecidos na LOA, em conformidade com a Lei de Responsabilidade Fiscal; C) A LOA compreenderá o orçamento monetário das empresas nas quais o Estado detenha a maioria do capital social, o orçamento fiscal com as despesas relativas à previdência, à saúde e à assistência social e o orçamento da seguridade social com as demais despesas correntes; D) No orçamento da União, a LDO não poderá dispor sobre a exclusão de quaisquer despesas primárias da apuração da meta de resultado primário dos orçamentos fiscal e da seguridade social; E) O plano plurianual (PPA) estabelecerá as metas e as prioridades da administração pública e trará as orientações para a elaboração da lei orçamentária anual (LOA), além das políticas de aplicação das agências financeiras oficiais de fomento.','A',7,true),
(56,'Orçamento Público','Considerando a figura das etapas da receita orçamentária (previsão, planejamento; lançamento, arrecadação, recolhimento, execução), assinale a opção correta a respeito das etapas da receita orçamentária: A) Nem todas as etapas apresentadas na figura acontecem para todos os tipos de receitas orçamentárias, pois pode ocorrer arrecadação de receitas não previstas e das que não foram lançadas; B) Na fase do lançamento, os recursos financeiros do superávit do orçamento corrente do ano anterior devem ser registrados como receitas correntes; C) As receitas de capital que aumentam as disponibilidades financeiras do Estado provocam efeito sobre o patrimônio líquido e não obedecem a todas as etapas da receita orçamentária; D) No lançamento da receita, são considerados os efeitos das alterações na legislação e a variação do índice de preços, sendo acompanhado de demonstrativo de evolução da receita nos últimos dois anos e da sua projeção para os três seguintes; E) A arrecadação consiste na transferência dos valores arrecadados à conta específica do governo, responsável pela administração e controle da arrecadação e pela programação financeira.','C',8,true),
(58,'Orçamento Público','Em relação aos convênios regidos pela Instrução Normativa STN n.º 1/1997, assinale a opção correta: A) Nos contratos de repasse, a apresentação do projeto básico ou do termo de referência poderá ser feita após a primeira liberação da parcela de recursos; B) Somente no caso de denúncia ou rescisão do convênio, os saldos financeiros remanescentes, excluindo os provenientes de receitas de aplicações, serão devolvidos ao órgão repassador, no prazo improrrogável de 30 dias do evento, sob pena de instauração de tomada de contas especial; C) Convenente é o órgão da administração pública federal direta, autárquica ou fundacional, empresa pública ou sociedade de economia mista responsável pela transferência dos recursos financeiros ou pela descentralização dos créditos orçamentários destinados à execução do objeto do convênio; D) Quando da rescisão do convênio poderá ocorrer a tomada de contas especial por eventuais prejuízos causados ao ente público, sendo a tomada de conta especial um processo judicial instaurado depois de esgotadas as medidas administrativas para reparação do dano ao erário; E) Os elementos que compõem a prestação de contas devem permitir à administração a comprovação da legalidade dos atos praticados e o efetivo cumprimento do objeto do convênio ou do contrato de repasse.','E',8,true),
(59,'Orçamento Público','Assinale a opção correta a respeito da metodologia de trabalho do Sistema de Controle Interno (SCI), disciplinada pela Instrução Normativa SFC/MF n.º 1/2001: A) A auditoria de avaliação da gestão é realizada com o objetivo de se atuar em tempo real sobre os atos efetivos e as consequências potenciais positivas e negativas de um ente público, prevenindo gargalos ao desempenho da sua missão institucional; B) A auditoria contábil tem entre seus objetivos verificar a efetividade e a aplicação de recursos externos, oriundos de agentes financeiros e organismos internacionais, por unidades ou entidades públicas executoras de projetos celebrados com aqueles organismos com vistas a emitir opinião sobre a adequação e a fidedignidade das demonstrações financeiras; C) Os recursos que podem ser objeto da atuação do sistema de controle interno limitam-se aos valores originários da LOA, de créditos adicionais e de operações de crédito da União; D) No procedimento de auditoria, a adoção da técnica de testes de observância tem por finalidade a coleta de evidências quanto à suficiência, à exatidão e à validação das informações contábeis da entidade; E) O controle assistemático tem como premissa a existência de um processo detalhado de planejamento, que é a base para a deflagração das ações do controle, inclusive para as questões pontuais e agudas como aquelas oriundas de solicitação de autoridades.','E',8,true),
(60,'Orçamento Público','Acerca do controle externo e do sistema de controle interno do Poder Executivo Federal, assinale a opção correta: A) É atribuição exclusiva dos tribunais de contas dos estados, no exercício da sua função de controle externo, fiscalizar a aplicação de quaisquer recursos repassados pela União mediante convênio, acordo, ajuste ou outros instrumentos congêneres, ao estado, ao Distrito Federal ou ao município; B) As auditorias a cargo dos órgãos setoriais que precisem ser executadas de forma descentralizada nos estados, incluindo a execução de convênios, acordos e contratos, poderão ser realizadas pela Secretaria Federal de Controle Interno; C) Os órgãos setoriais, as unidades de controle interno dos estados da federação e as unidades de controle interno da União integram o Sistema de Planejamento e de Orçamento Federal; D) Entre as finalidades do Sistema de Planejamento e de Orçamento Federal encontra-se a formulação de planos nacionais, estaduais e regionais de desenvolvimento econômico e social, assim como a articulação com os estados visando à compatibilização de normas e tarefas afins aos diversos sistemas, nos planos federal e estadual; E) Com finalidade de evitar a dupla responsabilidade nas atribuições de auditorias, os recursos financeiros recebidos pelos estados decorrentes da transferência de órgãos e das entidades da administração direta e indireta da União não podem ser registrados nos seus respectivos orçamentos.','B',9,true)
)
insert into public.official_exam_questions (
  question_source_id, answer_key_source_id, syllabus_topic_id,
  contest_name, exam_year, career_name, exam_board,
  item_number, subject, question_text, raw_extraction, official_answer, source_page,
  content_status, legal_review_required, context_review_required, legal_basis, review_note
)
select
  sources.prova_id,
  case when imported.is_specifico then sources.gab_especificos_id else sources.gab_gerais_id end,
  topics.topic_id,
  'SEFAZ/AC - Secretaria de Estado da Fazenda do Acre', 2023, 'Especialista da Fazenda Estadual', 'CEBRASPE',
  imported.item_number, imported.subject, imported.question_text, imported.question_text,
  imported.official_answer, imported.source_page,
  case when imported.subject = 'Direito Constitucional' then 'under_review' else 'active' end,
  imported.subject = 'Direito Constitucional', false, '[]'::jsonb,
  case when imported.subject = 'Direito Constitucional'
    then 'Conferida contra a foto original da prova e contra o gabarito oficial definitivo do CEBRASPE (aplicação 02/06/2024). Aguardando auditoria jurídica individual (legal_basis + verificação de vigência) exigida pelo CONTENT_GOVERNANCE.md antes de ficar ativa para estudo.'
    else 'Conferida contra a foto original da prova e contra o gabarito oficial definitivo do CEBRASPE (aplicação 02/06/2024).'
  end
from imported
cross join sources
join topics on topics.discipline = imported.subject
on conflict (contest_name, exam_year, item_number) do update set
  subject = excluded.subject,
  question_text = excluded.question_text,
  raw_extraction = excluded.raw_extraction,
  official_answer = excluded.official_answer,
  source_page = excluded.source_page,
  content_status = excluded.content_status,
  legal_basis = excluded.legal_basis,
  review_note = excluded.review_note,
  verified_at = now();
