-- Importação das questões do concurso Prefeitura de Feijó 2017 (Edital nº 005/2017, FUNDAPE),
-- cargo Professor - Licenciatura Plena - Pedagogo, itens 1-34, a partir das fotos da prova do
-- candidato. Os itens 35-40 não constam nas fotos e NÃO foram cadastrados.
--
-- GABARITO: o gabarito oficial da FUNDAPE de 2017 não foi localizado online. As respostas dos
-- itens que o candidato acertou foram confirmadas pela correção dele nas fotos (visto) e pela nota
-- oficial; as dos itens que errou vêm da correção dele nas fotos ou de cálculo/conferência
-- (matemática, atualidades, LDB). Itens sem confirmação segura ficam 'under_review'; Q10 e Q24 são
-- anuladas (X); Q23 e Q32 são obsoletas (valor do salário mínimo / Lei 11.494/2007 revogada).
--
-- Também corrige o resultado do candidato: as questões 16 e 20 foram respondidas (B e C) e estão
-- erradas, não em branco (23 certas, 9 erradas, 2 anuladas).

insert into public.content_sources (source_type,title,issuer,url,published_on,status,is_official,notes) values
('edital','Edital de Concurso Público nº 005/2017','Prefeitura Municipal de Feijó-AC / Fundape','https://jcconcursos.com.br/media/uploads/anexos/2017/ac-feijo-pref-edital-ed-1924.pdf','2017-10-20','vigente',true,'Edital do concurso de 2017 (Quadro 07: nível superior, 40 questões, 100 pontos).'),
('outro','Correção da prova pelo candidato (fotos) - Feijó 2017','Candidato (conferência própria)','https://www.qconcursos.com/questoes-de-concursos/concursos/prefeitura-de-feijo-ac-2017-edital-n-005#correcao-candidato',null,'em_revisao',false,'Gabarito oficial da FUNDAPE de 2017 não localizado online; respostas conferidas pela correção do candidato nas fotos, pela nota oficial (59,5) e por cálculo. Substituir pelo gabarito oficial quando localizado.')
on conflict (url) do update set checked_at=now(), status=excluded.status, notes=excluded.notes;

insert into public.syllabus_editions (contest_name,role_name,contest_year,exam_board,source_id,status)
select 'Prefeitura de Feijó','Professor - Licenciatura Plena - Pedagogo',2017,'Fundape',id,'active'
from public.content_sources where url='https://jcconcursos.com.br/media/uploads/anexos/2017/ac-feijo-pref-edital-ed-1924.pdf'
on conflict (contest_name,role_name,contest_year) do update set source_id=excluded.source_id, status='active';

with edition as (
  select id from public.syllabus_editions
  where contest_name='Prefeitura de Feijó' and role_name='Professor - Licenciatura Plena - Pedagogo' and contest_year=2017
)
insert into public.syllabus_topics (edition_id,block_name,discipline,topic_order,topic_text)
select edition.id, data.block_name, data.discipline, 1, data.topic_text from edition cross join (values
('Bloco Único','Língua Portuguesa','Interpretação de textos (crônica, poema), acentuação gráfica, figuras de linguagem, classes de palavras, crase, funções da linguagem, denotação e conotação, orações coordenadas e subordinadas — conforme cobrado nas questões 1 a 10 do caderno.'),
('Bloco Único','Matemática','Matemática financeira (juros simples e compostos), probabilidade, análise combinatória, lógica proposicional, conjuntos, razão e proporção, funções — conforme cobrado nas questões 11 a 20 do caderno.'),
('Bloco Único','Conhecimentos Gerais e Atualidades','Fatos nacionais e internacionais de 2017, geografia política do Acre — conforme cobrado nas questões 21 a 25 do caderno.'),
('Bloco Único','Pedagogia','Planejamento escolar, avaliação (diagnóstica, formativa, somativa), formação docente, psicologia da educação, LDB, FUNDEB e Diretrizes Curriculares Nacionais — conforme cobrado nas questões 26 a 34 do caderno.')
) as data(block_name,discipline,topic_text)
on conflict (edition_id,discipline,topic_order) do update set topic_text=excluded.topic_text, content_status='current';

with sources as (
  select
    (select id from public.content_sources where url='https://jcconcursos.com.br/media/uploads/anexos/2017/ac-feijo-pref-edital-ed-1924.pdf') as prova_id,
    (select id from public.content_sources where url='https://www.qconcursos.com/questoes-de-concursos/concursos/prefeitura-de-feijo-ac-2017-edital-n-005#correcao-candidato') as gabarito_id
),
topics as (
  select t.discipline, t.id as topic_id
  from public.syllabus_topics t
  join public.syllabus_editions e on e.id = t.edition_id
  where e.contest_name='Prefeitura de Feijó' and e.role_name='Professor - Licenciatura Plena - Pedagogo' and e.contest_year=2017
),
imported(item_number,subject,question_text,official_answer,source_page,content_status,legal_review_required,context_review_required,review_note) as (values
(1,'Língua Portuguesa','Texto I (tema: timidez; texto completo não consta nas fotos). No texto I, o autor motiva o leitor a uma complexa análise comportamental sobre "O que é ser tímido". Com relação ao trecho "... É gastar pérolas ou suéteres onde não deve." (l.27), pode-se inferir que o autor acredita que: A) o ser tímido reluta em dizer certas coisas a quem não sabe compreendê-las ou apreciá-las, pois é o mesmo que jogar pérolas aos porcos; B) o ser tímido evita jogar pérolas aos porcos, pois perderá suas pérolas e os porcos não saberão o que fazer com elas; C) em alguns momentos, o indivíduo tímido guarda as palavras, pois não é prudente gastar pérolas ou suéteres onde não se deve; D) o ser tímido não hesita em dizer certas coisas a quem não sabe compreendê-las ou apreciá-las, pois é o mesmo que jogar pérolas aos porcos; E) os tímidos abstêm-se da preocupação de não gastar pérolas ou suéteres onde não devem.','E',3,'under_review',false,true,'Texto I completo (págs. 1-2 do caderno) não está nas fotos; item mantido em revisão até a inclusão do texto. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(2,'Língua Portuguesa','Texto I. Em cada uma das opções a seguir é apresentada uma proposta de reescrita para o seguinte período do texto I: "E curtir até com soberbas emoções de somenos para os outros, e ser humilde naquilo de que os demais se orgulham." (l.15 e 16). Assinale a opção em que a proposta apresentada preserva o sentido do referido trecho. A) É curtir até com inferioridade emoções de somenos para os outros, e ser humilde naquilo de que os demais se orgulham; B) É curtir até com chaneza emoções de somenos para os outros, e ser humilde naquilo de que os demais se orgulham; C) É curtir até com chaneza emoções de grande valor para os outros, e ser humilde naquilo de que os demais se orgulham; D) É curtir até com empáfia emoções sem importância para os outros, e ser humilde naquilo de que os demais se orgulham; E) É curtir até com superioridade emoções de grande valor para os outros, e ser humilde naquilo de que os demais se orgulham.','D',3,'under_review',false,true,'Texto I completo não está nas fotos; item mantido em revisão. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(3,'Língua Portuguesa','Texto I. "Ser tímido é sentir alegria no que não dá resultado e enfadar-se com as vitórias. É esperar algo que não se sabe, mas se aguarda com fé." (l.21, 22 e 23). Sobre o período e as orações que o constituem (texto 1), é correto afirmar que: A) o período é composto por duas orações; B) todas as orações do período são subordinadas; C) a última oração é coordenada sindética adversativa; D) o período é composto por três orações; E) temos duas orações coordenadas e duas orações subordinadas.','C',3,'under_review',false,true,'Texto I completo não está nas fotos; item mantido em revisão. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(4,'Língua Portuguesa','Texto I. As duas palavras do texto I que são acentuadas graficamente em função da mesma regra são: A) insuportável / solidão; B) tímido / último; C) tímido / próprio; D) impossível / solidão; E) próprio / olímpico.','B',4,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(5,'Língua Portuguesa','Texto II ("Você já foi à Bahia?", Jorge Amado): "E, quando a viola gemer nas mãos do seresteiro na rua trepidante da cidade mais agitada, não tenhas moça, um só minuto de indecisão. Atende ao chamado e vem. A Bahia te espera para a sua festa quotidiana. Teus olhos se encharcarão de pitoresco, mas se entristecerão também ante a miséria que sobra nestas ruas onde começam a subir, magros e feios os arranha-céus modernos. Verás as igrejas, grávidas de ouro. Dizem que são trezentas e sessenta e cinco. Talvez não sejam tantas, mas que importa? Onde estará mesmo a verdade quando ela se refere a esta cidade da Bahia? Nunca se sabe bem o que é verdade e o que é mentira nesta cidade. No seu mistério lírico e na sua trágica pobreza, a verdade e a lenda se confundem[...]". O texto II é um fragmento de um guia turístico da cidade de Salvador. Para o autor, há um momento em que se deseja conhecer a cidade. A passagem do texto que define esse momento é: A) "A Bahia te espera para a sua festa cotidiana"; B) "quando a viola gemer nas mãos do seresteiro na rua trepidante da cidade mais agitada"; C) "Teus olhos se encharcarão de pitoresco..."; D) "Atende ao chamado e vem."; E) "Onde estará mesmo a verdade quando ela se refere a esta cidade da Bahia?"','B',4,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(6,'Língua Portuguesa','Texto II ("Você já foi à Bahia?", Jorge Amado): "E, quando a viola gemer nas mãos do seresteiro na rua trepidante da cidade mais agitada, não tenhas moça, um só minuto de indecisão. Atende ao chamado e vem. A Bahia te espera para a sua festa quotidiana. Teus olhos se encharcarão de pitoresco, mas se entristecerão também ante a miséria que sobra nestas ruas onde começam a subir, magros e feios os arranha-céus modernos. Verás as igrejas, grávidas de ouro. Dizem que são trezentas e sessenta e cinco. Talvez não sejam tantas, mas que importa? Onde estará mesmo a verdade quando ela se refere a esta cidade da Bahia? Nunca se sabe bem o que é verdade e o que é mentira nesta cidade. No seu mistério lírico e na sua trágica pobreza, a verdade e a lenda se confundem[...]". "Verás as igrejas, grávidas de ouro. Dizem que são trezentas e sessenta e cinco." O trecho do texto II, em destaque, exemplifica qual figura de linguagem? A) Metáfora; B) Ironia; C) Hipérbole; D) Pleonasmo; E) Zeugma.','A',4,'active',false,false,'Candidato marcou C (hipérbole) e errou. A alternativa A (metáfora) aparece destacada na correção do candidato na foto: "grávidas de ouro" atribui às igrejas uma qualidade por semelhança (cheias de ouro), sem comparativo explícito; a hipérbole estaria em "trezentas e sessenta e cinco", fora do trecho destacado.'),
(7,'Língua Portuguesa','Texto II ("Você já foi à Bahia?", Jorge Amado): "E, quando a viola gemer nas mãos do seresteiro na rua trepidante da cidade mais agitada, não tenhas moça, um só minuto de indecisão. Atende ao chamado e vem. A Bahia te espera para a sua festa quotidiana. Teus olhos se encharcarão de pitoresco, mas se entristecerão também ante a miséria que sobra nestas ruas onde começam a subir, magros e feios os arranha-céus modernos. Verás as igrejas, grávidas de ouro. Dizem que são trezentas e sessenta e cinco. Talvez não sejam tantas, mas que importa? Onde estará mesmo a verdade quando ela se refere a esta cidade da Bahia? Nunca se sabe bem o que é verdade e o que é mentira nesta cidade. No seu mistério lírico e na sua trágica pobreza, a verdade e a lenda se confundem[...]". Um dos aspectos do estudo dos vocábulos é o que procura verificar se ocorre uma variação ou flexão. Assim, as palavras classificam-se em variáveis e invariáveis. Considerando este aspecto, observe o seguinte trecho do texto II: "Teus olhos se encharcarão de pitoresco, mas se entristecerão também ante a miséria que sobra nestas ruas onde começam a subir, magros e feios os arranha-céus modernos." A opção que destaca do texto apenas palavras invariáveis é: A) mas – também – onde – se; B) teus – onde – se – mas; C) pitoresco – onde – de – se; D) sobra – nestas – ruas – mas; E) mas – estas – se – teus.','A',4,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(8,'Língua Portuguesa','Observe o título do texto II: "Você já foi à Bahia?" e analise a alternativa que melhor justifique o emprego da crase: A) O uso da crase é opcional, pois geralmente o acento indicador da existência de crase é facultativo antes de pronomes possessivos femininos; B) crase nunca ocorrerá antes de substantivo masculino; C) antes de nomes próprios de pessoas femininos e antes de pronomes possessivos femininos, pode ou não ocorrer a crase, portanto, o uso é facultativo; D) Haverá crase quando o termo anterior exigir a preposição "a" e o termo posterior admitir o artigo definido "a"; E) O verbo IR não aceita a preposição "a" e o nome do lugar vem antecedido do artigo definido "a".','D',5,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(9,'Língua Portuguesa','Textos A (Catar feijão, João Cabral de Melo Neto: "Catar feijão se limita com escrever: / Jogam-se os grãos na água do alguidar / E as palavras na da folha de papel; / e depois, joga-se fora o que boiar. [...]"), B (Vinícius de Morais: "De tudo ao meu amor serei atento / Antes, e com tal zelo, e sempre, e tanto, / Que mesmo em face do maior encanto / Dele se encante mais meu pensamento."), C (Duarte, M. O guia dos curiosos: a biosfera se divide em ecossistemas, que têm mecanismos que regulam o número de organismos) e D (Piza, D.: "hoje podemos dizer que não sabemos como era a vida antes do computador"). Nos textos A, B, C e D, predominam respectivamente, as seguintes funções da linguagem: A) função poética, função emotiva, função referencial e função metalinguística; B) função metalinguística, função emotiva, função referencial e função referencial; C) função poética, função conativa, função referencial e função referencial; D) função emotiva, função metalinguística, função referencial e função fática; E) função referencial, função poética, função referencial e função conativa.','B',5,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos. Textos C e D resumidos a partir da foto.'),
(10,'Língua Portuguesa','Os trechos a seguir são exemplos de denotação e conotação. I - "Tantas palavras / Que eu conhecia / E já não falo mais, jamais / Quantas palavras / Que ela adorava / Saíram de cartaz" (conotativo); II - "A ciência que se constituiu em torno dos fatos da língua passou por três fases sucessivas antes de reconhecer seu verdadeiro e único objeto" (denotativo); III - "Humorismo é a arte de fazer cócegas no raciocínio dos outros." (conotativo); IV - "O Araketu quando toca deixa todo mundo pulando que nem pipoca." (conotativo). Sobre o que foi dito nas afirmativas acima, pode-se concluir que: A) Todas as afirmativas estão corretas; B) Está correta apenas a afirmativa I; C) Estão corretas as afirmativas I, III e IV; D) Estão corretas as afirmativas II, III e IV; E) Está correta apenas a afirmativa III.','X',6,'annulled',false,false,'Questão ANULADA pela banca (conferência anterior registrada na migration 20260928040000); pontos creditados a todos os candidatos.'),
(11,'Matemática','Um diretor de uma escola do município de Feijó-AC, necessita realizar uma compra de material de papelaria para a sua escola. Ele observou que alguns produtos eram vendidos em kits promocionais e outros não. Tabela de preços: 1 kit com três pincéis = R$ 15,00; 1 resma de papel = R$ 13,00; 1 kit com 4 apagadores = R$ 10,00; 1 kit com 20 folhas de papel EVA = R$ 30,00. O diretor necessita comprar as seguintes quantidades: 180 pincéis, 40 resmas de papel, 32 apagadores e 60 folhas de EVA. Sendo assim, ele gastará nesta compra o valor de: A) R$ 4.470,00; B) R$ 2.680,00; C) R$ 1.770,00; D) R$ 1.590,00; E) R$ 885,00.','D',6,'active',false,false,'Cálculo: pincéis 180 x R$ 5,00 = 900; resmas 40 x 13 = 520; apagadores 32 x R$ 2,50 = 80; folhas de EVA 60 x R$ 1,50 = 90; total R$ 1.590,00. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(12,'Matemática','A tabela a seguir representa o número de eleitores do município de Feijó-AC, por grupos de idade no ano de 2010, segundo o IBGE: 16 e 17 anos = 719; 18 a 69 anos = 17695; 70 anos ou mais = 1319. Considerando as informações apresentadas na tabela anterior, pode-se dizer que os eleitores mais jovens (entre 16 e 17 anos) representaram no município de Feijó em 2010 aproximadamente: A) 7,19% dos eleitores do município; B) 6,80% dos eleitores do município; C) 5,00% dos eleitores do município; D) 4,64% dos eleitores do município; E) 3,64% dos eleitores do município.','E',6,'active',false,false,'Cálculo: total 719 + 17.695 + 1.319 = 19.733; 719 / 19.733 = 3,64%. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(13,'Matemática','Tabela de estabelecimentos de saúde (Feijó / Acre / Brasil): Federais 0 / 11 / 950; Estaduais 1 / 47 / 1.318; Municipais 9 / 230 / 49.753; Privados 1 / 92 / 42.049. Suponha que uma entidade não governamental resolva patrocinar um dos estabelecimentos públicos do município de Feijó e resolva fazer isso através de um sorteio somente entre tais estabelecimentos. Suponha que todas as unidades públicas de Feijó têm a mesma chance de serem sorteadas. Com base nestas informações, a probabilidade deste estabelecimento de saúde ser da esfera municipal é de: A) 9/10; B) 9/11; C) [alternativa ilegível na foto]; D) [alternativa ilegível na foto]; E) 1/12.','A',7,'under_review',false,true,'Alternativas C e D ilegíveis na foto; item mantido em revisão. Cálculo da resposta: públicos de Feijó = 0 + 1 + 9 = 10; municipais = 9; probabilidade = 9/10 (A).'),
(14,'Matemática','Um professor de matemática do Ensino Fundamental do município de Feijó-AC, verificou que 1/4 (um quarto) dos seus alunos são da zona urbana do município. Dentre os alunos que são da zona rural, 30% apresentam deficiência em multiplicação por números decimais. Se a sala de aula deste professor é composta por 40 alunos, pode-se dizer que: A) 3 alunos da zona urbana apresentam dificuldades em realizar operações com números decimais; B) 10 alunos desta sala são da zona rural; C) 12 alunos desta sala apresentam dificuldades em realizar operações com números decimais; D) 12 alunos desta sala são da zona urbana; E) 9 alunos desta sala são da zona rural e apresentam dificuldades em realizar operações com números decimais.','E',7,'active',false,false,'Cálculo: urbana = 40 / 4 = 10; rural = 30; 30% de 30 = 9. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(15,'Matemática','Um médico receita a um paciente um Xarope que vem num frasco contendo 120 cm³. Na receita consta que o paciente deve tomar esta medicação na quantidade de 5 mL e de 6 em 6 horas. O número de vezes que este paciente deverá tomar este medicamento para esvaziar todo o frasco é: A) 15; B) 20; C) 24; D) 30; E) 40.','C',7,'active',false,false,'Cálculo: 120 cm³ = 120 mL; 120 / 5 = 24 doses. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(16,'Matemática','Um grupo com 5 enfermeiros, 4 médicos e 10 professores desejam realizar uma comissão para discutirem na câmara de vereadores de uma cidade um projeto de Iniciativa popular. A comissão será composta por 9 pessoas e deverá ter exatamente 3 enfermeiros, 2 médicos e 4 professores. Neste sentido, o número de comissões distintas que podem ser formadas é: A) 24; B) 200; C) 226; D) 12600; E) 3.628.800.','D',7,'active',false,false,'Candidato marcou B e errou. Cálculo: C(5,3) x C(4,2) x C(10,4) = 10 x 6 x 210 = 12.600 (D).'),
(17,'Matemática','Considere as seguintes proposições lógicas: - Se Eduardo vai a França então Ana é uma criança; - Se Ana é uma criança então Luís é campeão de natação; - Se Luís é campeão de natação então Moisés não era um profeta. Sabe-se que Moisés era um profeta, logo: A) Eduardo vai a França; B) Eduardo não vai a França; C) Luís é campeão de natação; D) Luís é campeão de natação e Eduardo não vai a França; E) Luís não é campeão de natação e Eduardo vai a França.','B',8,'active',false,false,'Raciocínio: Moisés era profeta, logo Luís não é campeão (contrapositiva da 3ª), logo Ana não é criança (2ª), logo Eduardo não vai à França (1ª). Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(18,'Matemática','Uma escola do município de Feijó-AC, resolveu realizar uma pesquisa sobre as preferências de seus alunos por alguns estilos musicais. Resultados: 100 alunos gostam de Rock; 50 de música Gospel; 40 de Sertanejo; 30 gostam de sertanejo e de música gospel; 20 de rock e música gospel; 15 de rock e sertanejo; 5 gostam dos três estilos; 25 afirmaram não gostar de nenhum destes três estilos. Neste sentido, considerando que todos os alunos participaram da pesquisa, pode-se dizer que o número de alunos desta escola é igual a: A) 285; B) 155; C) 130; D) 110; E) 100.','B',8,'active',false,false,'Candidato marcou A e errou. Cálculo: união = 100 + 50 + 40 - 30 - 20 - 15 + 5 = 130; mais 25 que não gostam de nenhum = 155 (B).'),
(19,'Matemática','João aplicou R$ 2.000,00 a uma taxa de juros simples de 6% ao mês durante 12 meses. Por sua vez, José aplicou a mesma quantia a uma taxa de juros compostos de 5% ao mês também durante um ano. Com base nestas informações pode-se dizer que [Considere que 1,05^12 = 1,7959]: A) O montante obtido por João foi maior, tendo em vista que a taxa de juros de sua aplicação era maior do que a de José; B) O montante obtido por João foi de R$ 1.440,00; C) O montante obtido por José foi o dobro daquele obtido por João; D) Os dois receberam ao final dos 12 meses exatamente a mesma quantia relativa ao montante da aplicação; E) O montante obtido por José foi de R$ 3.591,80 um pouco superior ao obtido por João que foi de R$ 3.440,00.','E',8,'active',false,false,'Cálculo: João = 2.000 x (1 + 0,06 x 12) = 3.440; José = 2.000 x 1,7959 = 3.591,80. Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(20,'Matemática','Um gestor público tem em suas mãos dois planos de telefonia do qual deve escolher o melhor para sua administração: Plano A: R$ 70,00 fixo mais R$ 0,05 por cada minuto de ligação; Plano B: R$ 55,00 fixo mais R$ 0,06 por cada minuto de ligação. Considerando estas opções, pode-se dizer que: A) O Plano A é melhor do que o Plano B em qualquer cenário, pois apresenta um valor a ser pago por minuto de ligação menor; B) O Plano B se torna mais caro que o Plano A depois de 25 horas de ligações; C) O Plano A e o Plano B fornecem o mesmo valor de despesa para até 30 horas de ligações; D) O Plano A é mais caro que o Plano B a partir de 30 horas de ligações; E) O Plano B é sempre melhor que o Plano A em qualquer cenário, pois apresenta uma taxa fixa menor.','B',8,'active',false,false,'Candidato marcou C e errou. Cálculo: 70 + 0,05t = 55 + 0,06t, logo t = 1.500 min = 25 h; depois disso o Plano B fica mais caro (B).'),
(21,'Conhecimentos Gerais e Atualidades','Recentemente, nos Estados Unidos, um atirador abriu fogo contra uma igreja batista, deixando dezenas de mortos e feridos. O atirador foi identificado como Devin Patrick Kelley, de 26 anos, e aparentemente não tem ligação com organizações terroristas. Este ataque ocorreu na cidade de: A) Nova York, NY; B) Las Vegas, em Nevada; C) Oklahoma City; D) Sutherland Springs, no Texas; E) Orlando, na Flórida.','D',9,'active',false,false,'Candidato marcou C e errou. O ataque de novembro de 2017 à First Baptist Church ocorreu em Sutherland Springs, Texas (D).'),
(22,'Conhecimentos Gerais e Atualidades','Em 2017, o Exame Nacional do Ensino Médio (Enem) foi aplicado pela primeira vez em dois finais de semana consecutivos. Por determinação do Supremo Tribunal Federal (STF), as redações que contiverem trechos que desrespeitem os direitos humanos não receberão mais nota zero, mantendo a decisão anterior da Justiça Federal, que suspendeu o item do edital da prova que previa nota zero à redação "que apresente impropérios, desenhos e outras formas propositais de anulação, bem como que desrespeite os direitos humanos". A medida foi confirmada pela presidente do STF, ministra: A) Cármen Lúcia; B) Rosa Weber; C) Ellen Gracie; D) Luislinda Valois; E) Marta Suplicy.','A',9,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos. Item de atualidades: a presidência do STF muda a cada dois anos.'),
(23,'Conhecimentos Gerais e Atualidades','Todo trabalhador brasileiro tem direito a um salário mínimo, de acordo com o artigo 7º da Constituição Federal do Brasil, de 1988. Atualmente, o valor do salário mínimo é de: A) R$ 964,00; B) R$ 880,00; C) R$ 724,00; D) R$ 817,00; E) R$ 937,00.','E',9,'obsolete',false,true,'Candidato marcou A e errou. O valor vigente em 2017 era R$ 937,00 (E), mas o salário mínimo é redefinido por decreto todo ano; mantido só como registro histórico (obsoleto) para não induzir erro como questão de treino.'),
(24,'Conhecimentos Gerais e Atualidades','Considerando o Mapa Político do Estado do Acre, o município de Feijó é limítrofe aos seguintes municípios: A) Jordão, Manoel Urbano e Tarauacá; B) Jordão, Santa Rosa do Purus e Tarauacá; C) Jordão, Manoel Urbano, Santa Rosa do Purus e Tarauacá; D) Manoel Urbano, Santa Rosa do Purus e Tarauacá; E) Manoel Urbano, Santa Rosa do Purus, Sena Madureira e Tarauacá.','X',9,'annulled',false,false,'Questão ANULADA pela banca (conferência anterior registrada na migration 20260928040000); pontos creditados a todos os candidatos.'),
(25,'Conhecimentos Gerais e Atualidades','Governadores e representantes de 23 estados defenderam no dia 27 de outubro deste ano a criação de um Sistema Nacional de Segurança para combater o narcotráfico. A proposta foi apresentada durante o Encontro de Governadores do Brasil pela Segurança e Controle das Fronteiras, que ocorreu na capital acreana, Rio Branco. O estado do Acre faz fronteira com dois países e o município de Feijó com apenas um deles, sendo: A) Bolívia; B) Peru; C) Colômbia; D) Equador; E) Venezuela.','B',10,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(26,'Pedagogia','No atual contexto escolar, o processo de planejamento tem sido alvo de questionamentos, reflexões e críticas quanto a sua validade como instrumento de intervenção, mudança e melhoria na qualidade do trabalho docente. Diante do exposto, podemos afirmar que a perspectiva crítica do planejamento escolar preconiza que: A) a única preocupação do planejamento escolar, está voltada apenas para a organização e desenvolvimento das metodologias para o ensino; B) o ato de planejar deve ser norteado pela contemplação da relação dialética entre escola e sociedade; C) os objetivos, métodos e avaliação devem ser determinados por modelos prescritos na legislação educacional; D) os elementos do planejamento (objetivos, conteúdos, métodos e avaliação) assumem um significado político pelas implicações sociais que os envolvem; E) a preocupação central do planejamento escolar deve ser a aplicabilidade de métodos e técnicas inovadores que compreendem os elementos prescritos na legislação educacional.','D',10,'under_review',false,false,'Candidato marcou B e errou. A alternativa D aparece destacada na correção do candidato na foto, mas o gabarito oficial não foi localizado online; mantido em revisão.'),
(27,'Pedagogia','A formação profissional docente implica em compreender a aprendizagem como um processo contínuo e exige uma análise cuidadosa da ação docente, pois o modelo de professor crítico-reflexivo vem se destacando e um dos pressupostos fundamentais desse modelo em sua respectiva caracterização é: A) a crítica, elemento central no modelo docente que compreende a aprendizagem como algo intrínseco ao fazer docente; B) as competências inerentes ao exercício da profissão docente, que possuem um status distinto na divisão social do trabalho; C) a pesquisa realizada como atividade que avalia o desempenho dos alunos e que é obrigatória no cotidiano escolar; D) a reflexão produzida pelos docentes sobre a sua própria ação pedagógica; E) a crítica, elemento central no modelo docente que compreende a aprendizagem como algo inerente ao fazer docente.','D',10,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(28,'Pedagogia','A Lei de Diretrizes e Bases da Educação Nacional – LDB (Lei 9.394/1996), em seu Art. 13, destaca a incumbência dos docentes quanto a avaliação da aprendizagem escolar. De acordo com a Lei, um dos critérios observados para a verificação do rendimento escolar é: A) recuperação condicionada à disponibilidade de oferta por parte da instituição escolar; B) progressão automática no interior de um ciclo de aprendizagem em todo o ensino fundamental e médio; C) possibilidade de avanço nos cursos e nas séries mediante verificação do aprendizado; D) avaliação contínua e cumulativa, com porcentagem igual para aspectos qualitativos e quantitativos; E) progressão automática no interior de um ciclo de aprendizagem, apenas no ensino fundamental.','C',10,'active',true,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos. Conteúdo de legislação (LDB, art. 24, V): pendente de auditoria legal antes de uso no treinador.'),
(29,'Pedagogia','Psicanálise e Behaviorismo são abordagem teóricas que contribuem para o pensar, sentir e fazer em psicologia. Difundidas no século XX, essas abordagens privilegiam, respectivamente os seguintes objetos de estudo: A) sonhos, delírios e esquecimento; B) alma e inconsciente; C) alma e consciência; D) comportamento e consciência; E) inconsciente e comportamento.','E',11,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(30,'Pedagogia','O planejamento é uma atividade constante na atuação docente, e entre objetivos e conteúdos, destaca-se a importância da previsão das atividades que serão realizadas em sala de aula com os alunos. O ponto de partida na elaboração desse planejamento é a: A) definição de objetivos específicos que valorizem as necessidades de uma determinada comunidade; B) definição de conteúdos que privilegiem a autonomia do aluno; C) definição de conteúdos e objetivos específicos que não permeiam o desenvolvimento reflexivo do aluno; D) definição de critérios de avaliação; E) identificação do perfil da turma.','E',11,'under_review',false,false,'Candidato marcou B e errou. A alternativa E aparece indicada por seta na correção do candidato na foto, mas o gabarito oficial não foi localizado online; mantido em revisão.'),
(31,'Pedagogia','O ato de avaliar sugere a coleta e análise de dados com o objetivo de configurar um novo formato de avaliação que tenha por finalidade apontar falhas e auxiliar o professor na construção do conhecimento e em sua ação didática. Com relação as avaliações diagnósticas, somativa e formativa, assinale a opção correta: A) a avaliação diagnóstica tem por objetivo revelar os conhecimentos que o aluno não assimilou ao decorrer do ano letivo; B) a avaliação diagnóstica é utilizada quando o objetivo é preterir a verificação dos conhecimentos prévios que o aluno possui sobre determinado conteúdo; C) a avaliação somativa funciona como parâmetro para observar se as metas estabelecidas na elaboração do currículo foram alcançadas; D) a avaliação somativa é uma avaliação de aprendizagem de acordo com a qual notas e conceitos são atribuídos ao aluno; E) a função da avaliação somativa é observar se os objetivos contidos no Projeto Político Pedagógico da escola foram alcançados.','D',11,'active',false,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos.'),
(32,'Pedagogia','Sobre a composição financeira e a distribuição de recursos referentes ao Fundo de Manutenção e Desenvolvimento da Educação Básica e de Valorização dos Profissionais da Educação (FUNDEB), regulamentado pela Lei nº 11.494, de 20 de junho de 2007. Assinale a alternativa correta: I) a complementação da União observará o cronograma da programação financeira do Tesouro Nacional e contemplará pagamentos mensais de, no mínimo, 5% da complementação anual, a serem realizados até o último dia útil de cada mês; II) a distribuição de recursos do Fundo dar-se-á igualmente para todas as etapas, modalidades e tipos de estabelecimento de ensino da educação básica; III) a apropriação dos recursos em função das matrículas na modalidade de jovens e adultos observará, em cada Estado do Distrito Federal, percentual de até 25% dos recursos do Fundo respectivo; IV) para os fins da distribuição dos recursos de que trata a referida Lei, serão considerados exclusivamente as matrículas presenciais efetivas, conforme os dados apurados no censo escolar mais atualizado, realizado anualmente pelo INEP, considerando as ponderações aplicáveis. Marque a opção correta: A) Apenas os itens I e II estão corretos; B) Apenas os itens II e III estão corretos; C) Apenas o item III está correto; D) Apenas os itens II e IV estão corretos; E) Apenas o Item IV está correto.','A',11,'obsolete',true,false,'A Lei nº 11.494/2007 foi revogada pela Lei nº 14.113/2020 (novo FUNDEB); a questão perdeu aderência à legislação vigente e é mantida só como registro histórico (obsoleta). Resposta original: A (candidato acertou).'),
(33,'Pedagogia','Dadas as afirmativas sobre a Lei de Diretrizes e Bases da Educação Nacional (LDB) nº 9.394/1996, marque V para as assertivas verdadeiras e F para as falsas: ( ) Art. 2º a educação é dever da família e do Estado e inspirada nos princípios de liberdade e nos ideais de solidariedade humana, tem por finalidade o pleno desenvolvimento do educando, seu preparo para o exercício da cidadania e sua qualificação para o trabalho; ( ) Art. 4º o dever do Estado com a educação escolar pública será efetivado mediante a garantia de: educação básica obrigatória e gratuita dos quatro aos dezessete anos de idade; ( ) Art. 2º a educação é dever da família, do Estado e da comunidade em que a criança ou jovem está inserida, e inspirada nos princípios de liberdade e nos ideais de solidariedade humana, tem por finalidade o pleno desenvolvimento do educando, seu preparo para o exercício da cidadania e sua qualificação para o trabalho; ( ) Art. 4º o dever do Estado com a educação escolar pública será efetivado mediante a garantia de: educação básica obrigatória e gratuita dos quatro aos dezesseis anos de idade. Assinale a sequência correta. A) V, F, V, F; B) F, F, V, F; C) [alternativa ilegível na foto]; D) V, V, F, F; E) F, F, V, V.','D',12,'under_review',true,true,'Candidato marcou A e errou. Resposta D conferida contra o texto da LDB (art. 2º, caput: "dever da família e do Estado"; art. 4º, I: educação básica obrigatória e gratuita dos 4 aos 17 anos). Alternativa C ilegível na foto e auditoria legal pendente; mantido em revisão.'),
(34,'Pedagogia','De acordo com a Resolução N.º 4, de 12 de julho de 2010, que define as Diretrizes Curriculares Nacionais para a Educação Básica em seu art. 2.º que se refere aos objetivos. Analise os itens abaixo: I) A Resolução tem por objetivo sistematizar os princípios e as diretrizes gerais da Educação Básica contidos na Constituição, na LDB (Lei de Diretrizes e Bases) e demais dispositivos legais que contribuam para assegurar a formação básica comum nacional, tendo como foco os sujeitos que dão vida ao currículo e à escola; II) Estimular a reflexão crítica e propositiva que deve subsidiar a formulação, a execução e a avaliação do projeto político-pedagógico da escola de Educação Básica; III) A Resolução tem por objetivo sistematizar os princípios e as diretrizes gerais da Educação Básica contidos na Constituição e demais dispositivos legais que contribuam parcialmente para assegurar a formação básica comum nacional, tendo como foco o aluno; IV) Orientar os cursos de formação inicial e continuada de docentes e demais profissionais da Educação Básica, os sistemas educacionais dos diferentes entes federados e as escolas que os integram, indistintamente da rede a que pertençam. Estão corretos os itens: A) I e II; B) II, III e IV; C) I e III; D) II e III; E) I, II e IV.','E',12,'under_review',true,false,'Resposta conferida pela correção feita pelo candidato nas fotos da prova (visto = acerto) e pela nota oficial de 59,5 pontos. Norma (Resolução CNE/CEB nº 4/2010): auditoria legal pendente.')
)
insert into public.official_exam_questions (
  question_source_id, answer_key_source_id, syllabus_topic_id,
  contest_name, exam_year, career_name, exam_board,
  item_number, subject, question_text, raw_extraction, official_answer, source_page,
  content_status, legal_review_required, context_review_required, legal_basis, review_note
)
select
  sources.prova_id, sources.gabarito_id, topics.topic_id,
  'Prefeitura de Feijó', 2017, 'Professor - Licenciatura Plena - Pedagogo', 'Fundape',
  imported.item_number, imported.subject, imported.question_text, imported.question_text,
  imported.official_answer, imported.source_page,
  imported.content_status, imported.legal_review_required, imported.context_review_required,
  case when imported.item_number in (28,33) then jsonb_build_array(jsonb_build_object('title','Lei nº 9.394/1996 - LDB','url','https://www.planalto.gov.br/ccivil_03/leis/l9394.htm'))
       else '[]'::jsonb end,
  imported.review_note
from imported
cross join sources
join topics on topics.discipline = imported.subject
on conflict (contest_name, exam_year, item_number) do update set
  subject = excluded.subject,
  question_text = excluded.question_text,
  raw_extraction = excluded.raw_extraction,
  official_answer = excluded.official_answer,
  source_page = excluded.source_page,
  content_status = excluded.content_status,
  legal_review_required = excluded.legal_review_required,
  context_review_required = excluded.context_review_required,
  legal_basis = excluded.legal_basis,
  review_note = excluded.review_note,
  verified_at = now();

update public.student_exam_documents set
  correct_count=23, wrong_count=9, blank_count=0, score_net=59.5,
  extracted_data='{"method": "nota 59,5 anotada pelo candidato na capa (sem os títulos). Itens 1-34 lidos nas fotos e na planilha pessoal (as questões 16 e 20 foram respondidas, B e C, e erradas); 10 e 24 anulados pela banca. Itens 35-40 sem registro (a diferença de 4 pontos até 59,5 equivale a um item específico nessa faixa)", "items": {"1": "correta", "2": "correta", "3": "correta", "4": "correta", "5": "correta", "6": "errada", "7": "correta", "8": "correta", "9": "correta", "10": "anulada", "11": "correta", "12": "correta", "13": "correta", "14": "correta", "15": "correta", "16": "errada", "17": "correta", "18": "errada", "19": "correta", "20": "errada", "21": "errada", "22": "correta", "23": "errada", "24": "anulada", "25": "correta", "26": "errada", "27": "correta", "28": "correta", "29": "correta", "30": "errada", "31": "correta", "32": "correta", "33": "errada", "34": "correta"}}'::jsonb
where storage_path='manual-entry/feijo-2017-franc-denis';
