-- Auditoria jurídica refeita: PF 2021 (Agente). Textos oficiais compilados do Planalto e súmulas conferidos em 27/09/2026.

update public.official_exam_questions set review_note=$q$Conferido no texto compilado da Lei 8.112/1990 (Planalto, 27/09/2026): art. 132, IX, comina demissão para a revelação de segredo do qual o servidor se apropriou em razão do cargo. Gabarito C confere.$q$, question_text=$q$Texto-base:
Determinado agente da Polícia Federal revelou um segredo sobre uma operação policial que seria realizada para deter uma quadrilha de traficantes. Ele havia se apropriado desse segredo em razão do seu cargo. Tendo a operação fracassado, a administração da Polícia recebeu uma denúncia sobre o ocorrido e abriu processo administrativo disciplinar contra o referido servidor.
Considerando essa situação hipotética, julgue os itens subsequentes.

Item: O servidor, em razão do seu ato, está sujeito à pena de demissão.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Noções de Direito Administrativo$q$ and t.topic_order=2 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Lei nº 8.112/1990 – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/leis/l8112compilado.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=25 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Bloqueado (27/09/2026): o item depende do conceito doutrinário de poder disciplinar x poder de polícia, sem texto legal que o defina; a governança exige fonte oficial vigente. A chave oficial (E) continua valendo para a pontuação.$q$ where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=26 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido (Planalto, 27/09/2026): a CF, arts. 70 e 74, distingue controle externo (Congresso/TCU) de controle interno de cada Poder; a instauração de processo disciplinar pela própria Administração é controle interno, ligado ao dever de apuração (Lei 8.112, art. 143) e à autotutela (Lei 9.784, art. 53). Gabarito E confere.$q$, question_text=$q$Texto-base:
Determinado agente da Polícia Federal revelou um segredo sobre uma operação policial que seria realizada para deter uma quadrilha de traficantes. Ele havia se apropriado desse segredo em razão do seu cargo. Tendo a operação fracassado, a administração da Polícia recebeu uma denúncia sobre o ocorrido e abriu processo administrativo disciplinar contra o referido servidor.
Considerando essa situação hipotética, julgue os itens subsequentes.

Item: A abertura do processo contra o servidor em questão é considerada controle externo e posterior.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Noções de Direito Administrativo$q$ and t.topic_order=3 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Constituição Federal de 1988 – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm$q$),jsonb_build_object('title',$q$Lei nº 9.784/1999$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/leis/l9784.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=27 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido no texto compilado da CF (Planalto, 27/09/2026): art. 5º, XLIII, torna inafiançável o tráfico ilícito de entorpecentes e drogas afins. Gabarito C confere.$q$, question_text=$q$Comando:
A polícia foi acionada para atender a um chamado de suspeita de ocorrência de tráfico ilícito de entorpecentes no interior de determinada sociedade de economia mista federal. Ao chegar ao local, os policiais verificaram que um dos traficantes era um brasileiro naturalizado.
Considerando essa situação hipotética, julgue os itens subsecutivos.

Item: O tráfico ilícito de entorpecentes é crime inafiançável.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Noções de Direito Constitucional$q$ and t.topic_order=1 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Constituição Federal de 1988 – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=29 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido no texto compilado da CF (Planalto, 27/09/2026): art. 5º, LI, permite extraditar o naturalizado por crime comum anterior à naturalização OU por comprovado envolvimento em tráfico de drogas; portanto o item, que só invoca a data do crime, é errado. Gabarito E confere.$q$, question_text=$q$Comando:
A polícia foi acionada para atender a um chamado de suspeita de ocorrência de tráfico ilícito de entorpecentes no interior de determinada sociedade de economia mista federal. Ao chegar ao local, os policiais verificaram que um dos traficantes era um brasileiro naturalizado.
Considerando essa situação hipotética, julgue os itens subsecutivos.

Item: O traficante naturalizado brasileiro não poderá ser extraditado porque o crime foi praticado depois da naturalização.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Noções de Direito Constitucional$q$ and t.topic_order=1 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Constituição Federal de 1988 – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=30 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido no texto compilado do CPP (Planalto, 27/09/2026): art. 158-B, V, define acondicionamento como o ato de embalar individualmente o vestígio; armazenamento (art. 158-B, IX) é a guarda em condições adequadas. Gabarito E confere.$q$, question_text=$q$Comando:
    Com relação ao direito penal e ao direito processual penal, julgue
    os itens que se seguem.

Item: Armazenamento consiste no procedimento de embalar, de forma individualizada, cada vestígio coletado, de acordo com suas características físicas, químicas e biológicas, para análise posterior.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Direito Penal e Processual Penal$q$ and t.topic_order=4 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Código de Processo Penal – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=31 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Bloqueado (27/09/2026): a afirmativa depende de entendimento jurisprudencial (consumação do descaminho, art. 334 do CP, independente do esgotamento da via administrativa) que não foi confirmado em fonte oficial do STJ/STF nesta revisão (o repositório de súmulas do STJ não traz enunciado sobre o ponto). A chave oficial (C) continua valendo para a pontuação.$q$ where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=32 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido no portal do STF (27/09/2026): Súmula 145 — não há crime quando a preparação do flagrante pela polícia torna impossível a consumação; flagrante preparado é o provocado/induzido pela polícia. Gabarito C confere.$q$, question_text=$q$Comando:
    Com relação ao direito penal e ao direito processual penal, julgue
    os itens que se seguem.

Item: Caracteriza-se como flagrante preparado a situação em que os policiais provocam ou induzem o cometimento do crime pelo agente.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Direito Penal e Processual Penal$q$ and t.topic_order=4 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$STF – Súmula 145$q$,'url',$q$https://portal.stf.jus.br/jurisprudencia/sumariosumulas.asp?base=30&sumula=2119$q$),jsonb_build_object('title',$q$Código de Processo Penal – texto compilado$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=33 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido (27/09/2026): Lei 11.343/2006, art. 40, I (transnacionalidade), e Súmula 607 do STJ, no repositório do tribunal: a majorante se configura com a prova da destinação internacional das drogas, ainda que não consumada a transposição da fronteira. Gabarito E confere.$q$, question_text=$q$Comando:
    Cada um dos itens a seguir apresenta uma situação hipotética
    seguida de uma assertiva a ser julgada. Julgue-os com base na
    legislação especial.

Item: Determinada pessoa foi presa em flagrante delito, porque estava, no território brasileiro, próximo à região de fronteira com determinado país da América do Sul, transportando uma grande quantidade de drogas. Nessa situação, a configuração do tráfico transnacional depende da comprovação da transposição da fronteira, hipótese em que a pena poderá aumentar.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Legislação Especial$q$ and t.topic_order=2 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Lei nº 11.343/2006 – Lei de Drogas$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11343.htm$q$),jsonb_build_object('title',$q$STJ – Súmula 607$q$,'url',$q$https://scon.stj.jus.br/SCON/pesquisar.jsp?b=SUMU&sumula=607$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=34 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido no texto compilado da Lei 13.445/2017 (Planalto, 27/09/2026): art. 54, caput e §4º, prevê impedimento de reingresso por prazo determinado, proporcional à pena e nunca superior ao dobro dela. Gabarito E confere.$q$, question_text=$q$Comando:
    Cada um dos itens a seguir apresenta uma situação hipotética
    seguida de uma assertiva a ser julgada. Julgue-os com base na
    legislação especial.

Item: No ano de 2020, um estrangeiro considerado um indivíduo nocivo e perigoso foi expulso do Brasil por ter cometido um crime comum doloso com pena privativa de liberdade. Nessa situação, ele estará impedido de reingressar no Brasil por prazo indeterminado.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Legislação Especial$q$ and t.topic_order=1 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Lei nº 13.445/2017 – Lei de Migração$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/lei/l13445.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=35 and content_status='under_review';
-- @@
update public.official_exam_questions set review_note=$q$Conferido no texto compilado da Lei 9.605/1998 (Planalto, 27/09/2026): art. 29, §4º, III e V, aumenta a pena da metade se o crime é praticado durante a noite ou em unidade de conservação. Gabarito C confere.$q$, question_text=$q$Comando:
    Cada um dos itens a seguir apresenta uma situação hipotética
    seguida de uma assertiva a ser julgada. Julgue-os com base na
    legislação especial.

Item: Uma pessoa apanhou à noite, em uma unidade da conservação, um espécime da fauna silvestre brasileira sem a devida permissão. Nessa situação, a pena deverá aumentar.$q$, context_review_required=false, content_status='active', current_syllabus_topic_id=(select t.id from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name=$q$Polícia Federal$q$ and e.contest_year=2025 and e.role_name=$q$Agente de Polícia Federal$q$ and t.discipline=$q$Legislação Especial$q$ and t.topic_order=2 and t.block_name not ilike '%Hist%' limit 1), legal_audit_completed=true, legal_review_required=false, legal_basis=jsonb_build_array(jsonb_build_object('title',$q$Lei nº 9.605/1998 – Crimes Ambientais$q$,'url',$q$https://www.planalto.gov.br/ccivil_03/leis/l9605.htm$q$)), law_version_checked_at=now() where exam_year=2021 and career_name=$q$Agente de Polícia Federal$q$ and item_number=36 and content_status='under_review';
-- @@
