-- Import of PF 2021 official exam items for the career "Papiloscopista
-- Policial Federal" (Edital nº 1 - DGP/PF, de 15 de janeiro de 2021,
-- CONCURSO PÚBLICO APLICAÇÃO: 2021, banca CEBRASPE). This is Cargo 4, the
-- final cargo of the same concurso already imported for Agente
-- (20260926050000/20260927080000), Delegado (20260929240000) and Escrivão
-- (20260929250000).
--
-- Source material read verbatim from Google Drive this session:
--   - Prova: CARGO_4_PAPILOSCOPISTA_POLICIAL_FEDERAL.pdf (fileId
--     1KbXyqwbK3-g27fCgxmQ2gzeJ7-DONF7v) - full 120-item CEBRASPE
--     Certo/Errado objective test, cover states "CARGO 4_PAPILOSCOPISTA
--     POLICIAL FEDERAL"; read fully in this session (not just the
--     papiloscopia block).
--   - Gabarito: GAB_DEFINITIVO_PPF.PDF (fileId
--     1a4uF_zzQnp4ijZupXQen_H0BIY9a9aZB) - explicitly labeled
--     "CARGO: PAPILOSCOPISTA POLICIAL FEDERAL", Matriz_577_PF_004_00.
--
-- The unique constraint official_exam_questions_contest_career_year_item_key
-- = (contest_name,career_name,exam_year,item_number) was already widened
-- by migration 20260929240000_pf_2021_delegado_import.sql, so this
-- migration only inserts with the matching ON CONFLICT target and does not
-- repeat the ALTER TABLE.

-- Content sources for this specific cargo's booklet and gabarito matriz.
insert into public.content_sources (source_type,title,issuer,url,status,notes) values
('outro','Prova objetiva PF - Papiloscopista - 2021','Polícia Federal / CEBRASPE','https://www.gov.br/pf/pt-br/acesso-a-informacao/servidores/concursos/provas-e-gabaritos-de-concursos-anteriores/concurso-carreira-policial-2021/papiloscopista-policial-federal/prova_cargo_4_papiloscopista_policial_federal.pdf/view','vigente','Caderno oficial usado para extração auditável de itens (Google Drive fileId 1KbXyqwbK3-g27fCgxmQ2gzeJ7-DONF7v, texto lido verbatim nesta sessão).'),
('outro','Gabarito definitivo PF - Papiloscopista - 2021','Polícia Federal / CEBRASPE','https://www.gov.br/pf/pt-br/acesso-a-informacao/servidores/concursos/provas-e-gabaritos-de-concursos-anteriores/concurso-carreira-policial-2021/papiloscopista-policial-federal/gab_definitivo_ppf.pdf/view','vigente','Gabarito oficial definitivo Matriz_577_PF_004_00, explicitamente rotulado CARGO: PAPILOSCOPISTA POLICIAL FEDERAL (Google Drive fileId 1a4uF_zzQnp4ijZupXQen_H0BIY9a9aZB); X identifica item anulado.')
on conflict (url) do update set checked_at=now(),status=excluded.status,notes=excluded.notes;

-- New syllabus edition for this career.
insert into public.syllabus_editions (contest_name,role_name,contest_year,source_id)
select 'Polícia Federal','Papiloscopista Policial Federal',2021,(select id from public.content_sources where url=$q$https://www.gov.br/pf/pt-br/acesso-a-informacao/servidores/concursos/provas-e-gabaritos-de-concursos-anteriores/concurso-carreira-policial-2021/papiloscopista-policial-federal/prova_cargo_4_papiloscopista_policial_federal.pdf/view$q$)
where not exists (
  select 1 from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Papiloscopista Policial Federal' and contest_year=2021
);

-- Discipline breakdown derived directly from reading the prova's own item
-- text (command blocks and subject matter): Língua Portuguesa (1-18, two
-- reading-comprehension texts shared with other cargos of this concurso),
-- Redação Oficial (19-24), Direito Administrativo (25-27), Direito
-- Constitucional (28-30), Direito Penal e Processual Penal (31-33),
-- Legislação Penal Especial (34-36), Estatística e Probabilidade (37-48),
-- Raciocínio Lógico-Matemático (49-60), Informática (61-96, a much larger
-- block than in Delegado/Escrivão, spanning Internet/intranet, redes,
-- segurança, cloud computing, teoria geral de sistemas, mineração de
-- dados/bigdata, modelagem e bancos de dados, programação Python/R e API),
-- and, distinctively for this cargo, the "Conhecimentos Específicos" block
-- of natural sciences applied to papiloscopia/perícia: Biologia (97-104:
-- composição química da matéria viva, organelas, placenta, vias
-- metabólicas, gemelaridade/DNA), Física (105-112: ondas, eletrostática,
-- óptica) and Química (113-120: tabela periódica, entalpia de dissolução,
-- óxido de ferro(III) usado na revelação de impressões digitais, equilíbrio
-- químico, interações intermoleculares — directly tied to the fingerprint
-- (papiloscopia) identification techniques named in items 113-120's own
-- prompt text).
with edition as (
  select id from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Papiloscopista Policial Federal' and contest_year=2021
)
insert into public.syllabus_topics (edition_id,block_name,discipline,topic_order,topic_text,content_status)
select edition.id,'Prova objetiva',d.discipline,1,d.topic_text,'current'
from edition cross join (values
  ('Língua Portuguesa','Compreensão e interpretação de textos; tipologia textual; aspectos linguísticos: coesão e coerência, morfossintaxe, reescrita de frases e pontuação.'),
  ('Redação Oficial','Manual de Redação da Presidência da República: e-mail como documento oficial, exposição de motivos, pronomes de tratamento, grafia de datas, vocativos e padrão ofício.'),
  ('Direito Administrativo','Sigilo funcional, poder de polícia administrativo e controle da administração pública sobre o regime disciplinar do servidor público.'),
  ('Direito Constitucional','Competência constitucional da Polícia Federal (art. 144 da CF), crimes inafiançáveis e extradição de brasileiro naturalizado (art. 5º da CF).'),
  ('Direito Penal e Processual Penal','Cadeia de custódia da prova, consumação do crime de descaminho e flagrante preparado.'),
  ('Legislação Penal Especial','Lei de Abuso de Autoridade, extradição e prescrição segundo a lei brasileira, e acesso ao Banco Nacional Multibiométrico e de Impressões Digitais.'),
  ('Estatística e Probabilidade','Variáveis aleatórias contínuas, distribuições conjuntas, estimação de parâmetros e regressão linear simples.'),
  ('Raciocínio Lógico-Matemático','Análise combinatória, lógica proposicional (equivalência, negação, tabela-verdade, validade de argumentos) e teoria dos conjuntos.'),
  ('Informática','Internet e intranet, redes de computadores, segurança da informação, computação em nuvem, teoria geral de sistemas, dados/informação/conhecimento/inteligência, mineração de dados e bigdata, modelagem conceitual, banco de dados, dados estruturados, SQL, programação (Python e R) e API.'),
  ('Biologia Aplicada à Papiloscopia','Composição química da matéria viva, componentes citoplasmáticos de células eucarióticas, placenta, vias metabólicas e gemelaridade/DNA aplicados à identificação humana.'),
  ('Física Aplicada à Papiloscopia','Ondas estacionárias, eletrostática de distribuições de carga não uniformes e óptica geométrica e ondulatória.'),
  ('Química Aplicada à Papiloscopia','Tabela periódica, entalpia de dissolução, reações do óxido de ferro (III) usado na revelação de impressões digitais, equilíbrio químico e interações intermoleculares.')
) d(discipline,topic_text)
on conflict (edition_id,discipline,topic_order) do update set topic_text=excluded.topic_text;

with imported(exam_year,item_number,subject,question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,context_review_required,review_note) as (values
(2021,1,$q$Língua Portuguesa$q$,$q$Infere-se do texto que a personagem, ao longo de toda a narrativa, está sendo tomada por um tipo de nostalgia que não está relacionada ao espaço físico, mas, sim, a uma saudade de um estado — o da primeira paixão.$q$,$q$Infere-se do texto que a personagem, ao longo de toda a narrativa, está sendo tomada por um tipo de nostalgia que não está relacionada ao espaço físico, mas, sim, a uma saudade de um estado — o da primeira paixão.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,2,$q$Língua Portuguesa$q$,$q$O vocábulo “até” (sétimo período do primeiro parágrafo), empregado no sentido de inclusive, poderia ser deslocado para o início do trecho “com alegria até”.$q$,$q$O vocábulo “até” (sétimo período do primeiro parágrafo), empregado no sentido de inclusive, poderia ser deslocado para o início do trecho “com alegria até”.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,3,$q$Língua Portuguesa$q$,$q$O termo “ali” (quinto período do segundo parágrafo) refere-se a “aquela casa” (primeiro período do texto).$q$,$q$O termo “ali” (quinto período do segundo parágrafo) refere-se a “aquela casa” (primeiro período do texto).$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,4,$q$Língua Portuguesa$q$,$q$Os vocábulos “Claro” e “arejado” (ao final do primeiro parágrafo) fazem referência a “navio”, vocábulo que os antecede no período anterior.$q$,$q$Os vocábulos “Claro” e “arejado” (ao final do primeiro parágrafo) fazem referência a “navio”, vocábulo que os antecede no período anterior.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,5,$q$Língua Portuguesa$q$,$q$Sem prejuízo para o sentido original do texto, o período “Quando anoitecia, toda aquela vizinhança começava, ao mesmo tempo, a fazer bife, e o ar ficava cheirando a cebola e alho” poderia ser reescrito da seguinte maneira: Ao anoitecer, toda aquela vizinhança começava a fazer bife e o ar ficava cheirando à cebola e alho ao mesmo tempo.$q$,$q$Sem prejuízo para o sentido original do texto, o período “Quando anoitecia, toda aquela vizinhança começava, ao mesmo tempo, a fazer bife, e o ar ficava cheirando a cebola e alho” poderia ser reescrito da seguinte maneira: Ao anoitecer, toda aquela vizinhança começava a fazer bife e o ar ficava cheirando à cebola e alho ao mesmo tempo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,6,$q$Língua Portuguesa$q$,$q$No sétimo período do primeiro parágrafo, a forma “lhe” desempenha a função de complemento indireto da forma verbal “mostrasse” e funciona como elemento de coesão ao retomar o personagem da narrativa.$q$,$q$No sétimo período do primeiro parágrafo, a forma “lhe” desempenha a função de complemento indireto da forma verbal “mostrasse” e funciona como elemento de coesão ao retomar o personagem da narrativa.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,7,$q$Língua Portuguesa$q$,$q$A forma verbal “tinha” foi empregada com o mesmo sentido nas duas ocorrências nos seguintes períodos do segundo parágrafo: “Mas tinha a gaveta. Tinha de desocupar aquela gaveta.”.$q$,$q$A forma verbal “tinha” foi empregada com o mesmo sentido nas duas ocorrências nos seguintes períodos do segundo parágrafo: “Mas tinha a gaveta. Tinha de desocupar aquela gaveta.”.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,8,$q$Língua Portuguesa$q$,$q$Na oração “Cabia tudo em uma mala só”, o vocábulo “tudo” exerce a função de sujeito.$q$,$q$Na oração “Cabia tudo em uma mala só”, o vocábulo “tudo” exerce a função de sujeito.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,9,$q$Língua Portuguesa$q$,$q$Conclui-se das ideias do texto que, apesar de existirem peculiaridades culturais e históricas sobre o estabelecimento das penas em cada país, o crescimento do encarceramento apresenta-se como um fenômeno universal que, chancelado pela opinião pública, tem sido adotado como política de segurança por muitos governos, principalmente os das regiões mais desenvolvidas do mundo.$q$,$q$Conclui-se das ideias do texto que, apesar de existirem peculiaridades culturais e históricas sobre o estabelecimento das penas em cada país, o crescimento do encarceramento apresenta-se como um fenômeno universal que, chancelado pela opinião pública, tem sido adotado como política de segurança por muitos governos, principalmente os das regiões mais desenvolvidas do mundo.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,10,$q$Língua Portuguesa$q$,$q$Seriam preservados a correção gramatical e os sentidos do texto caso a vírgula empregada imediatamente após o vocábulo “rapidamente” (primeiro período do texto) fosse suprimida.$q$,$q$Seriam preservados a correção gramatical e os sentidos do texto caso a vírgula empregada imediatamente após o vocábulo “rapidamente” (primeiro período do texto) fosse suprimida.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,11,$q$Língua Portuguesa$q$,$q$No segundo período do texto, a partícula “se” classifica-se como partícula apassivadora.$q$,$q$No segundo período do texto, a partícula “se” classifica-se como partícula apassivadora.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,12,$q$Língua Portuguesa$q$,$q$Conclui-se do trecho ‘há uma crescente necessidade de disciplinar importantes grupos e segmentos populacionais’ que os grupos populacionais a serem disciplinados são compostos por pessoas que têm autoridade e gozam de prestígio na sociedade, do que se infere que tais grupos têm adotado comportamentos indesejáveis.$q$,$q$Conclui-se do trecho ‘há uma crescente necessidade de disciplinar importantes grupos e segmentos populacionais’ que os grupos populacionais a serem disciplinados são compostos por pessoas que têm autoridade e gozam de prestígio na sociedade, do que se infere que tais grupos têm adotado comportamentos indesejáveis.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,13,$q$Língua Portuguesa$q$,$q$A forma verbal “crescem” (terceiro período do primeiro parágrafo) está flexionada no plural para concordar com o sujeito composto cujos núcleos são “gastos”, “efetivos” e “serviços”.$q$,$q$A forma verbal “crescem” (terceiro período do primeiro parágrafo) está flexionada no plural para concordar com o sujeito composto cujos núcleos são “gastos”, “efetivos” e “serviços”.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,14,$q$Língua Portuguesa$q$,$q$O travessão empregado no último período do primeiro parágrafo confere ao trecho final do período, por ele isolado, um destaque, mas sua supressão manteria a correção gramatical do texto.$q$,$q$O travessão empregado no último período do primeiro parágrafo confere ao trecho final do período, por ele isolado, um destaque, mas sua supressão manteria a correção gramatical do texto.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,15,$q$Língua Portuguesa$q$,$q$Seria mantida a correção gramatical do texto caso a forma verbal “esperam” (primeiro período do texto) fosse substituída por espera.$q$,$q$Seria mantida a correção gramatical do texto caso a forma verbal “esperam” (primeiro período do texto) fosse substituída por espera.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,16,$q$Língua Portuguesa$q$,$q$Na argumentação desenvolvida no texto, a informação presente em “Cresce rapidamente em quase todos os países o número de pessoas na prisão” (primeiro período do texto) coaduna-se com a informação presente em “o rápido crescimento parece ser um fenômeno universal em toda a ponta ‘mais desenvolvida’ do mundo” (final do último parágrafo do texto).$q$,$q$Na argumentação desenvolvida no texto, a informação presente em “Cresce rapidamente em quase todos os países o número de pessoas na prisão” (primeiro período do texto) coaduna-se com a informação presente em “o rápido crescimento parece ser um fenômeno universal em toda a ponta ‘mais desenvolvida’ do mundo” (final do último parágrafo do texto).$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,17,$q$Língua Portuguesa$q$,$q$A palavra “idiossincrasias” (segundo parágrafo) poderia ser substituída por compatibilidades sem prejuízo para a correção gramatical e para os sentidos do texto.$q$,$q$A palavra “idiossincrasias” (segundo parágrafo) poderia ser substituída por compatibilidades sem prejuízo para a correção gramatical e para os sentidos do texto.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,18,$q$Língua Portuguesa$q$,$q$As palavras “intensamente”, em “Em quase toda parte, a rede de prisões está se ampliando intensamente”, e “ampliada”, em “e sugere uma ‘significação muito ampliada da solução institucional como componente da política criminal’” desempenham a mesma função sintática nos períodos em que ocorrem.$q$,$q$As palavras “intensamente”, em “Em quase toda parte, a rede de prisões está se ampliando intensamente”, e “ampliada”, em “e sugere uma ‘significação muito ampliada da solução institucional como componente da política criminal’” desempenham a mesma função sintática nos períodos em que ocorrem.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,19,$q$Redação Oficial$q$,$q$Quando da redação de e-mail que possa ser considerado um documento oficial, devem-se usar os mesmos parâmetros de redação dos demais documentos oficiais, o que inclui linguagem adequada.$q$,$q$Quando da redação de e-mail que possa ser considerado um documento oficial, devem-se usar os mesmos parâmetros de redação dos demais documentos oficiais, o que inclui linguagem adequada.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,20,$q$Redação Oficial$q$,$q$A exposição de motivos é modalidade de comunicação dirigida pelos ministros ao Presidente da República e, em determinadas circunstâncias, poderá ser encaminhada cópia do documento ao Congresso Nacional ou ao Poder Judiciário.$q$,$q$A exposição de motivos é modalidade de comunicação dirigida pelos ministros ao Presidente da República e, em determinadas circunstâncias, poderá ser encaminhada cópia do documento ao Congresso Nacional ou ao Poder Judiciário.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,21,$q$Redação Oficial$q$,$q$No endereçamento das comunicações dirigidas às autoridades superiores, devem-se empregar os seguintes pronomes de tratamento: “A Vossa Excelência o Senhor” ou “A Vossa Excelência a Senhora”.$q$,$q$No endereçamento das comunicações dirigidas às autoridades superiores, devem-se empregar os seguintes pronomes de tratamento: “A Vossa Excelência o Senhor” ou “A Vossa Excelência a Senhora”.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,22,$q$Redação Oficial$q$,$q$Na grafia de datas em um documento oficial, o conteúdo deve constar conforme exemplificado a seguir: Brasília, 02/04/2021.$q$,$q$Na grafia de datas em um documento oficial, o conteúdo deve constar conforme exemplificado a seguir: Brasília, 02/04/2021.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,23,$q$Redação Oficial$q$,$q$Nas comunicações oficiais, aboliu-se o uso dos vocativos Digníssimo (DD) e de Ilustríssimo (Ilmo.).$q$,$q$Nas comunicações oficiais, aboliu-se o uso dos vocativos Digníssimo (DD) e de Ilustríssimo (Ilmo.).$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,24,$q$Redação Oficial$q$,$q$No padrão ofício, o cabeçalho deve estar centralizado na área determinada pela formatação e constar em todas as páginas do documento.$q$,$q$No padrão ofício, o cabeçalho deve estar centralizado na área determinada pela formatação e constar em todas as páginas do documento.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,25,$q$Direito Administrativo$q$,$q$O servidor, em razão do seu ato, está sujeito à pena de demissão.$q$,$q$O servidor, em razão do seu ato, está sujeito à pena de demissão.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,26,$q$Direito Administrativo$q$,$q$O processo aberto contra o servidor caracteriza poder de polícia administrativo.$q$,$q$O processo aberto contra o servidor caracteriza poder de polícia administrativo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,27,$q$Direito Administrativo$q$,$q$A abertura do processo contra o servidor em questão é considerada controle externo e posterior.$q$,$q$A abertura do processo contra o servidor em questão é considerada controle externo e posterior.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,28,$q$Direito Constitucional$q$,$q$A competência para a apuração do referido delito é da Polícia Federal, uma vez que lhe cabe apurar infrações penais que envolvam bens e interesses da União, suas autarquias, fundações, empresas públicas e sociedades de economia mistas.$q$,$q$A competência para a apuração do referido delito é da Polícia Federal, uma vez que lhe cabe apurar infrações penais que envolvam bens e interesses da União, suas autarquias, fundações, empresas públicas e sociedades de economia mistas.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_004_00); não é exibido aos estudantes.$q$),
(2021,29,$q$Direito Constitucional$q$,$q$O tráfico ilícito de entorpecentes é crime inafiançável.$q$,$q$O tráfico ilícito de entorpecentes é crime inafiançável.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,30,$q$Direito Constitucional$q$,$q$O traficante naturalizado brasileiro não poderá ser extraditado porque o crime foi praticado depois da naturalização.$q$,$q$O traficante naturalizado brasileiro não poderá ser extraditado porque o crime foi praticado depois da naturalização.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,31,$q$Direito Penal e Processual Penal$q$,$q$Armazenamento consiste no procedimento de embalar, de forma individualizada, cada vestígio coletado, de acordo com suas características físicas, químicas e biológicas, para análise posterior.$q$,$q$Armazenamento consiste no procedimento de embalar, de forma individualizada, cada vestígio coletado, de acordo com suas características físicas, químicas e biológicas, para análise posterior.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,32,$q$Direito Penal e Processual Penal$q$,$q$A consumação do delito de descaminho independe do esgotamento da via administrativa.$q$,$q$A consumação do delito de descaminho independe do esgotamento da via administrativa.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,33,$q$Direito Penal e Processual Penal$q$,$q$Caracteriza-se como flagrante preparado a situação em que os policiais provocam ou induzem o cometimento do crime pelo agente.$q$,$q$Caracteriza-se como flagrante preparado a situação em que os policiais provocam ou induzem o cometimento do crime pelo agente.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,34,$q$Legislação Penal Especial$q$,$q$Suponha que determinado policial federal tenha dado início à persecução penal contra uma pessoa, sem justa causa fundamentada, e outro policial, da mesma delegacia, tenha impedido, sem justa causa, a entrevista pessoal e reservada do preso com seu advogado. Nessas situações, os dois policiais estarão sujeitos à mesma sanção penal.$q$,$q$Suponha que determinado policial federal tenha dado início à persecução penal contra uma pessoa, sem justa causa fundamentada, e outro policial, da mesma delegacia, tenha impedido, sem justa causa, a entrevista pessoal e reservada do preso com seu advogado. Nessas situações, os dois policiais estarão sujeitos à mesma sanção penal.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,35,$q$Legislação Penal Especial$q$,$q$Suponha que determinado estrangeiro tenha cometido crime no seu país e tenha vindo e permanecido no Brasil e que, passado algum tempo, o governo do país do estrangeiro tenha descoberto sua localização e requerido sua extradição. Nessa situação, se, conforme a lei brasileira, a punibilidade estiver extinta pela prescrição, ele não poderá ser extraditado, ainda que a prescrição não tenha ocorrido no país requerente.$q$,$q$Suponha que determinado estrangeiro tenha cometido crime no seu país e tenha vindo e permanecido no Brasil e que, passado algum tempo, o governo do país do estrangeiro tenha descoberto sua localização e requerido sua extradição. Nessa situação, se, conforme a lei brasileira, a punibilidade estiver extinta pela prescrição, ele não poderá ser extraditado, ainda que a prescrição não tenha ocorrido no país requerente.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,36,$q$Legislação Penal Especial$q$,$q$No curso de um inquérito, a autoridade policial somente poderá ter acesso ao Banco Nacional Multibiométrico e de impressões digitais mediante autorização judicial.$q$,$q$No curso de um inquérito, a autoridade policial somente poderá ter acesso ao Banco Nacional Multibiométrico e de impressões digitais mediante autorização judicial.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,37,$q$Estatística e Probabilidade$q$,$q$O valor da constante 𝐾 é inferior a 0,01.$q$,$q$O valor da constante 𝐾 é inferior a 0,01.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,38,$q$Estatística e Probabilidade$q$,$q$O valor esperado de 𝑋 é igual a 12.$q$,$q$O valor esperado de 𝑋 é igual a 12.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,39,$q$Estatística e Probabilidade$q$,$q$𝑃(𝑋 < 5) < 𝐾.$q$,$q$𝑃(𝑋 < 5) < 𝐾.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,40,$q$Estatística e Probabilidade$q$,$q$𝑋 é uma variável aleatória uniforme no intervalo (0,1).$q$,$q$𝑋 é uma variável aleatória uniforme no intervalo (0,1).$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,41,$q$Estatística e Probabilidade$q$,$q$𝑋 e 𝑌 são variáveis aleatórias independentes.$q$,$q$𝑋 e 𝑌 são variáveis aleatórias independentes.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,42,$q$Estatística e Probabilidade$q$,$q$𝐸(𝑌) = 𝐸(𝑌|𝑋).$q$,$q$𝐸(𝑌) = 𝐸(𝑌|𝑋).$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,43,$q$Estatística e Probabilidade$q$,$q$A estimativa de máxima verossimilhança para o parâmetro 𝛽 é igual ou superior a 3,5.$q$,$q$A estimativa de máxima verossimilhança para o parâmetro 𝛽 é igual ou superior a 3,5.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,44,$q$Estatística e Probabilidade$q$,$q$Pelo método dos mínimos quadrados ordinários, a estimativa da média populacional é igual ou superior a 3,5.$q$,$q$Pelo método dos mínimos quadrados ordinários, a estimativa da média populacional é igual ou superior a 3,5.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,45,$q$Estatística e Probabilidade$q$,$q$A média amostral é uma estatística suficiente para a estimação do parâmetro 𝛽.$q$,$q$A média amostral é uma estatística suficiente para a estimação do parâmetro 𝛽.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,46,$q$Estatística e Probabilidade$q$,$q$A correlação linear entre as variáveis 𝑋 e 𝑌 foi igual a 0,1.$q$,$q$A correlação linear entre as variáveis 𝑋 e 𝑌 foi igual a 0,1.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,47,$q$Estatística e Probabilidade$q$,$q$Considere que 𝛽 denote o coeficiente angular do modelo de regressão linear simples e considere, ainda, que o teste de hipóteses 𝐻0:𝛽 = 0 versus 𝐻1:𝛽 ≠ 0. Nessa situação, com referência a esse teste, caso o nível de significância escolhido seja igual a 5%, os resultados do estudo em questão indicarão que não há evidências estatísticas contra a hipótese nula 𝐻0:𝛽 = 0.$q$,$q$Considere que 𝛽 denote o coeficiente angular do modelo de regressão linear simples e considere, ainda, que o teste de hipóteses 𝐻0:𝛽 = 0 versus 𝐻1:𝛽 ≠ 0. Nessa situação, com referência a esse teste, caso o nível de significância escolhido seja igual a 5%, os resultados do estudo em questão indicarão que não há evidências estatísticas contra a hipótese nula 𝐻0:𝛽 = 0.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,48,$q$Estatística e Probabilidade$q$,$q$Se a média amostral da variável 𝑋 for igual a 6,5, então a média amostral da variável 𝑌 será igual a 4,35 mil ocorrências.$q$,$q$Se a média amostral da variável 𝑋 for igual a 6,5, então a média amostral da variável 𝑌 será igual a 4,35 mil ocorrências.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,49,$q$Raciocínio Lógico-Matemático$q$,$q$Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes seria igual ao número de maneiras de se montar, escolhendo-se entre esses mesmos profissionais, uma única equipe para a realização de uma busca em uma única localidade.$q$,$q$Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes seria igual ao número de maneiras de se montar, escolhendo-se entre esses mesmos profissionais, uma única equipe para a realização de uma busca em uma única localidade.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,50,$q$Raciocínio Lógico-Matemático$q$,$q$Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes é igual a 4!.$q$,$q$Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes é igual a 4!.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,51,$q$Raciocínio Lógico-Matemático$q$,$q$Se estiverem disponíveis, no momento de formação das equipes, 3 delegados, 4 escrivães e 6 agentes, o número de maneiras distintas de se montar as duas equipes é superior a 6.500.$q$,$q$Se estiverem disponíveis, no momento de formação das equipes, 3 delegados, 4 escrivães e 6 agentes, o número de maneiras distintas de se montar as duas equipes é superior a 6.500.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,52,$q$Raciocínio Lógico-Matemático$q$,$q$A proposição P2 é equivalente a “Se as falhas construtivas não foram corrigidas, os mutuários tiveram prejuízos”.$q$,$q$A proposição P2 é equivalente a “Se as falhas construtivas não foram corrigidas, os mutuários tiveram prejuízos”.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,53,$q$Raciocínio Lógico-Matemático$q$,$q$Uma negação correta da proposição P1 pode ser expressa por: “Se a fiscalização não foi deficiente, as falhas construtivas foram corrigidas”.$q$,$q$Uma negação correta da proposição P1 pode ser expressa por: “Se a fiscalização não foi deficiente, as falhas construtivas foram corrigidas”.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,54,$q$Raciocínio Lógico-Matemático$q$,$q$A tabela verdade da proposição condicional associada ao argumento tem menos de dez linhas.$q$,$q$A tabela verdade da proposição condicional associada ao argumento tem menos de dez linhas.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,55,$q$Raciocínio Lógico-Matemático$q$,$q$A proposição P1 é equivalente a “Não é verdade que a fiscalização foi deficiente e que as falhas construtivas foram corrigidas”.$q$,$q$A proposição P1 é equivalente a “Não é verdade que a fiscalização foi deficiente e que as falhas construtivas foram corrigidas”.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,56,$q$Raciocínio Lógico-Matemático$q$,$q$Caso o argumento apresentado seja válido, a proposição C será verdadeira.$q$,$q$Caso o argumento apresentado seja válido, a proposição C será verdadeira.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,57,$q$Raciocínio Lógico-Matemático$q$,$q$O argumento apresentado não é válido.$q$,$q$O argumento apresentado não é válido.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,58,$q$Raciocínio Lógico-Matemático$q$,$q$O conjunto P é igual à união infinita dos conjuntos P1, P2, P3, ...$q$,$q$O conjunto P é igual à união infinita dos conjuntos P1, P2, P3, ...$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,59,$q$Raciocínio Lógico-Matemático$q$,$q$P2 é subconjunto de P1.$q$,$q$P2 é subconjunto de P1.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,60,$q$Raciocínio Lógico-Matemático$q$,$q$Escolhendo-se aleatoriamente um integrante do conjunto P, a probabilidade de ele ter entre dois e três anos de experiência no exercício do cargo é dada por n(P2 – P3)/n(P3), em que n(X) indica o número de elementos do conjunto X e P2 – P3 é o conjunto formado pelos indivíduos que estão em P2, mas não estão em P3.$q$,$q$Escolhendo-se aleatoriamente um integrante do conjunto P, a probabilidade de ele ter entre dois e três anos de experiência no exercício do cargo é dada por n(P2 – P3)/n(P3), em que n(X) indica o número de elementos do conjunto X e P2 – P3 é o conjunto formado pelos indivíduos que estão em P2, mas não estão em P3.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,61,$q$Informática$q$,$q$A forma correta para pesquisar no Google a correspondência exata da frase “crime organizado”, exclusivamente no sítio pf.gov.br, é "crime organizado" in pf.gov.br.$q$,$q$A forma correta para pesquisar no Google a correspondência exata da frase “crime organizado”, exclusivamente no sítio pf.gov.br, é "crime organizado" in pf.gov.br.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,62,$q$Informática$q$,$q$A versão atual do Google Chrome dispõe de recurso que permite avisar o usuário sobre a possibilidade de ele estar utilizando uma combinação de senha e de nome de usuário comprometida em um vazamento de dados em um sítio ou em um aplicativo de terceiros.$q$,$q$A versão atual do Google Chrome dispõe de recurso que permite avisar o usuário sobre a possibilidade de ele estar utilizando uma combinação de senha e de nome de usuário comprometida em um vazamento de dados em um sítio ou em um aplicativo de terceiros.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,63,$q$Informática$q$,$q$Se, quando do acesso ao sítio https://www.gov.br/pf/pt-br na versão mais recente do Google Chrome, for visualizado o ícone de um cadeado cinza ao lado da URL, o símbolo em questão estará sinalizando que esse ambiente refere-se à intranet da Polícia Federal.$q$,$q$Se, quando do acesso ao sítio https://www.gov.br/pf/pt-br na versão mais recente do Google Chrome, for visualizado o ícone de um cadeado cinza ao lado da URL, o símbolo em questão estará sinalizando que esse ambiente refere-se à intranet da Polícia Federal.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,64,$q$Informática$q$,$q$No Linux, o comando pwd é utilizado para realizar a troca de senha das contas de usuários do sistema, ação que somente pode ser realizada por usuário que tenha determinados privilégios no ambiente para executá-la.$q$,$q$No Linux, o comando pwd é utilizado para realizar a troca de senha das contas de usuários do sistema, ação que somente pode ser realizada por usuário que tenha determinados privilégios no ambiente para executá-la.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,65,$q$Informática$q$,$q$Se um usuário recebesse a planilha Excel a seguir somente com os dados contidos nas colunas A e B e necessitasse preencher a coluna C, em vez de digitar manualmente os dados, ele poderia, para fazer o referido preenchimento, digitar o conteúdo “Acre - AC” na célula C1; selecionar a célula C1; e acionar o botão na guia dados.$q$,$q$Se um usuário recebesse a planilha Excel a seguir somente com os dados contidos nas colunas A e B e necessitasse preencher a coluna C, em vez de digitar manualmente os dados, ele poderia, para fazer o referido preenchimento, digitar o conteúdo “Acre - AC” na célula C1; selecionar a célula C1; e acionar o botão na guia dados.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,66,$q$Informática$q$,$q$Na comunicação entre dois dispositivos na Internet, o protocolo IP especifica o formato dos pacotes que trafegam entre roteadores e sistemas finais.$q$,$q$Na comunicação entre dois dispositivos na Internet, o protocolo IP especifica o formato dos pacotes que trafegam entre roteadores e sistemas finais.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,67,$q$Informática$q$,$q$A pilha de protocolos TCP/IP de cinco camadas e a pilha do modelo de referência OSI têm, em comum, as camadas física, de enlace, de rede, de transporte e de aplicação.$q$,$q$A pilha de protocolos TCP/IP de cinco camadas e a pilha do modelo de referência OSI têm, em comum, as camadas física, de enlace, de rede, de transporte e de aplicação.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,68,$q$Informática$q$,$q$O SMTP é o protocolo indicado para prover o serviço confiável de transferência de dados em formulários de dados no caso de o usuário estar trafegando em sítios da Internet, por exemplo.$q$,$q$O SMTP é o protocolo indicado para prover o serviço confiável de transferência de dados em formulários de dados no caso de o usuário estar trafegando em sítios da Internet, por exemplo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,69,$q$Informática$q$,$q$Caso o usuário tenha recebido um conjunto de arquivos com trojan em seu conteúdo e esses arquivos estejam em uma mídia de armazenamento local em sua estação de trabalho, recomenda-se a utilização de IDS (intrusion detection system) para a realização da limpeza dos arquivos.$q$,$q$Caso o usuário tenha recebido um conjunto de arquivos com trojan em seu conteúdo e esses arquivos estejam em uma mídia de armazenamento local em sua estação de trabalho, recomenda-se a utilização de IDS (intrusion detection system) para a realização da limpeza dos arquivos.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,70,$q$Informática$q$,$q$Denomina-se backdoor a situação em que um usuário sofre um ataque, seus dados são criptografados, ficam inacessíveis e, então, exige-se desse usuário o pagamento de resgate para o restabelecimento do acesso a seus dados.$q$,$q$Denomina-se backdoor a situação em que um usuário sofre um ataque, seus dados são criptografados, ficam inacessíveis e, então, exige-se desse usuário o pagamento de resgate para o restabelecimento do acesso a seus dados.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,71,$q$Informática$q$,$q$A PaaS (plataforma como um serviço) contém os componentes básicos da IT na nuvem e oferece o mais alto nível de flexibilidade e de controle de gerenciamento sobre os recursos de tecnologia da informação no que diz respeito a cloud computing.$q$,$q$A PaaS (plataforma como um serviço) contém os componentes básicos da IT na nuvem e oferece o mais alto nível de flexibilidade e de controle de gerenciamento sobre os recursos de tecnologia da informação no que diz respeito a cloud computing.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,72,$q$Informática$q$,$q$As desvantagens da cloud computing incluem a inflexibilidade relativa ao provisionamento de recursos computacionais: é necessário estabelecê-los no momento da contratação e não há possibilidade de ajustes de escala, de acordo com a evolução das necessidades, no mesmo contrato.$q$,$q$As desvantagens da cloud computing incluem a inflexibilidade relativa ao provisionamento de recursos computacionais: é necessário estabelecê-los no momento da contratação e não há possibilidade de ajustes de escala, de acordo com a evolução das necessidades, no mesmo contrato.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,73,$q$Informática$q$,$q$À medida que os sistemas sofrem mudanças, o ajustamento sistemático ocorre de forma contínua; dessas mudanças e dos ajustamentos decorrem fenômenos como, por exemplo, a entropia e a homeostasia.$q$,$q$À medida que os sistemas sofrem mudanças, o ajustamento sistemático ocorre de forma contínua; dessas mudanças e dos ajustamentos decorrem fenômenos como, por exemplo, a entropia e a homeostasia.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,74,$q$Informática$q$,$q$Cada sistema existe dentro de um meio ambiente constituído por outros sistemas e, nesse contexto, os sistemas abertos caracterizam-se por consistirem em um processo infinito de intercâmbio com o seu ambiente para a realização da troca de informações.$q$,$q$Cada sistema existe dentro de um meio ambiente constituído por outros sistemas e, nesse contexto, os sistemas abertos caracterizam-se por consistirem em um processo infinito de intercâmbio com o seu ambiente para a realização da troca de informações.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,75,$q$Informática$q$,$q$Embora não seja dirigido a riscos, o modelo de desenvolvimento de sistemas espiral de Boehm inclui, em seu framework, a etapa de análise e validação dos requisitos.$q$,$q$Embora não seja dirigido a riscos, o modelo de desenvolvimento de sistemas espiral de Boehm inclui, em seu framework, a etapa de análise e validação dos requisitos.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,76,$q$Informática$q$,$q$Uma das etapas descritas em um método de desenvolvimento de sistema clássico é a de análise e definição de requisitos, etapa em que as restrições e as metas do sistema são obtidas por meio de consulta a usuários, com o objetivo de realizar a especificação do sistema.$q$,$q$Uma das etapas descritas em um método de desenvolvimento de sistema clássico é a de análise e definição de requisitos, etapa em que as restrições e as metas do sistema são obtidas por meio de consulta a usuários, com o objetivo de realizar a especificação do sistema.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,77,$q$Informática$q$,$q$Considerando-se a classificação dados, informação, conhecimento e inteligência, é correto afirmar que o gráfico representa, por si só, a inteligência.$q$,$q$Considerando-se a classificação dados, informação, conhecimento e inteligência, é correto afirmar que o gráfico representa, por si só, a inteligência.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,78,$q$Informática$q$,$q$O número 1.789 sozinho caracteriza uma informação, independentemente do contexto.$q$,$q$O número 1.789 sozinho caracteriza uma informação, independentemente do contexto.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,79,$q$Informática$q$,$q$Os roteadores operam na camada de rede do modelo ISO/OSI.$q$,$q$Os roteadores operam na camada de rede do modelo ISO/OSI.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,80,$q$Informática$q$,$q$UDP (user datagram protocol) e TCP (transmission control protocol) são protocolos da camada de transporte do modelo ISO/OSI.$q$,$q$UDP (user datagram protocol) e TCP (transmission control protocol) são protocolos da camada de transporte do modelo ISO/OSI.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,81,$q$Informática$q$,$q$Os bits são empacotados em quadros (dataframes) em camada de transporte do modelo de rede.$q$,$q$Os bits são empacotados em quadros (dataframes) em camada de transporte do modelo de rede.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,82,$q$Informática$q$,$q$Uma LAN (local area network) fornece conectividade em tempo integral para os serviços de conexão da Internet.$q$,$q$Uma LAN (local area network) fornece conectividade em tempo integral para os serviços de conexão da Internet.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,83,$q$Informática$q$,$q$A função do metadado de arquivo é descrever o destino final do arquivo definido pelo emissor da mensagem e proprietário do arquivo.$q$,$q$A função do metadado de arquivo é descrever o destino final do arquivo definido pelo emissor da mensagem e proprietário do arquivo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,84,$q$Informática$q$,$q$O código Python a seguir apresenta como resultado "True". x = bool(-3); y = bool("True"*x); z = bool("False"); print (x and y and z)$q$,$q$O código Python a seguir apresenta como resultado "True". x = bool(-3); y = bool("True"*x); z = bool("False"); print (x and y and z)$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,85,$q$Informática$q$,$q$O resultado do código R seguinte será "12". f<- function(x) { g <- function(y) { y + z } z <- 4 x + g(x) } z <- 10 f(4)$q$,$q$O resultado do código R seguinte será "12". f<- function(x) { g <- function(y) { y + z } z <- 4 x + g(x) } z <- 10 f(4)$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,86,$q$Informática$q$,$q$A análise de clustering é uma tarefa que consiste em agrupar um conjunto de objetos de tal forma que estes, juntos no mesmo grupo, sejam mais semelhantes entre si que em outros grupos.$q$,$q$A análise de clustering é uma tarefa que consiste em agrupar um conjunto de objetos de tal forma que estes, juntos no mesmo grupo, sejam mais semelhantes entre si que em outros grupos.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,87,$q$Informática$q$,$q$Entropia da informação é uma medida de certeza de que o intervalo contém um parâmetro da população.$q$,$q$Entropia da informação é uma medida de certeza de que o intervalo contém um parâmetro da população.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,88,$q$Informática$q$,$q$As aplicações de bigdata caracterizam-se exclusivamente pelo grande volume de dados armazenados em tabelas relacionais.$q$,$q$As aplicações de bigdata caracterizam-se exclusivamente pelo grande volume de dados armazenados em tabelas relacionais.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,89,$q$Informática$q$,$q$Se uma tabela de banco de dados tiver 205 atributos, então isso significa que ela tem 205 registros.$q$,$q$Se uma tabela de banco de dados tiver 205 atributos, então isso significa que ela tem 205 registros.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,90,$q$Informática$q$,$q$No modelo de entidade-relacionamento, entidade normalmente representa um objeto do mundo real.$q$,$q$No modelo de entidade-relacionamento, entidade normalmente representa um objeto do mundo real.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,91,$q$Informática$q$,$q$Em um sistema gerenciado de banco de dados, as restrições de integridade garantem que os dados possam ser armazenados, consultados e utilizados com confiabilidade.$q$,$q$Em um sistema gerenciado de banco de dados, as restrições de integridade garantem que os dados possam ser armazenados, consultados e utilizados com confiabilidade.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,92,$q$Informática$q$,$q$Atomicidade refere-se à propriedade de um sistema gerenciador de banco de dados (SGBD) que garante que os dados armazenados sejam indivisíveis.$q$,$q$Atomicidade refere-se à propriedade de um sistema gerenciador de banco de dados (SGBD) que garante que os dados armazenados sejam indivisíveis.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_004_00); não é exibido aos estudantes.$q$),
(2021,93,$q$Informática$q$,$q$Uma hiperchave é uma tupla que permite recuperar uma relação de uma tabela.$q$,$q$Uma hiperchave é uma tupla que permite recuperar uma relação de uma tabela.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,94,$q$Informática$q$,$q$Os dados estruturados diferenciam-se dos dados não estruturados pela rigidez em seu formato e pelo fato de poderem ser armazenados em campos de tabelas de um banco de dados relacional.$q$,$q$Os dados estruturados diferenciam-se dos dados não estruturados pela rigidez em seu formato e pelo fato de poderem ser armazenados em campos de tabelas de um banco de dados relacional.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,95,$q$Informática$q$,$q$Na linguagem SQL (structured query language), DTL (data transaction language) são comandos responsáveis por gerenciar diferentes transações ocorridas dentro de um banco de dados.$q$,$q$Na linguagem SQL (structured query language), DTL (data transaction language) são comandos responsáveis por gerenciar diferentes transações ocorridas dentro de um banco de dados.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,96,$q$Informática$q$,$q$API é um padrão XML usado para desenvolver uma interface de aplicativos em dispositivos computacionais em servidores HTTP ou HTTPS.$q$,$q$API é um padrão XML usado para desenvolver uma interface de aplicativos em dispositivos computacionais em servidores HTTP ou HTTPS.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,97,$q$Biologia Aplicada à Papiloscopia$q$,$q$Os principais elementos químicos que constituem os organismos vivos são: carbono (C), oxigênio (O), hidrogênio (H), nitrogênio (N) e argônio (Ar).$q$,$q$Os principais elementos químicos que constituem os organismos vivos são: carbono (C), oxigênio (O), hidrogênio (H), nitrogênio (N) e argônio (Ar).$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,98,$q$Biologia Aplicada à Papiloscopia$q$,$q$O papel biológico dos íons magnésio no organismo inclui a formação de tecidos, ossos e dentes, o metabolismo de carboidratos e a regulação da excitabilidade neuromuscular.$q$,$q$O papel biológico dos íons magnésio no organismo inclui a formação de tecidos, ossos e dentes, o metabolismo de carboidratos e a regulação da excitabilidade neuromuscular.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,99,$q$Biologia Aplicada à Papiloscopia$q$,$q$A mitocôndria e o aparelho de Golgi são organelas que possuem material genético (DNA) próprio, razão por que elas são frequentemente empregadas nas análises para determinar a história evolutiva humana.$q$,$q$A mitocôndria e o aparelho de Golgi são organelas que possuem material genético (DNA) próprio, razão por que elas são frequentemente empregadas nas análises para determinar a história evolutiva humana.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,100,$q$Biologia Aplicada à Papiloscopia$q$,$q$Embora as balsas lipídicas na membrana plasmática atuem na transdução de sinais promovendo a resposta imunológica na defesa do organismo, elas podem facilitar a entrada de vírus da família dos coronavírus por meio da ligação entre o vírus e a proteína transmembrana localizada nas regiões dessas balsas.$q$,$q$Embora as balsas lipídicas na membrana plasmática atuem na transdução de sinais promovendo a resposta imunológica na defesa do organismo, elas podem facilitar a entrada de vírus da família dos coronavírus por meio da ligação entre o vírus e a proteína transmembrana localizada nas regiões dessas balsas.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,101,$q$Biologia Aplicada à Papiloscopia$q$,$q$A placenta é formada pela parte fetal, constituída pelo córion viloso, e pela parte materna, constituída pela decídua basal.$q$,$q$A placenta é formada pela parte fetal, constituída pelo córion viloso, e pela parte materna, constituída pela decídua basal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,102,$q$Biologia Aplicada à Papiloscopia$q$,$q$Nos seres eucariontes, o ciclo de Krebs, ou ciclo dos ácidos tricarboxílicos, ocorre nos ribossomos livres no citosol.$q$,$q$Nos seres eucariontes, o ciclo de Krebs, ou ciclo dos ácidos tricarboxílicos, ocorre nos ribossomos livres no citosol.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,103,$q$Biologia Aplicada à Papiloscopia$q$,$q$Como o exame de DNA tradicional não foi suficiente para elucidar a situação descrita, uma forma de confirmar a paternidade seria submeter os gêmeos ao teste de paternidade por tipagem sanguínea, utilizando o sistema ABO.$q$,$q$Como o exame de DNA tradicional não foi suficiente para elucidar a situação descrita, uma forma de confirmar a paternidade seria submeter os gêmeos ao teste de paternidade por tipagem sanguínea, utilizando o sistema ABO.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,104,$q$Biologia Aplicada à Papiloscopia$q$,$q$Os gêmeos na situação em tela possuem a mesma carga genética porque eles se originaram de um único óvulo fertilizado pelo mesmo espermatozoide, com posterior fissão do zigoto.$q$,$q$Os gêmeos na situação em tela possuem a mesma carga genética porque eles se originaram de um único óvulo fertilizado pelo mesmo espermatozoide, com posterior fissão do zigoto.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,105,$q$Física Aplicada à Papiloscopia$q$,$q$No estudo das ondas estacionárias, o princípio da superposição depende da linearidade da equação de onda e da propriedade correspondente da combinação linear de suas soluções.$q$,$q$No estudo das ondas estacionárias, o princípio da superposição depende da linearidade da equação de onda e da propriedade correspondente da combinação linear de suas soluções.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,106,$q$Física Aplicada à Papiloscopia$q$,$q$A principal diferença entre as ondas mecânicas e as eletromagnéticas é que, apesar de ambas transportarem energia, somente as mecânicas transportam matéria.$q$,$q$A principal diferença entre as ondas mecânicas e as eletromagnéticas é que, apesar de ambas transportarem energia, somente as mecânicas transportam matéria.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,107,$q$Física Aplicada à Papiloscopia$q$,$q$Uma região de raio r < R concêntrica à esfera isolante possui carga total proporcional ao quadrado de r.$q$,$q$Uma região de raio r < R concêntrica à esfera isolante possui carga total proporcional ao quadrado de r.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,108,$q$Física Aplicada à Papiloscopia$q$,$q$A uma distância r < R do centro da esfera isolante, o campo elétrico é proporcional a r.$q$,$q$A uma distância r < R do centro da esfera isolante, o campo elétrico é proporcional a r.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,109,$q$Física Aplicada à Papiloscopia$q$,$q$O potencial elétrico dentro da esfera isolante é maior que o da superfície.$q$,$q$O potencial elétrico dentro da esfera isolante é maior que o da superfície.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_004_00); não é exibido aos estudantes.$q$),
(2021,110,$q$Física Aplicada à Papiloscopia$q$,$q$Embora a distribuição de carga não seja uniforme, a superfície da esfera isolante é equipotencial.$q$,$q$Embora a distribuição de carga não seja uniforme, a superfície da esfera isolante é equipotencial.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,111,$q$Física Aplicada à Papiloscopia$q$,$q$Se o objeto da figura A estiver posicionado à distância x1 do foco objeto da lente e sua imagem conjugada estiver posicionada à distância x2 do foco imagem da lente, então a distância focal f da lente pode ser corretamente calculada por meio da seguinte equação: f = (x1x2)1/2.$q$,$q$Se o objeto da figura A estiver posicionado à distância x1 do foco objeto da lente e sua imagem conjugada estiver posicionada à distância x2 do foco imagem da lente, então a distância focal f da lente pode ser corretamente calculada por meio da seguinte equação: f = (x1x2)1/2.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,112,$q$Física Aplicada à Papiloscopia$q$,$q$Se o filme fino da figura B for utilizado com o objetivo de eliminar (por interferência) os reflexos da luz de comprimento λ, então a menor espessura L do filme fino será dada por L = λ/(2 nf).$q$,$q$Se o filme fino da figura B for utilizado com o objetivo de eliminar (por interferência) os reflexos da luz de comprimento λ, então a menor espessura L do filme fino será dada por L = λ/(2 nf).$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_004_00); não é exibido aos estudantes.$q$),
(2021,113,$q$Química Aplicada à Papiloscopia$q$,$q$O eletrólito de sódio citado no texto fica no mesmo grupo do átomo neutro, mas se posiciona no segundo período da Tabela Periódica.$q$,$q$O eletrólito de sódio citado no texto fica no mesmo grupo do átomo neutro, mas se posiciona no segundo período da Tabela Periódica.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,114,$q$Química Aplicada à Papiloscopia$q$,$q$O suor tem temperatura de ebulição maior que a da água pura.$q$,$q$O suor tem temperatura de ebulição maior que a da água pura.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,115,$q$Química Aplicada à Papiloscopia$q$,$q$A temperatura da água aumenta com a dissolução de NaCl.$q$,$q$A temperatura da água aumenta com a dissolução de NaCl.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,116,$q$Química Aplicada à Papiloscopia$q$,$q$O óxido de ferro (III) é um peróxido.$q$,$q$O óxido de ferro (III) é um peróxido.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,117,$q$Química Aplicada à Papiloscopia$q$,$q$Na reação do Fe2O3 apresentada, o ácido é o catalisador.$q$,$q$Na reação do Fe2O3 apresentada, o ácido é o catalisador.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,118,$q$Química Aplicada à Papiloscopia$q$,$q$A estequiometria correta da equação química apresentada é obtida com os seguintes valores para x, y e z, respectivamente: 6, 2 e 3.$q$,$q$A estequiometria correta da equação química apresentada é obtida com os seguintes valores para x, y e z, respectivamente: 6, 2 e 3.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,119,$q$Química Aplicada à Papiloscopia$q$,$q$A constante de equilíbrio K da reação do óxido de ferro (III) é corretamente expressa pela seguinte equação. K = [Fe3+]y[H2O]z / [Fe2O3][H+]x$q$,$q$A constante de equilíbrio K da reação do óxido de ferro (III) é corretamente expressa pela seguinte equação. K = [Fe3+]y[H2O]z / [Fe2O3][H+]x$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,120,$q$Química Aplicada à Papiloscopia$q$,$q$A interação intermolecular citada no texto envolve atração entre cargas de sinais opostos.$q$,$q$A interação intermolecular citada no texto envolve atração entre cargas de sinais opostos.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 4 - Papiloscopista Policial Federal (PF 2021); gabarito conferido em Matriz_577_PF_004_00 (cargo Papiloscopista). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$)
), editions as (
  select id,contest_year from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Papiloscopista Policial Federal' and contest_year=2021
), resolved as (
  select imported.*, question_source.id question_source_id, answer_source.id answer_key_source_id, topic.id syllabus_topic_id
  from imported
  join editions on editions.contest_year=imported.exam_year
  join public.syllabus_topics topic on topic.edition_id=editions.id and topic.discipline=imported.subject and topic.topic_order=1
  join public.content_sources question_source on question_source.title='Prova objetiva PF - Papiloscopista - ' || imported.exam_year
  join public.content_sources answer_source on answer_source.title='Gabarito definitivo PF - Papiloscopista - ' || imported.exam_year
)
insert into public.official_exam_questions (
  question_source_id,answer_key_source_id,syllabus_topic_id,contest_name,career_name,exam_board,exam_year,item_number,subject,
  question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,
  context_review_required,review_note
)
select question_source_id,answer_key_source_id,syllabus_topic_id,'Polícia Federal','Papiloscopista Policial Federal','CEBRASPE',exam_year,item_number,subject,
  question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,
  context_review_required,review_note
from resolved
on conflict (contest_name,career_name,exam_year,item_number) do nothing;
