-- Root-cause repair for the exam_year=2021 unique-key collision described in
-- 20260927000500_widen_exam_question_unique_key.sql. That migration widened
-- official_exam_questions' unique key to (contest_name,exam_year,item_number)
-- but never repaired existing data. Tracing the collision chain:
--   1) 20260926050000 inserted PF 2021 (120 items, contest_name default
--      'Polícia Federal') under the old key unique(exam_year,item_number).
--   2) 20260926080000 (PRF 2021, same exam_year=2021, same item_number range
--      1-120) used "on conflict (exam_year,item_number) do update set
--      question_text=..., official_answer=..." — this updated PF's existing
--      120 rows in place with PRF's content, but never touched their
--      contest_name column, so they stayed labeled 'Polícia Federal' while
--      holding PRF's questions/answers. No new PRF-labeled rows were created
--      at this point (the conflict target didn't include contest_name).
--   3) 20260926190000 (DEPEN 2021, same exam_year=2021, same range) repeated
--      the same "on conflict (exam_year,item_number) do update" pattern,
--      again updating those same 120 rows in place — now holding DEPEN's
--      content while still labeled 'Polícia Federal'.
--   4) 20260927000500 widened the key. 20260927001000/003000 correctly
--      re-inserted DEPEN's own 120 rows under contest_name='Departamento
--      Penitenciário Nacional' (on conflict (contest_name,exam_year,
--      item_number) do nothing), since no such labeled rows existed yet.
--      DEPEN is fine as of that migration.
--   5) Nobody ever repaired the 120 rows still mislabeled 'Polícia Federal'
--      (holding DEPEN's stale content) nor recreated PRF 2021's own 120
--      rows — 'Polícia Rodoviária Federal' exam_year=2021 has zero rows in
--      official_exam_questions today.
--
-- This migration:
--   A) deletes the 120 rows currently mislabeled contest_name='Polícia
--      Federal', exam_year=2021 (their question_text/official_answer belong
--      to DEPEN, not PF).
--   B) re-inserts PF's real 2021 gabarito (item-for-item identical to what
--      20260926050000 originally inserted for exam_year=2021, before it was
--      clobbered), protected by the composite key this time.
--   C) inserts PRF's real 2021 gabarito (item-for-item identical to what
--      20260926080000 tried to insert) under its own
--      contest_name='Polícia Rodoviária Federal' label, which never
--      actually existed as its own row set until now.
-- No candidate grading data (student_exam_documents) is touched — those
-- rows already store the candidate's own pre-computed verdicts directly and
-- were unaffected by this table's corruption.

delete from public.official_exam_questions
where contest_name='Polícia Federal' and exam_year=2021;

with imported(exam_year,item_number,subject,question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,context_review_required,review_note) as (values
(2021,1,'Língua Portuguesa','Ao receber este caderno de provas, confira inicialmente se os dados transcritos acima estão corretos e se estão corretamente registrados na sua Folha de Respostas e na sua Folha de Texto Definitivo da Prova Discursiva. Confira também seus dados em cada página numerada deste caderno de provas (desconsidere estas instruções, caso se trate de caderno de provas reserva).E m seguida, verifique se ele contém a quantidade de itens indicada em sua , Folha de Respostas correspondentes à prova objetiva, e a prova discursiva, acompanhada de espaço para rascunho. Caso o caderno esteja incompleto, tenha qualquer defeito e(ou) apresente divergência quanto aos seus dados, solicite, de imediato, ao(à) aplicador(a) de provas mais próximo(a) que tome as providências necessárias.','Ao receber este caderno de provas, confira inicialmente se os dados transcritos acima estão corretos e se estão corretamente registrados na sua Folha de Respostas e na sua Folha de Texto Definitivo da Prova Discursiva. Confira também seus dados em cada página numerada deste caderno de provas (desconsidere estas instruções, caso se trate de caderno de provas reserva).E m seguida, verifique se ele contém a quantidade de itens indicada em sua , Folha de Respostas correspondentes à prova objetiva, e a prova discursiva, acompanhada de espaço para rascunho. Caso o caderno esteja incompleto, tenha qualquer defeito e(ou) apresente divergência quanto aos seus dados, solicite, de imediato, ao(à) aplicador(a) de provas mais próximo(a) que tome as providências necessárias.','E',1,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,2,'Língua Portuguesa','Durante a realização das provas, não se comunique com outros(as) candidatos(as) nem se levante sem autorização de um(a) dos(as) aplicadores(as) de provas.','Durante a realização das provas, não se comunique com outros(as) candidatos(as) nem se levante sem autorização de um(a) dos(as) aplicadores(as) de provas.','C',1,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,3,'Língua Portuguesa','Não serão fornecidas folhas suplementares para rascunho nem para a transcrição do texto definitivo da prova discursiva.','Não serão fornecidas folhas suplementares para rascunho nem para a transcrição do texto definitivo da prova discursiva.','E',1,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,4,'Língua Portuguesa','Na duração das provas, está incluído o tempo destinado à identificação — que será feita no decorrer das provas —, ao preenchimento da e à transcrição do texto da prova discursiva para aFolha de Respostas Folha de Texto Definitivo da Prova Discursiva.','Na duração das provas, está incluído o tempo destinado à identificação — que será feita no decorrer das provas —, ao preenchimento da e à transcrição do texto da prova discursiva para aFolha de Respostas Folha de Texto Definitivo da Prova Discursiva.','E',1,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,5,'Língua Portuguesa','Ao terminar as provas, chame o(a) aplicador(a) de provas mais próximo(a), devolva-lhe a sua Folha de Respostas Folha de Texto Definitivo da Prova Discursivae a sua e deixe o local de provas.','Ao terminar as provas, chame o(a) aplicador(a) de provas mais próximo(a), devolva-lhe a sua Folha de Respostas Folha de Texto Definitivo da Prova Discursivae a sua e deixe o local de provas.','E',1,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,6,'Língua Portuguesa','Nenhuma folha deste caderno pode ser destacada, exceto a folha que contém os documentos Folha de Respostas Folha de Texto Definitivo da Prova Discursivae , cujo cabeçalho será destacado pelo(a) chefe de sala ao final das provas, para fins de desidentificação.','Nenhuma folha deste caderno pode ser destacada, exceto a folha que contém os documentos Folha de Respostas Folha de Texto Definitivo da Prova Discursivae , cujo cabeçalho será destacado pelo(a) chefe de sala ao final das provas, para fins de desidentificação.','C',1,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,7,'Língua Portuguesa','A desobediência a qualquer uma das determinações constantes em edital, no presente caderno, naFolha de Respostas Folha de Texto Definitivo da Prova Discursivaou na implicará a anulação das suas provas.','A desobediência a qualquer uma das determinações constantes em edital, no presente caderno, naFolha de Respostas Folha de Texto Definitivo da Prova Discursivaou na implicará a anulação das suas provas. LEIA COM ATENÇÃO AS INSTRUÇÕES ABAIXO. POLÍCIA FEDERAL (PF)POLÍCIA FEDERAL (PF)POLÍCIA FEDERAL (PF)POLÍCIA FEDERAL (PF) O CEBRASPE TRABALHA PARA OFERECER O MELHOR!','E',1,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,8,'Língua Portuguesa','Na oração “Cabia tudo em uma mala só”, o vocábulo “tudo” exerce a função de sujeito.','Na oração “Cabia tudo em uma mala só”, o vocábulo “tudo” exerce a função de sujeito. Texto 2A1-II Cresce rapidamente, em quase todos os países, o número de pessoas na prisão ou que esperam prováveis sentenças de prisão. Em quase toda parte, a rede de prisões está se ampliand o intensamente. Os gastos orçamentários do Estado com as forças da lei e da ordem, principalmente os efetivos policiais e os serviços penitenciários, crescem em todo o planeta. Mais importante, a proporção da popu lação em conflito direto com a lei e sujeita à prisão cresce em ritmo que indica uma mudança mais que meramente quantitativa e sugere uma “significação muito ampliada da solução institucional como componente da política criminal” — e assinala, além disso, que muitos governo s alimentam a pressuposição, que goza de amplo apoio na opinião pública, de que “há uma crescente necessidade de disciplinar importantes grupos e segmentos populacionais”. A proporção da população que cumpre sentenças de prisão é distinta em cada país, refletindo idiossincrasias de tradiçõe s culturais e histórias de pensamen to e de práticas penais, mas o rápido crescimento parece ser um fenômeno universal em toda a ponta “mais desenvolvida” do mundo. Zygmunt Bauman. Globalização: as consequências humanas. Tradução: Marcus Penchel. Rio de Janeiro, Zahar, 1999, p. 122-123 (com adaptações).','C',2,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,9,'Língua Portuguesa','Conclui-se das ideias do tex to que, apesar de existirem peculiaridades culturais e histó ricas sobre o estabelecimento das penas em cada país, o crescimento do encarceramento apresenta-se como um fenômeno universal que, chancelado pela opinião pública, tem sido adotado como política de segurança por muitos governos, principalmente os das regiões mais desenvolvidas do mundo.','Conclui-se das ideias do tex to que, apesar de existirem peculiaridades culturais e histó ricas sobre o estabelecimento das penas em cada país, o crescimento do encarceramento apresenta-se como um fenômeno universal que, chancelado pela opinião pública, tem sido adotado como política de segurança por muitos governos, principalmente os das regiões mais desenvolvidas do mundo.','C',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,10,'Língua Portuguesa','Seriam preservados a correção gramatical e os sentidos do texto caso a vírgula empregada imediatamente após o vocábulo “rapidamente” (primeiro período do texto) fosse suprimida.','Seriam preservados a correção gramatical e os sentidos do texto caso a vírgula empregada imediatamente após o vocábulo “rapidamente” (primeiro período do texto) fosse suprimida.','E',3,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,11,'Língua Portuguesa','No segundo período do texto, a partícula “se” classifica-se como partícula apassivadora.','No segundo período do texto, a partícula “se” classifica-se como partícula apassivadora.','E',3,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,12,'Língua Portuguesa','Conclui-se do trecho ‘há uma crescente necessidade de disciplinar importantes grupo s e segmentos populacionais’ que os grupos populacionais a serem disciplinados são compostos por pessoas que têm autoridade e gozam de prestígio na sociedade, do que s e infere que tais grupos têm adotado comportamentos indesejáveis.','Conclui-se do trecho ‘há uma crescente necessidade de disciplinar importantes grupo s e segmentos populacionais’ que os grupos populacionais a serem disciplinados são compostos por pessoas que têm autoridade e gozam de prestígio na sociedade, do que s e infere que tais grupos têm adotado comportamentos indesejáveis.','E',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,13,'Língua Portuguesa','A forma verbal “crescem” (ter ceiro período do primeiro parágrafo) está flexionada no plural para concordar com o sujeito composto cujos núcleos são “gastos”, “efetivos” e “serviços”.','A forma verbal “crescem” (ter ceiro período do primeiro parágrafo) está flexionada no plural para concordar com o sujeito composto cujos núcleos são “gastos”, “efetivos” e “serviços”.','E',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,14,'Língua Portuguesa','O travessão empregado no último período do primeiro parágrafo confere ao trecho final do período, por ele isolado, um destaque, mas sua supressão manteria a correção gramatical do texto.','O travessão empregado no último período do primeiro parágrafo confere ao trecho final do período, por ele isolado, um destaque, mas sua supressão manteria a correção gramatical do texto. Ainda com relação ao texto 2A1-II, julgue os itens subsecutivos.','C',3,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,15,'Língua Portuguesa','Seria mantida a correção gram atical do texto caso a forma verbal “esperam” (primeiro período do texto) fosse substituída por espera.','Seria mantida a correção gram atical do texto caso a forma verbal “esperam” (primeiro período do texto) fosse substituída por espera.','C',3,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,16,'Língua Portuguesa','Na argumentação desenvolvid a no texto, a informação presente em “Cresce rapidamente em quase todos os países o número de pessoas na prisão” (primeiro período do texto) coaduna-se com a informação presente em “o rápido crescimento parece ser um fenômeno universal em toda a ponta ‘mais desenvolvida’ do mundo” (final do último parágrafo do texto).','Na argumentação desenvolvid a no texto, a informação presente em “Cresce rapidamente em quase todos os países o número de pessoas na prisão” (primeiro período do texto) coaduna-se com a informação presente em “o rápido crescimento parece ser um fenômeno universal em toda a ponta ‘mais desenvolvida’ do mundo” (final do último parágrafo do texto).','C',3,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,17,'Língua Portuguesa','A palavra “idiossincrasias” (s egundo parágrafo) poderia ser substituída por compatibilidades s e m p r e j u í z o p a r a a correção gramatical e para os sentidos do texto.','A palavra “idiossincrasias” (s egundo parágrafo) poderia ser substituída por compatibilidades s e m p r e j u í z o p a r a a correção gramatical e para os sentidos do texto.','E',3,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,18,'Língua Portuguesa','As palavras “intensamente”, em “Em quase toda parte, a rede de prisões está se ampliando intensamente”, e “ampliada”, em “e sugere uma ‘significação muito ampliada da solução institucional como componente da política criminal’” desempenham a mesma função sintática nos períodos em que ocorrem.','As palavras “intensamente”, em “Em quase toda parte, a rede de prisões está se ampliando intensamente”, e “ampliada”, em “e sugere uma ‘significação muito ampliada da solução institucional como componente da política criminal’” desempenham a mesma função sintática nos períodos em que ocorrem. Considerando o Manual de Redação da Presidência da República, julgue os itens que se seguem.','E',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,19,'Língua Portuguesa','Quando da redação de e-mail que possa ser considerado um documento oficial, devem-se usar os mesmos parâmetros de redação dos demais documentos oficiais, o que inclui linguagem adequada.','Quando da redação de e-mail que possa ser considerado um documento oficial, devem-se usar os mesmos parâmetros de redação dos demais documentos oficiais, o que inclui linguagem adequada.','C',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,20,'Língua Portuguesa','A exposição de motivos é modalidade de comunicação dirigida pelos ministros ao Presidente da República e, em determinadas circunstâncias, poderá ser encaminhada cópia do documento ao Congresso Nacional ou ao Poder Judiciário.','A exposição de motivos é modalidade de comunicação dirigida pelos ministros ao Presidente da República e, em determinadas circunstâncias, poderá ser encaminhada cópia do documento ao Congresso Nacional ou ao Poder Judiciário.','C',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,21,'Língua Portuguesa','No endereçamento das comunicações dirigidas às autoridades superiores, devem-se empregar os seguintes pronomes de tratamento: “A Vos sa Excelência o Senhor” ou “A Vossa Excelência a Senhora”.','No endereçamento das comunicações dirigidas às autoridades superiores, devem-se empregar os seguintes pronomes de tratamento: “A Vos sa Excelência o Senhor” ou “A Vossa Excelência a Senhora”.','E',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,22,'Língua Portuguesa','Na grafia de datas em um doc umento oficial, o conteúdo deve constar conforme exemplificado a seguir: Brasília, 02/04/ 2021.','Na grafia de datas em um doc umento oficial, o conteúdo deve constar conforme exemplificado a seguir: Brasília, 02/04/ 2021.','E',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,23,'Língua Portuguesa','Nas comunicações oficiais, aboliu-se o uso dos vocativos Digníssimo (DD) e de Ilustríssimo (Ilmo.).','Nas comunicações oficiais, aboliu-se o uso dos vocativos Digníssimo (DD) e de Ilustríssimo (Ilmo.).','C',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,24,'Língua Portuguesa','No padrão ofício, o cabeçalho deve estar centralizado na área determinada pela formatação e constar em todas as páginas do documento.','No padrão ofício, o cabeçalho deve estar centralizado na área determinada pela formatação e constar em todas as páginas do documento. Determinado agente da Po lícia Federal revelou um segredo sobre uma operação policial que seria realizada para deter uma quadrilha de traficantes. Ele havia se apropriado des se segredo em razão do seu cargo. Tendo a operação fracassado, a administração da Polícia recebeu uma denúncia sobre o ocorrido e abriu processo administrativo disciplinar contra o referido servidor. Considerando essa situação hipotética, julgue os itens subsequentes.','E',3,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,25,'Direito Administrativo','O servidor, em razão do seu ato, está sujeito à pena de demissão.','O servidor, em razão do seu ato, está sujeito à pena de demissão.','C',3,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,26,'Direito Administrativo','O processo aberto contra o servidor caracteriza poder de polícia administrativo.','O processo aberto contra o servidor caracteriza poder de polícia administrativo.','E',3,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,27,'Direito Administrativo','A abertura do processo contra o servidor em questão é considerada controle externo e posterior.','A abertura do processo contra o servidor em questão é considerada controle externo e posterior. A polícia foi acionada para atender a um chamado de suspeita de ocorrência de tráfico ilícito de entorpecentes no interior de determinada sociedade de economia mista federal. Ao chegar ao local, os policiais verificaram que um dos traficante s era um brasileiro naturalizado. Considerando essa situação hipotética, julgue os itens subsecutivos.','E',3,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,28,'Direito Constitucional','A competência para a apuração do referido delito é da Polícia Federal, uma vez que lhe cabe apurar infrações penais que envolvam bens e interesses da União, suas autarquias, fundações, empresas públicas e sociedades de economia mistas.','A competência para a apuração do referido delito é da Polícia Federal, uma vez que lhe cabe apurar infrações penais que envolvam bens e interesses da União, suas autarquias, fundações, empresas públicas e sociedades de economia mistas.','X',3,'annulled',true,false,'Item anulado no gabarito oficial definitivo; não é exibido aos estudantes.'),
(2021,29,'Direito Constitucional','O tráfico ilícito de entorpecentes é crime inafiançável.','O tráfico ilícito de entorpecentes é crime inafiançável.','C',3,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,30,'Direito Constitucional','O traficante naturalizado brasileiro não poderá ser extraditado porque o crime foi praticado depois da naturalização.','O traficante naturalizado brasileiro não poderá ser extraditado porque o crime foi praticado depois da naturalização.','E',3,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,31,'Direito Penal e Processual Penal','Armazenamento consiste no pr ocedimento de embalar, de forma individualizada, cada vestígio coletado, de acordo com suas características físicas, químicas e biológicas, para análise posterior.','Armazenamento consiste no pr ocedimento de embalar, de forma individualizada, cada vestígio coletado, de acordo com suas características físicas, químicas e biológicas, para análise posterior.','E',4,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,32,'Direito Penal e Processual Penal','A consumação do delito de descaminho independe do esgotamento da via administrativa.','A consumação do delito de descaminho independe do esgotamento da via administrativa.','C',4,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,33,'Direito Penal e Processual Penal','Caracteriza-se como flagrante preparado a situação em que os policiais provocam ou induzem o cometimento do crime pelo agente.','Caracteriza-se como flagrante preparado a situação em que os policiais provocam ou induzem o cometimento do crime pelo agente. Cada um dos itens a seguir apresenta uma situação hipotética seguida de uma assertiva a ser julgada. Julgue-os com base na legislação especial.','C',4,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,34,'Direito Penal e Processual Penal','Determinada pessoa foi presa em flagrante delito, porque estava, no território brasileiro, próximo à região de fronteira com determinado país da América do Sul, transportando uma grande quantidade de drogas. Nessa situação, a configuração do tráfico transnacional d epende da comprovação da transposição da fronteira, hipótese em que a pena poderá aumentar.','Determinada pessoa foi presa em flagrante delito, porque estava, no território brasileiro, próximo à região de fronteira com determinado país da América do Sul, transportando uma grande quantidade de drogas. Nessa situação, a configuração do tráfico transnacional d epende da comprovação da transposição da fronteira, hipótese em que a pena poderá aumentar.','E',4,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,35,'Legislação Especial','No ano de 2020, um estrangeiro considerado um indivíduo nocivo e perigoso foi expulso do Brasil por ter cometido um crime comum doloso com pena privativa de liberdade. Nessa situação, ele estará impedido de reingressar no Brasil por prazo indeterminado.','No ano de 2020, um estrangeiro considerado um indivíduo nocivo e perigoso foi expulso do Brasil por ter cometido um crime comum doloso com pena privativa de liberdade. Nessa situação, ele estará impedido de reingressar no Brasil por prazo indeterminado.','E',4,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,36,'Legislação Especial','Uma pessoa apanhou à noite, em uma unidade da conservação, um espécime da fauna silvestre brasileira sem a devida permissão. Nessa situação, a pena deverá aumentar.','Uma pessoa apanhou à noite, em uma unidade da conservação, um espécime da fauna silvestre brasileira sem a devida permissão. Nessa situação, a pena deverá aumentar. Considerando que o horário de ocorrência de certo tipo de crime em determinado local seja representado por uma variável aleatória contínua 𝑋, cuja função de densidade é escrita como 𝑓ሺ𝑥ሻൌ𝛾ሺ𝑥െ1 2ሻଶ, em que 0൑𝑥൏2 4 e 𝛾 é uma constante de normalização ሺ𝛾 ൐ 0ሻ, julgue os itens subsequentes.','C',4,'under_review',true,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,37,'Estatística','O valor da constante 𝛾 é inferior a 0,01.','O valor da constante 𝛾 é inferior a 0,01.','C',4,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,38,'Estatística','O valor esperado de 𝑋 é igual a 12.','O valor esperado de 𝑋 é igual a 12.','C',4,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,39,'Estatística','𝑃ሺ𝑋ൌ5 ሻ൐ 𝛾.','𝑃ሺ𝑋ൌ5 ሻ൐ 𝛾. Considere que 𝑋 e 𝑌 sejam variáveis aleatórias contínuas que se distribuem conjuntamente conforme a função de densidade 𝑓ሺ𝑥, 𝑦ሻൌ𝑥൅𝑦 , na qual 0൏𝑥൏1 e 0൏𝑦൏1 . Com base nessas informações, julgue os itens seguintes.','E',4,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,40,'Estatística','𝑌 é uma variável aleatória uniforme no intervalo (0,1).','𝑌 é uma variável aleatória uniforme no intervalo (0,1).','E',4,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,41,'Estatística','𝑋 e 𝑌 são variáveis aleatórias independentes.','𝑋 e 𝑌 são variáveis aleatórias independentes.','E',4,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,42,'Estatística','𝐸ቂ 𝑋൅𝑌 | 𝑋ൌ ଵ ଶቃൌ ଵସ ଵଶ .','𝐸ቂ 𝑋൅𝑌 | 𝑋ൌ ଵ ଶቃൌ ଵସ ଵଶ . Espaço livre','E',4,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,43,'Estatística','A estimativa de máxima verossimilhança para o parâmetro 𝛽 é igual ou superior a 3,5.','A estimativa de máxima verossimilhança para o parâmetro 𝛽 é igual ou superior a 3,5.','E',5,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,44,'Estatística','Pelo método dos mínimos quadrados ordinários, a estimativa da média populacional é igual ou superior a 3,5.','Pelo método dos mínimos quadrados ordinários, a estimativa da média populacional é igual ou superior a 3,5.','C',5,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,45,'Estatística','A média amostral é uma estatística suficiente para a estimação do parâmetro 𝛽.','A média amostral é uma estatística suficiente para a estimação do parâmetro 𝛽. Um estudo objetivou avaliar a evolução do número mensal Y de milhares de ocorrências de certo tipo de crime em determinado ano. Com base no método dos mínimos quadrados ordinários, esse estudo apresentou um modelo de regressão linear simples da forma 𝑌෠ൌ5െ0 , 1ൈ𝑇 , em que 𝑌෠ representa a reta ajustada em função da variável regressora 𝑇, tal que 1൑𝑇൑1 2 . O s e r r o s p a d r ã o d a s e s t i m a t i v a s d o s c o e f i c i e n t e s d e s s e modelo, as razões t e seus respectivos p-valores encontram-se na tabela a seguir. erro padrão razão t p-valor intercepto 0,584 8,547 0,00 coeficiente angular 0,064 1,563 0,15 Os desvios padrão amostrais das variáveis 𝑌 e 𝑇 f o r a m , respectivamente, 1 e 3,6. Com base nessas informações, julgue os itens a seguir.','E',5,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,46,'Estatística','A correlação linear entre as variáveis 𝑌 e 𝑇 foi igual a െ0,1.','A correlação linear entre as variáveis 𝑌 e 𝑇 foi igual a െ0,1.','E',5,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,47,'Estatística','Considere que 𝑎 denote o coeficiente angular do modelo de regressão linear simples e considere, ainda, que o teste de hipóteses 𝐻଴:𝑎 ൌ 0 versus 𝐻ଵ:𝑎 ് 0. Nessa situação, com referência a esse teste, caso o nível de significância escolhido seja igual a 5%, os resultados do estudo em questão indicarão que não há evidências estatísticas contra a hipótese nula 𝐻 ଴:𝑎 ൌ 0.','Considere que 𝑎 denote o coeficiente angular do modelo de regressão linear simples e considere, ainda, que o teste de hipóteses 𝐻଴:𝑎 ൌ 0 versus 𝐻ଵ:𝑎 ് 0. Nessa situação, com referência a esse teste, caso o nível de significância escolhido seja igual a 5%, os resultados do estudo em questão indicarão que não há evidências estatísticas contra a hipótese nula 𝐻 ଴:𝑎 ൌ 0.','C',5,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,48,'Estatística','S e a m é d i a a m o s t r a l d a v a r i á v e l 𝑇 f o r i g u a l a 6 , 5 , e n t ã o a média amostral da variável 𝑌 será igual a 4,35 mil ocorrências.','S e a m é d i a a m o s t r a l d a v a r i á v e l 𝑇 f o r i g u a l a 6 , 5 , e n t ã o a média amostral da variável 𝑌 será igual a 4,35 mil ocorrências. Espaço livre','C',5,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,49,'Raciocínio Lógico','Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes seria igual ao número de maneiras de se montar, escolhendo-se entre esses mesmos profissionais, uma única equipe para a realização de uma busca em uma única localidade.','Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes seria igual ao número de maneiras de se montar, escolhendo-se entre esses mesmos profissionais, uma única equipe para a realização de uma busca em uma única localidade.','C',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,50,'Raciocínio Lógico','Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes é igual a 4!.','Se estiverem disponíveis, no momento de formação das equipes, exatamente, 2 delegados, 2 escrivães e 4 agentes, o número de maneiras distintas de se montar as duas equipes é igual a 4!.','C',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,51,'Raciocínio Lógico','Se estiverem disponíveis, no momento de formação das equipes, 3 delegados, 4 escrivães e 6 agentes, o número de maneiras distintas de se montar as duas equipes é superior a 6.500.','Se estiverem disponíveis, no momento de formação das equipes, 3 delegados, 4 escrivães e 6 agentes, o número de maneiras distintas de se montar as duas equipes é superior a 6.500. P1: Se a fiscalização foi deficiente, as falhas construtivas nã o foram corrigidas. P2: Se as falhas construtivas foram corrigidas, os mutuários nã o tiveram prejuízos. P3: A fiscalização foi deficiente. C: Os mutuários tiveram prejuízos. Considerando um argumento formado pelas proposições precedentes, em que C é a conclusão, e P1 a P3 são as premissas , julgue os itens a seguir.','E',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,52,'Raciocínio Lógico','A proposição P2 é equivalente a “Se as falhas construtivas não foram corrigidas, os mutuários tiveram prejuízos”.','A proposição P2 é equivalente a “Se as falhas construtivas não foram corrigidas, os mutuários tiveram prejuízos”.','E',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,53,'Raciocínio Lógico','Uma negação correta da proposição P1 pode ser expressa por: “Se a fiscalização não foi deficiente, as falhas construtivas foram corrigidas”.','Uma negação correta da proposição P1 pode ser expressa por: “Se a fiscalização não foi deficiente, as falhas construtivas foram corrigidas”.','E',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,54,'Raciocínio Lógico','A tabela verdade da proposição condicional associada ao argumento tem menos de dez linhas.','A tabela verdade da proposição condicional associada ao argumento tem menos de dez linhas.','C',6,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,55,'Raciocínio Lógico','A proposição P1 é equivalente a “Não é verdade que a fiscalização foi deficiente e que as falhas construtivas foram corrigidas”.','A proposição P1 é equivalente a “Não é verdade que a fiscalização foi deficiente e que as falhas construtivas foram corrigidas”.','C',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,56,'Raciocínio Lógico','C a s o o a r g u m e n t o a p r e s e n t a d o s e j a v á l i d o , a p r o p o s i ç ã o C será verdadeira.','C a s o o a r g u m e n t o a p r e s e n t a d o s e j a v á l i d o , a p r o p o s i ç ã o C será verdadeira.','E',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,57,'Raciocínio Lógico','O argumento apresentado não é válido.','O argumento apresentado não é válido. Considere os seguintes conjuntos: P = {todos os policiais federais em efetivo exercício no país} P1 = {policiais federais em efetivo exercício no país e que têm até 1 ano de experiência no exercício do cargo} P2 = {policiais federais em efetivo exercício no país e que têm até 2 anos de experiência no exercício do cargo} P3 = {policiais federais em efetivo exercício no país e que têm até 3 anos de experiência no exercício do cargo} e, assim, sucessivamente. Com base nessas informações, julgue os itens que se seguem.','C',6,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,58,'Raciocínio Lógico','O c o n j u n t o P é i g u a l à u n i ã o i n f i n i t a d o s c o n j u n t o s P1, P 2, P3, ...','O c o n j u n t o P é i g u a l à u n i ã o i n f i n i t a d o s c o n j u n t o s P1, P 2, P3, ...','C',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,59,'Raciocínio Lógico','P2 é subconjunto de P1.','P2 é subconjunto de P1.','E',6,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,60,'Raciocínio Lógico','Escolhendo-se aleatoriamente um integrante do conjunto P, a probabilidade de ele ter entre doi s e três anos de experiência no exercício do cargo é dada por n(P 2 – P3)/n(P3), em que n(X) indica o número de elementos do conjunto X e P2 – P3 é o conjunto formado pelos indivíduos que estão em P 2, mas não estão em P3.','Escolhendo-se aleatoriamente um integrante do conjunto P, a probabilidade de ele ter entre doi s e três anos de experiência no exercício do cargo é dada por n(P 2 – P3)/n(P3), em que n(X) indica o número de elementos do conjunto X e P2 – P3 é o conjunto formado pelos indivíduos que estão em P 2, mas não estão em P3. Espaço livre','E',6,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,61,'Informática','A forma correta para pesquisar no Google a correspondência exata da frase “crime organizado”, exclusivamente no sítio pf.gov.br, é "crime organizado" in pf.gov.br.','A forma correta para pesquisar no Google a correspondência exata da frase “crime organizado”, exclusivamente no sítio pf.gov.br, é "crime organizado" in pf.gov.br.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,62,'Informática','A versão atual do Google Chrome dispõe de recurso que permite avisar o usuário sobre a possibilidade de ele estar utilizando uma combinação de senha e de nome de usuário comprometida em um vazamento de dados em um sítio ou em um aplicativo de terceiros.','A versão atual do Google Chrome dispõe de recurso que permite avisar o usuário sobre a possibilidade de ele estar utilizando uma combinação de senha e de nome de usuário comprometida em um vazamento de dados em um sítio ou em um aplicativo de terceiros.','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,63,'Informática','Se, quando do acesso ao sítio https://www.gov.br/pf/pt-br n a versão mais recente do Google Chrome, for visualizado o ícone de um cadeado cinza ao lado da URL, o símbolo em questão estará sinalizando q ue esse ambiente refere-se à intranet da Polícia Federal.','Se, quando do acesso ao sítio https://www.gov.br/pf/pt-br n a versão mais recente do Google Chrome, for visualizado o ícone de um cadeado cinza ao lado da URL, o símbolo em questão estará sinalizando q ue esse ambiente refere-se à intranet da Polícia Federal.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,64,'Informática','No Linux, o comando pwd é utilizado para realizar a troca de senha das contas de usuários do sistema, ação que somente pode ser realizada por usuário que tenha determinados privilégios no ambiente para executá-la.','No Linux, o comando pwd é utilizado para realizar a troca de senha das contas de usuários do sistema, ação que somente pode ser realizada por usuário que tenha determinados privilégios no ambiente para executá-la.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,65,'Informática','Se um usuário recebesse a planilha Excel a seguir somente com os dados contidos nas colunas A e B e necessitasse preencher a coluna C, em vez de digitar manualmente os dados, ele poderia, para fazer o referido preenchimento, digitar o conteúdo “Acre - AC” na célula C1; selecionar a célula C1; e acionar o botão na guia dados.','Se um usuário recebesse a planilha Excel a seguir somente com os dados contidos nas colunas A e B e necessitasse preencher a coluna C, em vez de digitar manualmente os dados, ele poderia, para fazer o referido preenchimento, digitar o conteúdo “Acre - AC” na célula C1; selecionar a célula C1; e acionar o botão na guia dados. No que se refere a redes de computadores, julgue os itens que s e seguem.','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,66,'Informática','Na comunicação entre dois di spositivos na Internet, o protocolo IP especifica o formato dos pacotes que trafegam entre roteadores e sistemas finais.','Na comunicação entre dois di spositivos na Internet, o protocolo IP especifica o formato dos pacotes que trafegam entre roteadores e sistemas finais.','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,67,'Informática','A pilha de protocolos TCP/IP de cinco camadas e a pilha do modelo de referência OSI têm, em comum, as camadas física, de enlace, de rede, de transporte e de aplicação.','A pilha de protocolos TCP/IP de cinco camadas e a pilha do modelo de referência OSI têm, em comum, as camadas física, de enlace, de rede, de transporte e de aplicação.','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,68,'Informática','O S M T P é o p r o t o c o l o i n d i c a d o p a r a p r o v e r o s e r v i ç o confiável de transferência de dados em formulários de dados no caso de o usuário estar trafegando em sítios da Internet, por exemplo.','O S M T P é o p r o t o c o l o i n d i c a d o p a r a p r o v e r o s e r v i ç o confiável de transferência de dados em formulários de dados no caso de o usuário estar trafegando em sítios da Internet, por exemplo. Com referência a conceitos de proteção e de segurança, julgue o s itens subsecutivos.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,69,'Informática','Caso o usuário tenha recebido um conjunto de arquivos com trojan em seu conteúdo e esses arquivos estejam em uma mídia de armazenamento local em sua estação de trabalho, recomenda-se a utilização de IDS ( intrusion detection system) para a realização da limpeza dos arquivos.','Caso o usuário tenha recebido um conjunto de arquivos com trojan em seu conteúdo e esses arquivos estejam em uma mídia de armazenamento local em sua estação de trabalho, recomenda-se a utilização de IDS ( intrusion detection system) para a realização da limpeza dos arquivos.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,70,'Informática','Denomina-se backdoor a situação em que um usuário sofre um ataque, seus dados são criptografados, ficam inacessíveis e, então, exige-se desse usuário o pagamento de resgate para o restabelecimento do acesso a seus dados.','Denomina-se backdoor a situação em que um usuário sofre um ataque, seus dados são criptografados, ficam inacessíveis e, então, exige-se desse usuário o pagamento de resgate para o restabelecimento do acesso a seus dados. Acerca de computação na nuvem ( cloud computing ), julgue os itens subsequentes.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,71,'Informática','A PaaS (plataforma como um serviço) c o n t é m o s componentes básicos da IT na nuvem e oferece o mais alto nível de flexibilidade e de controle de gerenciamento sobre os recursos de tecnologia da informação no que diz respeito a cloud computing.','A PaaS (plataforma como um serviço) c o n t é m o s componentes básicos da IT na nuvem e oferece o mais alto nível de flexibilidade e de controle de gerenciamento sobre os recursos de tecnologia da informação no que diz respeito a cloud computing.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,72,'Informática','As desvantagens da cloud computing i n c l u e m a inflexibilidade relativa ao provisionamento de recursos computacionais: é necessário estabelecê-los no momento da contratação e não há possibilidade de ajustes de escala, de acordo com a evolução das necessidades, no mesmo contrato.','As desvantagens da cloud computing i n c l u e m a inflexibilidade relativa ao provisionamento de recursos computacionais: é necessário estabelecê-los no momento da contratação e não há possibilidade de ajustes de escala, de acordo com a evolução das necessidades, no mesmo contrato. Considerando a teoria geral de sistemas e sistemas de informação, julgue os itens a seguir.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,73,'Informática','À medida que os sistemas sofrem mudanças, o ajustamento sistemático ocorre de forma contínua; dessas mudanças e dos ajustamentos decorrem fenômenos como, por exemplo, a entropia e a homeostasia.','À medida que os sistemas sofrem mudanças, o ajustamento sistemático ocorre de forma contínua; dessas mudanças e dos ajustamentos decorrem fenômenos como, por exemplo, a entropia e a homeostasia.','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,74,'Informática','Cada sistema existe dentro de um meio ambiente constituído por outros sistemas e, nesse contexto, os sistemas abertos caracterizam-se por consistirem em um processo infinito de intercâmbio com o seu ambiente para a realização da troca de informações.','Cada sistema existe dentro de um meio ambiente constituído por outros sistemas e, nesse contexto, os sistemas abertos caracterizam-se por consistirem em um processo infinito de intercâmbio com o seu ambiente para a realização da troca de informações.','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,75,'Informática','Embora não seja dirigido a riscos, o modelo de desenvolvimento de sistemas espiral de Boehm inclui, em seu framework, a etapa de análise e validação dos requisitos.','Embora não seja dirigido a riscos, o modelo de desenvolvimento de sistemas espiral de Boehm inclui, em seu framework, a etapa de análise e validação dos requisitos.','E',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,76,'Informática','Uma das etapas descritas em um método de desenvolvimento de sistema clássico é a de análise e definição de requisitos, etapa em que as restrições e a s metas do sistema são obtidas por meio de consulta a usuários, com o objetivo de realizar a especificação do sistema.','Uma das etapas descritas em um método de desenvolvimento de sistema clássico é a de análise e definição de requisitos, etapa em que as restrições e a s metas do sistema são obtidas por meio de consulta a usuários, com o objetivo de realizar a especificação do sistema. Espaço livre','C',7,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,77,'Informática','Considerando-se a classificação dados, informação, conhecimento e inteligência, é c orreto afirmar que o gráfico representa, por si só, a inteligência.','Considerando-se a classificação dados, informação, conhecimento e inteligência, é c orreto afirmar que o gráfico representa, por si só, a inteligência.','E',8,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,78,'Informática','O número 1.789 sozinho car acteriza uma informação, independentemente do contexto.','O número 1.789 sozinho car acteriza uma informação, independentemente do contexto. Com referência aos conceitos de rede de computadores, julgue os itens a seguir.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,79,'Informática','Os roteadores operam na camada de rede do modelo ISO/OSI.','Os roteadores operam na camada de rede do modelo ISO/OSI.','C',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,80,'Informática','UDP (user datagram protocol ) e TCP (transmission control protocol) são protocolos da camada de transporte do modelo ISO/OSI.','UDP (user datagram protocol ) e TCP (transmission control protocol) são protocolos da camada de transporte do modelo ISO/OSI.','C',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,81,'Informática','Os bits são empacotados em quadros ( dataframes) em camada de transporte do modelo de rede.','Os bits são empacotados em quadros ( dataframes) em camada de transporte do modelo de rede.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,82,'Informática','Uma LAN ( local area network ) fornece conectividade em tempo integral para os serviços de conexão da Internet.','Uma LAN ( local area network ) fornece conectividade em tempo integral para os serviços de conexão da Internet. Julgue o próximo item, relativo a conceitos de metadados de arquivos.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,83,'Informática','A função do metadado de arquivo é descrever o destino final do arquivo definido pelo emissor da mensagem e proprietário do arquivo.','A função do metadado de arquivo é descrever o destino final do arquivo definido pelo emissor da mensagem e proprietário do arquivo. Com relação a conceitos de programação Python e R, julgue os itens que se seguem.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,84,'Informática','O código Python a seguir apresenta como resultado "True".','O código Python a seguir apresenta como resultado "True". x = bool(-3) y = bool("True"*x) z = bool("False") print (x and y and z)','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,85,'Informática','O resultado do código R seguinte será "12".','O resultado do código R seguinte será "12". f<- function(x) { g <- function(y) { y + z } z <- 4 x + g(x) } z <- 10 f (4) Acerca dos conceitos de mineração de dados, aprendizado de máquina e bigdata, julgue os próximos itens.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,86,'Informática','A análise de clustering é uma tarefa que consiste em agrupar um conjunto de objetos de tal forma que estes, juntos no mesmo grupo, sejam mais semelhantes entre si que em outros grupos.','A análise de clustering é uma tarefa que consiste em agrupar um conjunto de objetos de tal forma que estes, juntos no mesmo grupo, sejam mais semelhantes entre si que em outros grupos.','C',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,87,'Informática','Entropia da informação é uma medida de certeza de que o intervalo contém um parâmetro da população.','Entropia da informação é uma medida de certeza de que o intervalo contém um parâmetro da população.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,88,'Informática','As aplicações de bigdata caracterizam-se exclusivamente pelo grande volume de dados armazenados em tabelas relacionais.','As aplicações de bigdata caracterizam-se exclusivamente pelo grande volume de dados armazenados em tabelas relacionais. No que diz respeito a modelagem conceitual, julgue os itens que se seguem.','E',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,89,'Informática','Se uma tabela de banco de dados tiver 205 atributos, então isso significa que ela tem 205 registros.','Se uma tabela de banco de dados tiver 205 atributos, então isso significa que ela tem 205 registros.','E',8,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,90,'Informática','No modelo de entidade-relacionamento, entidade normalmente representa um objeto do mundo real.','No modelo de entidade-relacionamento, entidade normalmente representa um objeto do mundo real. Julgue os itens a seguir relativos a conceitos de base de dados , documentação e prototipação.','C',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,91,'Informática','Em um sistema gerenciado de banco de dados, as restrições de integridade garantem que os dados possam ser armazenados, consultados e utilizados com confiabilidade.','Em um sistema gerenciado de banco de dados, as restrições de integridade garantem que os dados possam ser armazenados, consultados e utilizados com confiabilidade.','C',8,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,92,'Informática','Atomicidade refere-se à propriedade de um sistema gerenciador de banco de dados (SGBD) que garante que os dados armazenados sejam indivisíveis.','Atomicidade refere-se à propriedade de um sistema gerenciador de banco de dados (SGBD) que garante que os dados armazenados sejam indivisíveis. Espaço livre 3% 53%32% 9% 3% 0% Idade dos traficantes 15 a 19 anos 20 a 29 anos 30 a 39 anos 40 a 49 anos 50 a 59 anos 60 anos ou mais','X',8,'annulled',false,false,'Item anulado no gabarito oficial definitivo; não é exibido aos estudantes.'),
(2021,93,'Informática','Uma hiperchave é uma tupla que permite recuperar uma relação de uma tabela.','Uma hiperchave é uma tupla que permite recuperar uma relação de uma tabela. No que se refere aos conceitos de dados estruturados e não estruturados, julgue o próximo item.','E',9,'under_review',false,true,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,94,'Informática','Os dados estruturados diferenciam-se dos dados não estruturados pela rigidez em seu formato e pelo fato de poderem ser armazenados em campos de tabelas de um banco de dados relacional.','Os dados estruturados diferenciam-se dos dados não estruturados pela rigidez em seu formato e pelo fato de poderem ser armazenados em campos de tabelas de um banco de dados relacional. Com referência a conceitos de banco de dados relacionais, julgu e o item subsequente.','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,95,'Informática','Na linguagem SQL (structured query language), DTL (data transaction language ) são comandos responsáveis por gerenciar diferentes transações ocorridas dentro de um banco de dados.','Na linguagem SQL (structured query language), DTL (data transaction language ) são comandos responsáveis por gerenciar diferentes transações ocorridas dentro de um banco de dados. Julgue o item a seguir, a respeito dos conceitos de API (application programming interface).','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,96,'Informática','API é um padrão XML usado para desenvolver uma interface de aplicativos em dispositivos computacionais em servidores HTTP ou HTTPS.','API é um padrão XML usado para desenvolver uma interface de aplicativos em dispositivos computacionais em servidores HTTP ou HTTPS. BLOCO III Determinada empresa apresentou, em 31 de dezembro de 2020, um patrimônio composto pelos seguintes elementos, cujo registro e cuja avaliação contábei s estão de acordo com as regr as estabelecidas na legislação socie tária (Lei n.º 6.404/1976 e su as alterações). elemento patrimonial valor (R$) caixa 20.000 duplicatas a receber 50.000 empréstimos a pagar 30.000 estoques 40.000 imóveis de uso próprio 200.000 depreciação acumulada 10.000 capital social 220.000 fornecedores 20.000 salários a pagar 50.000 reservas de lucros 10.000 depósitos em bancos 10.000 impostos a recolher 10.000 aplicações financeiras de liquidez imediata 30.000 Considerando os elementos patrimoniais apresentados nessa situação hipotética, julgue os itens a seguir.','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,97,'Contabilidade Geral','Em 31 de dezembro de 2020, a situação patrimonial líquida da empresa alcançou o montante de R$ 230.000.','Em 31 de dezembro de 2020, a situação patrimonial líquida da empresa alcançou o montante de R$ 230.000.','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,98,'Contabilidade Geral','Conclui-se que os imóveis de uso próprio foram avaliados pelo seu custo de aquisição, deduzido do saldo da respectiva conta de depreciação acumulada.','Conclui-se que os imóveis de uso próprio foram avaliados pelo seu custo de aquisição, deduzido do saldo da respectiva conta de depreciação acumulada.','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,99,'Contabilidade Geral','Caixa e estoques são elementos patrimoniais cujas contas apresentam saldos de natureza credora.','Caixa e estoques são elementos patrimoniais cujas contas apresentam saldos de natureza credora.','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,100,'Contabilidade Geral','As disponibilidades da empresa totalizaram R$ 30.000 em 31 de dezembro de 2020.','As disponibilidades da empresa totalizaram R$ 30.000 em 31 de dezembro de 2020.','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,101,'Contabilidade Geral','Os saldos dos recursos aplicados no ativo da empresa totalizaram R$ 350.000 em 31 de dezembro de 2020; desse total, R$ 120.000 foram provenientes de capital de terceiros.','Os saldos dos recursos aplicados no ativo da empresa totalizaram R$ 350.000 em 31 de dezembro de 2020; desse total, R$ 120.000 foram provenientes de capital de terceiros. Considere que a empresa XYZ tenha quitado antecipadamente uma dívida, tendo obtido, no ato da quitação, um desconto pela antecipação dos valores até então pendentes de pagamento. Com base nessa situação hipotética, julgue os itens seguintes.','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,102,'Contabilidade Geral','O pagamento antecipado da dívida representa um fato contábil misto para a empresa XYZ.','O pagamento antecipado da dívida representa um fato contábil misto para a empresa XYZ.','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,103,'Contabilidade Geral','O desconto obtido pela empresa XYZ deve ser reconhecido como receita financeira na mesma data da quitação da dívida, em consonância com o regime de competência.','O desconto obtido pela empresa XYZ deve ser reconhecido como receita financeira na mesma data da quitação da dívida, em consonância com o regime de competência. Com relação à técnica de escritu ração contábil, julgue os itens subsequentes.','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,104,'Contabilidade Geral','A versão ampliada da equação do patrimônio pode ser expressa da seguinte forma: ativo + receitas + ganhos = passivo + despesas + perdas + patrimônio líquido (contas de capital).','A versão ampliada da equação do patrimônio pode ser expressa da seguinte forma: ativo + receitas + ganhos = passivo + despesas + perdas + patrimônio líquido (contas de capital).','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,105,'Contabilidade Geral','No livro Razão devem ser apresentados os saldos das contas representativas dos elementos patrimoniais de uma entidade.','No livro Razão devem ser apresentados os saldos das contas representativas dos elementos patrimoniais de uma entidade.','C',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,106,'Contabilidade Geral','As contas de compensação destinam-se ao controle e ao registro contábil de fatos que podem vir a provocar alterações no patrimônio da entidade no futuro.','As contas de compensação destinam-se ao controle e ao registro contábil de fatos que podem vir a provocar alterações no patrimônio da entidade no futuro.','X',9,'annulled',false,false,'Item anulado no gabarito oficial definitivo; não é exibido aos estudantes.'),
(2021,107,'Contabilidade Geral','Os saldos da conta fornecedores e da conta impostos a recolher são, por natureza, devedores.','Os saldos da conta fornecedores e da conta impostos a recolher são, por natureza, devedores.','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,108,'Contabilidade Geral','Os rendimentos decorrentes das aplicações financeiras representam um fato modificativo cujo lançamento contábil deve ser efetuado a débito da própria conta representativa dessas aplicações financeiras.','Os rendimentos decorrentes das aplicações financeiras representam um fato modificativo cujo lançamento contábil deve ser efetuado a débito da própria conta representativa dessas aplicações financeiras.','X',9,'annulled',false,false,'Item anulado no gabarito oficial definitivo; não é exibido aos estudantes.'),
(2021,109,'Contabilidade Geral','A terceira fórmula de lançamento contábil, também denominada fórmula complexa, requer a utilização de uma conta devedora e duas ou mais contas credoras para o registro de um evento contábil.','A terceira fórmula de lançamento contábil, também denominada fórmula complexa, requer a utilização de uma conta devedora e duas ou mais contas credoras para o registro de um evento contábil. Espaço livre','E',9,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,110,'Contabilidade Geral','Bens sem potencial de serviços ou incapazes de gerar benefícios econômicos não se enquadram na definição de ativo.','Bens sem potencial de serviços ou incapazes de gerar benefícios econômicos não se enquadram na definição de ativo.','C',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,111,'Contabilidade Geral','O custo de liberação é uma base de mensuração aplicável aos ativos em geral, representando o montante necessário para a baixa imediata de um bem ou direito sob controle de uma entidade.','O custo de liberação é uma base de mensuração aplicável aos ativos em geral, representando o montante necessário para a baixa imediata de um bem ou direito sob controle de uma entidade.','E',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,112,'Contabilidade Geral','A consistência é uma condição que favorece a comparabilidade da informação contábil ao estabelecer que sejam utilizados os mesmos princípios ou políticas contábeis e a mesma base de elaboração para as demonstrações contábeis, procedimento que v ale de período para período dentro de uma mesma empresa, bem como em relação a um mesmo período contábil envolvendo empresas distintas.','A consistência é uma condição que favorece a comparabilidade da informação contábil ao estabelecer que sejam utilizados os mesmos princípios ou políticas contábeis e a mesma base de elaboração para as demonstrações contábeis, procedimento que v ale de período para período dentro de uma mesma empresa, bem como em relação a um mesmo período contábil envolvendo empresas distintas. Considere que determinada empresa possua, entre seus ativos, alguns recebíveis oriundos de vendas a prazo, cujo recebimento não é considerado líquido e certo. Diante dessa situação hipotética, julgue os itens a seguir.','C',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,113,'Contabilidade Geral','O procedimento contábil indicado para o caso é avaliar tais recebíveis pelo seu valor líquido de realização, efetuando-se os ajustes contábeis necessários para que o valor do patrimônio da empresa passe a refletir as perdas estimadas relacionadas aos recebíveis cuja liquidação tenha caráter duvidoso.','O procedimento contábil indicado para o caso é avaliar tais recebíveis pelo seu valor líquido de realização, efetuando-se os ajustes contábeis necessários para que o valor do patrimônio da empresa passe a refletir as perdas estimadas relacionadas aos recebíveis cuja liquidação tenha caráter duvidoso.','C',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,114,'Contabilidade Geral','As perdas estimadas relacionadas a recebíveis de liquidação duvidosa devem ser reconhecidas como despesas, em contrapartida à própria conta de ativo que representa esses recebíveis.','As perdas estimadas relacionadas a recebíveis de liquidação duvidosa devem ser reconhecidas como despesas, em contrapartida à própria conta de ativo que representa esses recebíveis. Com relação à demonstração do resultado do exercício, julgue os itens subsecutivos.','E',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,115,'Contabilidade Geral','Adiantamentos a empregados é uma despesa administrativa que deve ser tratada na demonstração do resultado do exercício como um item de natureza operacional.','Adiantamentos a empregados é uma despesa administrativa que deve ser tratada na demonstração do resultado do exercício como um item de natureza operacional.','E',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,116,'Contabilidade Geral','Deduções sobre vendas são todas as despesas que incidem diretamente sobre a receita bruta de vendas.','Deduções sobre vendas são todas as despesas que incidem diretamente sobre a receita bruta de vendas.','E',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,117,'Contabilidade Geral','Nas empresas do setor industrial, o custo das vendas recebe o nome de custo do produto vendido (CPV).','Nas empresas do setor industrial, o custo das vendas recebe o nome de custo do produto vendido (CPV). Com relação aos pronunciamen tos técnicos do Comitê de Pronunciamentos Contábeis (CPC), julgue os próximos itens.','C',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,118,'Contabilidade Geral','A dívida que uma entidade mantém com o intuito de negociação no mercado deve ser classificada no passivo circulante.','A dívida que uma entidade mantém com o intuito de negociação no mercado deve ser classificada no passivo circulante.','C',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.'),
(2021,119,'Contabilidade Geral','O valor residual de um ativo não deve ser considerado para fins de cálculo do seu valor depreciável.','O valor residual de um ativo não deve ser considerado para fins de cálculo do seu valor depreciável.','X',10,'annulled',false,false,'Item anulado no gabarito oficial definitivo; não é exibido aos estudantes.'),
(2021,120,'Contabilidade Geral','Um ativo intangível com vida útil definida está sujeito à amortização de seu valor, a qual terá início no momento em que tal ativo estiver disponível para uso.','Um ativo intangível com vida útil definida está sujeito à amortização de seu valor, a qual terá início no momento em que tal ativo estiver disponível para uso. Espaço livre','C',10,'under_review',false,false,'Item histórico aguardando confronto individual com o edital PF 2025 e fontes vigentes.')
), editions as (
  select id,contest_year from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Agente de Polícia Federal' and contest_year=2021
), resolved as (
  select imported.*, question_source.id question_source_id, answer_source.id answer_key_source_id, topic.id syllabus_topic_id
  from imported
  join editions on editions.contest_year=imported.exam_year
  join public.syllabus_topics topic on topic.edition_id=editions.id and topic.discipline=imported.subject and topic.topic_order=1
  join public.content_sources question_source on question_source.title='Prova objetiva PF - Agente - ' || imported.exam_year
  join public.content_sources answer_source on answer_source.title='Gabarito definitivo PF - Agente - ' || imported.exam_year
)
insert into public.official_exam_questions (
  question_source_id,answer_key_source_id,syllabus_topic_id,contest_name,career_name,exam_board,exam_year,item_number,subject,
  question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,
  context_review_required,review_note
)
select question_source_id,answer_key_source_id,syllabus_topic_id,'Polícia Federal','Agente de Polícia Federal','CEBRASPE',exam_year,item_number,subject,
  question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,
  context_review_required,review_note
from resolved
on conflict (contest_name,exam_year,item_number) do nothing;

with src as (select id from public.content_sources where url='https://www.cebraspe.org.br/concursos/encerrado'),
edition as (select id from public.syllabus_editions where contest_name='Polícia Rodoviária Federal' and role_name='Policial Rodoviário Federal' and contest_year=2021),
topic_map(item_from,item_to,discipline) as (values
  (1,8,'Língua Estrangeira - Inglês'),(9,26,'Língua Portuguesa'),(27,32,'Raciocínio Lógico-Matemático'),
  (33,39,'Informática'),(40,44,'Física'),(45,50,'Ética no Serviço Público'),(51,55,'Geografia dos Transportes'),
  (56,85,'Direito de Trânsito'),(86,92,'Direito Administrativo'),(93,99,'Direito Constitucional'),
  (100,115,'Direito Penal e Processual Penal'),(116,120,'Direitos Humanos')
),
imported(item_number,statement,official_answer,source_page) as (values
(1,'Extremely cold temperatures in Texas created problems for the distribution of energy in the state.','X',1),
(2,'In the last paragraph of the text, "That" refers to the decision by Texas to isolate its energy grid from the rest of the country.','C',1),
(3,'Despite the cold temperatures, energy production in Texas continued unimpeded.','E',1),
(4,'Changes in energy production in Texas are having an impact across the United States.','C',1),
(5,'There are other states, like Florida, that produce energy on a level similar to that of Texas.','E',1),
(6,'There are places in the world where wind power works well in freezing temperatures.','C',1),
(7,'In "Natural gas and coal-fired power plants need water to stay online. Yet those water facilities froze in the cold temperatures and others lost access to the electricity they require to operate", it is possible to substitute "Yet" for Even so without changing the meaning of the sentence.','C',1),
(8,'The text points to the lack of wind as the primary cause for a dip in the production of wind energy during the period described.','E',1),
(9,'A transferência da polícia do sistema de justiça para o governo da cidade marca o que pode ser considerado uma mudança de paradigma no que se refere ao papel da polícia na sociedade.','C',1),
(10,'Seriam mantidos a correção gramatical e os sentidos do texto caso o segundo período do primeiro parágrafo fosse reescrito da seguinte maneira: Porque nos países europeus houve empenho em prevenir crimes, o que representou nova atitude de controle social, o resultado foi o desenvolvimento de uma habilidade específica pelas autoridades policiais: a de explicar e prevenir o crime.','E',1),
(11,'Infere-se da leitura do primeiro parágrafo do texto que o desenvolvimento de áreas científicas ligadas à justiça criminal no século XIX está associado a visões preconceituosas sobre certos grupos de indivíduos.','C',1),
(12,'Um dos traços característicos da modernidade, segundo Norbert Elias, é a renúncia de certas emoções e de certos prazeres pelos indivíduos, que, em compensação, passaram a ser protegidos da violência devido à atuação do Estado.','C',1),
(13,'Depreende-se do segundo parágrafo do texto que a violência na era medieval era comum e socialmente aceita.','C',1),
(14,'Conclui-se do texto que o monopólio da violência legítima pelo Estado deveu-se à necessidade de reação aos índices insustentáveis de violência física entre os indivíduos.','E',1),
(15,'O pronome "Isso", que introduz o terceiro período do primeiro parágrafo do texto, poderia ser corretamente substituído por O que.','E',1),
(16,'Infere-se do segundo parágrafo do texto que a agressividade humana passou por um processo de transformação gradativo de perda de aspectos primitivos e animalescos.','C',1),
(17,'O emprego do vocábulo "irrupção", no último período do texto, indica que a violência atingia os indivíduos de forma súbita.','C',1),
(18,'Mantém-se a correção gramatical do trecho "o autocontrole e a moderação das emoções que acabaram por se impor na modernidade", do texto, caso a forma verbal "impor" seja flexionada no plural imporem.','E',1),
(19,'A correção gramatical do último período do texto seria mantida, embora seu sentido original fosse prejudicado, se a locução "na medida em que" fosse substituída por à medida que e a vírgula empregada logo após "vida" fosse suprimida.','C',1),
(20,'O trecho "A conversão do controle que se exercia por terceiros no autocontrole é relacionada à organização e à estabilização de Estados modernos" poderia ser reescrito da seguinte forma, sem prejuízo para os sentidos e para a correção gramatical do texto: Converter o controle efetuado por terceiros a autocontrole concatena a organização e estabilização dos Estados do mundo moderno.','E',1),
(21,'A coerência e os sentidos do texto seriam mantidos caso fosse suprimido o artigo "os", no trecho "desenvolveram-se os vários campos de saber", no último período do primeiro parágrafo.','E',1),
(22,'Entre as características da redação oficial incluem-se a objetividade, a impessoalidade e a informatividade.','E',1),
(23,'Na identificação do signatário de uma comunicação oficial destinada a uma pessoa do sexo feminino, dispensa-se flexão de gênero no nome do cargo.','E',1),
(24,'O vocativo, nas comunicações oficiais, deverá ser sempre seguido de vírgula.','C',1),
(25,'De acordo com a legislação vigente, o e-mail institucional tem valor documental e, por isso, deve ser aceito como documento original.','E',1),
(26,'O assunto das comunicações oficiais deve apresentar de forma geral o que será tratado no documento e seu formato deve seguir as orientações do MRPR, conforme o exemplo a seguir. Assunto: Realização de concurso público.','C',1),
(27,'Se, em determinado instante, 30% da população já conhece a notícia, então, nesse instante, o seu espalhamento estaria em patamar superior a 20% por unidade de tempo.','E',2),
(28,'Se, em determinado instante, o espalhamento de uma notícia é igual a 16% por unidade de tempo, então, nesse instante, mais de 75% da população ainda desconhece a notícia.','E',2),
(29,'De acordo com a modelagem realizada, é possível que, em determinado instante, o espalhamento da notícia seja superior a 50% por unidade de tempo.','E',2),
(30,'O espalhamento de uma notícia será tanto maior quanto maior for o número de pessoas que dela tiverem tomado conhecimento.','E',2),
(31,'Mais de 550 veículos terão sido fiscalizados até o fim da sétima hora de realização da operação.','C',2),
(32,'Considere que {qn}, para n variando de 1 a 10, seja a sequência numérica formada pelas quantidades de veículos fiscalizados apenas no decorrer da n-ésima hora de realização da operação. Nessa situação, a sequência {qn}, para n variando de 1 a 10, é uma progressão aritmética.','C',2),
(33,'Embora as versões mais atuais do Mozilla Firefox e do Google Chrome permitam salvar e sincronizar senhas para realizar, posteriormente, login automático em formulários de sítios da Internet, essa ação somente será possível se os sítios em questão estiverem disponibilizados em uma intranet e utilizarem o protocolo HTTPS.','E',2),
(34,'No Windows, ainda que seja possível compartilhar configurações — como plano de fundo e histórico de navegação do Internet Explorer — entre computadores que utilizem a mesma conta em outras máquinas com Windows 10, não é permitido, em razão da segurança, o compartilhamento de senhas.','C',2),
(35,'Caso sejam digitados os termos descritos a seguir na ferramenta de busca do Google, serão pesquisadas publicações que contenham os termos "PRF" e "campanha" na rede social Twitter. campanha PRF @twitter','C',2),
(36,'A Internet das coisas (IoT) aumenta a quantidade e a complexidade dos dados por meio de novas formas e novas fontes de informações, influenciando diretamente em uma ou mais das características do big data, a exemplo de volume, velocidade e variedade.','C',2),
(37,'Ransomware é um programa malicioso de computador que se propaga por meio da inserção de cópias de si mesmo em arquivos criptografados.','E',2),
(38,'Identifica-se Software como Serviço (SaaS) quando um provedor de serviços oferece acesso a um ambiente baseado em cloud, no qual os usuários podem construir e disponibilizar aplicativos.','E',2),
(39,'O firewall da próxima geração (NGFW) dispõe, em um mesmo equipamento, de recursos como IDS (intrusion detection system), IPS (intrusion prevention system) e antivírus.','X',2),
(40,'Durante todo o movimento, a aceleração vetorial do projétil será constante.','C',2),
(41,'Na posição de altura máxima, a força resultante sobre o projétil será nula.','E',2),
(42,'Na posição de altura máxima, a velocidade vetorial do projétil será nula.','E',2),
(43,'Na posição de compressão máxima, a energia potencial elástica armazenada na mola tem valor menor que o da energia cinética do projétil antes da colisão.','C',3),
(44,'Como não há atrito entre o bloco de madeira e a mesa horizontal, a conservação da energia mecânica garante que o valor da energia cinética do sistema imediatamente antes da colisão seja igual ao valor da energia cinética do sistema imediatamente após a colisão.','E',3),
(45,'A revelação de segredo do qual o servidor se apropriou em razão do cargo enseja a penalidade de demissão, o que implica o ressarcimento ao erário por parte do servidor.','X',3),
(46,'De acordo com o Código de Ética Profissional do Servidor Público Civil do Poder Executivo Federal, ausência de servidor do seu local de trabalho é fator de desmoralização do serviço público, já que pode acarretar desordem nas relações humanas.','C',3),
(47,'A estratégia, que consiste em um mecanismo para o exercício da governança pública, compreende a definição de diretrizes, objetivos, planos e ações, para que os serviços de responsabilidade da organização alcancem o resultado pretendido.','C',3),
(48,'O investigado poderá ter vista dos autos, com direito a cópia se assim o desejar, mesmo antes da notificação da existência de procedimento investigatório em comissão de ética.','C',3),
(49,'Caso terceiro solicite, por telefone, informação sobre aquisições de determinado órgão público, o servidor deverá orientá-lo a preencher o formulário padrão, disponibilizado em meio eletrônico e físico, com os dados exigidos pela lei.','E',3),
(50,'O diretor-geral da Polícia Rodoviária Federal, desde que satisfeitos os requisitos legais, poderá realizar a contratação direta de empresa na qual um primo seja sócio.','C',3),
(51,'A duplicação dos principais eixos rodoviários, a restruturação do modelo de investimento e de exploração das ferrovias e a expansão e o aumento da capacidade da malha ferroviária são considerados condições para o desenvolvimento das regiões brasileiras no que diz respeito às redes de transporte.','C',3),
(52,'Na escala interurbana, o Brasil apresenta uma rede de transportes integrada, diversa e eficiente, o que resulta em integração regional e competitividade no contexto da economia nacional.','E',3),
(53,'As políticas públicas no Brasil, sobretudo as implementadas a partir da segunda metade do século passado, incentivaram o transporte rodoviário de pessoas e de cargas em detrimento de outros modais de transporte.','C',3),
(54,'As metrópoles brasileiras são arranjos populacionais acima de um milhão de habitantes que exercem influência direta sobre os demais níveis de cidades na rede urbana.','C',3),
(55,'Os arranjos populacionais de Campinas e Ribeirão Preto, no estado de São Paulo, e de Uberlândia, em Minas Gerais, configuram-se como metrópoles em ascensão na rede urbana brasileira e encontram-se no primeiro nível da hierarquia urbana.','E',3),
(56,'Em rodovias de via dupla de zonas rurais em que não houver sinalização regulamentadora, deve-se aplicar a automóveis, camionetas e motocicletas o mesmo limite máximo de velocidade permitido para transitar.','C',4),
(57,'Veículos em movimento em via pública que possuam espelhos retrovisores em ambos os lados poderão usar cortinas nas áreas envidraçadas.','C',4),
(58,'Considere que, em determinada rodovia federal, tenha havido um acidente, sem vítimas, em que um veículo colidira com outro, do que resultara, para os dois veículos, em avaria e em dano patrimonial. Nessa situação hipotética, o causador do acidente deverá preservar o local, a fim de facilitar os trabalhos da polícia e da perícia, sob pena de responder por grave infração administrativa de trânsito.','E',4),
(59,'Para que autoridade ou agente policial possa autorizar a remoção de veículos envolvidos em acidente de trânsito ocorrido em leito de via pública que tenha causado lesão em pessoas e dano aos veículos envolvidos, é necessário que antes tenha sido prestado socorro às vítimas e realizada a perícia no local.','E',4),
(60,'Cidadão que seja penalmente inimputável não pode obter habilitação para conduzir veículo automotor e elétrico.','C',4),
(61,'A fiscalização de trânsito por videomonitoramento independe de sinalização na via e, em caso de infração, a autoridade ou o agente de trânsito responsável pela lavratura de auto de infração deve indicar, no campo observação, informações relativas ao modo de constatação da referida infração.','E',4),
(62,'A emissão de Certificado de Registro e Licenciamento de Veículo em meio digital (CRLV-e), no qual constam o Certificado de Registro de Veículo (CRV) e o Certificado de Licenciamento Anual (CLA), é obrigatória se houver transferência de propriedade, sendo dispensável em caso de mudança de município de residência do proprietário.','E',4),
(63,'Os objetivos da campanha educativa de trânsito do ano de 2021 incluem divulgar, mensalmente, temas com orientações específicas, as quais promovam, por exemplo, reflexões sobre como lesões e sequelas psicológicas e sociais decorrentes de acidentes de trânsito impactam a vida das vítimas e de seus familiares.','C',4),
(64,'Para a medição de velocidade de veículos automotores elétricos, reboques e semirreboques em rodovias, utilizam-se medidores de velocidade do tipo fixo; entre estes, somente o medidor de velocidade do tipo fixo redutor deve obrigatoriamente ser dotado de display.','C',4),
(65,'Como os reboques e os semirreboques são identificados somente por placa de identificação veicular (PIV) traseira, caso seja necessário, veículos equipados com engates para reboques ou com carroceria intercambiável deverão obrigatoriamente usar uma segunda PIV traseira.','C',4),
(66,'Infração de trânsito concomitante é aquela em que o cometimento de uma infração tem como pressuposto o cometimento de outra.','E',4),
(67,'O Plano Nacional de Trânsito é composto por um rol de iniciativas e de ações, sendo um de seus pilares a mobilidade e a engenharia.','X',4),
(68,'A circulação de veículos em via pode ocorrer a título precário, sendo vedado o transporte de passageiro que esteja em pé no veículo ou que tenha menos de dezoito anos de idade no caso de transporte de passageiros em veículos de carga ou misto.','E',4),
(69,'Lanternas especiais de emergência que emitem luz de cor azul são de uso exclusivo de veículos que estejam devidamente identificados e destinados a socorro de incêndio e salvamento, a exemplo dos veículos de polícia, de fiscalização e de operações de trânsito e de ambulâncias, quando da efetiva prestação do serviço de urgência.','X',4),
(70,'É permitido que veículos de passageiros, ônibus, micro-ônibus e caminhões transitem em rodovia com trincas em seus para-brisas, desde que elas estejam dentro do limite previsto em norma específica e não haja fratura de configuração circular.','E',4),
(71,'O equipamento em questão deve apresentar o tempo de movimentação do veículo, bem como suas interrupções.','C',4),
(72,'Em caso de operação de fiscalização do registrador instantâneo e inalterável de velocidade e tempo, o policial rodoviário federal deve identificar-se e assinar o verso do disco ou da fita diagrama, além de mencionar o local, a data e horário em que ocorreu a fiscalização.','C',4),
(73,'É de seis meses o prazo em que as informações relativas às últimas vinte e quatro horas de operação do veículo devem ficar à disposição das autoridades competentes em caso de acidente.','E',4),
(74,'A largura máxima autorizada para a circulação de veículos em via pública, com ou sem carga, é de 2,50 metros.','E',5),
(75,'Cumpridos os requisitos legais, para a combinação de veículos de carga com mais de duas unidades, incluída a unidade tratora, o peso bruto total deve ser de até 60 toneladas.','E',5),
(76,'O comprimento máximo permitido para a circulação de veículos não articulados em vias públicas é de 14,00 metros.','X',5),
(77,'A fiscalização do tempo de direção e do intervalo de descanso pode ocorrer por meio da verificação do diário de bordo, da papeleta ou da ficha de trabalho externo, fornecidos pelo empregador.','C',5),
(78,'Na condução de veículo de carga com peso bruto total superior a 4.536 kg, é permitido ao motorista profissional dirigir por até seis horas e meia ininterruptas.','E',5),
(79,'A responsabilidade pela guarda, pela proteção e pela precisão das informações contidas no equipamento registrador instantâneo inalterável de velocidade e de tempo é do proprietário do veículo.','E',5),
(80,'O slogan da campanha educativa de trânsito de 2021, a qual deve ser veiculada, obrigatoriamente, nos meios de comunicação social, em toda peça publicitária de produtos automobilísticos, é: "No trânsito, sua responsabilidade salva vidas".','C',5),
(81,'Excetuados os produtos perigosos e a critério do policial rodoviário federal, desde que observadas as condições de segurança, produtos perecíveis e cargas vivas podem ser dispensados do remanejamento ou transbordo em caso de excesso de peso veicular.','E',5),
(82,'Em rodovias federais, na fiscalização de peso dos veículos por balança rodoviária, é admitida a tolerância de 12,5% sobre os limites de peso regulamentares por eixo de veículos transmitidos à superfície das vias públicas.','E',5),
(83,'Para a amarração de carga, é proibida a utilização de cordas, sendo permitido o seu uso exclusivamente para a fixação da lona de cobertura, quando necessário.','X',5),
(84,'Quando não há pontos de amarração adequados ou em número suficiente, pode-se realizar a fixação dos dispositivos de amarração no próprio chassi do veículo.','C',5),
(85,'Para a amarração da carga, devem ser utilizadas cintas têxteis, correntes ou cabos de aço, com resistência total à ruptura por tração de, no mínimo, 1,50 vez o peso da carga.','E',5),
(86,'A impetração de mandado de segurança configura controle judicial de mérito administrativo.','E',6),
(87,'Órgão público é ente descentralizado da administração indireta que possui personalidade jurídica de direito público.','E',6),
(88,'Essa situação caracteriza contratação direta por dispensa de licitação.','E',6),
(89,'A aplicação da multa em questão decorre do poder administrativo disciplinar.','X',6),
(90,'O ajuizamento da ação judicial para conter eventuais abusos praticados pela administração pública caracteriza a aplicação do princípio da sindicabilidade.','C',6),
(91,'A promoção do policial rodoviário federal para a segunda classe depende de participação em cursos de capacitação cujo conteúdo seja compatível com as atribuições do cargo e que tenha duração de, no mínimo, 150 horas.','E',6),
(92,'As atribuições do policial rodoviário federal de terceira classe, cuja jornada de trabalho é de quarenta horas semanais, incluem realizar patrulhamento e policiamento ostensivo.','C',6),
(93,'A manifestação pública em defesa da abolição de crime, por ser considerada incitação à prática de fato criminoso, não está protegida pela liberdade de reunião.','E',6),
(94,'Autoriza-se o confisco de bem utilizado para o tráfico de drogas nas situações em que se constatar que houve habitualidade do uso do bem para a prática do referido crime.','C',6),
(95,'As hipóteses de perda da nacionalidade brasileira previstas na Constituição Federal de 1988 têm natureza taxativa, de modo que nem mesmo convenções ou tratados internacionais podem ampliá-las.','C',6),
(96,'A Constituição Federal de 1988 não garante o direito à escusa de consciência sobre o dever de votar para os maiores de 18 anos de idade e para os menores de 70 anos de idade.','E',6),
(97,'De acordo com o Supremo Tribunal Federal, não é cabível habeas data para a obtenção de informações a respeito da identidade de responsáveis por agressões e denúncias feitas contra o impetrante.','X',6),
(98,'Durante a vigência do estado de sítio, as imunidades parlamentares poderão ser suspensas pelo voto de dois terços dos membros da respectiva casa legislativa.','X',6),
(99,'Em caso de decretação do estado de sítio em razão de comoção interna autorizada pelo Congresso Nacional, admite-se a suspensão de todas as garantias constitucionais.','E',6),
(100,'A remarcação de novo número no chassi e a falsificação do certificado de registro do veículo caracterizam crime único de falsificação de documento público.','E',7),
(101,'A remarcação do chassi com o mesmo número original do veículo caracteriza crime contra a fé pública e infração administrativa de trânsito.','C',7),
(102,'Ao oferecer dinheiro para ser irregularmente liberado da blitz, o condutor praticou o crime de corrupção ativa.','E',7),
(103,'Nessa situação, se o policial não aceitar o dinheiro oferecido, a conduta da pessoa deve ser punida na modalidade tentada.','C',7),
(104,'A adulteração grosseira do chassi do veículo não caracteriza crime impossível.','E',7),
(105,'A busca e a apreensão no veículo foram ilícitas, já que o policial as realizou sem autorização judicial.','C',7),
(106,'A situação caracteriza flagrante próprio e, em até vinte e quatro horas após a realização da prisão, deverá ser entregue a nota de culpa ao preso.','E',7),
(107,'A identificação criminal do condutor não poderá ser feita, uma vez que ele foi identificado civilmente pela CNH.','E',7),
(108,'O policial poderá ser arrolado como testemunha, caso em que seu depoimento terá valor probatório superior ao do interrogatório do condutor.','E',7),
(109,'A prisão do condutor é uma espécie de prisão provisória, dispensa a expedição de mandado e o policial deve exigir o recibo de entrega do preso.','C',7),
(110,'Caso três pessoas associadas, com divisão de tarefas, subtraiam substância explosiva, estará configurado crime hediondo.','E',7),
(111,'Qualquer agente público, ainda que não seja servidor e não perceba remuneração, pode ser sujeito ativo do crime de abuso de autoridade.','C',7),
(112,'Mesmo em caso de apresentação do documento de identificação civil, é possível a identificação criminal em caso de constar de registros policiais o uso de outros nomes ou diferentes qualificações.','C',7),
(113,'Entre as atividades de prevenção do uso indevido de drogas, está o fortalecimento da autonomia e da responsabilidade individual em relação ao uso indevido dessas substâncias ilícitas.','C',7),
(114,'Conduzir arma de fogo, no exercício de atividade comercial, sem autorização, configura comércio ilegal de arma de fogo.','C',7),
(115,'Praticam o crime de tortura policiais rodoviários federais que, dentro de um posto policial, submetem o autor de crime a sofrimento físico, independentemente de sua intensidade.','E',7),
(116,'A mera intuição de que esteja havendo tráfico de drogas em uma casa não configura justa causa para autorizar o ingresso sem mandado judicial ou sem o consentimento do morador, exceto em caso de flagrante delito.','C',7),
(117,'O aviso prévio é uma condicionante ao exercício do direito de reunião previsto na CF: a inexistência de notificação às autoridades competentes torna ilegal a manifestação coletiva.','E',7),
(118,'A alteração do gênero nos assentamentos de registro civil independe da realização de procedimento cirúrgico, denominado transgenitalização, ou da comprovação da realização de tratamentos hormonais ou patologizantes, por parte da pessoa interessada.','C',7),
(119,'A Declaração Universal dos Direitos Humanos, um dos primeiros instrumentos normativos gerais de direitos humanos adotados por uma organização internacional, destacou-se pelo fato de comportar a ideia de dignidade da pessoa humana como ponto de convergência da ética universal e do fundamento valorativo do sistema protetivo global dos direitos humanos.','C',7),
(120,'A Convenção Internacional dos Direitos das Pessoas com Deficiência possui status supraconstitucional no ordenamento pátrio, sendo um exemplo de instrumento normativo internacional de caráter inclusivo adotado pelo Brasil para promover a acessibilidade e a autodeterminação de pessoas com deficiência.','E',7)
)
insert into public.official_exam_questions
  (question_source_id,answer_key_source_id,syllabus_topic_id,contest_name,exam_year,career_name,exam_board,
   item_number,subject,question_text,raw_extraction,official_answer,source_page,content_status,
   legal_review_required,context_review_required,legal_basis,review_note)
select
  src.id, src.id, t.id, 'Polícia Rodoviária Federal', 2021, 'Policial Rodoviário Federal', 'CEBRASPE',
  imported.item_number,
  coalesce(tm.discipline,'Geral'),
  imported.statement, imported.statement, imported.official_answer, imported.source_page,
  case when imported.official_answer='X' then 'annulled' else 'under_review' end,
  (tm.discipline in ('Direito de Trânsito','Direito Administrativo','Direito Constitucional','Direito Penal e Processual Penal','Direitos Humanos')),
  true,
  '[]'::jsonb,
  case when imported.official_answer='X'
    then 'Item anulado no gabarito oficial definitivo; não é exibido aos estudantes.'
    else 'Transcrição verbatim do caderno de provas fornecido pelo candidato; gabarito conferido nos documentos oficiais definitivos (578_PRF_001_01 e 578_PRF_ING_01). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.'
  end
from imported
cross join src
cross join edition
join topic_map tm on imported.item_number between tm.item_from and tm.item_to
join public.syllabus_topics t on t.edition_id=edition.id and t.discipline=coalesce(tm.discipline,'Geral')
on conflict (contest_name,exam_year,item_number) do nothing;
