-- Explicações por artigo — Código de Processo Penal. Texto-base: dispositivos oficiais já cadastrados em legal_course_units.

-- Entram como 'under_review': só administradores veem até a publicação (update ... set status = 'published').

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O Código de Processo Penal vale em todo o território brasileiro. Há ressalvas: tratados, convenções e regras de direito internacional; prerrogativas constitucionais do Presidente da República, dos ministros de Estado e dos ministros do Supremo Tribunal Federal nos crimes de responsabilidade; processos da Justiça Militar; processos do tribunal especial; e crimes de imprensa. Aos dois últimos, o Código se aplica quando as leis especiais não dispuserem de modo diverso.', '["Regra: o CPP rege o processo penal em todo o território brasileiro.","Ressalvas: tratados e regras internacionais; prerrogativas constitucionais; Justiça Militar; tribunal especial; crimes de imprensa.","Parágrafo único: aplica-se aos processos do tribunal especial e de imprensa, se a lei especial não dispuser diferente."]'::jsonb, '["O texto remete a normas de constituição anterior: é leitura histórica.","Há referência à ADPF nº 130 no texto compilado (crimes de imprensa)."]'::jsonb, 'Um processo da competência da Justiça Militar segue a legislação militar, e não o CPP.', '["Assertiva que aplica o CPP a processos da Justiça Militar erra: ela é ressalvada."]'::jsonb, '[]'::jsonb, '["Art. 2º","Art. 3º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-1'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A lei processual penal aplica-se desde logo (aplicação imediata), sem prejuízo da validade dos atos realizados sob a vigência da lei anterior (princípio do tempus regit actum).', '["Aplicação imediata da lei processual penal.","Os atos já praticados sob a lei anterior continuam válidos."]'::jsonb, '["Normas processuais penais materiais (mistas) seguem a lei penal: retroatividade benéfica."]'::jsonb, 'Nova regra de intimação vale para os atos futuros; as intimações já feitas continuam válidas.', '["Assertiva que invalida os atos realizados sob a lei anterior, por força da nova lei processual, erra: eles permanecem válidos."]'::jsonb, '[{"termo":"Tempus regit actum","significado":"O ato se rege pela lei vigente quando praticado."}]'::jsonb, '["Art. 1º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-2'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A lei processual penal admite interpretação extensiva e aplicação analógica, bem como o suplemento dos princípios gerais de direito.', '["Interpretação extensiva é admitida.","Aplicação analógica é admitida.","Princípios gerais de direito suplementam a lei."]'::jsonb, '["Diferente do direito penal material, a analogia em prejuízo do réu é debatida: a doutrina distingue normas processuais das de caráter material."]'::jsonb, 'Aplicar por analogia regra processual civil a lacuna do CPP.', '["Assertiva que veda interpretação extensiva e analogia na lei processual penal erra: ambas são admitidas."]'::jsonb, '[{"termo":"Interpretação extensiva","significado":"Amplia o alcance literal da norma para o que o legislador quis dizer."}]'::jsonb, '["Art. 1º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O processo penal terá estrutura acusatória, vedadas a iniciativa do juiz na fase de investigação e a substituição da atuação probatória do órgão de acusação. O texto compilado indica discussão de sua eficácia no Supremo Tribunal Federal (ADIs).', '["Estrutura acusatória do processo penal.","Veda a iniciativa do juiz na fase de investigação.","Veda a substituição da atuação probatória do órgão de acusação."]'::jsonb, '["Dispositivo incluído pela Lei nº 13.964, de 2019 (Pacote Anticrime).","Eficácia discutida em ADIs: confira a situação atual."]'::jsonb, 'O juiz não pode determinar, por conta própria, a produção de prova em substituição ao Ministério Público.', '["Assertiva que permite ao juiz a iniciativa na fase de investigação, segundo o art. 3º-A, erra."]'::jsonb, '[{"termo":"Sistema acusatório","significado":"Separação entre quem acusa, quem defende e quem julga."}]'::jsonb, '["Art. 3º-B","Art. 156"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3-a'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O juiz das garantias é responsável pelo controle da legalidade da investigação criminal e pela salvaguarda dos direitos individuais cuja franquia tenha sido reservada à autorização prévia do Poder Judiciário. Entre outras funções, recebe a comunicação imediata da prisão e o auto de prisão em flagrante, zela pelos direitos do preso, decide sobre prisão provisória e medidas cautelares, e decide sobre a homologação de acordo de não persecução penal ou de colaboração premiada formalizados durante a investigação. O preso será encaminhado à audiência de custódia no prazo de 24 horas. Se o investigado estiver preso, o juiz das garantias pode prorrogar o inquérito, uma única vez, por até 15 dias, após o que a prisão será relaxada.', '["Controla a legalidade da investigação e protege direitos individuais sob reserva de jurisdição.","Recebe a comunicação da prisão e o auto de flagrante.","Decide sobre prisão provisória e outras cautelares.","Homologa ANPP e colaboração premiada na fase de investigação.","§1º: audiência de custódia em 24 horas, por videoconferência.","§2º: prorrogação única do inquérito do preso, por até 15 dias; depois, relaxamento."]'::jsonb, '["Eficácia do instituto discutida em ADIs: confira a situação atual.","A redação do §1º veio da Lei nº 15.358, de 2026."]'::jsonb, 'O juiz das garantias decide sobre pedido de interceptação durante o inquérito.', '["Assertiva que atribui ao juiz das garantias o julgamento do mérito da ação penal erra: sua função é a legalidade da investigação."]'::jsonb, '[]'::jsonb, '["Art. 3º-C","Art. 310"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3-b'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A competência do juiz das garantias abrange todas as infrações penais, exceto as de menor potencial ofensivo, e cessa com o recebimento da denúncia ou queixa. Recebida a denúncia, as questões pendentes serão decididas pelo juiz da instrução e julgamento. As decisões do juiz das garantias não vinculam o juiz da instrução e julgamento, que, após o recebimento da denúncia ou queixa, deverá reexaminar a necessidade das medidas cautelares em curso, no prazo máximo de 10 dias. Os autos das matérias do juiz das garantias ficam acautelados na secretaria desse juízo, à disposição do Ministério Público e da defesa, e não são apensados ao processo, ressalvados os documentos relativos às provas irrepetíveis, medidas de obtenção de provas ou de antecipação de provas. Fica assegurado às partes o amplo acesso aos autos acautelados.', '["Abrange todas as infrações, exceto as de menor potencial ofensivo.","Cessa com o recebimento da denúncia ou queixa.","Juiz da instrução reexamina as cautelares em até 10 dias.","Autos do juízo das garantias ficam na secretaria, com acesso amplo às partes.","Exceção ao não apensamento: provas irrepetíveis, medidas de obtenção e antecipação de provas."]'::jsonb, '["Eficácia discutida em ADIs.","Prazo de 10 dias para reexame das cautelares."]'::jsonb, 'Após o recebimento da denúncia, outro juiz assume o processo e reexamina a prisão preventiva em até 10 dias.', '["Assertiva que estende a competência do juiz das garantias às infrações de menor potencial ofensivo erra: elas são excluídas."]'::jsonb, '[]'::jsonb, '["Art. 3º-B","Art. 399"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3-c'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O juiz que, na fase de investigação, praticar qualquer ato incluído nas competências dos arts. 4º e 5º do Código ficará impedido de funcionar no processo. Nas comarcas em que funcionar apenas um juiz, os tribunais criarão um sistema de rodízio de magistrados.', '["Juiz que atua na investigação fica impedido de funcionar no processo.","Comarca com um só juiz: rodízio de magistrados criado pelos tribunais."]'::jsonb, '["Eficácia discutida em ADIs."]'::jsonb, 'O juiz que decretou medida cautelar na investigação não julga o processo.', '["Assertiva que permite ao juiz da investigação julgar o processo, segundo o art. 3º-D, erra."]'::jsonb, '[]'::jsonb, '["Art. 3º-B"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3-d'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O juiz das garantias será designado conforme as normas de organização judiciária da União, dos Estados e do Distrito Federal, observando critérios objetivos a serem periodicamente divulgados pelo respectivo tribunal.', '["Designação conforme a organização judiciária.","Critérios objetivos, periodicamente divulgados pelo tribunal."]'::jsonb, '["Eficácia discutida em ADIs."]'::jsonb, 'O tribunal divulga os critérios objetivos para designar o juiz das garantias.', '["Assertiva que dispensa critérios objetivos na designação do juiz das garantias erra."]'::jsonb, '[]'::jsonb, '["Art. 3º-B"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3-e'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O juiz das garantias deve assegurar o cumprimento das regras para o tratamento dos presos, impedindo o acordo ou ajuste de qualquer autoridade com órgãos da imprensa para explorar a imagem da pessoa submetida à prisão, sob pena de responsabilidade civil, administrativa e penal. Por regulamento, as autoridades disciplinarão, em 180 dias, o modo padronizado de transmitir à imprensa as informações sobre a prisão e a identidade do preso.', '["Garantir as regras de tratamento dos presos.","Impedir acordo com a imprensa para explorar a imagem do preso.","Responsabilidade civil, administrativa e penal.","Parágrafo único: regulamento em 180 dias para padronizar as informações à imprensa."]'::jsonb, '["Eficácia discutida em ADIs."]'::jsonb, 'Autoridade combina com a imprensa a exposição da imagem do preso: pode ser responsabilizada.', '["Assertiva que permite a exploração da imagem do preso mediante acordo com a imprensa erra."]'::jsonb, '[]'::jsonb, '["Art. 3º-B"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-3-f'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A polícia judiciária será exercida pelas autoridades policiais no território de suas respectivas circunscrições e terá por fim a apuração das infrações penais e da sua autoria. A competência não exclui a de autoridades administrativas a quem a lei atribua a mesma função.', '["Polícia judiciária exercida por autoridades policiais nas suas circunscrições.","Finalidade: apurar infrações penais e autoria.","Parágrafo único: não exclui outras autoridades administrativas com a mesma função."]'::jsonb, '["Exemplo clássico: Comissões Parlamentares de Inquérito têm poderes de investigação próprios."]'::jsonb, 'O delegado de polícia apura o crime na sua circunscrição.', '["Assertiva que torna a polícia judiciária exclusiva das autoridades policiais erra: o parágrafo único admite outras autoridades."]'::jsonb, '[{"termo":"Polícia judiciária","significado":"Apura infrações penais e autoria, auxiliando o Judiciário e o Ministério Público."}]'::jsonb, '["Art. 5º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-4'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Nos crimes de ação pública, o inquérito policial é iniciado de ofício ou mediante requisição da autoridade judiciária ou do Ministério Público, ou a requerimento do ofendido ou de quem tiver qualidade para representá-lo. O requerimento conterá, sempre que possível, a narração do fato com as circunstâncias; a individualização do indiciado e as razões de convicção; e a nomeação das testemunhas. Do despacho que indeferir o requerimento cabe recurso para o chefe de Polícia. Qualquer pessoa do povo pode comunicar a infração à autoridade (delatio criminis). Nos crimes de ação pública condicionada à representação, o inquérito não pode ser iniciado sem ela. Nos crimes de ação privada, a autoridade só procede a inquérito a requerimento de quem tenha qualidade para intentar a ação.', '["Ação pública: inquérito de ofício, por requisição ou a requerimento do ofendido.","§1º: conteúdo do requerimento (fato, indiciado, testemunhas).","§2º: recurso ao chefe de Polícia contra o indeferimento.","§3º: qualquer pessoa pode comunicar o fato.","§4º: representação é condição para iniciar o inquérito.","§5º: ação privada: só a requerimento do legitimado."]'::jsonb, '["Requisição do Ministério Público ou do juiz não pode ser recusada sem fundamento.","Sem representação, não há inquérito na ação pública condicionada."]'::jsonb, 'Vítima de crime de ação pública condicionada precisa representar para que o inquérito se instaure.', '["Assertiva que permite instaurar inquérito em ação pública condicionada sem representação erra: o §4º veda."]'::jsonb, '[{"termo":"Delatio criminis","significado":"Comunicação de crime à autoridade."}]'::jsonb, '["Art. 24","Art. 39"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-5'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Logo que tiver conhecimento da prática da infração penal, a autoridade policial deve: dirigir-se ao local e preservá-lo até a chegada dos peritos; apreender os objetos relacionados ao fato, após liberados pelos peritos; colher todas as provas; ouvir o ofendido; ouvir o indiciado; proceder a reconhecimento de pessoas e coisas e a acareações; determinar exame de corpo de delito e outras perícias; ordenar a identificação datiloscópica e juntar a folha de antecedentes; averiguar a vida pregressa do indiciado; e colher informações sobre a existência de filhos, idades, eventual deficiência e o responsável pelos cuidados indicado pela pessoa presa.', '["Preservar o local do crime até a chegada dos peritos.","Apreender objetos após liberados pelos peritos.","Colher provas, ouvir ofendido e indiciado.","Reconhecimento de pessoas e coisas, acareações.","Exame de corpo de delito e perícias.","Identificação datiloscópica e folha de antecedentes.","Vida pregressa do indiciado.","Informações sobre filhos da pessoa presa."]'::jsonb, '["O termo do interrogatório do indiciado é assinado por duas testemunhas que ouviram a leitura.","O inciso X (filhos) veio da Lei nº 13.257, de 2016."]'::jsonb, 'Ao chegar ao local do crime, o delegado providencia que nada seja alterado até a perícia.', '["Assertiva que autoriza a apreensão de objetos antes de liberados pelos peritos erra."]'::jsonb, '[]'::jsonb, '["Art. 5º","Art. 158"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-6'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Para verificar a possibilidade de a infração ter sido praticada de determinado modo, a autoridade policial pode proceder à reprodução simulada dos fatos (reconstituição), desde que esta não contrarie a moralidade ou a ordem pública.', '["Reprodução simulada dos fatos (reconstituição).","Limite: não contrariar a moralidade ou a ordem pública."]'::jsonb, '["O investigado não pode ser obrigado a participar (direito de não produzir prova contra si)."]'::jsonb, 'Reconstituição do crime no local, com a participação voluntária do investigado.', '["Assertiva que obriga o investigado a participar da reconstituição erra."]'::jsonb, '[]'::jsonb, '["Art. 6º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-7'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Havendo prisão em flagrante, será observado o disposto no Capítulo II do Título IX deste Livro.', '["Prisão em flagrante segue o Capítulo II do Título IX do Livro I."]'::jsonb, '["Remissão às regras do flagrante (arts. 301 e seguintes)."]'::jsonb, 'Preso em flagrante, o indivíduo é conduzido à autoridade e o auto é lavrado.', '["Assertiva que cria rito próprio no art. 8º para o flagrante erra: ele remete ao Título da prisão."]'::jsonb, '[]'::jsonb, '["Art. 301"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-8'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Todas as peças do inquérito policial serão, num só processado, reduzidas a escrito ou datilografadas e, neste caso, rubricadas pela autoridade.', '["Peças do inquérito reunidas em um só processado.","Reduzidas a escrito ou datilografadas.","Se datilografadas, rubricadas pela autoridade."]'::jsonb, '["Regra de forma do inquérito; na prática, usa-se o meio digital."]'::jsonb, 'Os termos e depoimentos do inquérito são reunidos e rubricados pelo delegado.', '["Assertiva que dispensa a rubrica da autoridade nas peças datilografadas erra."]'::jsonb, '[]'::jsonb, '["Art. 10"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-9'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O inquérito deverá terminar no prazo de 10 dias, se o indiciado tiver sido preso em flagrante ou estiver preso preventivamente (contado, nesta hipótese, do dia em que se executar a ordem de prisão), ou no prazo de 30 dias, quando estiver solto, mediante fiança ou sem ela. A autoridade fará minucioso relatório do que apurou e enviará os autos ao juiz competente, podendo indicar testemunhas não inquiridas. Quando o fato for de difícil elucidação e o indiciado estiver solto, a autoridade pode requerer ao juiz a devolução dos autos para ulteriores diligências no prazo marcado pelo juiz.', '["Preso: 10 dias.","Solto: 30 dias, com ou sem fiança.","§1º: relatório minucioso e remessa ao juiz competente.","§2º: pode indicar testemunhas não inquiridas.","§3º: fato de difícil elucidação, indiciado solto: devolução dos autos para novas diligências."]'::jsonb, '["Em preventiva, o prazo conta do cumprimento da ordem de prisão.","Em leis especiais, os prazos podem ser diferentes."]'::jsonb, 'Indiciado preso em flagrante: inquérito conclui em 10 dias.', '["Assertiva que fixa em 30 dias o prazo do inquérito com indiciado preso erra: são 10 dias."]'::jsonb, '[]'::jsonb, '["Art. 3º-B"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-10'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Os instrumentos do crime, bem como os objetos que interessarem à prova, acompanharão os autos do inquérito.', '["Instrumentos do crime acompanham os autos.","Objetos de interesse para a prova também."]'::jsonb, '["Relaciona-se à cadeia de custódia da prova."]'::jsonb, 'A arma usada no crime é encaminhada junto com os autos do inquérito.', '["Assertiva que determina o descarte dos instrumentos do crime após o inquérito erra: eles acompanham os autos."]'::jsonb, '[]'::jsonb, '["Art. 6º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-11'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O inquérito policial acompanhará a denúncia ou queixa, sempre que servir de base a uma ou outra.', '["O inquérito acompanha a denúncia ou queixa quando serve de base a elas."]'::jsonb, '["O inquérito é peça informativa, dispensável para o oferecimento da denúncia se houver elementos suficientes."]'::jsonb, 'A denúncia é oferecida com o inquérito anexo.', '["Assertiva que torna o inquérito indispensável ao oferecimento da denúncia erra."]'::jsonb, '[]'::jsonb, '["Art. 39"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-12'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Incumbe ainda à autoridade policial: fornecer às autoridades judiciárias as informações necessárias à instrução e ao julgamento; realizar as diligências requisitadas pelo juiz ou pelo Ministério Público; cumprir os mandados de prisão expedidos pelas autoridades judiciárias; e representar acerca da prisão preventiva.', '["Fornecer informações ao Judiciário.","Realizar diligências requisitadas pelo juiz ou Ministério Público.","Cumprir mandados de prisão.","Representar pela prisão preventiva."]'::jsonb, '["A autoridade policial REPRESENTA pela preventiva; quem decreta é o juiz."]'::jsonb, 'Delegado representa ao juiz pela prisão preventiva do investigado.', '["Assertiva que atribui à autoridade policial o poder de decretar a prisão preventiva erra: ela representa."]'::jsonb, '[]'::jsonb, '["Art. 311"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-13'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Nos crimes de sequestro e cárcere privado, redução à condição análoga à de escravo, tráfico de pessoas, extorsão com restrição da liberdade da vítima, extorsão mediante sequestro e no art. 239 do Estatuto da Criança e do Adolescente, o membro do Ministério Público ou o delegado de polícia pode requisitar, de órgãos do poder público ou de empresas privadas, dados e informações cadastrais da vítima ou de suspeitos. A requisição será atendida no prazo de 24 horas e conterá o nome da autoridade requisitante, o número do inquérito policial e a identificação da unidade de polícia judiciária responsável.', '["Requisição de dados cadastrais da vítima ou de suspeitos por MP ou delegado.","Crimes: arts. 148, 149, 149-A, 158 §3º, 159 do CP e art. 239 do ECA.","Prazo de atendimento: 24 horas.","A requisição indica a autoridade, o número do inquérito e a unidade responsável."]'::jsonb, '["Dados cadastrais; o conteúdo de comunicação depende de ordem judicial."]'::jsonb, 'Delegado requisita dados cadastrais de suspeito de extorsão mediante sequestro.', '["Assertiva que fixa o prazo de atendimento em 72 horas erra: são 24 horas."]'::jsonb, '[]'::jsonb, '["Art. 13-B"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-13-a'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Se necessário à prevenção e à repressão dos crimes relacionados ao tráfico de pessoas, o membro do Ministério Público ou o delegado de polícia podem requisitar, mediante autorização judicial, às empresas de telecomunicações e/ou telemática que disponibilizem imediatamente os meios técnicos adequados, como sinais e informações, que permitam localizar a vítima ou os suspeitos do delito em curso. Sinal significa posicionamento da estação de cobertura, setorização e intensidade de radiofrequência. O sinal não permite acesso ao conteúdo da comunicação, será fornecido por período não superior a 30 dias, renovável uma única vez por igual período; períodos superiores exigem ordem judicial. O inquérito deverá ser instaurado em até 72 horas do registro da ocorrência. Se não houver manifestação judicial em 12 horas, a autoridade competente requisitará os meios, com imediata comunicação ao juiz.', '["Requisição às operadoras para localizar vítima ou suspeitos, mediante autorização judicial.","Sinal: estação de cobertura, setorização e intensidade de radiofrequência.","Sem acesso ao conteúdo da comunicação.","Fornecimento por até 30 dias, renovável por igual período, uma única vez.","Inquérito instaurado em até 72 horas.","Sem manifestação judicial em 12 horas, a autoridade requisita, comunicando ao juiz."]'::jsonb, '["Prazos: 30 dias (renovável uma vez), 72 horas para o inquérito, 12 horas para a manifestação judicial."]'::jsonb, 'Delegado, com autorização judicial, requisita o sinal do celular de vítima de tráfico de pessoas.', '["Assertiva que permite o acesso ao conteúdo das comunicações pelo mero sinal erra."]'::jsonb, '[]'::jsonb, '["Art. 13-A"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-13-b'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O ofendido, ou seu representante legal, e o indiciado podem requerer qualquer diligência, que será realizada, ou não, a juízo da autoridade.', '["Ofendido, representante legal e indiciado podem requerer diligências.","A autoridade decide se realiza ou não."]'::jsonb, '["Exceção: o exame de corpo de delito, quando a infração deixa vestígios, é obrigatório (art. 158)."]'::jsonb, 'A vítima requer a oitiva de uma testemunha, e a autoridade decide se o faz.', '["Assertiva que obriga a autoridade a realizar qualquer diligência requerida pelo indiciado erra."]'::jsonb, '[]'::jsonb, '["Art. 158"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-14'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Quando servidores das instituições do art. 144 da Constituição figurarem como investigados em inquéritos policiais, inquéritos policiais militares e procedimentos extrajudiciais sobre fatos relacionados ao uso da força letal praticados no exercício profissional, de forma consumada ou tentada, incluindo as situações do art. 23 do Código Penal, o indiciado pode constituir defensor. O investigado será citado da instauração e poderá constituir defensor em até 48 horas. Esgotado o prazo sem nomeação, a autoridade intimará a instituição a que o investigado estava vinculado, para que, em 48 horas, indique defensor. Havendo necessidade de defesa técnica, a escolha recairá preferencialmente na Defensoria Pública; onde não houver, a União ou a Unidade da Federação disponibilizará profissional. Na ausência da Defensoria, os custos correm por conta do orçamento da instituição a que o investigado estava vinculado. Aplica-se aos militares do art. 142 da Constituição em missões de Garantia da Lei e da Ordem.', '["Aplica-se a servidores do art. 144 da Constituição investigados por uso da força letal.","Citação do investigado e prazo de 48 horas para constituir defensor.","Sem defensor, a instituição indica um em 48 horas.","Preferência pela Defensoria Pública.","Custos da defesa, na ausência da Defensoria, correm por conta da instituição.","Estende-se a militares em missões de Garantia da Lei e da Ordem."]'::jsonb, '["Prazos de 48 horas para constituir e para indicar defensor."]'::jsonb, 'Policial investigado por morte em serviço é citado e tem 48 horas para constituir defensor.', '["Assertiva que fixa em 24 horas o prazo para o investigado constituir defensor erra: são 48 horas."]'::jsonb, '[]'::jsonb, '["Art. 23 do Código Penal"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-14-a'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Se o indiciado for menor, ser-lhe-á nomeado curador pela autoridade policial.', '["Indiciado menor: nomeação de curador pela autoridade policial."]'::jsonb, '["Dispositivo anterior ao Código Civil de 2002: a menoridade processual hoje é discutida em relação aos menores de 18 anos, inimputáveis."]'::jsonb, 'Indiciado menor de 21 anos teria curador nomeado na vigência original do dispositivo.', '["Assertiva que dispensa curador para o indiciado menor, segundo o art. 15, erra."]'::jsonb, '[]'::jsonb, '["Art. 5º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-15'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'O Ministério Público não pode requerer a devolução do inquérito à autoridade policial, senão para novas diligências imprescindíveis ao oferecimento da denúncia.', '["Devolução do inquérito à polícia só para diligências imprescindíveis ao oferecimento da denúncia."]'::jsonb, '["Evita a devolução meramente protelatória."]'::jsonb, 'MP devolve o inquérito para a oitiva de uma testemunha essencial.', '["Assertiva que permite a devolução do inquérito por qualquer motivo erra: só diligências imprescindíveis."]'::jsonb, '[]'::jsonb, '["Art. 10"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-16'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A autoridade policial não pode mandar arquivar autos de inquérito.', '["Vedado à autoridade policial arquivar inquérito."]'::jsonb, '["O arquivamento é ato do Ministério Público (art. 28)."]'::jsonb, 'Delegado conclui o inquérito e o remete ao juízo; não pode arquivá-lo.', '["Assertiva que permite ao delegado arquivar o inquérito por falta de provas erra."]'::jsonb, '[]'::jsonb, '["Art. 28"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-17'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Depois de ordenado o arquivamento do inquérito pela autoridade judiciária, por falta de base para a denúncia, a autoridade policial poderá proceder a novas pesquisas, se de outras provas tiver notícia.', '["Arquivamento por falta de base para a denúncia.","A polícia pode fazer novas pesquisas se tiver notícia de outras provas."]'::jsonb, '["Súmula 524 do STF: arquivado por falta de provas, só se instaura ação com novas provas."]'::jsonb, 'Arquivado o inquérito, surge nova testemunha e a polícia retoma as investigações.', '["Assertiva que veda qualquer nova investigação após o arquivamento por falta de base erra."]'::jsonb, '[]'::jsonb, '["Art. 28"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-18'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Nos crimes em que não couber ação pública, os autos do inquérito serão remetidos ao juízo competente, onde aguardarão a iniciativa do ofendido ou de seu representante legal, ou serão entregues ao requerente, se o pedir, mediante traslado.', '["Ação privada: autos remetidos ao juízo, onde aguardam a iniciativa do ofendido.","Ou entregues ao requerente, mediante traslado."]'::jsonb, '["Vale para crimes de ação privada."]'::jsonb, 'Inquérito de crime de ação privada fica no juízo à espera da queixa.', '["Assertiva que manda arquivar de ofício o inquérito de ação privada erra: os autos aguardam o ofendido."]'::jsonb, '[]'::jsonb, '["Art. 30"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-19'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A autoridade assegurará no inquérito o sigilo necessário à elucidação do fato ou exigido pelo interesse da sociedade. Nos atestados de antecedentes solicitados, a autoridade policial não pode mencionar anotações referentes à instauração de inquérito contra os requerentes.', '["Sigilo do inquérito, quando necessário à elucidação ou ao interesse da sociedade.","Atestados de antecedentes não mencionam a instauração de inquérito."]'::jsonb, '["O sigilo não alcança o advogado (Súmula Vinculante 14), quanto às provas já documentadas."]'::jsonb, 'Atestado de antecedentes não pode informar que há inquérito em curso contra o requerente.', '["Assertiva que oponibiliza o sigilo do inquérito ao advogado em relação a provas já documentadas erra."]'::jsonb, '[]'::jsonb, '["Art. 7º do Estatuto da Advocacia"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-20'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A incomunicabilidade do indiciado depende de despacho nos autos e somente será permitida quando o interesse da sociedade ou a conveniência da investigação o exigir. A incomunicabilidade, que não excederá três dias, será decretada por despacho fundamentado do juiz, a requerimento da autoridade policial ou do Ministério Público, respeitado o Estatuto da Ordem dos Advogados.', '["Incomunicabilidade depende de despacho nos autos.","Prazo máximo de três dias.","Decretada por despacho fundamentado do juiz.","Respeita a prerrogativa do advogado."]'::jsonb, '["Entende-se majoritariamente que o dispositivo não foi recepcionado pela Constituição vigente."]'::jsonb, 'Dispositivo hoje tem pouca aplicação prática.', '["Assertiva que permite incomunicabilidade por prazo indeterminado erra: o texto fixa limite de três dias."]'::jsonb, '[]'::jsonb, '["Art. 5º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-21'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'No Distrito Federal e nas comarcas com mais de uma circunscrição policial, a autoridade com exercício em uma delas pode, nos inquéritos que presidir, ordenar diligências em circunscrição de outra, independentemente de precatórias ou requisições, e providenciará, até que compareça a autoridade competente, sobre qualquer fato que ocorra em sua presença noutra circunscrição.', '["Diligências em outra circunscrição da mesma comarca, sem precatória.","Providências urgentes em outra circunscrição até a chegada da autoridade competente."]'::jsonb, '["Aplica-se ao Distrito Federal e às comarcas com mais de uma circunscrição policial."]'::jsonb, 'Delegado de uma delegacia da comarca realiza diligência na área de outra, sem precisar de precatória.', '["Assertiva que exige precatória para diligências em circunscrições da mesma comarca erra."]'::jsonb, '[]'::jsonb, '["Art. 4º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-22'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Ao remeter os autos do inquérito ao juiz competente, a autoridade policial oficiará ao Instituto de Identificação e Estatística, ou repartição congênere, mencionando o juízo a que forem distribuídos e os dados relativos à infração penal e ao indiciado.', '["Na remessa ao juiz, a polícia oficia o Instituto de Identificação e Estatística.","Informa o juízo, a infração e o indiciado."]'::jsonb, '["Finalidade: manter atualizados os registros e estatísticas criminais."]'::jsonb, 'Ao encaminhar o inquérito, o delegado comunica ao instituto de identificação o juízo de distribuição.', '["Assertiva que dispensa a comunicação ao Instituto de Identificação erra."]'::jsonb, '[]'::jsonb, '["Art. 10"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-23'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Nos crimes de ação pública, a ação é promovida por denúncia do Ministério Público, mas dependerá, quando a lei o exigir, de requisição do Ministro da Justiça ou de representação do ofendido ou de quem tiver qualidade para representá-lo. No caso de morte do ofendido ou quando declarado ausente por decisão judicial, o direito de representação passa ao cônjuge, ascendente, descendente ou irmão. Qualquer que seja o crime, quando praticado em detrimento do patrimônio ou interesse da União, Estado e Município, a ação penal será pública.', '["Ação pública: denúncia do Ministério Público.","Pode depender de requisição do Ministro da Justiça ou representação do ofendido.","§1º: morte ou ausência do ofendido: representação passa ao cônjuge, ascendente, descendente ou irmão.","§2º: crime contra patrimônio ou interesse da União, Estado e Município: ação pública."]'::jsonb, '["Ordem de sucessão: cônjuge, ascendente, descendente, irmão (CADI)."]'::jsonb, 'Morte do ofendido: o cônjuge pode oferecer a representação.', '["Assertiva que torna privada a ação penal de crime contra o patrimônio da União erra: será pública."]'::jsonb, '[{"termo":"Representação","significado":"Autorização da vítima para o Ministério Público agir."}]'::jsonb, '["Art. 25","Art. 5º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-24'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A representação do ofendido será irretratável depois de oferecida a denúncia: até esse momento, ele ainda pode se arrepender e retratar-se.', '["Representação pode ser retratada até o oferecimento da denúncia.","Oferecida a denúncia, é irretratável."]'::jsonb, '["Marco: OFERECIMENTO da denúncia (não o recebimento)."]'::jsonb, 'A vítima se arrepende após a denúncia: não pode retratar a representação.', '["Assertiva que fixa o recebimento da denúncia como marco da irretratabilidade erra: é o oferecimento."]'::jsonb, '[]'::jsonb, '["Art. 24"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-25'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'A ação penal, nas contravenções, será iniciada com o auto de prisão em flagrante ou por meio de portaria expedida pela autoridade judiciária ou policial.', '["Contravenções: início pelo auto de prisão em flagrante ou por portaria."]'::jsonb, '["Dispositivo não recepcionado pela Constituição vigente (privatividade da ação penal pública do Ministério Público)."]'::jsonb, 'Dispositivo hoje sem aplicação, pois a ação pública é privativa do Ministério Público.', '["Assertiva que admite portaria da autoridade policial para iniciar a ação penal hoje erra."]'::jsonb, '[{"termo":"Processo judicialiforme","significado":"Ação iniciada de ofício por portaria ou auto de prisão."}]'::jsonb, '["Art. 24"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-26'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Qualquer pessoa do povo pode provocar a iniciativa do Ministério Público, nos casos em que caiba a ação pública, fornecendo-lhe, por escrito, informações sobre o fato e a autoria e indicando o tempo, o lugar e os elementos de convicção.', '["Qualquer pessoa pode provocar o Ministério Público.","Por escrito, informando fato, autoria, tempo, lugar e elementos de convicção."]'::jsonb, '["A provocação não vincula o Ministério Público."]'::jsonb, 'Cidadão envia ao MP, por escrito, informações sobre um crime de ação pública.', '["Assertiva que obriga o MP a denunciar após a provocação de qualquer pessoa erra."]'::jsonb, '[]'::jsonb, '["Art. 5º"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-27'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Ordenado o arquivamento do inquérito policial ou de elementos informativos de mesma natureza, o órgão do Ministério Público comunicará à vítima, ao investigado e à autoridade policial e encaminhará os autos para a instância de revisão ministerial para homologação. Se a vítima ou seu representante legal não concordar, poderá, no prazo de 30 dias do recebimento da comunicação, submeter a matéria à revisão da instância competente do órgão ministerial. Nas ações relativas a crimes em detrimento da União, Estados e Municípios, a revisão pode ser provocada pela chefia do órgão a quem couber a representação judicial.', '["O MP ordena o arquivamento e comunica vítima, investigado e polícia.","Autos seguem à instância de revisão ministerial para homologação.","Vítima discordante: 30 dias para submeter à revisão.","Crimes contra entes públicos: revisão pode ser provocada pela chefia do órgão de representação judicial."]'::jsonb, '["Eficácia discutida em ADIs.","O arquivamento deixou de ser homologado pelo juiz."]'::jsonb, 'Vítima discorda do arquivamento e, em 30 dias, pede revisão ao órgão superior do MP.', '["Assertiva que mantém a homologação do arquivamento pelo juiz, nos termos do art. 28, erra: ela é feita pela instância de revisão ministerial."]'::jsonb, '[]'::jsonb, '["Art. 17","Art. 18"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-28'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Não sendo caso de arquivamento e tendo o investigado confessado formal e circunstancialmente a prática de infração penal sem violência ou grave ameaça e com pena mínima inferior a 4 anos, o Ministério Público pode propor acordo de não persecução penal, desde que necessário e suficiente para reprovação e prevenção do crime, mediante condições ajustadas cumulativa e alternativamente: reparar o dano ou restituir a coisa; renunciar a bens e direitos instrumentos, produto ou proveito do crime; prestar serviço à comunidade; pagar prestação pecuniária; ou cumprir outra condição indicada pelo Ministério Público. A vítima é intimada da homologação do acordo e de seu descumprimento. Descumpridas as condições, o MP comunica o juízo para rescisão e oferece a denúncia; o descumprimento pode também justificar o não oferecimento de suspensão condicional do processo. A celebração e o cumprimento do acordo não constam de certidão de antecedentes, salvo para os fins do inciso III do §2º. Cumprido integralmente, o juízo decreta a extinção de punibilidade. Em caso de recusa do MP em propor o acordo, o investigado pode requerer a remessa dos autos a órgão superior, na forma do art. 28.', '["Requisitos: confissão formal e circunstanciada; infração sem violência ou grave ameaça; pena mínima inferior a 4 anos.","Acordo necessário e suficiente para reprovação e prevenção do crime.","Condições: reparar o dano, renunciar a bens, prestar serviço, pagar prestação pecuniária, outra condição.","A vítima é intimada da homologação e do descumprimento.","Descumprimento: rescisão e denúncia; pode impedir a suspensão condicional do processo.","Cumprimento integral: extinção de punibilidade.","Recusa do MP: remessa a órgão superior (art. 28)."]'::jsonb, '["O limite é a pena MÍNIMA inferior a 4 anos.","Eficácia discutida em ADIs.","Cumprido o acordo, não constam antecedentes (salvo exceção)."]'::jsonb, 'Investigado confesso de furto sem violência, com pena mínima baixa, aceita acordo e repara o dano.', '["Assertiva que exige pena máxima inferior a 4 anos para o ANPP erra: o critério é a pena mínima."]'::jsonb, '[{"termo":"ANPP","significado":"Acordo de não persecução penal."}]'::jsonb, '["Art. 28","Art. 395"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-28-a'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Será admitida ação privada nos crimes de ação pública se esta não for intentada no prazo legal. Cabe ao Ministério Público aditar a queixa, repudiá-la e oferecer denúncia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de negligência do querelante, retomar a ação como parte principal.', '["Ação privada subsidiária da pública, se a denúncia não for oferecida no prazo legal.","MP pode aditar a queixa, repudiá-la e oferecer denúncia substitutiva.","MP intervém em todos os termos, fornece prova e recorre.","Em caso de negligência do querelante, o MP retoma a ação como parte principal."]'::jsonb, '["Exige INÉRCIA do Ministério Público. Pedido de arquivamento ou requisição de diligências não autoriza a ação subsidiária."]'::jsonb, 'O MP não oferece denúncia no prazo legal, e a vítima ajuíza queixa subsidiária.', '["Assertiva que permite a ação subsidiária mesmo quando o MP pede o arquivamento erra."]'::jsonb, '[{"termo":"Querelante","significado":"Quem ajuíza a queixa-crime."}]'::jsonb, '["Art. 5º, LIX da Constituição"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-29'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();

insert into public.legal_unit_explanations (unit_id, content_sha256, simples, pontos, atencao, exemplo, prova, termos, remissoes, status, authored_by)
select u.id, u.content_sha256, 'Ao ofendido ou a quem tenha qualidade para representá-lo caberá intentar a ação privada.', '["Legitimado a propor a ação privada: o ofendido ou quem o represente."]'::jsonb, '["Para pessoa menor ou incapaz, a legitimidade passa ao representante legal."]'::jsonb, 'Vítima de calúnia ajuíza queixa-crime contra o ofensor.', '["Assertiva que atribui ao Ministério Público a propositura da ação privada erra: cabe ao ofendido ou seu representante."]'::jsonb, '[]'::jsonb, '["Art. 31"]'::jsonb, 'under_review', 'claude'
from public.legal_course_units u join public.legal_courses c on c.id = u.course_id where c.slug = 'codigo-processo-penal' and u.unit_key = 'art-30'
on conflict (unit_id) do update set content_sha256 = excluded.content_sha256, simples = excluded.simples, pontos = excluded.pontos, atencao = excluded.atencao, exemplo = excluded.exemplo, prova = excluded.prova, termos = excluded.termos, remissoes = excluded.remissoes, status = case when public.legal_unit_explanations.status = 'published' then 'published' else 'under_review' end, updated_at = now();
