-- Catálogo de questões da prova Professor - Licenciatura Plena - Pedagogo,
-- Prefeitura de Feijó-AC, Edital nº 006/2018 (banca Fundape), conferida
-- contra o gabarito oficial de 22/12/2018 (fundape.ufac.br, arquivado no
-- Wayback Machine — o domínio original saiu do ar).
--
-- Das 50 questões do caderno, 43 foram transcritas com confiança total a
-- partir das fotos do próprio candidato (paginas legíveis). As questões 29,
-- 30, 31, 33 e 35 NÃO foram cadastradas: as duas páginas do caderno que as
-- contêm (itens 29-35) estão fora de foco/ilegíveis nas fotos enviadas — não
-- há aqui nenhuma transcrição inventada. As questões 32 e 34 (dessa mesma
-- faixa) foram ANULADAS pela banca e também ficaram de fora por estarem nas
-- páginas ilegíveis. A questão 47 também foi anulada, mas sua página é
-- legível — foi cadastrada com content_status='annulled' para preservar o
-- registro sem servir como questão de treino ativa.
--
-- A questão 23 (valor vigente do salário mínimo em 2018) foi marcada como
-- 'obsolete': o valor correto na época (R$ 954,00) muda todo ano por decreto,
-- então reutilizá-la como treino atual induziria o candidato a erro.

insert into public.content_sources (source_type,title,issuer,url,published_on,status,notes) values
('edital','Edital de Concurso Público nº 006/2018','Prefeitura Municipal de Feijó-AC / Fundape','https://editalconcursosbrasil.com.br/wp-content/uploads/2018/11/edital-006-2018-feijo-ac.pdf','2018-11-18','vigente','Edital do concurso para Professor - Licenciatura Plena (inclui o cargo Pedagogo).'),
('outro','Gabarito Oficial - Professor/Pedagogo - Feijó 2018 (22/12/2018)','Fundape','http://fundape.ufac.br/auto/conc/2018--8-feijo/12_gabarito_oficial.pdf','2018-12-22','vigente','Domínio original (fundape.ufac.br) fora do ar; documento conferido via Wayback Machine: https://web.archive.org/web/20181228231037/http://fundape.ufac.br/auto/conc/2018--8-feijo/12_gabarito_oficial.pdf. Itens 32, 34 e 47 anulados.')
on conflict (url) do update set checked_at=now(), status=excluded.status, notes=excluded.notes;

insert into public.syllabus_editions (contest_name,role_name,contest_year,exam_board,source_id,status)
select 'Prefeitura de Feijó','Professor - Licenciatura Plena - Pedagogo',2018,'Fundape',id,'active'
from public.content_sources where url='https://editalconcursosbrasil.com.br/wp-content/uploads/2018/11/edital-006-2018-feijo-ac.pdf'
on conflict (contest_name,role_name,contest_year) do update set source_id=excluded.source_id, status='active';

with edition as (
  select id from public.syllabus_editions
  where contest_name='Prefeitura de Feijó' and role_name='Professor - Licenciatura Plena - Pedagogo' and contest_year=2018
)
insert into public.syllabus_topics (edition_id,block_name,discipline,topic_order,topic_text)
select edition.id, data.block_name, data.discipline, 1, data.topic_text from edition cross join (values
('Bloco Único','Língua Portuguesa','Compreensão e interpretação de textos variados (crônica, poema, conto, notícia); classes gramaticais; pronomes; figuras de linguagem; regência e concordância — conforme cobrado nas questões 1 a 15 do caderno.'),
('Bloco Único','Matemática','Matemática financeira (juros simples/compostos), probabilidade, razão e proporção, progressões, conversão de unidades — conforme cobrado nas questões 16 a 20 do caderno.'),
('Bloco Único','Conhecimentos Gerais e Atualidades','Fatos históricos, geográficos e políticos nacionais e do Acre — conforme cobrado nas questões 21 a 25 do caderno.'),
('Bloco Único','Legislação','Estatuto da Criança e do Adolescente (Lei nº 8.069/1990); Constituição Federal de 1988, arts. 205 e 210 — conforme cobrado nas questões 26 a 30 do caderno.'),
('Bloco Único','Pedagogia','Didática e planejamento escolar (Libâneo); tendências pedagógicas; Paulo Freire; transposição didática; teorias de Piaget e Vygotsky; PCN — conforme cobrado nas questões 31 a 50 do caderno.')
) as data(block_name,discipline,topic_text)
on conflict (edition_id,discipline,topic_order) do update set topic_text=excluded.topic_text, content_status='current';

with sources as (
  select
    (select id from public.content_sources where url='https://editalconcursosbrasil.com.br/wp-content/uploads/2018/11/edital-006-2018-feijo-ac.pdf') as prova_id,
    (select id from public.content_sources where url='http://fundape.ufac.br/auto/conc/2018--8-feijo/12_gabarito_oficial.pdf') as gabarito_id,
    (select id from public.content_sources where url='https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm') as cf_id,
    (select id from public.content_sources where url='https://www.planalto.gov.br/ccivil_03/leis/l8069.htm') as eca_id
),
topics as (
  select t.discipline, t.id as topic_id
  from public.syllabus_topics t
  join public.syllabus_editions e on e.id = t.edition_id
  where e.contest_name='Prefeitura de Feijó' and e.role_name='Professor - Licenciatura Plena - Pedagogo' and e.contest_year=2018
),
imported(item_number,subject,question_text,official_answer,source_page,content_status,legal_review_required,context_review_required,legal_basis_url,review_note) as (values
(1,'Língua Portuguesa','Texto I ("Felicidade Clandestina", Clarice Lispector). Da leitura do texto I, infere-se que: A) Os adjetivos gorda, baixa e sardenta referem-se à narradora do texto; B) O adjetivo bordadíssima está no grau superlativo absoluto sintético; C) Os adjetivos crespos e arruivados referem-se aos cabelos da narradora do texto; D) A personagem narradora do texto caracteriza a filha do dono da livraria como uma pessoa amável; E) A filha do dono da livraria atendia a maior parte dos desejos da personagem narradora.','B',2,'active',false,false,null,'Conferida contra a foto original da prova (pág. 2) e contra o gabarito oficial Fundape de 22/12/2018.'),
(2,'Língua Portuguesa','Texto I. Em "Até que veio para ela o magno dia de começar a exercer sobre mim uma tortura chinesa.", a palavra em destaque pode ser substituída, sem prejuízo de sentido, por: A) Insignificante; B) Irrelevante; C) Grandioso; D) Tradicional; E) Inquestionável.','C',2,'active',false,false,null,'Conferida contra a foto original da prova (pág. 2) e contra o gabarito oficial Fundape de 22/12/2018.'),
(3,'Língua Portuguesa','Texto I. Em "Tinha um busto enorme, enquanto nós todas ainda éramos achatadas. Como se não bastasse enchia os dois bolsos da blusa, por cima do busto, com balas.", éramos e bastasse estão flexionados, respectivamente, no: A) Pretérito imperfeito do indicativo - pretérito imperfeito do subjuntivo; B) Pretérito imperfeito do subjuntivo - pretérito perfeito do indicativo; C) Pretérito mais que perfeito do indicativo - pretérito imperfeito do indicativo; D) Pretérito perfeito do indicativo - pretérito mais que perfeito do indicativo; E) Pretérito imperfeito do indicativo - pretérito perfeito do indicativo.','A',2,'active',false,false,null,'Conferida contra a foto original da prova (pág. 2) e contra o gabarito oficial Fundape de 22/12/2018.'),
(4,'Língua Portuguesa','Texto II ("O dia da minha morte", Jairo Marques, Folha de S.Paulo, 05/11/2014). Analisando as principais características do texto II, pode-se dizer que seu gênero predominante é: A) Conto; B) Poesia; C) Prosa; D) Crônica; E) Diário.','D',3,'active',false,false,null,'Conferida contra a foto original da prova (pág. 3) e contra o gabarito oficial Fundape de 22/12/2018.'),
(5,'Língua Portuguesa','Texto II. A partir da leitura do texto II, é possível concluir que o motivo que levou o autor a escrevê-lo foi: A) Encontrar-se em profunda reflexão em virtude do seu aniversário de 40 anos; B) O fato de admitir que não haja feitos em vida capazes de reacender os sorrisos; C) O fato de não duvidar dos dramas alheios; D) Para mostrar ao mundo que é possível viver diante das mais temíveis impossibilidades; E) O fato de uma moça norte-americana, mais jovem que ele, vítima de um mal avassalador, ter marcado o dia de seu último suspiro.','E',4,'active',false,false,null,'Conferida contra a foto original da prova (pág. 4) e contra o gabarito oficial Fundape de 22/12/2018.'),
(6,'Língua Portuguesa','Texto II. Assinale a alternativa em que o termo destacado NÃO pertence à mesma classe gramatical dos demais: A) "minutos de despedida ao lado do filho amado"; B) "vítima de um mal avassalador"; C) "complexidade das dores profundas"; D) "e do ar tomar conta aquele cheiro de terra molhada"; E) "do céu brotar um arco-íris escandaloso."','A',4,'active',false,false,null,'Conferida contra a foto original da prova (pág. 4) e contra o gabarito oficial Fundape de 22/12/2018.'),
(7,'Língua Portuguesa','Texto III ("Os outros", Antonio Prata) e resenha sobre o filme "Hoje eu quero voltar sozinho". Com base no texto III, analise as afirmativas: I - O narrador é em terceira pessoa e representa um indivíduo que, em um cenário urbano, observa um pedestre na calçada e, em seguida, se põe a pensar sobre a alteridade; II - No texto de Antonio Prata, temos aspectos característicos da crônica que se apresentam em uma visão inusitada de uma cena do cotidiano; III - A linguagem empregada no texto é composta por frases curtas e vocabulário simples. Há por vezes expressões adversas à fala cotidiana; IV - Por ser um "outro", o pedestre desperta no narrador o sentimento de alteridade. Está(ão) incorreta(s) apenas a(s) afirmativa(s): A) I, II; B) IV; C) I,III; D) I, III e IV; E) III.','C',5,'active',false,false,null,'Conferida contra a foto original da prova (pág. 5) e contra o gabarito oficial Fundape de 22/12/2018.'),
(8,'Língua Portuguesa','Observando a construção semântica de "O farol abriu, o pedestre ficou para trás, mas eu não conseguia parar de pensar que ele agora estava no quarteirão de cima, aprisionado em seus pensamentos, embalado por sua pele, tão centro do Cosmos e da Criação quanto eu, você e sua tia avó.", os pronomes em destaque classificam-se, respectivamente, como: A) Pronome pessoal, pronome possessivo, pronome possessivo, pronome pessoal de tratamento; B) Pronome demonstrativo, pronome possessivo, pronome pessoal, pronome pessoal; C) Pronome interrogativo, pronome interrogativo, pronome pessoal, pronome de tratamento; D) Pronome indeterminado, pronome demonstrativo, pronome pessoal, pronome de tratamento; E) Pronome pessoal, pronome possessivo, pronome pessoal, pronome pessoal.','A',5,'active',false,false,null,'Conferida contra a foto original da prova (pág. 5) e contra o gabarito oficial Fundape de 22/12/2018.'),
(9,'Língua Portuguesa','Texto IV (poema de Manoel de Barros). Nos versos 6 e 9 do texto IV, respectivamente, podem ser reconhecidas as seguintes figuras de linguagem: A) assonância e aliteração; B) sinestesia e paradoxo; C) sinestesia e assonância; D) anáfora e assíndeto; E) paradoxo e aliteração.','B',6,'active',false,false,null,'Conferida contra a foto original da prova (pág. 6) e contra o gabarito oficial Fundape de 22/12/2018.'),
(10,'Língua Portuguesa','Texto IV. Com base no texto IV, julgue em (V) verdadeiras ou (F) falsas as afirmações: (¿) a despalavra buscada pelo eu lírico parece impossível de se encontrar, pois ele busca a palavra sem som e sem grafia. (¿) a palavra antesmente é formada por derivação sufixal. (¿) o sentido de "antesmente verbal" no poema está relacionado à procura do eu lírico pela palavra inaugural, estritamente poética, que de modo paradoxal é uma despalavra. (¿) o antesmente reforça a ideia de princípio e de origem que o eu lírico busca. A ordem correta de preenchimento dos parênteses, de cima para baixo, é: A) V, V, V, F; B) V, F, F, V; C) F, F, V, V; D) F, V, V, F; E) V, V, V, V.','E',6,'active',false,false,null,'Conferida contra a foto original da prova (pág. 6) e contra o gabarito oficial Fundape de 22/12/2018.'),
(11,'Língua Portuguesa','Texto V ("Os seres humanos e Zeus", Esopo). O substantivo animal é retomado por alguns termos utilizados no texto V, esses termos são: A) serem – viram – força; B) uns – outros – outros ainda; C) permanecia – aquinhoado – belo; D) serem – outros – outros ainda; E) aquinhoado – belo – serem.','B',6,'active',false,false,null,'Conferida contra a foto original da prova (pág. 6) e contra o gabarito oficial Fundape de 22/12/2018.'),
(12,'Língua Portuguesa','Texto VI ("Infância", Guilherme de Almeida). Julgue em verdadeiras (V) ou falsas (F) as afirmações relacionadas ao texto VI: (¿) O texto trata-se de uma haicai do poeta brasileiro Guilherme de Almeida. (¿) O modo como a coerência de um texto se constrói está estreitamente vinculado ao seu gênero. No haicai, a coerência se produz pela integração efetuada pelo leitor entre elementos aparentemente desconexos, os quais também são responsáveis pela coesão. (¿) O haicai é uma forma poética de origem americana, marcada pela concisão. A ordem correta de preenchimento dos parênteses, de cima para baixo, é: A) V, V, V; B) F, F, F; C) F, V,F; D) V, V,F; E) F,F,V.','D',7,'active',false,false,null,'Conferida contra a foto original da prova (pág. 7) e contra o gabarito oficial Fundape de 22/12/2018.'),
(13,'Língua Portuguesa','Releia um trecho da resenha sobre o filme "Hoje eu quero voltar sozinho": "[...] o filme tem temática gay, algo cada vez mais comum, mas tem também como maior qualidade não ser panfletário. Ele não foi feito para defender uma causa. Seu objetivo, dito pelo próprio diretor, é se comunicar com todo tipo de público. E consegue." Sobre o trecho é correto afirmar que: I – A palavra panfletário é empregada para indicar algo ou alguém que faz a defesa radical de uma ideia. II – No contexto explicitado, ser panfletário pode ser visto como um defeito, porque levaria a obra a repetir as abordagens mais convencionais dos relacionamentos entre pessoas do mesmo sexo. III – A maneira como o comentário foi redigido para explicar o efeito expressivo obtido com a última frase do parágrafo evidencia que, ao colocar o verbo sem nenhum complemento, o produtor do texto sugere que o objetivo foi atingido plenamente. Com relação às afirmações é correto afirmar que: A) As afirmativas I e II são incorretas; B) As afirmativas I, II e III são incorretas; C) Está correto apenas o que se afirma em I; D) Está correto apenas o que se afirma em III; E) Todas as afirmativas estão corretas.','E',7,'active',false,false,null,'Conferida contra a foto original da prova (pág. 7) e contra o gabarito oficial Fundape de 22/12/2018.'),
(14,'Língua Portuguesa','Texto VII (Marcelo Rubens Paiva, sobre os cadeados na Pont des Arts, Paris). Segundo o texto VII, os casais prendiam cadeados nessa ponte porque: A) Queriam garantir a "chegada" de um amor platônico; B) Segundo a tradição, os cadeados fechados na ponte eternizariam o relacionamento dos casais; C) Estavam cansados dos amores duradouros e buscavam aventuras mais intensas; D) Almejavam fraternidade e liberdade; E) Queriam expressar o amor à civilização.','B',8,'active',false,false,null,'Conferida contra a foto original da prova (pág. 8) e contra o gabarito oficial Fundape de 22/12/2018.'),
(15,'Língua Portuguesa','Texto VII. No texto VII, a opinião contrária do autor sobre o hábito de prender cadeados na ponte é evidenciada por palavras e expressões que estão descritas na alternativa: A) Deslumbrantes e fruto da engenharia humana; B) Meia dúzia de cadeados e prova de amor; C) Aberração urbana e ato pretensioso; D) No beiral de ferro e cadeado de bicicleta; E) Crescimento desordenado e prova de amor.','C',8,'active',false,false,null,'Conferida contra a foto original da prova (pág. 8) e contra o gabarito oficial Fundape de 22/12/2018.'),
(16,'Matemática','Uma professora da rede municipal de Feijó – AC solicitou aos seus alunos que resolvessem: "Fui ao mercado e verifiquei que um pacote com 5 kg de arroz custam R$ 15,00, 1 kg de feijão custa R$ 4,50 e um pacote com 2,5 kg de calabresa custa R$ 30,00. Eu quero comprar 10 kg de arroz, 2 kg de feijão e 5 kg de calabresa. Entretanto, eu tenho apenas R$ 100,00 para realizar esta compra." Sobre este problema, pode-se afirmar que: A) O dinheiro é insuficiente para realizar a compra; B) O dinheiro é suficiente e ainda sobram R$ 5,00 de troco; C) O dinheiro é suficiente para a compra sem sobras de troco; D) O dinheiro é suficiente sobrando apenas R$ 1,00 de troco; E) O dinheiro é suficiente para realizar esta compra e ainda comprar mais 2 kg de feijão.','D',8,'active',false,false,null,'Conferida contra a foto original da prova (pág. 8) e contra o gabarito oficial Fundape de 22/12/2018.'),
(17,'Matemática','O salário bruto da professora Maria é de R$ 2.000,00. Entretanto ela possui os seguintes descontos realizados em seu contracheque: 14% do valor bruto para a previdência social (INSS); 10% do valor bruto referente a um empréstimo bancário; 1% do valor bruto referente à sua contribuição sindical. Neste sentido, o salário líquido da professora Maria (igual ao salário bruto subtraído dos descontos) será igual a: A) R$ 1450,00; B) R$ 1500,00; C) R$ 1550,00; D) R$ 1600,00; E) R$ 1650,00.','B',9,'active',false,false,null,'Conferida contra a foto original da prova (pág. 9) e contra o gabarito oficial Fundape de 22/12/2018.'),
(18,'Matemática','Numa escola estadual foi realizada uma pesquisa quanto à preferência dos alunos por determinados esportes (tabela por sexo x atividade: Futebol, Voleibol, Basquetebol, Handebol). Suponha que todos os alunos desta escola participaram da pesquisa. Se aleatoriamente sortearmos um aluno desta escola e ele for do sexo masculino, a probabilidade de ele ter escolhido voleibol como seu esporte preferido é de: A) 20%; B) 30%; C) 40%; D) 50%; E) 70%.','A',9,'active',false,false,null,'Conferida contra a foto original da prova (pág. 9) e contra o gabarito oficial Fundape de 22/12/2018.'),
(19,'Matemática','Uma professora do Ensino Fundamental, trabalhando conversão de unidades de medida, comenta que a distância geográfica entre a cidade de Feijó – AC e a capital do estado do Acre, Rio Branco, pela estrada, é de aproximadamente 363 km. Um aluno pergunta: "Professora, a minha régua mede 30 cm, se eu fosse medir a distância, pela estrada, entre Rio Branco e Feijó utilizando-a, quantas seriam necessárias?". A alternativa que responda a pergunta do aluno é: A) 12.100 medições com comprimento igual ao da régua do aluno; B) 121.000 medições com comprimento igual ao da régua do aluno; C) 1.210.000 medições com comprimento igual ao da régua do aluno; D) 12.100.000 medições com comprimento igual ao da régua do aluno; E) 121.000.000 medições com comprimento igual ao da régua do aluno.','C',9,'active',false,false,null,'Conferida contra a foto original da prova (pág. 9) e contra o gabarito oficial Fundape de 22/12/2018.'),
(20,'Matemática','João tomou emprestado de Pedro a quantia de R$ 1.000,00. Nesta negociação, ficou estipulado que a cada mês João pagaria, de juros, a quantia de R$ 10,00. Neste sentido, pode-se afirmar que: A) Este empréstimo foi realizado segundo o sistema de juros compostos, com uma taxa de 1% ao mês; B) Este empréstimo foi realizado segundo o sistema de juros simples com uma taxa de 10% ao mês; C) A sequência formada pelo saldo devedor ao final de cada mês é uma progressão geométrica de razão igual a 1,01; D) A sequência formada pelo saldo devedor ao final de cada mês é uma progressão aritmética de razão igual a 10% do valor emprestado; E) A sequência formada pelo do saldo devedor ao final de cada mês é uma progressão aritmética de razão igual a R$ 10,00.','E',10,'active',false,false,null,'Conferida contra a foto original da prova (pág. 10) e contra o gabarito oficial Fundape de 22/12/2018.'),
(21,'Conhecimentos Gerais e Atualidades','Na formação cultural da população brasileira, a religiosidade é bastante marcante. Neste sentido, é correto afirmar que o Natal é comemorado no dia: A) 25 de março; B) 25 de dezembro; C) 06 de agosto; D) 15 de novembro; E) 06 de janeiro.','B',10,'active',false,false,null,'Fato do calendário civil/religioso, sem dependência de vigência de norma — conferida contra a foto original (pág. 10) e o gabarito oficial Fundape de 22/12/2018.'),
(22,'Conhecimentos Gerais e Atualidades','Em setembro de 2015, o Tribunal Superior Eleitoral (TSE) aprovou a concessão de registro do partido idealizado pela ex-ministra e ex-senadora Marina Silva, o Rede Sustentabilidade. Em outubro deste ano, na eleição presidencial, a idealizadora concorreu mais uma vez e acabou derrotada, não tendo uma votação expressiva como anteriormente. A candidata em questão é natural de qual estado brasileiro? A) Rondônia; B) Amapá; C) Pará; D) Acre; E) Amazonas.','D',10,'active',false,false,null,'Fato biográfico fixo (naturalidade), não dependente de vigência temporal — conferida contra a foto original (pág. 10) e o gabarito oficial Fundape de 22/12/2018.'),
(23,'Conhecimentos Gerais e Atualidades','De acordo com o Artigo 7.º da Constituição Federal do Brasil, de 1988, todos os trabalhadores brasileiros têm direito a, pelo menos, um salário mínimo como remuneração. Neste sentido, o valor vigente do salário mínimo é de: A) R$ 954,00; B) R$ 1.888,00; C) R$ 634,00; D) R$ 717,00; E) R$ 837,00.','A',10,'obsolete',false,true,null,'O valor do salário mínimo nacional é redefinido por decreto todo ano — R$ 954,00 era o valor vigente apenas em 2018 (o correto na aplicação da prova). Reutilizar este item como questão de treino "atual" induziria o candidato a erro; mantido apenas como registro histórico (content_status=obsolete), conforme a regra de exclusão de itens dependentes de atualidades do CONTENT_GOVERNANCE.md.'),
(24,'Conhecimentos Gerais e Atualidades','Em dezembro de 2018, completam-se 30 anos de morte do seringueiro e sindicalista que se tornou símbolo internacional na luta pelo uso sustentável dos recursos ambientais da Amazônia Brasileira e pela sobrevivência das populações da floresta. Suas ações conduziram à criação de um novo tipo de unidade de conservação no Brasil denominada "Reserva Extrativista (RESEX)". A liderança de que se trata o enunciado é: A) Chico Ferramenta; B) Vicente Paulo da Silva; C) Chico Mendes; D) Nelsinho Metalúrgico; E) Rômulo Marinho.','C',10,'active',false,false,null,'Fato histórico fixo (identidade do seringueiro/sindicalista), não dependente de vigência temporal — conferida contra a foto original (pág. 10) e o gabarito oficial Fundape de 22/12/2018.'),
(25,'Conhecimentos Gerais e Atualidades','O estado do Acre faz fronteira com dois países. Porém, o município de Feijó faz fronteira com apenas um deles, sendo este o(a): A) Bolívia; B) Paraguai; C) Chile; D) Equador; E) Peru.','E',11,'active',false,false,null,'Fato geográfico fixo, não dependente de vigência temporal — conferida contra a foto original (pág. 11) e o gabarito oficial Fundape de 22/12/2018.'),
(26,'Legislação','De acordo com o Estatuto da Criança e do Adolescente (ECA), Lei N.º 8.068, de 13 de julho de 1990, em seu Art. 2.º, é correto afirmar que, para os efeitos desta Lei: A) Considera-se criança quem tem até onze anos de idade, incompletos, e adolescente quem tem entre doze e dezoito anos de idade; B) Considera-se criança quem tem até dez anos de idade, incompletos, e adolescente quem tem entre doze e dezoito anos de idade; C) Considera-se criança quem tem até doze anos de idade, incompletos, e adolescente quem tem entre doze e dezoito anos de idade; D) Considera-se criança quem tem até doze anos de idade, incompletos, e adolescente quem tem entre treze e dezoito anos de idade; E) Considera-se criança quem tem até doze anos de idade, incompletos, e adolescente quem tem entre quinze e dezoito anos de idade.','C',11,'active',true,false,'eca','Art. 2º da Lei nº 8.069/1990 (o enunciado da prova grafa "8.068", erro de digitação da banca — o Estatuto da Criança e do Adolescente é a Lei nº 8.069/1990) segue com a mesma redação desde a publicação; texto conferido no compilado do Planalto. Fonte oficial vinculada em legal_basis.'),
(27,'Legislação','Em consonância com a Constituição Federal de 1988, em seu Art. 205, as três finalidades da educação são: A) O pleno desenvolvimento da pessoa, seu preparo para o exercício da cidadania e sua qualificação para o trabalho; B) O pleno desenvolvimento da pessoa, sua liberdade de aprender e sua qualificação para o trabalho; C) Liberdade de aprender, ensinar e pesquisar; D) Garantia ao direito a padrões de qualidade, promoção física e intelectual; E) O pleno desenvolvimento da pessoa, seu preparo para o mercado de trabalho e promoção do desenvolvimento intelectual.','A',11,'active',true,false,'cf','Art. 205 da Constituição Federal de 1988, sem alteração de redação; texto conferido no compilado do Planalto. Fonte oficial vinculada em legal_basis.'),
(28,'Legislação','A Constituição Federal de 1988, em seu Art. 210 estabelece que sejam fixados os conteúdos mínimos para o ensino fundamental, de maneira a assegurar formação básica comum e respeito aos valores ____ e ____, ____ e ____. Assinale a opção que completa corretamente as lacunas do enunciado: A) culturais e artísticos, estaduais e regionais; B) políticos e sociais, nacionais e regionais; C) artísticos e sociais, nacionais e regionais; D) artísticos e sociais, municipais e regionais; E) culturais e artísticos, nacionais e regionais.','E',11,'active',true,false,'cf','Art. 210 da Constituição Federal de 1988, sem alteração de redação; texto conferido no compilado do Planalto. Fonte oficial vinculada em legal_basis.'),
(36,'Pedagogia','Em relação à Didática, analise as opções abaixo e assinale (V) para Verdadeira e (F) para falsa: (¿) contribui para transformar a prática pedagógica da escola, ao desenvolver a compreensão articulada entre os conteúdos a serem ensinados e as práticas sociais. (¿) não compete refletir acerca dos objetivos sócio-políticos e pedagógicos, ao selecionar os conteúdos e métodos de ensino. (¿) realiza-se por meio de ação consciente, intencional e planejada, no processo de formação humana, estabelecendo-se objetivos e critérios socialmente determinados. (¿) sua finalidade é converter objetivos sócio-políticos e pedagógicos em objetivos de ensino, selecionar conteúdos e métodos em função desses objetivos. Marque a alternativa com a sequência CORRETA, de cima para baixo: A) V, V, F, F; B) F, F, V, V; C) F, V, F, F; D) V, F, V, F; E) V, F, V, V.','E',14,'active',false,false,null,'Conferida contra a foto original da prova (pág. 14) e contra o gabarito oficial Fundape de 22/12/2018.'),
(37,'Pedagogia','De acordo com LIBÂNEO, 1994, o modo de se fazer docente determina a direção e a qualidade do ensino. Segundo o autor, os principais objetivos da atuação docente são: I. Assegurar ao aluno domínio duradouro e seguro dos conhecimentos. II. Criar condições para o desenvolvimento de capacidades e habilidades visando a autonomia na aprendizagem e independência de pensamento dos alunos. III. Orientar as tarefas do ensino para a formação da personalidade. IV. Criar condições para o desenvolvimento de capacidades e habilidades visando a dependência de pensamento dos alunos. Está correto o que se afirma nos itens: A) I, II e III; B) II, III e IV; C) I, III e IV; D) I, II e IV; E) Todos os itens estão corretos.','A',14,'active',false,false,null,'Conferida contra a foto original da prova (pág. 14) e contra o gabarito oficial Fundape de 22/12/2018.'),
(38,'Pedagogia','A didática é uma ramificação da pedagogia, sendo uma das disciplinas fundamentais na formação dos professores, denominada por LIBÂNEO (1990, p.25) como ____ por investigar os fundamentos, as condições e as formas de realização do ensino. Assinale a opção que completa corretamente a lacuna do enunciado: A) teoria da educação; B) teoria do ensino; C) teoria do conhecimento; D) teoria social; E) teoria dos conteúdos.','B',14,'active',false,false,null,'Conferida contra a foto original da prova (pág. 14) e contra o gabarito oficial Fundape de 22/12/2018.'),
(39,'Pedagogia','Luckesi (2001), afirma que a função da Didática é a de criar condições para ajudar o educador a se preparar para sua atuação. O docente precisa ter conhecimentos: A) técnicos, científicos e culturais para estar apto a exercer a sua profissão; B) técnicos, científicos e sociológicos para estar apto a exercer a sua profissão; C) técnicos, sociais e filosóficos para estar apto a exercer a sua profissão; D) técnicos, científicos e filosóficos para estar apto a exercer a sua profissão; E) técnicos, científicos e psicológicos para estar apto a exercer a sua profissão.','D',14,'active',false,false,null,'Conferida contra a foto original da prova (pág. 14) e contra o gabarito oficial Fundape de 22/12/2018.'),
(40,'Pedagogia','Segundo LIBÂNEO, 1994, são pontos principais que norteiam o planejamento escolar o que se descreve nas opções seguintes, EXCETO o que se afirma na alternativa: A) Compreensão da relação entre educação escolar e objetivo sócio-político; B) Domínio de conteúdo, sua relação com a vida prática e a capacidade de dividir a matéria em módulos ou unidades; C) Conhecer as características socioculturais e individuais dos alunos e ter domínio de método de ensino; D) Manter-se bem informado sobre livros e artigos ligados à sua disciplina, aos fatos relevantes e ter conhecimento sobre os programas oficiais; E) Domínio de conteúdo, sua relação com o cotidiano e a capacidade de fragmentar a matéria em módulos ou unidades.','E',15,'active',false,false,null,'Conferida contra a foto original da prova (pág. 15) e contra o gabarito oficial Fundape de 22/12/2018.'),
(41,'Pedagogia','A função social da escola está a cada vez mais diversificada diante das mudanças que se processam de forma acelerada, em função dos avanços da tecnologia, da ciência e o mundo do trabalho. Sobre o exposto é correto afirmar que: A) A função do currículo escolar é priorizar disciplinas que valorizem a capacitação para o mundo do trabalho; B) A cultura escolar deve priorizar o ensino interdisciplinar; C) A função do currículo escolar é priorizar disciplinas que valorizem a ciência e a tecnologia; D) A cultura escolar deve desenvolver um ensino que crie conexões entre a aprendizagem do aluno e as experiências de vida; E) A função do currículo escolar é priorizar conteúdos e métodos que valorizem a capacitação para o mundo do trabalho.','D',15,'active',false,false,null,'Conferida contra a foto original da prova (pág. 15) e contra o gabarito oficial Fundape de 22/12/2018.'),
(42,'Pedagogia','Paulo Freire, em sua obra "Pedagogia do Oprimido" afirma que quanto mais analisamos as relações entre educador e educando na escola, mais nos convenceremos de que essas relações apresentam um caráter especial e marcante. O autor afirma que se deve priorizar o diálogo enquanto essência da educação como prática da liberdade. A respeito da relação entre professor, aluno e conhecimento, assinale a opção correta: A) O professor deve evitar envolver-se efetivamente com os alunos, para que estes desenvolvam autonomia no processo de aprendizagem; B) O professor deve incentivar os alunos quanto a atitudes e valores, quanto mais os alunos se comportem e pensem como o professor, mais positivo e harmônico será o relacionamento entre eles na sala de aula; C) O professor que valoriza os erros dos alunos para corrigi-los em outra oportunidade adota uma prática pedagógica construtiva, que aproxima o aluno e o professor; D) As atividades pedagógicas que envolvem classificação, comparação e dedução são supressoras das capacidades de trabalho coletivo nos anos iniciais do ensino fundamental; E) Nos anos iniciais do ensino fundamental, a relação entre professor e aluno torna-se positiva à medida que este se reconhece como independente daquele para a construção do conhecimento.','E',15,'active',false,false,null,'Conferida contra a foto original da prova (pág. 15) e contra o gabarito oficial Fundape de 22/12/2018.'),
(43,'Pedagogia','Na função de mediador do processo de construção do conhecimento pelo aluno, o professor deve empenhar-se em realizar um trabalho que contribua para o sucesso da aprendizagem da turma. Uma mediação eficaz do processo de aprendizagem de alunos dos anos iniciais do ensino fundamental depende de o professor: A) Incentivar os estudantes a competirem entre si para que possam alcançar maiores notas nas avaliações; B) Investir na aprendizagem dos estudantes que apresentem déficit de aprendizagem em detrimento aos alunos com altas habilidades, pois estes conseguem aprender sozinhos; C) Aproximar-se dos estudantes, construir relações respeitosas com eles e considerar suas diferenças individuais; D) Valorizar as habilidades individuais para garantir o desenvolvimento do pensamento crítico dos estudantes; E) Valorizar as disciplinas que são a base, como português e matemática, em detrimento as demais disciplinas.','C',16,'active',false,false,null,'Conferida contra a foto original da prova (pág. 16) e contra o gabarito oficial Fundape de 22/12/2018.'),
(44,'Pedagogia','De acordo com a concepção pedagógica Liberal Renovada não Diretiva, cabe à escola: I) Proporcionar aos alunos experiências que os possibilitem educar-se por meio da interação entre as estruturas culturais e o ambiente. II) Proporcionar aos alunos experiências que os permitam confrontá-las com o saber sistematizado. III) Valorizar a formação de atitudes, razão pela qual deve preocupar-se mais com os problemas de ordem psicológicos do que com os pedagógicos ou sociais. IV) Proporcionar ao indivíduo uma mudança interna, ou seja, uma adequação pessoal às solicitações do ambiente. Está correto o que se afirma nos itens: A) I e II; B) II e III; C) II e IV; D) III e IV; E) I e IV.','D',16,'active',false,false,null,'Conferida contra a foto original da prova (pág. 16) e contra o gabarito oficial Fundape de 22/12/2018.'),
(45,'Pedagogia','Sobre as tendências pedagógicas, preencha a segunda coluna de acordo com a primeira: (1) Pedagogia tradicional. (2) Pedagogia tecnicista. (3) Pedagogia da escola nova. (¿) Centra-se na mera transmissão de conteúdos e autoridade do professor. (¿) Está associada à transmissão de conteúdos, mas prioriza o desenvolvimento de habilidades práticas, no saber fazer. (¿) Não se exclui a transmissão de conhecimento, mas considera mais importante a organização do ambiente de aprendizagem para que o aluno possa desenvolver sua própria atividade de aprender. Assinale a opção que apresenta a sequência correta, de cima para baixo: A) 1, 2, 3; B) 1, 3, 2; C) 2, 3, 1; D) 3, 2, 1; E) 2, 1, 3.','A',16,'active',false,false,null,'Conferida contra a foto original da prova (pág. 16) e contra o gabarito oficial Fundape de 22/12/2018.'),
(46,'Pedagogia','Concernente aos temas transversais, relacionados nos Parâmetros Curriculares Nacionais - PCN''s, assinale a opção incorreta: A) Referem-se às questões que interferem na vida dos alunos e no seu cotidiano; B) São temas que constituem novas áreas para o fazer docente; C) São temas que aparecem transversalizados em áreas específicas; D) São temas transversais, meio ambiente, ética e saúde; E) São temas que estão voltados para a compreensão e para a construção da realidade social.','B',16,'active',false,false,null,'Conferida contra a foto original da prova (pág. 16) e contra o gabarito oficial Fundape de 22/12/2018.'),
(47,'Pedagogia','De acordo com Almeida (2011), "A transposição didática pode ser entendida como uma competência que deve ser mobilizada constantemente na prática pedagógica, e ela ocorre quando...": A) o conteúdo é selecionado ou recortado de acordo com o que o professor considera importante para estabelecer competências definidas na proposta pedagógica; B) alguns aspectos ou temas são mais enfatizados, reforçados ou diminuídos; C) o conhecimento é dividido para facilitar sua compreensão e posteriormente volta-se a ele para estabelecer relação entre o que foi dividido; D) organiza-se o conteúdo em uma sequência, um ordenamento linear ou não, para se estabelecer relações e determina-se uma forma de organizar e apresentar os conteúdos, como por meio de textos e gráficos; E) o conteúdo é selecionado ou recortado de acordo com o que o professor considera importante, mas não estabelece competências com proposta pedagógica.','X',17,'annulled',false,false,null,'Questão ANULADA pela banca Fundape (confirmado no gabarito oficial de 22/12/2018 e na própria folha de prova do candidato, com anotação manuscrita "anulada" na pág. 17). Mantida apenas como registro — nunca deve ser servida como questão de treino ativa.'),
(48,'Pedagogia','A transposição didática é necessária a qualquer prática pedagógica que objetive a aprendizagem dos alunos. Pode-se definir transposição didática como: A) instrumento através do qual se transforma o conhecimento científico em conhecimento escolar; B) instrumento através do qual se transforma o conhecimento científico em conhecimento social; C) instrumento através do qual se transforma o conhecimento social em conhecimento escolar; D) instrumento através do qual se transforma a cultura em conhecimento escolar; E) instrumento através do qual se transforma a cultura em conhecimento científico.','A',17,'active',false,false,null,'Conferida contra a foto original da prova (pág. 17) e contra o gabarito oficial Fundape de 22/12/2018.'),
(49,'Pedagogia','De acordo com a teoria de Piaget, a aprendizagem é o processo que só tem sentido diante de situações de mudança. Por isso, aprender é, em parte, ter capacidade de se adaptar a essas novidades. Essa teoria explica a dinâmica de adaptação por meio dos processos de: A) Assimilação e condicionamento; B) Assimilação e estrutura cognitiva; C) Assimilação e acomodação; D) Assimilação e condicionantes externos; E) Assimilação e adaptação.','C',17,'active',false,false,null,'Conferida contra a foto original da prova (pág. 17) e contra o gabarito oficial Fundape de 22/12/2018.'),
(50,'Pedagogia','Consoante às ideias de Lev Vygotsky, a zona de desenvolvimento ____ refere-se ao que a criança, hoje, somente consegue realizar com auxílio de alguém e, mais adiante, ela conseguirá realizar sozinha. Assinale a opção que preenche corretamente a lacuna: A) Proximal; B) Amostral; C) Conceitual; D) Natural; E) Cognitivo.','A',17,'active',false,false,null,'Conferida contra a foto original da prova (pág. 17) e contra o gabarito oficial Fundape de 22/12/2018.')
)
insert into public.official_exam_questions (
  question_source_id, answer_key_source_id, syllabus_topic_id,
  contest_name, exam_year, career_name, exam_board,
  item_number, subject, question_text, raw_extraction, official_answer, source_page,
  content_status, legal_review_required, context_review_required, legal_basis, review_note
)
select
  sources.prova_id, sources.gabarito_id, topics.topic_id,
  'Prefeitura de Feijó', 2018, 'Professor - Licenciatura Plena - Pedagogo', 'Fundape',
  imported.item_number, imported.subject, imported.question_text, imported.question_text,
  imported.official_answer, imported.source_page,
  imported.content_status, imported.legal_review_required, imported.context_review_required,
  case imported.legal_basis_url
    when 'cf' then jsonb_build_array(jsonb_build_object('title','Constituição Federal de 1988','url','https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm'))
    when 'eca' then jsonb_build_array(jsonb_build_object('title','Lei nº 8.069/1990 - Estatuto da Criança e do Adolescente','url','https://www.planalto.gov.br/ccivil_03/leis/l8069.htm'))
    else '[]'::jsonb
  end,
  imported.review_note
from imported
cross join sources
join topics on topics.discipline = imported.subject
on conflict (contest_name, exam_year, item_number) do update set
  subject = excluded.subject,
  question_text = excluded.question_text,
  raw_extraction = excluded.raw_extraction,
  official_answer = excluded.official_answer,
  source_page = excluded.source_page,
  content_status = excluded.content_status,
  legal_review_required = excluded.legal_review_required,
  context_review_required = excluded.context_review_required,
  legal_basis = excluded.legal_basis,
  review_note = excluded.review_note,
  law_version_checked_at = case when excluded.legal_review_required then now() else public.official_exam_questions.law_version_checked_at end,
  verified_at = now();
