-- Import of PF 2021 official exam items for the NEW career "Delegado de
-- Polícia Federal" (Edital nº 1 - DGP/PF, de 15 de janeiro de 2021,
-- CONCURSO PÚBLICO APLICAÇÃO: 2021, banca CEBRASPE). This exam is a
-- different career booklet from the "Agente de Polícia Federal" 2021 exam
-- already imported by 20260926050000 (and repaired by 20260927080000).
--
-- Source material read verbatim from Google Drive:
--   - Prova: CARGO_1_DELEGADO_DE_POLCIA_FEDERAL.pdf (fileId
--     1esMINWul7kGQsxkeXE50W-83ZpEBVVC9) - full 120-item CEBRASPE Certo/Errado
--     objective test, cover states "CARGO 1_DELEGADO DE POLÍCIA FEDERAL".
--   - Gabarito: GAB_DEFINITIVO_MATRIZ_577_PF_001_00.pdf (fileId
--     1EGBBNJzr0C3zBcuLK_BwVQqChwp7izjc) - explicitly labeled
--     "CARGO: DELEGADO DE POLÍCIA FEDERAL", Matriz_577_PF_001_00. This is the
--     matriz actually used: the other two matrizes read for comparison,
--     Matriz_577_PF_002_00 (fileId 1Q-1-D7711ji9JYtGanYX2S8Ir8FkUdSj) and
--     Matriz_577_PF_003_00 (fileId 1NPqhTeEj6HOw3867iU4kezMup5r19iOc), are
--     explicitly labeled "CARGO: AGENTE DE POLÍCIA FEDERAL" and
--     "CARGO: ESCRIVÃO DE POLÍCIA FEDERAL" respectively and were NOT used.
--     Matriz 002 (Agente) is byte-for-byte identical in its C/E/X sequence to
--     what 20260926050000/20260927080000 already imported for Agente 2021,
--     confirming the cargo labels on these gabarito PDFs are reliable and
--     that Matriz 001 (Delegado) is the correct source for this migration.
--
-- Root schema fix (mirrors the precedent set by
-- 20260927080000_fix_pf_prf_2021_collision.sql): the unique constraint
-- currently on official_exam_questions is
-- official_exam_questions_contest_year_item_key = (contest_name,exam_year,
-- item_number), set by 20260927000500_widen_exam_question_unique_key.sql.
-- That is not enough to distinguish this import: "Delegado de Polícia
-- Federal" and "Agente de Polícia Federal" share contest_name='Polícia
-- Federal' and exam_year=2021, and both have item_number 1-120, so without
-- career_name in the key this insert would silently collide with (or
-- overwrite) the existing Agente rows exactly like the PRF/DEPEN collision
-- previously did. This migration widens the constraint to include
-- career_name BEFORE inserting, and the insert's own ON CONFLICT target
-- matches the new, fully-distinguishing key.
alter table public.official_exam_questions
  drop constraint if exists official_exam_questions_contest_year_item_key;
alter table public.official_exam_questions
  drop constraint if exists official_exam_questions_contest_career_year_item_key;
alter table public.official_exam_questions
  add constraint official_exam_questions_contest_career_year_item_key
  unique (contest_name,career_name,exam_year,item_number);

-- Content sources for this specific cargo's booklet and gabarito matriz.
insert into public.content_sources (source_type,title,issuer,url,status,notes) values
('outro','Prova objetiva PF - Delegado - 2021','Polícia Federal / CEBRASPE','https://www.gov.br/pf/pt-br/acesso-a-informacao/servidores/concursos/provas-e-gabaritos-de-concursos-anteriores/concurso-carreira-policial-2021/delegado-de-policia-federal/prova_cargo_1_delegado_de_polcia_federal.pdf/view','vigente','Caderno oficial usado para extração auditável de itens (Google Drive fileId 1esMINWul7kGQsxkeXE50W-83ZpEBVVC9, texto lido verbatim nesta sessão).'),
('outro','Gabarito definitivo PF - Delegado - 2021','Polícia Federal / CEBRASPE','https://www.gov.br/pf/pt-br/acesso-a-informacao/servidores/concursos/provas-e-gabaritos-de-concursos-anteriores/concurso-carreira-policial-2021/delegado-de-policia-federal/gab_definitivo_dpf.pdf/view','vigente','Gabarito oficial definitivo Matriz_577_PF_001_00, explicitamente rotulado CARGO: DELEGADO DE POLICIA FEDERAL (Google Drive fileId 1EGBBNJzr0C3zBcuLK_BwVQqChwp7izjc); X identifica item anulado.')
on conflict (url) do update set checked_at=now(),status=excluded.status,notes=excluded.notes;

-- New syllabus edition for this career (distinct from the existing Agente
-- 2021 edition row).
insert into public.syllabus_editions (contest_name,role_name,contest_year)
select 'Polícia Federal','Delegado de Polícia Federal',2021
where not exists (
  select 1 from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Delegado de Polícia Federal' and contest_year=2021
);

-- Discipline breakdown derived directly from reading the prova's own item
-- text (command blocks and subject matter), not guessed: Direito
-- Administrativo (1-15), Direito Constitucional (16-30), Direito Civil
-- (31-33, 37-39), Direito Processual Civil (34-36), Direito Internacional
-- (40-46), Legislação Penal Especial (47-51, 75-85), Direito Penal
-- (52-74), Direito Processual Penal (86-102), Criminologia (103-105),
-- Direito Previdenciário (106-113), Direito Financeiro (114-115), Direito
-- Tributário (116-120).
with edition as (
  select id from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Delegado de Polícia Federal' and contest_year=2021
)
insert into public.syllabus_topics (edition_id,block_name,discipline,topic_order,topic_text,content_status)
select edition.id,'Prova objetiva',d.discipline,1,d.topic_text,'current'
from edition cross join (values
  ('Direito Administrativo','Improbidade administrativa, responsabilidade civil do Estado, controle da administração pública, delegação de competência e regime jurídico dos servidores públicos civis federais (Lei nº 8.429/1992, Lei nº 9.784/1999, Lei nº 8.112/1990).'),
  ('Direito Constitucional','Sentidos e concepções de constituição, direitos e deveres fundamentais, Poder Judiciário, segurança pública, atribuições constitucionais da Polícia Federal e controle de constitucionalidade.'),
  ('Direito Civil','Domicílio, responsabilidade civil e sociedades empresárias (sociedade limitada e sociedade em comum).'),
  ('Direito Processual Civil','Jurisdição, competência e poder geral de cautela no processo civil.'),
  ('Direito Internacional','Extradição e a Lei nº 13.445/2017 (Lei de Migração); Convenção das Nações Unidas contra o Crime Organizado Transnacional (Convenção de Palermo) e seu Protocolo Adicional relativo ao tráfico de pessoas.'),
  ('Legislação Penal Especial','Crimes previstos em legislação especial, incluindo Lei de Abuso de Autoridade, Lei nº 9.613/1998 (lavagem de dinheiro), Lei nº 7.492/1986 (crimes contra o Sistema Financeiro Nacional) e Lei nº 8.137/1990 (crimes contra a ordem tributária, econômica e relações de consumo).'),
  ('Direito Penal','Parte geral e parte especial do Código Penal: teoria geral do delito, teoria da pena, crimes contra a administração pública, crimes contra a fé pública.'),
  ('Direito Processual Penal','Prisão em flagrante e prisão preventiva, competência criminal, prova criminal, busca domiciliar, colaboração premiada e ação controlada.'),
  ('Criminologia','Prevenção primária, objetos da criminologia e controle social formal.'),
  ('Direito Previdenciário','Financiamento da seguridade social, segurado facultativo, contagem recíproca de tempo de contribuição e crimes previdenciários.'),
  ('Direito Financeiro','Emendas parlamentares impositivas, transferência especial constitucional e vinculação de receitas próprias dos estados.'),
  ('Direito Tributário','Princípios da anterioridade tributária, legislação tributária no CTN, imunidade tributária e suspensão da exigibilidade do crédito tributário.')
) d(discipline,topic_text)
on conflict (edition_id,discipline,topic_order) do update set topic_text=excluded.topic_text;

with imported(exam_year,item_number,subject,question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,context_review_required,review_note) as (values
(2021,1,$q$Direito Administrativo$q$,$q$É correto afirmar que, nessa situação, a conduta do agente que levou à condenação causou dano ao erário.$q$,$q$É correto afirmar que, nessa situação, a conduta do agente que levou à condenação causou dano ao erário.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,2,$q$Direito Administrativo$q$,$q$As penas de perda da função pública e de perda dos direitos políticos tivessem sido aplicadas somente podem ser efetivadas após o trânsito em julgado da sentença condenatória.$q$,$q$As penas de perda da função pública e de perda dos direitos políticos tivessem sido aplicadas somente podem ser efetivadas após o trânsito em julgado da sentença condenatória.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_001_00); não é exibido aos estudantes.$q$),
(2021,3,$q$Direito Administrativo$q$,$q$Eventual decretação de indisponibilidade de bens poderá recair sobre os bens adquiridos pelo referido agente antes da prática do ato ímprobo, devendo-se considerar, ainda, o valor de possível multa civil como sanção autônoma.$q$,$q$Eventual decretação de indisponibilidade de bens poderá recair sobre os bens adquiridos pelo referido agente antes da prática do ato ímprobo, devendo-se considerar, ainda, o valor de possível multa civil como sanção autônoma.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,4,$q$Direito Administrativo$q$,$q$É subjetiva a responsabilidade civil do Estado decorrente de conduta omissiva imprópria, sendo necessária a comprovação da culpa, do dano e do nexo de causalidade.$q$,$q$É subjetiva a responsabilidade civil do Estado decorrente de conduta omissiva imprópria, sendo necessária a comprovação da culpa, do dano e do nexo de causalidade.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_001_00); não é exibido aos estudantes.$q$),
(2021,5,$q$Direito Administrativo$q$,$q$Conforme a teoria do risco administrativo, uma empresa estatal dotada de personalidade jurídica de direito privado que exerça atividade econômica responderá objetivamente pelos danos que seus agentes, nessa qualidade, causarem a terceiros, resguardado o direito de regresso contra o causador do dano.$q$,$q$Conforme a teoria do risco administrativo, uma empresa estatal dotada de personalidade jurídica de direito privado que exerça atividade econômica responderá objetivamente pelos danos que seus agentes, nessa qualidade, causarem a terceiros, resguardado o direito de regresso contra o causador do dano.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,6,$q$Direito Administrativo$q$,$q$Apenas a Constituição Federal de 1988 pode prever modalidades de controle externo.$q$,$q$Apenas a Constituição Federal de 1988 pode prever modalidades de controle externo.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,7,$q$Direito Administrativo$q$,$q$O Poder Judiciário pode revogar atos praticados pelo Poder Executivo eivados de ilegalidade.$q$,$q$O Poder Judiciário pode revogar atos praticados pelo Poder Executivo eivados de ilegalidade.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,8,$q$Direito Administrativo$q$,$q$A reclamação para anular ato administrativo que confronte súmula vinculante é uma modalidade de controle externo da atividade administrativa.$q$,$q$A reclamação para anular ato administrativo que confronte súmula vinculante é uma modalidade de controle externo da atividade administrativa.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,9,$q$Direito Administrativo$q$,$q$Embora as comissões parlamentares de inquérito estejam, como uma modalidade de controle legislativo, aptas a investigar fatos determinados em prazos determinados, elas são desprovidas de poder condenatório.$q$,$q$Embora as comissões parlamentares de inquérito estejam, como uma modalidade de controle legislativo, aptas a investigar fatos determinados em prazos determinados, elas são desprovidas de poder condenatório.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,10,$q$Direito Administrativo$q$,$q$Nessa situação, o órgão delegante pertence necessariamente à administração pública federal, e não ao Poder Judiciário ou ao Poder Legislativo.$q$,$q$Nessa situação, o órgão delegante pertence necessariamente à administração pública federal, e não ao Poder Judiciário ou ao Poder Legislativo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,11,$q$Direito Administrativo$q$,$q$O órgão delegatário não precisa ser hierarquicamente subordinado ao delegante.$q$,$q$O órgão delegatário não precisa ser hierarquicamente subordinado ao delegante.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,12,$q$Direito Administrativo$q$,$q$O objeto do ato pode ser a edição de atos normativos.$q$,$q$O objeto do ato pode ser a edição de atos normativos.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,13,$q$Direito Administrativo$q$,$q$É correto afirmar que o cargo público em questão foi criado por lei.$q$,$q$É correto afirmar que o cargo público em questão foi criado por lei.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,14,$q$Direito Administrativo$q$,$q$Os aprovados no referido concurso público serão investidos em cargos em comissão mediante posse e somente adquirirão estabilidade se, após três anos de efetivo exercício, forem aprovados no estágio probatório.$q$,$q$Os aprovados no referido concurso público serão investidos em cargos em comissão mediante posse e somente adquirirão estabilidade se, após três anos de efetivo exercício, forem aprovados no estágio probatório.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,15,$q$Direito Administrativo$q$,$q$O concurso público seria desnecessário se a investidura se destinasse a emprego público na administração indireta federal.$q$,$q$O concurso público seria desnecessário se a investidura se destinasse a emprego público na administração indireta federal.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,16,$q$Direito Constitucional$q$,$q$A Constituição Federal brasileira pode ser considerada uma constituição-garantia, pois regulamenta, de forma analítica, os assuntos mais relevantes à formação, à destinação e ao funcionamento do Estado.$q$,$q$A Constituição Federal brasileira pode ser considerada uma constituição-garantia, pois regulamenta, de forma analítica, os assuntos mais relevantes à formação, à destinação e ao funcionamento do Estado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,17,$q$Direito Constitucional$q$,$q$Quanto ao objeto das constituições, são exemplos tradicionais o estabelecimento do modo de aquisição do poder e a forma de seu exercício.$q$,$q$Quanto ao objeto das constituições, são exemplos tradicionais o estabelecimento do modo de aquisição do poder e a forma de seu exercício.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,18,$q$Direito Constitucional$q$,$q$Sob a ótica da constituição política, um Estado pode ter uma constituição material sem que tenha uma constituição escrita que descreva a sua organização de poder.$q$,$q$Sob a ótica da constituição política, um Estado pode ter uma constituição material sem que tenha uma constituição escrita que descreva a sua organização de poder.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,19,$q$Direito Constitucional$q$,$q$A falta de estabelecimento penal adequado não autoriza a manutenção do condenado em regime prisional mais gravoso, podendo o juiz da execução autorizar a saída antecipada de sentenciados enquadrados nesse regime em razão da falta de vagas no estabelecimento penal.$q$,$q$A falta de estabelecimento penal adequado não autoriza a manutenção do condenado em regime prisional mais gravoso, podendo o juiz da execução autorizar a saída antecipada de sentenciados enquadrados nesse regime em razão da falta de vagas no estabelecimento penal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,20,$q$Direito Constitucional$q$,$q$O foro por prerrogativa de função estabelecido por uma constituição estadual prevalece sobre a competência constitucional do tribunal do júri.$q$,$q$O foro por prerrogativa de função estabelecido por uma constituição estadual prevalece sobre a competência constitucional do tribunal do júri.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,21,$q$Direito Constitucional$q$,$q$Como regra, a medida própria para a reparação de eventual abuso da liberdade de expressão é o direito de resposta ou a responsabilização civil, e não a supressão de texto jornalístico por meio de liminar.$q$,$q$Como regra, a medida própria para a reparação de eventual abuso da liberdade de expressão é o direito de resposta ou a responsabilização civil, e não a supressão de texto jornalístico por meio de liminar.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,22,$q$Direito Constitucional$q$,$q$Devido ao fato de a Força Nacional de Segurança Pública ser um programa de cooperação federativa ao qual podem aderir os entes federados, é inconstitucional o seu emprego em território de estado-membro sem a anuência de seu governador.$q$,$q$Devido ao fato de a Força Nacional de Segurança Pública ser um programa de cooperação federativa ao qual podem aderir os entes federados, é inconstitucional o seu emprego em território de estado-membro sem a anuência de seu governador.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,23,$q$Direito Constitucional$q$,$q$O confisco e a posterior reversão a fundo especial de bem apreendido em decorrência do tráfico ilícito de entorpecentes exigem prova de habitualidade e reiteração do uso do bem para a referida finalidade.$q$,$q$O confisco e a posterior reversão a fundo especial de bem apreendido em decorrência do tráfico ilícito de entorpecentes exigem prova de habitualidade e reiteração do uso do bem para a referida finalidade.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,24,$q$Direito Constitucional$q$,$q$Compete à Polícia Federal exercer as funções de polícia marítima.$q$,$q$Compete à Polícia Federal exercer as funções de polícia marítima.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,25,$q$Direito Constitucional$q$,$q$Cabe originariamente ao STF processar e julgar habeas data contra ato de ministro de estado.$q$,$q$Cabe originariamente ao STF processar e julgar habeas data contra ato de ministro de estado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,26,$q$Direito Constitucional$q$,$q$Cumpre ao STF julgar o recurso ordinário de habeas corpus decidido em única instância pelo Tribunal Superior Eleitoral (TSE).$q$,$q$Cumpre ao STF julgar o recurso ordinário de habeas corpus decidido em única instância pelo Tribunal Superior Eleitoral (TSE).$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,27,$q$Direito Constitucional$q$,$q$Compete à Advocacia-Geral da União exercer as atividades de consultoria e assessoramento jurídico à Polícia Federal.$q$,$q$Compete à Advocacia-Geral da União exercer as atividades de consultoria e assessoramento jurídico à Polícia Federal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,28,$q$Direito Constitucional$q$,$q$Conforme o conceito de bloco de constitucionalidade, há normas constitucionais não expressamente incluídas no texto da CF que podem servir como paradigma para o exercício de controle de constitucionalidade.$q$,$q$Conforme o conceito de bloco de constitucionalidade, há normas constitucionais não expressamente incluídas no texto da CF que podem servir como paradigma para o exercício de controle de constitucionalidade.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,29,$q$Direito Constitucional$q$,$q$Para o efeito do conhecimento da reclamação constitucional, o STF admite o uso da teoria da transcendência dos motivos determinantes das ações julgadas em sede de controle concentrado.$q$,$q$Para o efeito do conhecimento da reclamação constitucional, o STF admite o uso da teoria da transcendência dos motivos determinantes das ações julgadas em sede de controle concentrado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,30,$q$Direito Constitucional$q$,$q$É vedado ao Poder Legislativo efetuar o controle de constitucionalidade repressivo de normas em abstrato.$q$,$q$É vedado ao Poder Legislativo efetuar o controle de constitucionalidade repressivo de normas em abstrato.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,31,$q$Direito Civil$q$,$q$Se uma pessoa viver, de forma alternada, em diversas residências, qualquer uma delas poderá ser considerada seu domicílio.$q$,$q$Se uma pessoa viver, de forma alternada, em diversas residências, qualquer uma delas poderá ser considerada seu domicílio.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,32,$q$Direito Civil$q$,$q$Se um terceiro aproximar-se de um autor de um crime que estiver imobilizado pela polícia e acertá-lo com um tiro letal, estará configurada a responsabilidade objetiva do Estado.$q$,$q$Se um terceiro aproximar-se de um autor de um crime que estiver imobilizado pela polícia e acertá-lo com um tiro letal, estará configurada a responsabilidade objetiva do Estado.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,33,$q$Direito Civil$q$,$q$A dissolução de sociedade limitada constituída por prazo indeterminado deve ocorrer por consenso unânime dos sócios.$q$,$q$A dissolução de sociedade limitada constituída por prazo indeterminado deve ocorrer por consenso unânime dos sócios.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,34,$q$Direito Processual Civil$q$,$q$As características da jurisdição incluem substituir, no caso concreto, a vontade das partes pela vontade do juiz, o que, por sua vez, resolve a lide e promove a pacificação social.$q$,$q$As características da jurisdição incluem substituir, no caso concreto, a vontade das partes pela vontade do juiz, o que, por sua vez, resolve a lide e promove a pacificação social.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,35,$q$Direito Processual Civil$q$,$q$No curso de processo de ação de acidente de trabalho que tramite na justiça estadual, se a União intervier como interessada, o juiz deverá efetuar a remessa dos autos para a justiça federal.$q$,$q$No curso de processo de ação de acidente de trabalho que tramite na justiça estadual, se a União intervier como interessada, o juiz deverá efetuar a remessa dos autos para a justiça federal.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,36,$q$Direito Processual Civil$q$,$q$Caso haja fundado receio de que no curso da lide uma parte cause ao direito do réu lesão grave e de difícil reparação, o juiz poderá determinar medida provisória que julgue adequada.$q$,$q$Caso haja fundado receio de que no curso da lide uma parte cause ao direito do réu lesão grave e de difícil reparação, o juiz poderá determinar medida provisória que julgue adequada.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,37,$q$Direito Civil$q$,$q$Os sócios em questão respondem solidária e ilimitadamente com seu patrimônio pessoal pelas dívidas da sociedade.$q$,$q$Os sócios em questão respondem solidária e ilimitadamente com seu patrimônio pessoal pelas dívidas da sociedade.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,38,$q$Direito Civil$q$,$q$Nessa situação, para tentar superar a fase crítica, os sócios podem pedir a recuperação judicial da empresa.$q$,$q$Nessa situação, para tentar superar a fase crítica, os sócios podem pedir a recuperação judicial da empresa.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,39,$q$Direito Civil$q$,$q$Geraldo poderá pleitear que a execução de seu imóvel particular por dívidas da sociedade ocorra somente após a execução dos bens sociais.$q$,$q$Geraldo poderá pleitear que a execução de seu imóvel particular por dívidas da sociedade ocorra somente após a execução dos bens sociais.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,40,$q$Direito Internacional$q$,$q$Caso deseje, Luigi pode entregar-se ao Estado italiano por meio da extradição voluntária, procedimento que, por seu caráter simplificado e célere, torna desnecessário o pronunciamento prévio do STF.$q$,$q$Caso deseje, Luigi pode entregar-se ao Estado italiano por meio da extradição voluntária, procedimento que, por seu caráter simplificado e célere, torna desnecessário o pronunciamento prévio do STF.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,41,$q$Direito Internacional$q$,$q$A extradição de Luigi não poderá ser efetivada sem que a Itália assuma o compromisso de computar o tempo da prisão que tenha sido cumprido no Brasil em razão da decisão cautelar.$q$,$q$A extradição de Luigi não poderá ser efetivada sem que a Itália assuma o compromisso de computar o tempo da prisão que tenha sido cumprido no Brasil em razão da decisão cautelar.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,42,$q$Direito Internacional$q$,$q$O STF poderá, após a análise do caso, determinar que o extraditando responda ao processo de extradição em liberdade, além de impor medidas cautelares diversas da prisão, como a retenção do documento de viagem, até o julgamento definitivo da ação.$q$,$q$O STF poderá, após a análise do caso, determinar que o extraditando responda ao processo de extradição em liberdade, além de impor medidas cautelares diversas da prisão, como a retenção do documento de viagem, até o julgamento definitivo da ação.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,43,$q$Direito Internacional$q$,$q$A prisão cautelar poderá ser prorrogada até o julgamento final pela autoridade judiciária brasileira competente quanto à legalidade do requerimento estrangeiro, independentemente do momento de formalização do pedido de extradição feito pelo governo italiano ao governo brasileiro.$q$,$q$A prisão cautelar poderá ser prorrogada até o julgamento final pela autoridade judiciária brasileira competente quanto à legalidade do requerimento estrangeiro, independentemente do momento de formalização do pedido de extradição feito pelo governo italiano ao governo brasileiro.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,44,$q$Direito Internacional$q$,$q$Conforme entendimento do Superior Tribunal de Justiça, não é possível a homologação de sentença penal estrangeira que determine o perdimento de imóvel situado no Brasil por considerar que o bem seja produto de infrações previstas na Convenção de Palermo, como, por exemplo, o crime de lavagem de dinheiro.$q$,$q$Conforme entendimento do Superior Tribunal de Justiça, não é possível a homologação de sentença penal estrangeira que determine o perdimento de imóvel situado no Brasil por considerar que o bem seja produto de infrações previstas na Convenção de Palermo, como, por exemplo, o crime de lavagem de dinheiro.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,45,$q$Direito Internacional$q$,$q$Conforme o protocolo adicional à Convenção de Palermo, mesmo que não seja usada a força ou outras formas de coação para obter o consentimento, a transferência de uma pessoa com idade inferior a dezoito anos com o objetivo de explorá-la será considerada “tráfico de pessoas”.$q$,$q$Conforme o protocolo adicional à Convenção de Palermo, mesmo que não seja usada a força ou outras formas de coação para obter o consentimento, a transferência de uma pessoa com idade inferior a dezoito anos com o objetivo de explorá-la será considerada “tráfico de pessoas”.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,46,$q$Direito Internacional$q$,$q$A pobreza, o subdesenvolvimento e a desigualdade de oportunidades tornam as pessoas, especialmente as mulheres e as crianças, vulneráveis ao tráfico, razão por que devem os Estados-partes reforçar as medidas de combate e esses tipos de fatores sociais.$q$,$q$A pobreza, o subdesenvolvimento e a desigualdade de oportunidades tornam as pessoas, especialmente as mulheres e as crianças, vulneráveis ao tráfico, razão por que devem os Estados-partes reforçar as medidas de combate e esses tipos de fatores sociais.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,47,$q$Legislação Penal Especial$q$,$q$A importação de sementes de maconha em pequena quantidade é considerada conduta atípica.$q$,$q$A importação de sementes de maconha em pequena quantidade é considerada conduta atípica.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,48,$q$Legislação Penal Especial$q$,$q$A teoria do domínio do fato permite, isoladamente, que se faça uma acusação pela prática de crimes complexos, como o de sonegação fiscal, sem a descrição da conduta.$q$,$q$A teoria do domínio do fato permite, isoladamente, que se faça uma acusação pela prática de crimes complexos, como o de sonegação fiscal, sem a descrição da conduta.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,49,$q$Legislação Penal Especial$q$,$q$É conduta atípica o porte ilegal de arma de fogo de uso permitido com registro de cautela vencido.$q$,$q$É conduta atípica o porte ilegal de arma de fogo de uso permitido com registro de cautela vencido.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,50,$q$Legislação Penal Especial$q$,$q$A conduta de impedir ou dificultar a regeneração natural de florestas e demais formas de vegetação é delito de natureza permanente.$q$,$q$A conduta de impedir ou dificultar a regeneração natural de florestas e demais formas de vegetação é delito de natureza permanente.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,51,$q$Legislação Penal Especial$q$,$q$A antecipação, por delegado da Polícia Federal, por meio de rede social, da atribuição de culpa, antes de concluídas as apurações e formalizada a acusação, caracteriza crime previsto na Lei de Abuso de Autoridade.$q$,$q$A antecipação, por delegado da Polícia Federal, por meio de rede social, da atribuição de culpa, antes de concluídas as apurações e formalizada a acusação, caracteriza crime previsto na Lei de Abuso de Autoridade.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,52,$q$Direito Penal$q$,$q$Em se tratando do crime de falsidade ideológica, o prazo prescricional se reinicia com a eventual reiteração de seus efeitos.$q$,$q$Em se tratando do crime de falsidade ideológica, o prazo prescricional se reinicia com a eventual reiteração de seus efeitos.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,53,$q$Direito Penal$q$,$q$O furto qualificado impede o reconhecimento do princípio da insignificância.$q$,$q$O furto qualificado impede o reconhecimento do princípio da insignificância.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_001_00); não é exibido aos estudantes.$q$),
(2021,54,$q$Direito Penal$q$,$q$O crime de redução à condição análoga à de escravo pode ocorrer independentemente da restrição à liberdade de locomoção do trabalhador.$q$,$q$O crime de redução à condição análoga à de escravo pode ocorrer independentemente da restrição à liberdade de locomoção do trabalhador.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,55,$q$Direito Penal$q$,$q$A adoção de sistema de vigilância realizado por monitoramento eletrônico, por si só, não torna impossível a configuração do crime de furto.$q$,$q$A adoção de sistema de vigilância realizado por monitoramento eletrônico, por si só, não torna impossível a configuração do crime de furto.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,56,$q$Direito Penal$q$,$q$Em se tratando de crime de extorsão, não se admite tentativa.$q$,$q$Em se tratando de crime de extorsão, não se admite tentativa.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,57,$q$Direito Penal$q$,$q$Segundo o Superior Tribunal de Justiça, a determinação da fixação da medida de segurança de internação em hospital de custódia ou em tratamento ambulatorial deve ser vinculada à gravidade do delito perpetrado.$q$,$q$Segundo o Superior Tribunal de Justiça, a determinação da fixação da medida de segurança de internação em hospital de custódia ou em tratamento ambulatorial deve ser vinculada à gravidade do delito perpetrado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,58,$q$Direito Penal$q$,$q$O acórdão confirmatório da condenação interrompe a prescrição.$q$,$q$O acórdão confirmatório da condenação interrompe a prescrição.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,59,$q$Direito Penal$q$,$q$O inadimplemento da pena de multa não obsta a extinção da punibilidade do apenado.$q$,$q$O inadimplemento da pena de multa não obsta a extinção da punibilidade do apenado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,60,$q$Direito Penal$q$,$q$Na hipótese da prática de furto a residência, se a vítima não se encontrava no local e os autores desconheciam o fato de que ela era idosa, não se aplica a agravante relativa à vítima ser idosa.$q$,$q$Na hipótese da prática de furto a residência, se a vítima não se encontrava no local e os autores desconheciam o fato de que ela era idosa, não se aplica a agravante relativa à vítima ser idosa.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,61,$q$Direito Penal$q$,$q$A consciência atual da ilicitude é elemento do dolo, conforme a teoria finalista da ação.$q$,$q$A consciência atual da ilicitude é elemento do dolo, conforme a teoria finalista da ação.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,62,$q$Direito Penal$q$,$q$A conduta humana voluntária é irrelevante para a configuração do crime culposo.$q$,$q$A conduta humana voluntária é irrelevante para a configuração do crime culposo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,63,$q$Direito Penal$q$,$q$A imputabilidade é a possibilidade de se atribuir a alguém a responsabilidade pela prática de uma infração penal.$q$,$q$A imputabilidade é a possibilidade de se atribuir a alguém a responsabilidade pela prática de uma infração penal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,64,$q$Direito Penal$q$,$q$O dolo eventual é incompatível com a tentativa.$q$,$q$O dolo eventual é incompatível com a tentativa.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,65,$q$Direito Penal$q$,$q$Conforme a autoria de escritório, tanto o agente que dá a ordem como o que cumpre respondem pelo tipo penal.$q$,$q$Conforme a autoria de escritório, tanto o agente que dá a ordem como o que cumpre respondem pelo tipo penal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,66,$q$Direito Penal$q$,$q$Um médico de hospital particular conveniado ao Sistema Único de Saúde pode ser equiparado a funcionário público, para fins de responsabilização penal.$q$,$q$Um médico de hospital particular conveniado ao Sistema Único de Saúde pode ser equiparado a funcionário público, para fins de responsabilização penal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,67,$q$Direito Penal$q$,$q$Na hipótese de crime de peculato doloso, o ressarcimento do dano exclui a punibilidade.$q$,$q$Na hipótese de crime de peculato doloso, o ressarcimento do dano exclui a punibilidade.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,68,$q$Direito Penal$q$,$q$O crime de facilitação de contrabando e descaminho se consuma com a efetiva facilitação, não sendo necessária a consumação do contrabando ou descaminho.$q$,$q$O crime de facilitação de contrabando e descaminho se consuma com a efetiva facilitação, não sendo necessária a consumação do contrabando ou descaminho.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,69,$q$Direito Penal$q$,$q$A fuga do réu após a ordem de parada dos policiais para abordagem configura crime de desobediência.$q$,$q$A fuga do réu após a ordem de parada dos policiais para abordagem configura crime de desobediência.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,70,$q$Direito Penal$q$,$q$O pagamento do tributo devido extingue a punibilidade do crime de descaminho.$q$,$q$O pagamento do tributo devido extingue a punibilidade do crime de descaminho.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,71,$q$Direito Penal$q$,$q$O crime de moeda falsa é incompatível com o instituto do arrependimento posterior.$q$,$q$O crime de moeda falsa é incompatível com o instituto do arrependimento posterior.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,72,$q$Direito Penal$q$,$q$O indivíduo foragido do sistema carcerário que utiliza carteira de identidade falsa perante a autoridade policial para evitar ser preso pratica o crime de falsa identidade.$q$,$q$O indivíduo foragido do sistema carcerário que utiliza carteira de identidade falsa perante a autoridade policial para evitar ser preso pratica o crime de falsa identidade.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,73,$q$Direito Penal$q$,$q$O advogado de réu pode vir a responder pelo crime de falso testemunho, na hipótese de induzir testemunha a prestar determinado depoimento.$q$,$q$O advogado de réu pode vir a responder pelo crime de falso testemunho, na hipótese de induzir testemunha a prestar determinado depoimento.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,74,$q$Direito Penal$q$,$q$O funcionário público que faz afirmação falsa em procedimentos de autorização ou de licenciamento ambiental não responde por falsidade ideológica, crime previsto no Código Penal, mas por crime específico previsto na lei de crimes ambientais (Lei n.º 9.605/1998).$q$,$q$O funcionário público que faz afirmação falsa em procedimentos de autorização ou de licenciamento ambiental não responde por falsidade ideológica, crime previsto no Código Penal, mas por crime específico previsto na lei de crimes ambientais (Lei n.º 9.605/1998).$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,75,$q$Legislação Penal Especial$q$,$q$Ficarão suspensos o processo e o curso do prazo prescricional do acusado citado por edital que não comparecer nem constituir advogado.$q$,$q$Ficarão suspensos o processo e o curso do prazo prescricional do acusado citado por edital que não comparecer nem constituir advogado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,76,$q$Legislação Penal Especial$q$,$q$É requisito específico da denúncia a existência de indícios suficientes da ocorrência do crime antecedente cuja punibilidade não esteja extinta.$q$,$q$É requisito específico da denúncia a existência de indícios suficientes da ocorrência do crime antecedente cuja punibilidade não esteja extinta.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,77,$q$Legislação Penal Especial$q$,$q$No que se refere ao investigado, a autoridade policial terá acesso a dados cadastrais relativos à qualificação pessoal, à filiação e ao endereço mantidos nos bancos de dados da justiça eleitoral, de empresas telefônicas, de instituições financeiras, de provedores de Internet e de administradoras de cartão de crédito, independentemente de autorização judicial.$q$,$q$No que se refere ao investigado, a autoridade policial terá acesso a dados cadastrais relativos à qualificação pessoal, à filiação e ao endereço mantidos nos bancos de dados da justiça eleitoral, de empresas telefônicas, de instituições financeiras, de provedores de Internet e de administradoras de cartão de crédito, independentemente de autorização judicial.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,78,$q$Legislação Penal Especial$q$,$q$Ouvido o Ministério Público, ordens de prisão ou medidas assecuratórias de bens poderão ser suspensas pelo juiz quando a execução imediata dessas ações puder comprometer as investigações.$q$,$q$Ouvido o Ministério Público, ordens de prisão ou medidas assecuratórias de bens poderão ser suspensas pelo juiz quando a execução imediata dessas ações puder comprometer as investigações.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,79,$q$Legislação Penal Especial$q$,$q$O crime de lavagem de dinheiro está, consoante a lei, equiparado ao crime hediondo.$q$,$q$O crime de lavagem de dinheiro está, consoante a lei, equiparado ao crime hediondo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,80,$q$Legislação Penal Especial$q$,$q$É vedada a intercepção de comunicações telefônicas no caso de crime de operação de câmbio não autorizada com o objetivo de promover a evasão de divisas, em decorrência das penas cominadas para o crime.$q$,$q$É vedada a intercepção de comunicações telefônicas no caso de crime de operação de câmbio não autorizada com o objetivo de promover a evasão de divisas, em decorrência das penas cominadas para o crime.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,81,$q$Legislação Penal Especial$q$,$q$Todos os crimes cometidos contra o sistema financeiro nacional que estiverem previstos na Lei n.º 7.492/1986 são de competência da justiça federal.$q$,$q$Todos os crimes cometidos contra o sistema financeiro nacional que estiverem previstos na Lei n.º 7.492/1986 são de competência da justiça federal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,82,$q$Legislação Penal Especial$q$,$q$A gestão fraudulenta e a gestão temerária de instituição financeira são crimes afiançáveis.$q$,$q$A gestão fraudulenta e a gestão temerária de instituição financeira são crimes afiançáveis.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,83,$q$Legislação Penal Especial$q$,$q$Os crimes contra a ordem tributária, a ordem econômica e as relações de consumo previstos na Lei n.º 8.137/1990 submetem-se à ação penal pública incondicionada.$q$,$q$Os crimes contra a ordem tributária, a ordem econômica e as relações de consumo previstos na Lei n.º 8.137/1990 submetem-se à ação penal pública incondicionada.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,84,$q$Legislação Penal Especial$q$,$q$A Súmula Vinculante n.º 24 do STF — que dispõe que não se tipifica crime material contra a ordem tributária, conforme previsto no art. 1.º, incisos I a IV, da Lei n.º 8.137/1990, antes do lançamento definitivo do tributo — não pode ser aplicada a fatos anteriores a sua edição.$q$,$q$A Súmula Vinculante n.º 24 do STF — que dispõe que não se tipifica crime material contra a ordem tributária, conforme previsto no art. 1.º, incisos I a IV, da Lei n.º 8.137/1990, antes do lançamento definitivo do tributo — não pode ser aplicada a fatos anteriores a sua edição.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,85,$q$Legislação Penal Especial$q$,$q$A jurisprudência dos tribunais superiores não admite mitigação da Súmula Vinculante n.º 24 do STF.$q$,$q$A jurisprudência dos tribunais superiores não admite mitigação da Súmula Vinculante n.º 24 do STF.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,86,$q$Direito Processual Penal$q$,$q$Em se tratando do crime praticado por José, admite-se a decretação de prisão preventiva.$q$,$q$Em se tratando do crime praticado por José, admite-se a decretação de prisão preventiva.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,87,$q$Direito Processual Penal$q$,$q$Nessa situação, a primeira decisão do juiz foi regular, já que os tribunais superiores têm admitido, de ofício, a conversão da prisão em flagrante em prisão preventiva durante a audiência de custódia.$q$,$q$Nessa situação, a primeira decisão do juiz foi regular, já que os tribunais superiores têm admitido, de ofício, a conversão da prisão em flagrante em prisão preventiva durante a audiência de custódia.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,88,$q$Direito Processual Penal$q$,$q$A decisão do juiz, que relaxou a prisão por entender que a conduta de José havia sido atípica, não faz coisa julgada.$q$,$q$A decisão do juiz, que relaxou a prisão por entender que a conduta de José havia sido atípica, não faz coisa julgada.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,89,$q$Direito Processual Penal$q$,$q$Devido à pena prevista para o crime praticado por José, delegados ficam vedados a arbitrar a fiança.$q$,$q$Devido à pena prevista para o crime praticado por José, delegados ficam vedados a arbitrar a fiança.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,90,$q$Direito Processual Penal$q$,$q$Compete à justiça federal processar e julgar o crime de redução à condição análoga à de escravo.$q$,$q$Compete à justiça federal processar e julgar o crime de redução à condição análoga à de escravo.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,91,$q$Direito Processual Penal$q$,$q$Em regra, cabe à justiça federal processar e julgar os crimes contra o meio ambiente.$q$,$q$Em regra, cabe à justiça federal processar e julgar os crimes contra o meio ambiente.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,92,$q$Direito Processual Penal$q$,$q$Compete à justiça federal processar e julgar o crime de disponibilizar ou adquirir material pornográfico que envolva criança ou adolescente praticado por meio de troca de informações privadas, como, por exemplo, conversas via aplicativos de mensagens ou chat nas redes sociais.$q$,$q$Compete à justiça federal processar e julgar o crime de disponibilizar ou adquirir material pornográfico que envolva criança ou adolescente praticado por meio de troca de informações privadas, como, por exemplo, conversas via aplicativos de mensagens ou chat nas redes sociais.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,93,$q$Direito Processual Penal$q$,$q$A confissão do acusado não dispensa a realização do exame de corpo de delito nos casos de crimes não transeuntes.$q$,$q$A confissão do acusado não dispensa a realização do exame de corpo de delito nos casos de crimes não transeuntes.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,94,$q$Direito Processual Penal$q$,$q$Na ausência de um perito oficial, a perícia pode ser feita por duas pessoas idôneas portadoras de curso superior, preferencialmente com habilitação técnica relacionada à natureza do exame.$q$,$q$Na ausência de um perito oficial, a perícia pode ser feita por duas pessoas idôneas portadoras de curso superior, preferencialmente com habilitação técnica relacionada à natureza do exame.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,95,$q$Direito Processual Penal$q$,$q$No que se refere ao procedimento de reconhecimento, a pessoa que será reconhecida deverá, se possível, ser posicionada ao lado de outras pessoas com semelhanças físicas, sem número definido de indivíduos, para que, em seguida, a pessoa que tiver de fazer o reconhecimento seja convidada a apontá-la.$q$,$q$No que se refere ao procedimento de reconhecimento, a pessoa que será reconhecida deverá, se possível, ser posicionada ao lado de outras pessoas com semelhanças físicas, sem número definido de indivíduos, para que, em seguida, a pessoa que tiver de fazer o reconhecimento seja convidada a apontá-la.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,96,$q$Direito Processual Penal$q$,$q$É nula a decisão judicial que indefere a oitiva das vítimas do crime arroladas pela defesa.$q$,$q$É nula a decisão judicial que indefere a oitiva das vítimas do crime arroladas pela defesa.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,97,$q$Direito Processual Penal$q$,$q$A ordem judicial de busca domiciliar autoriza o acesso aos dados armazenados no celular apreendido pela autoridade policial.$q$,$q$A ordem judicial de busca domiciliar autoriza o acesso aos dados armazenados no celular apreendido pela autoridade policial.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,98,$q$Direito Processual Penal$q$,$q$A substância apreendida deve ser submetida à perícia para a elaboração do laudo de constatação provisório da natureza e da quantidade da droga, análise que deve ser realizada por perito, o qual, por sua vez, ficará impedido de elaborar o laudo definitivo.$q$,$q$A substância apreendida deve ser submetida à perícia para a elaboração do laudo de constatação provisório da natureza e da quantidade da droga, análise que deve ser realizada por perito, o qual, por sua vez, ficará impedido de elaborar o laudo definitivo.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,99,$q$Direito Processual Penal$q$,$q$A ação controlada na investigação da organização criminosa independe de prévia autorização judicial e parecer ministerial.$q$,$q$A ação controlada na investigação da organização criminosa independe de prévia autorização judicial e parecer ministerial.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,100,$q$Direito Processual Penal$q$,$q$De acordo com o Supremo Tribunal Federal, a entrevista informalmente conduzida pelo delegado durante a realização da busca domiciliar viola as garantias individuais dos presos.$q$,$q$De acordo com o Supremo Tribunal Federal, a entrevista informalmente conduzida pelo delegado durante a realização da busca domiciliar viola as garantias individuais dos presos.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,101,$q$Direito Processual Penal$q$,$q$A busca domiciliar fundamentada em notícia anônima foi válida em razão da descoberta da situação que culminou em flagrante delito.$q$,$q$A busca domiciliar fundamentada em notícia anônima foi válida em razão da descoberta da situação que culminou em flagrante delito.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,102,$q$Direito Processual Penal$q$,$q$Devido à colaboração relevante do preso para a identificação da organização criminosa nos autos do inquérito policial, o delegado, com a manifestação do Ministério Público, poderá representar ao juiz pela concessão de perdão judicial.$q$,$q$Devido à colaboração relevante do preso para a identificação da organização criminosa nos autos do inquérito policial, o delegado, com a manifestação do Ministério Público, poderá representar ao juiz pela concessão de perdão judicial.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,103,$q$Criminologia$q$,$q$Prevenção primária consiste na implementação de medidas sociais indiretas de prevenção para evitar que fatores exógenos sirvam como estímulo à prática delituosa.$q$,$q$Prevenção primária consiste na implementação de medidas sociais indiretas de prevenção para evitar que fatores exógenos sirvam como estímulo à prática delituosa.$q$,'C',1,'under_review',false,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,104,$q$Criminologia$q$,$q$Os objetos da criminologia são o delinquente, a vítima, o controle social e a justiça criminal.$q$,$q$Os objetos da criminologia são o delinquente, a vítima, o controle social e a justiça criminal.$q$,'E',1,'under_review',false,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,105,$q$Criminologia$q$,$q$A polícia, o Poder Judiciário e o sistema penitenciário exercem o controle social formal.$q$,$q$A polícia, o Poder Judiciário e o sistema penitenciário exercem o controle social formal.$q$,'C',1,'under_review',false,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,106,$q$Direito Previdenciário$q$,$q$As contribuições sociais do empregador compõem o financiamento da seguridade social e são incidentes sobre a folha de salários, o faturamento e o lucro.$q$,$q$As contribuições sociais do empregador compõem o financiamento da seguridade social e são incidentes sobre a folha de salários, o faturamento e o lucro.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,107,$q$Direito Previdenciário$q$,$q$Para a execução do orçamento da seguridade social, o tesouro nacional deve repassar mensalmente os recursos referentes às contribuições sociais incidentes sobre a receita de concursos de prognósticos.$q$,$q$Para a execução do orçamento da seguridade social, o tesouro nacional deve repassar mensalmente os recursos referentes às contribuições sociais incidentes sobre a receita de concursos de prognósticos.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,108,$q$Direito Previdenciário$q$,$q$É correto afirmar que, atualmente, o servidor em questão é segurado facultativo da previdência social.$q$,$q$É correto afirmar que, atualmente, o servidor em questão é segurado facultativo da previdência social.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,109,$q$Direito Previdenciário$q$,$q$Caso venha a ser aprovado no concurso almejado, esse servidor poderá requerer a contagem recíproca do tempo de contribuição.$q$,$q$Caso venha a ser aprovado no concurso almejado, esse servidor poderá requerer a contagem recíproca do tempo de contribuição.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,110,$q$Direito Previdenciário$q$,$q$Caso a aposentadoria de Luzia seja futuramente deferida, será possível a acumulação desse benefício com o auxílio-acidente.$q$,$q$Caso a aposentadoria de Luzia seja futuramente deferida, será possível a acumulação desse benefício com o auxílio-acidente.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,111,$q$Direito Previdenciário$q$,$q$Se for comprovado o ilícito criminal, Luzia poderá responder pela prática do crime de apropriação indébita previdenciária.$q$,$q$Se for comprovado o ilícito criminal, Luzia poderá responder pela prática do crime de apropriação indébita previdenciária.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,112,$q$Direito Previdenciário$q$,$q$O crime configurado na situação narrada é crime próprio, de modo que Luzia só poderá ser penalizada na esfera criminal se ficar comprovada sua coautoria ou coparticipação no referido crime.$q$,$q$O crime configurado na situação narrada é crime próprio, de modo que Luzia só poderá ser penalizada na esfera criminal se ficar comprovada sua coautoria ou coparticipação no referido crime.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Matriz_577_PF_001_00); não é exibido aos estudantes.$q$),
(2021,113,$q$Direito Previdenciário$q$,$q$O limite de prazo para que Luzia ajuizasse a ação contra o indeferimento administrativo era, de fato, o ano de 2015, já que, por exemplo, se ela tivesse postergado para o ano de 2021, haveria decadência do direito.$q$,$q$O limite de prazo para que Luzia ajuizasse a ação contra o indeferimento administrativo era, de fato, o ano de 2015, já que, por exemplo, se ela tivesse postergado para o ano de 2021, haveria decadência do direito.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,114,$q$Direito Financeiro$q$,$q$A possibilidade de a emenda parlamentar impositiva alocar recursos a estados e municípios, por meio da transferência especial constitucional, a qual permite o repasse direto sem convênio, só é cabível no caso de emenda individual, e não de emenda de bancada.$q$,$q$A possibilidade de a emenda parlamentar impositiva alocar recursos a estados e municípios, por meio da transferência especial constitucional, a qual permite o repasse direto sem convênio, só é cabível no caso de emenda individual, e não de emenda de bancada.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,115,$q$Direito Financeiro$q$,$q$É permitida aos estados a vinculação de receitas próprias geradas pela cobrança do IPVA para a prestação de contragarantia à União.$q$,$q$É permitida aos estados a vinculação de receitas próprias geradas pela cobrança do IPVA para a prestação de contragarantia à União.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,116,$q$Direito Tributário$q$,$q$Para a instituição de novas taxas, deve-se observar tanto a anterioridade anual quanto a anterioridade nonagesimal.$q$,$q$Para a instituição de novas taxas, deve-se observar tanto a anterioridade anual quanto a anterioridade nonagesimal.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,117,$q$Direito Tributário$q$,$q$De acordo com o Código Tributário Nacional, a legislação tributária restringe-se a leis, tratados e convenções internacionais, sendo os decretos e demais atos normativos expedidos por autoridades administrativas considerados normas complementares.$q$,$q$De acordo com o Código Tributário Nacional, a legislação tributária restringe-se a leis, tratados e convenções internacionais, sendo os decretos e demais atos normativos expedidos por autoridades administrativas considerados normas complementares.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,118,$q$Direito Tributário$q$,$q$De acordo com o STF, a imunidade tributária aplicável aos livros, quanto ao imposto de importação, alcança os leitores de livros eletrônicos apenas se estes não possuírem funcionalidades acessórias.$q$,$q$De acordo com o STF, a imunidade tributária aplicável aos livros, quanto ao imposto de importação, alcança os leitores de livros eletrônicos apenas se estes não possuírem funcionalidades acessórias.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,119,$q$Direito Tributário$q$,$q$O parcelamento e a moratória são hipóteses de suspensão da exigibilidade do crédito tributário.$q$,$q$O parcelamento e a moratória são hipóteses de suspensão da exigibilidade do crédito tributário.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$),
(2021,120,$q$Direito Tributário$q$,$q$No caso de o imposto de renda de pessoa jurídica ser tributado com base no lucro real, a apuração dos seus resultados deve ser trimestral.$q$,$q$No caso de o imposto de renda de pessoa jurídica ser tributado com base no lucro real, a apuração dos seus resultados deve ser trimestral.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas Cargo 1 - Delegado de Polícia Federal (PF 2021); gabarito conferido em Matriz_577_PF_001_00 (cargo Delegado). Base legal ainda não conferida individualmente no planalto.gov.br — aguardando revisão item a item antes de content_status=active.$q$)
), editions as (
  select id,contest_year from public.syllabus_editions
  where contest_name='Polícia Federal' and role_name='Delegado de Polícia Federal' and contest_year=2021
), resolved as (
  select imported.*, question_source.id question_source_id, answer_source.id answer_key_source_id, topic.id syllabus_topic_id
  from imported
  join editions on editions.contest_year=imported.exam_year
  join public.syllabus_topics topic on topic.edition_id=editions.id and topic.discipline=imported.subject and topic.topic_order=1
  join public.content_sources question_source on question_source.title='Prova objetiva PF - Delegado - ' || imported.exam_year
  join public.content_sources answer_source on answer_source.title='Gabarito definitivo PF - Delegado - ' || imported.exam_year
)
insert into public.official_exam_questions (
  question_source_id,answer_key_source_id,syllabus_topic_id,contest_name,career_name,exam_board,exam_year,item_number,subject,
  question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,
  context_review_required,review_note
)
select question_source_id,answer_key_source_id,syllabus_topic_id,'Polícia Federal','Delegado de Polícia Federal','CEBRASPE',exam_year,item_number,subject,
  question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,
  context_review_required,review_note
from resolved
on conflict (contest_name,career_name,exam_year,item_number) do nothing;
