-- Correção da chave oficial (official_answer) conferida contra os PDFs de gabarito definitivo do CEBRASPE.
-- Comparação item a item em 27/09/2026: PF 2014/2018/2021/2025 sem divergência; PRF 2019 (26), PRF 2021 (11) e DEPEN 2021 (1) corrigidos.
-- Itens que passam a X viram 'annulled'; itens que eram X e não são voltam a 'under_review'.

update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=11 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=14 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=16 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=17 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=19 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=25 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=38 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=52 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=55 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=59 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=60 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=64 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha X; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=71 and official_answer='X';
-- @@
update public.official_exam_questions set official_answer='X', content_status=case when 'X'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz X.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=73 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=74 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='X', content_status=case when 'X'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz X.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=75 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha X; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=76 and official_answer='X';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=79 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=80 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=81 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=84 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=85 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=86 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=98 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=102 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2019 (MATRIZ_440_PRF_001_00)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2019 and item_number=119 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=27 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=34 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=46 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha X; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=97 and official_answer='X';
-- @@
update public.official_exam_questions set official_answer='X', content_status=case when 'X'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz X.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=99 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=101 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=102 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=103 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=104 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz E.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=105 and official_answer='C';
-- @@
update public.official_exam_questions set official_answer='C', content_status=case when 'C'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha E; o gabarito definitivo (PRF 2021 (578_PRF_001_01 e 578_PRF_ING_01)) traz C.$q$ where career_name=$q$Polícia Rodoviária Federal$q$ and exam_year=2021 and item_number=106 and official_answer='E';
-- @@
update public.official_exam_questions set official_answer='E', content_status=case when 'E'='X' then 'annulled' when content_status='annulled' then 'under_review' else content_status end, review_note=review_note || ' ' || $q$Chave oficial corrigida em 27/09/2026: o banco tinha C; o gabarito definitivo (DEPEN 2021 (MATRIZ_541_DEPEN_008_00, CB2 e CG2)) traz E.$q$ where career_name=$q$Departamento Penitenciário Nacional$q$ and exam_year=2021 and item_number=45 and official_answer='C';
-- @@
