-- Primeiro lote: 26 questões de julgamento extraídas da coletânea do Drive.
-- Grava em curated_question_catalog como under_review; não publica.
-- Preserva origem, gabarito e autoria não original.
begin;
do $guard$ begin
 if (select count(*) from public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id where e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%') <> 1 then raise exception 'Edital ativo e tópico PF 2025 não encontrados de forma única; lote não aplicado.'; end if;
end $guard$;
insert into public.content_sources(source_type,title,issuer,url,status,is_official,notes) values
('outro','157 questões constitucional.pdf','Coletânea enviada pelo usuário','https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view','em_revisao',false,'Coletânea de terceiros: gabaritos e origem preservados. Conferência visual ainda pendente. Não é caderno oficial da PF.'),
('constituicao','Constituição Federal — texto compilado','Presidência da República','https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm','vigente',true,'Artigos relativos ao primeiro lote cotejados individualmente em 30/09/2026.')
on conflict(url) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-20','Repertório CEBRASPE — Direito Constitucional',2019,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. O direito à liberdade de imprensa abrange a garantia do sigilo da fonte.','C','O sigilo da fonte é protegido quando necessário ao exercício profissional. Origem declarada pela coletânea: CEBRASPE (CESPE) - AJ (TJ AM)/TJ AM/Direito/2019. Item 20 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XIV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. O direito à liberdade de imprensa abrange a garantia do sigilo da fonte.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. O direito à liberdade de imprensa abrange a garantia do sigilo da fonte.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. O direito à liberdade de imprensa abrange a garantia do sigilo da fonte.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-21','Repertório CEBRASPE — Direito Constitucional',2019,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. Os direitos constitucionais da pessoa presa incluem o direito à identificação dos responsáveis pela prisão, o direito ao silêncio e o direito à assistência da família e de advogado.','C','A Constituição assegura silêncio, assistência e identificação dos responsáveis. Origem declarada pela coletânea: CEBRASPE (CESPE) - AJ (TJ AM)/TJ AM/Direito/2019. Item 21 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LXIII e LXIV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. Os direitos constitucionais da pessoa presa incluem o direito à identificação dos responsáveis pela prisão, o direito ao silêncio e o direito à assistência da família e de advogado.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. Os direitos constitucionais da pessoa presa incluem o direito à identificação dos responsáveis pela prisão, o direito ao silêncio e o direito à assistência da família e de advogado.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais, julgue o item subsequente. Os direitos constitucionais da pessoa presa incluem o direito à identificação dos responsáveis pela prisão, o direito ao silêncio e o direito à assistência da família e de advogado.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-22','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A obrigação financeira da pessoa falecida de reparar determinado dano pode ser estendida aos seus sucessores, sendo limitada ao valor do patrimônio transferido pela sucessão decorrente do óbito.','C','A reparação pode atingir sucessores, limitada ao patrimônio transferido. Origem declarada pela coletânea: CEBRASPE (CESPE) - AMCI (CGM J Pessoa)/Pref João Pessoa/Tecnologia da Informação/Desenvolvimento de Sistemas/2018. Item 22 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XLV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A obrigação financeira da pessoa falecida de reparar determinado dano pode ser estendida aos seus sucessores, sendo limitada ao valor do patrimônio transferido pela sucessão decorrente do óbito.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A obrigação financeira da pessoa falecida de reparar determinado dano pode ser estendida aos seus sucessores, sendo limitada ao valor do patrimônio transferido pela sucessão decorrente do óbito.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A obrigação financeira da pessoa falecida de reparar determinado dano pode ser estendida aos seus sucessores, sendo limitada ao valor do patrimônio transferido pela sucessão decorrente do óbito.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-23','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A lei não pode prejudicar o direito adquirido, o ato jurídico perfeito e a expectativa de direito.','E','A proteção enumera coisa julgada, não mera expectativa de direito. Origem declarada pela coletânea: CEBRASPE (CESPE) - AMCI (CGM J Pessoa)/Pref João Pessoa/Tecnologia da Informação/Desenvolvimento de Sistemas/2018. Item 23 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XXXVI","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A lei não pode prejudicar o direito adquirido, o ato jurídico perfeito e a expectativa de direito.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A lei não pode prejudicar o direito adquirido, o ato jurídico perfeito e a expectativa de direito.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz do disposto na Constituição Federal de 1988 (CF), julgue o item a seguir, acerca dos princípios constitucionais e dos direitos fundamentais. A lei não pode prejudicar o direito adquirido, o ato jurídico perfeito e a expectativa de direito.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-25','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','À luz da Constituição Federal de 1988, julgue o item que se segue, acerca dos princípios fundamentais e do meio ambiente. Ressalvada a hipótese de flagrante delito, a prisão decorrente da prática de transgressão militar dependerá de ordem escrita e fundamentada de autoridade judiciária competente.','E','A regra constitucional ressalva transgressão militar e crime propriamente militar. Origem declarada pela coletânea: CEBRASPE (CESPE) - AJ (STM)/STM/Judiciária/"Sem Especialidade"/2018. Item 25 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LXI","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz da Constituição Federal de 1988, julgue o item que se segue, acerca dos princípios fundamentais e do meio ambiente. Ressalvada a hipótese de flagrante delito, a prisão decorrente da prática de transgressão militar dependerá de ordem escrita e fundamentada de autoridade judiciária competente.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz da Constituição Federal de 1988, julgue o item que se segue, acerca dos princípios fundamentais e do meio ambiente. Ressalvada a hipótese de flagrante delito, a prisão decorrente da prática de transgressão militar dependerá de ordem escrita e fundamentada de autoridade judiciária competente.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('À luz da Constituição Federal de 1988, julgue o item que se segue, acerca dos princípios fundamentais e do meio ambiente. Ressalvada a hipótese de flagrante delito, a prisão decorrente da prática de transgressão militar dependerá de ordem escrita e fundamentada de autoridade judiciária competente.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-32','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Dada a previsão constitucional de que nenhuma pena passará da pessoa do condenado a outrem, o ordenamento jurídico veda que obrigações de reparação de danos sejam estendidas aos sucessores do condenado.','E','A reparação admite extensão aos sucessores no limite patrimonial. Origem declarada pela coletânea: CEBRASPE (CESPE) - PCF/PF/Área 1/2018. Item 32 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XLV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Dada a previsão constitucional de que nenhuma pena passará da pessoa do condenado a outrem, o ordenamento jurídico veda que obrigações de reparação de danos sejam estendidas aos sucessores do condenado.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Dada a previsão constitucional de que nenhuma pena passará da pessoa do condenado a outrem, o ordenamento jurídico veda que obrigações de reparação de danos sejam estendidas aos sucessores do condenado.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Dada a previsão constitucional de que nenhuma pena passará da pessoa do condenado a outrem, o ordenamento jurídico veda que obrigações de reparação de danos sejam estendidas aos sucessores do condenado.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-33','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Com relação aos direitos e às garantias fundamentais constitucionalmente assegurados, julgue o item que se segue. Em regra, indivíduo civilmente identificado não será submetido à identificação criminal.','C','A identificação criminal é excepcional para quem já está civilmente identificado. Origem declarada pela coletânea: CEBRASPE (CESPE) - EPF/PF/2018. Item 33 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LVIII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais constitucionalmente assegurados, julgue o item que se segue. Em regra, indivíduo civilmente identificado não será submetido à identificação criminal.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais constitucionalmente assegurados, julgue o item que se segue. Em regra, indivíduo civilmente identificado não será submetido à identificação criminal.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais constitucionalmente assegurados, julgue o item que se segue. Em regra, indivíduo civilmente identificado não será submetido à identificação criminal.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-64','Repertório CEBRASPE — Direito Constitucional',2017,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. Caso, em determinado estado da Federação, um grupo de pessoas constitua uma associação, para certo fim, que se comprove ilícita por meio de processo regular, somente decisão judicial poderá suspender as atividades da associação, independentemente do trânsito julgado da ação.','C','A suspensão exige decisão judicial; trânsito em julgado aplica-se à dissolução. Origem declarada pela coletânea: CEBRASPE (CESPE) - AG (TCE-PE) /TCEPE/Julgamento/2017. Item 64 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XIX","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. Caso, em determinado estado da Federação, um grupo de pessoas constitua uma associação, para certo fim, que se comprove ilícita por meio de processo regular, somente decisão judicial poderá suspender as atividades da associação, independentemente do trânsito julgado da ação.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. Caso, em determinado estado da Federação, um grupo de pessoas constitua uma associação, para certo fim, que se comprove ilícita por meio de processo regular, somente decisão judicial poderá suspender as atividades da associação, independentemente do trânsito julgado da ação.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. Caso, em determinado estado da Federação, um grupo de pessoas constitua uma associação, para certo fim, que se comprove ilícita por meio de processo regular, somente decisão judicial poderá suspender as atividades da associação, independentemente do trânsito julgado da ação.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-66','Repertório CEBRASPE — Direito Constitucional',2017,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. A liberdade para o exercício de qualquer trabalho, ofício ou profissão está condicionada ao atendimento das qualificações profissionais estabelecidas por lei, mas nem todos os ofícios ou profissões, para serem exercidos, estarão sujeitos à existência de lei.','C','Qualificações profissionais dependem de previsão legal; não são exigência universal. Origem declarada pela coletânea: CEBRASPE (CESPE) - AG (TCE-PE) /TCEPE/Julgamento/2017. Item 66 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XIII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. A liberdade para o exercício de qualquer trabalho, ofício ou profissão está condicionada ao atendimento das qualificações profissionais estabelecidas por lei, mas nem todos os ofícios ou profissões, para serem exercidos, estarão sujeitos à existência de lei.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. A liberdade para o exercício de qualquer trabalho, ofício ou profissão está condicionada ao atendimento das qualificações profissionais estabelecidas por lei, mas nem todos os ofícios ou profissões, para serem exercidos, estarão sujeitos à existência de lei.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos princípios fundamentais e dos direitos e deveres individuais e coletivos, julgue o item a seguir. A liberdade para o exercício de qualquer trabalho, ofício ou profissão está condicionada ao atendimento das qualificações profissionais estabelecidas por lei, mas nem todos os ofícios ou profissões, para serem exercidos, estarão sujeitos à existência de lei.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-67','Repertório CEBRASPE — Direito Constitucional',2017,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca dos direitos e das garantias fundamentais previstos na Constituição Federal de 1988 (CF), julgue o item a seguir. No Estado brasileiro, é plena a liberdade de associação de seus cidadãos, desde que para fins lícitos, sendo expressamente vedado qualquer tipo de associação de caráter paramilitar.','C','Associações lícitas são livres; as de caráter paramilitar são vedadas. Origem declarada pela coletânea: CEBRASPE (CESPE) - Of (CBM AL)/CBM AL/Combatente/2017. Item 67 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XVII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais previstos na Constituição Federal de 1988 (CF), julgue o item a seguir. No Estado brasileiro, é plena a liberdade de associação de seus cidadãos, desde que para fins lícitos, sendo expressamente vedado qualquer tipo de associação de caráter paramilitar.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais previstos na Constituição Federal de 1988 (CF), julgue o item a seguir. No Estado brasileiro, é plena a liberdade de associação de seus cidadãos, desde que para fins lícitos, sendo expressamente vedado qualquer tipo de associação de caráter paramilitar.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e das garantias fundamentais previstos na Constituição Federal de 1988 (CF), julgue o item a seguir. No Estado brasileiro, é plena a liberdade de associação de seus cidadãos, desde que para fins lícitos, sendo expressamente vedado qualquer tipo de associação de caráter paramilitar.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-69','Repertório CEBRASPE — Direito Constitucional',2017,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca dos direitos e garantias fundamentais, julgue o item a seguir. A Constituição Federal de 1988 estabelece a prisão como medida excepcional, que, em regra, depende de flagrante delito ou de ordem escrita e fundamentada.','C','O item descreve a regra geral constitucional de prisão. Origem declarada pela coletânea: CEBRASPE (CESPE) - Sold (PM AL)/PM AL/Combatente/2017. Item 69 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LXI","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e garantias fundamentais, julgue o item a seguir. A Constituição Federal de 1988 estabelece a prisão como medida excepcional, que, em regra, depende de flagrante delito ou de ordem escrita e fundamentada.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e garantias fundamentais, julgue o item a seguir. A Constituição Federal de 1988 estabelece a prisão como medida excepcional, que, em regra, depende de flagrante delito ou de ordem escrita e fundamentada.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca dos direitos e garantias fundamentais, julgue o item a seguir. A Constituição Federal de 1988 estabelece a prisão como medida excepcional, que, em regra, depende de flagrante delito ou de ordem escrita e fundamentada.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-70','Repertório CEBRASPE — Direito Constitucional',2017,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Em relação à eficácia das normas constitucionais, aos direitos e garantias fundamentais e às disposições gerais constitucionais sobre os servidores públicos, julgue o item a seguir. A Constituição Federal, ao prever, de forma exaustiva, os direitos e garantias fundamentais dos indivíduos, faz que sejam desconsiderados outros direitos humanos, mesmo que estejam previstos em tratados internacionais dos quais o Brasil seja parte.','E','A enumeração constitucional não exclui outros direitos previstos em tratados. Origem declarada pela coletânea: CEBRASPE (CESPE) - AJ TRF1/TRF 1/Apoio Especializado/Taquigrafia/2017. Item 70 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, § 2º","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Em relação à eficácia das normas constitucionais, aos direitos e garantias fundamentais e às disposições gerais constitucionais sobre os servidores públicos, julgue o item a seguir. A Constituição Federal, ao prever, de forma exaustiva, os direitos e garantias fundamentais dos indivíduos, faz que sejam desconsiderados outros direitos humanos, mesmo que estejam previstos em tratados internacionais dos quais o Brasil seja parte.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Em relação à eficácia das normas constitucionais, aos direitos e garantias fundamentais e às disposições gerais constitucionais sobre os servidores públicos, julgue o item a seguir. A Constituição Federal, ao prever, de forma exaustiva, os direitos e garantias fundamentais dos indivíduos, faz que sejam desconsiderados outros direitos humanos, mesmo que estejam previstos em tratados internacionais dos quais o Brasil seja parte.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Em relação à eficácia das normas constitucionais, aos direitos e garantias fundamentais e às disposições gerais constitucionais sobre os servidores públicos, julgue o item a seguir. A Constituição Federal, ao prever, de forma exaustiva, os direitos e garantias fundamentais dos indivíduos, faz que sejam desconsiderados outros direitos humanos, mesmo que estejam previstos em tratados internacionais dos quais o Brasil seja parte.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-105','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Ainda que, em regra, inexista distinção entre brasileiros natos e naturalizados, o cargo de oficial das Forças Armadas só poderá ser exercido por brasileiro nato.','C','Oficial das Forças Armadas é cargo reservado a brasileiro nato. Origem declarada pela coletânea: CEBRASPE (CESPE) - PCF/PF/Área 1/2018. Item 105 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"12, § 3º, VI","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Ainda que, em regra, inexista distinção entre brasileiros natos e naturalizados, o cargo de oficial das Forças Armadas só poderá ser exercido por brasileiro nato.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Ainda que, em regra, inexista distinção entre brasileiros natos e naturalizados, o cargo de oficial das Forças Armadas só poderá ser exercido por brasileiro nato.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação aos direitos e às garantias fundamentais previstos na Constituição Federal de 1988, julgue o item a seguir. Ainda que, em regra, inexista distinção entre brasileiros natos e naturalizados, o cargo de oficial das Forças Armadas só poderá ser exercido por brasileiro nato.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-34','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. As associações, em regra, não precisam de autorização da administração pública para reunir-se, assim como para a sua criação.','C','Reunião e criação de associação independem de autorização. Origem declarada pela coletânea: CEBRASPE (CESPE) - PPF/PF/2018. Item 34 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XVI e XVIII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. As associações, em regra, não precisam de autorização da administração pública para reunir-se, assim como para a sua criação.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. As associações, em regra, não precisam de autorização da administração pública para reunir-se, assim como para a sua criação.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. As associações, em regra, não precisam de autorização da administração pública para reunir-se, assim como para a sua criação.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-35','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. A máxima da liberdade de expressão no âmbito das associações é extensamente garantida pela Constituição Federal de 1988, que assegura a livre manifestação do pensamento e protege o anonimato.','E','A manifestação do pensamento não protege o anonimato. Origem declarada pela coletânea: CEBRASPE (CESPE) - PPF/PF/2018. Item 35 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, IV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. A máxima da liberdade de expressão no âmbito das associações é extensamente garantida pela Constituição Federal de 1988, que assegura a livre manifestação do pensamento e protege o anonimato.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. A máxima da liberdade de expressão no âmbito das associações é extensamente garantida pela Constituição Federal de 1988, que assegura a livre manifestação do pensamento e protege o anonimato.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Uma associação, com o objetivo de pleitear direitos relativos à educação de adultos analfabetos, planeja realizar uma manifestação pacífica em local aberto ao público, inclusive para maior visibilidade e aderência. Considerando essa situação hipotética, julgue o item a seguir. A máxima da liberdade de expressão no âmbito das associações é extensamente garantida pela Constituição Federal de 1988, que assegura a livre manifestação do pensamento e protege o anonimato.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-36','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. A CF veda a extradição de estrangeiro em razão de crime político ou de opinião.','C','A extradição por crime político ou de opinião é vedada. Origem declarada pela coletânea: CEBRASPE (CESPE) - Diplomata/IRBr/2018. Item 36 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. A CF veda a extradição de estrangeiro em razão de crime político ou de opinião.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. A CF veda a extradição de estrangeiro em razão de crime político ou de opinião.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. A CF veda a extradição de estrangeiro em razão de crime político ou de opinião.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-37','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. Os tratados e convenções internacionais genericamente considerados terão status constitucional se forem aprovados pelo processo legislativo previsto para a votação de emendas à CF.','E','O rito especial alcança tratados de direitos humanos. Origem declarada pela coletânea: CEBRASPE (CESPE) - Diplomata/IRBr/2018. Item 37 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, § 3º","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. Os tratados e convenções internacionais genericamente considerados terão status constitucional se forem aprovados pelo processo legislativo previsto para a votação de emendas à CF.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. Os tratados e convenções internacionais genericamente considerados terão status constitucional se forem aprovados pelo processo legislativo previsto para a votação de emendas à CF.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('No que tange aos direitos e garantias fundamentais e ao processo legislativo, conforme disposto na Constituição Federal de 1988 (CF), julgue (C ou E) o item subsequente. Os tratados e convenções internacionais genericamente considerados terão status constitucional se forem aprovados pelo processo legislativo previsto para a votação de emendas à CF.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-38','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca do direito de propriedade, julgue o item a seguir à luz das disposições da CF. No caso de iminente perigo público, a autoridade competente poderá fazer uso de propriedade particular, assegurada ao proprietário indenização ulterior, ainda que essa utilização não acarrete danos.','E','A indenização ulterior depende de dano. Origem declarada pela coletânea: CEBRASPE (CESPE) - Ana Min (MPE PI)/MPE PI/Engenharia/Engenharia Civil/2018. Item 38 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XXV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca do direito de propriedade, julgue o item a seguir à luz das disposições da CF. No caso de iminente perigo público, a autoridade competente poderá fazer uso de propriedade particular, assegurada ao proprietário indenização ulterior, ainda que essa utilização não acarrete danos.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca do direito de propriedade, julgue o item a seguir à luz das disposições da CF. No caso de iminente perigo público, a autoridade competente poderá fazer uso de propriedade particular, assegurada ao proprietário indenização ulterior, ainda que essa utilização não acarrete danos.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca do direito de propriedade, julgue o item a seguir à luz das disposições da CF. No caso de iminente perigo público, a autoridade competente poderá fazer uso de propriedade particular, assegurada ao proprietário indenização ulterior, ainda que essa utilização não acarrete danos.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-40','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. Se um grupo de moradores do cerrado brasileiro pretender fundar associação com intuito de incentivar e promover a preservação do meio ambiente, será indispensável uma autorização estatal prévia para o funcionamento dessa associação.','E','Associações não dependem de autorização estatal. Origem declarada pela coletânea: CEBRASPE (CESPE) - Aux Inst (IPHAN)/IPHAN/Área 1/2018. Item 40 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XVIII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. Se um grupo de moradores do cerrado brasileiro pretender fundar associação com intuito de incentivar e promover a preservação do meio ambiente, será indispensável uma autorização estatal prévia para o funcionamento dessa associação.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. Se um grupo de moradores do cerrado brasileiro pretender fundar associação com intuito de incentivar e promover a preservação do meio ambiente, será indispensável uma autorização estatal prévia para o funcionamento dessa associação.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. Se um grupo de moradores do cerrado brasileiro pretender fundar associação com intuito de incentivar e promover a preservação do meio ambiente, será indispensável uma autorização estatal prévia para o funcionamento dessa associação.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-41','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. O direito de resposta proporcional a um cidadão que tenha sido ofendido não impede o direito à indenização por dano material, moral ou à imagem.','C','Resposta e indenização podem coexistir. Origem declarada pela coletânea: CEBRASPE (CESPE) - Aux Inst (IPHAN)/IPHAN/Área 1/2018. Item 41 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, V","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. O direito de resposta proporcional a um cidadão que tenha sido ofendido não impede o direito à indenização por dano material, moral ou à imagem.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. O direito de resposta proporcional a um cidadão que tenha sido ofendido não impede o direito à indenização por dano material, moral ou à imagem.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('A respeito dos direitos e das garantias fundamentais, julgue o item seguinte. O direito de resposta proporcional a um cidadão que tenha sido ofendido não impede o direito à indenização por dano material, moral ou à imagem.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-42','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Com relação às normas do direito brasileiro, julgue o item que se segue. Todos os tratados internacionais que versem sobre direitos humanos são incluídos no ordenamento jurídico brasileiro com força de norma constitucional.','E','Equivalência constitucional exige aprovação pelo rito constitucional especial. Origem declarada pela coletânea: CEBRASPE (CESPE) - Aux Inst (IPHAN)/IPHAN/Área 1/2018. Item 42 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, § 3º","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação às normas do direito brasileiro, julgue o item que se segue. Todos os tratados internacionais que versem sobre direitos humanos são incluídos no ordenamento jurídico brasileiro com força de norma constitucional.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação às normas do direito brasileiro, julgue o item que se segue. Todos os tratados internacionais que versem sobre direitos humanos são incluídos no ordenamento jurídico brasileiro com força de norma constitucional.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com relação às normas do direito brasileiro, julgue o item que se segue. Todos os tratados internacionais que versem sobre direitos humanos são incluídos no ordenamento jurídico brasileiro com força de norma constitucional.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-43','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','De acordo com as disposições da Constituição Federal de 1988 (CF) sobre princípios, direitos e garantias fundamentais, julgue o seguinte item. Tratados e convenções internacionais sobre direitos humanos que forem aprovados em cada casa do Congresso Nacional, nos termos da CF, serão equivalentes às emendas constitucionais.','C','A aprovação nos termos constitucionais confere equivalência a emendas. Origem declarada pela coletânea: CEBRASPE (CESPE) - Tec Min (MPE PI)/MPE PI/Administrativa/2018. Item 43 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, § 3º","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('De acordo com as disposições da Constituição Federal de 1988 (CF) sobre princípios, direitos e garantias fundamentais, julgue o seguinte item. Tratados e convenções internacionais sobre direitos humanos que forem aprovados em cada casa do Congresso Nacional, nos termos da CF, serão equivalentes às emendas constitucionais.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('De acordo com as disposições da Constituição Federal de 1988 (CF) sobre princípios, direitos e garantias fundamentais, julgue o seguinte item. Tratados e convenções internacionais sobre direitos humanos que forem aprovados em cada casa do Congresso Nacional, nos termos da CF, serão equivalentes às emendas constitucionais.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('De acordo com as disposições da Constituição Federal de 1988 (CF) sobre princípios, direitos e garantias fundamentais, julgue o seguinte item. Tratados e convenções internacionais sobre direitos humanos que forem aprovados em cada casa do Congresso Nacional, nos termos da CF, serão equivalentes às emendas constitucionais.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-45','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Julgue o item seguinte, relativo aos direitos e deveres individuais e coletivos e às garantias constitucionais. Conforme texto constitucional vigente, a prisão de qualquer pessoa e o local onde se encontra terão de ser comunicados em até vinte e quatro horas ao juiz competente e à família do preso ou a pessoa por ele indicada.','E','A Constituição exige comunicação imediata. Origem declarada pela coletânea: CEBRASPE (CESPE) - Del Pol (PC SE)/PC SE/2018. Item 45 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LXII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Julgue o item seguinte, relativo aos direitos e deveres individuais e coletivos e às garantias constitucionais. Conforme texto constitucional vigente, a prisão de qualquer pessoa e o local onde se encontra terão de ser comunicados em até vinte e quatro horas ao juiz competente e à família do preso ou a pessoa por ele indicada.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Julgue o item seguinte, relativo aos direitos e deveres individuais e coletivos e às garantias constitucionais. Conforme texto constitucional vigente, a prisão de qualquer pessoa e o local onde se encontra terão de ser comunicados em até vinte e quatro horas ao juiz competente e à família do preso ou a pessoa por ele indicada.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Julgue o item seguinte, relativo aos direitos e deveres individuais e coletivos e às garantias constitucionais. Conforme texto constitucional vigente, a prisão de qualquer pessoa e o local onde se encontra terão de ser comunicados em até vinte e quatro horas ao juiz competente e à família do preso ou a pessoa por ele indicada.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-47','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca de direitos e garantias fundamentais, julgue o item a seguir. Poderá ser violada a casa em cujo interior esteja indivíduo em flagrante delito, mesmo durante o período noturno e sem determinação judicial.','C','Flagrante permite ingresso noturno sem ordem judicial. Origem declarada pela coletânea: CEBRASPE (CESPE) - Sold (PM AL)/PM AL/Combatente/2018. Item 47 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, XI","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca de direitos e garantias fundamentais, julgue o item a seguir. Poderá ser violada a casa em cujo interior esteja indivíduo em flagrante delito, mesmo durante o período noturno e sem determinação judicial.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca de direitos e garantias fundamentais, julgue o item a seguir. Poderá ser violada a casa em cujo interior esteja indivíduo em flagrante delito, mesmo durante o período noturno e sem determinação judicial.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca de direitos e garantias fundamentais, julgue o item a seguir. Poderá ser violada a casa em cujo interior esteja indivíduo em flagrante delito, mesmo durante o período noturno e sem determinação judicial.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-49','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Acerca de direitos e garantias fundamentais, julgue o item a seguir. Uma pessoa presa em patrulha policial pelo cometimento de crime deverá ser informada, nos termos da Constituição Federal de 1988, do seu direito de permanecer calada.','C','O preso deve ser informado do direito ao silêncio. Origem declarada pela coletânea: CEBRASPE (CESPE) - Sold (PM AL)/PM AL/Combatente/2018. Item 49 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, LXIII","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca de direitos e garantias fundamentais, julgue o item a seguir. Uma pessoa presa em patrulha policial pelo cometimento de crime deverá ser informada, nos termos da Constituição Federal de 1988, do seu direito de permanecer calada.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca de direitos e garantias fundamentais, julgue o item a seguir. Uma pessoa presa em patrulha policial pelo cometimento de crime deverá ser informada, nos termos da Constituição Federal de 1988, do seu direito de permanecer calada.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Acerca de direitos e garantias fundamentais, julgue o item a seguir. Uma pessoa presa em patrulha policial pelo cometimento de crime deverá ser informada, nos termos da Constituição Federal de 1988, do seu direito de permanecer calada.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
insert into public.curated_question_catalog(source_id,syllabus_topic_id,external_item_key,contest_name,contest_year,career_name,exam_board,subject,subtopic,question_text,official_answer,explanation,legal_basis,difficulty,content_status,is_original,law_version_checked_at)
select s.id,t.id,'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-50','Repertório CEBRASPE — Direito Constitucional',2018,'Agente de Polícia Federal', 'CEBRASPE','Direito Constitucional','Direitos e garantias fundamentais','Com base nas disposições constitucionais acerca de princípios, direitos e garantias fundamentais, julgue o item a seguir. A liberdade de pensamento é exercida com ônus para o manifestante, que deverá se identificar e assumir a autoria daquilo que ele expressar.','C','A liberdade de pensamento acompanha a vedação ao anonimato. Origem declarada pela coletânea: CEBRASPE (CESPE) - Tec MPU/MPU/Apoio Técnico e Administrativo/Administração/2018. Item 50 do PDF. Conferência textual em 30/09/2026; aguarda conferência visual antes da publicação.','[{"norma":"Constituição Federal","artigo":"5º, IV","url":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm"}]'::jsonb,'média','under_review',false,'2026-09-30T00:00:00-03:00'::timestamptz
from public.content_sources s cross join public.syllabus_topics t join public.syllabus_editions e on e.id=t.edition_id
where s.url='https://drive.google.com/file/d/1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn/view' and e.contest_name='Polícia Federal' and e.role_name='Agente de Polícia Federal' and e.contest_year=2025 and e.status='active' and t.discipline='Noções de Direito Constitucional' and t.topic_order=1 and t.content_status='current' and t.block_name not ilike '%Hist%'
and not exists (select 1 from public.curated_question_catalog c where regexp_replace(lower(c.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com base nas disposições constitucionais acerca de princípios, direitos e garantias fundamentais, julgue o item a seguir. A liberdade de pensamento é exercida com ônus para o manifestante, que deverá se identificar e assumir a autoria daquilo que ele expressar.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.official_exam_questions o where regexp_replace(lower(o.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com base nas disposições constitucionais acerca de princípios, direitos e garantias fundamentais, julgue o item a seguir. A liberdade de pensamento é exercida com ônus para o manifestante, que deverá se identificar e assumir a autoria daquilo que ele expressar.'), '[[:space:]]+', ' ', 'g'))
and not exists (select 1 from public.question_bank b where regexp_replace(lower(b.question_text), '[[:space:]]+', ' ', 'g')=regexp_replace(lower('Com base nas disposições constitucionais acerca de princípios, direitos e garantias fundamentais, julgue o item a seguir. A liberdade de pensamento é exercida com ônus para o manifestante, que deverá se identificar e assumir a autoria daquilo que ele expressar.'), '[[:space:]]+', ' ', 'g'))
on conflict(source_id,external_item_key) do nothing;
commit;
select external_item_key,content_status,is_original,law_version_checked_at from public.curated_question_catalog where external_item_key like 'drive-1PKj-SV8e-8bWKTNhIj5LVBIZJaMRHqSn-%' order by external_item_key;
