-- Candidate's literal marked answers for PF 2021, pasted directly by the
-- candidate. Blank-question count matches exactly (42) against the already
-- stored final grading, confirming this is the right list for this contest.
with answers(item_number, letter) as (
  values
    ('1','E'),
    ('2','C'),
    ('3','C'),
    ('4','E'),
    ('5','C'),
    ('6','E'),
    ('8','C'),
    ('9','E'),
    ('10','E'),
    ('11','C'),
    ('13','E'),
    ('14','E'),
    ('15','E'),
    ('16','C'),
    ('17','E'),
    ('19','E'),
    ('20','C'),
    ('21','C'),
    ('23','E'),
    ('25','E'),
    ('27','C'),
    ('28','C'),
    ('29','C'),
    ('30','E'),
    ('31','E'),
    ('32','C'),
    ('33','C'),
    ('34','C'),
    ('35','E'),
    ('36','E'),
    ('43','E'),
    ('49','E'),
    ('50','E'),
    ('52','C'),
    ('53','C'),
    ('55','E'),
    ('56','E'),
    ('57','C'),
    ('58','C'),
    ('59','C'),
    ('61','C'),
    ('62','E'),
    ('63','E'),
    ('65','C'),
    ('66','E'),
    ('67','C'),
    ('68','C'),
    ('69','E'),
    ('70','E'),
    ('71','E'),
    ('72','E'),
    ('75','C'),
    ('77','E'),
    ('78','E'),
    ('79','C'),
    ('81','C'),
    ('83','E'),
    ('86','E'),
    ('89','C'),
    ('90','C'),
    ('92','C'),
    ('93','E'),
    ('94','E'),
    ('97','E'),
    ('98','C'),
    ('99','E'),
    ('101','C'),
    ('102','E'),
    ('103','C'),
    ('106','C'),
    ('107','E'),
    ('108','C'),
    ('109','E'),
    ('111','C'),
    ('115','C'),
    ('117','E'),
    ('118','C'),
    ('119','C')
),
agg as (
  select jsonb_object_agg(item_number, letter) as candidate_answers from answers
)
update public.student_exam_documents d
set extracted_data = d.extracted_data || jsonb_build_object('candidate_answers', agg.candidate_answers)
from agg
where d.user_id = (select id from auth.users where email='69598193268@norteconcurso.local')
  and d.contest_name = 'Agente de Polícia Federal'
  and d.contest_year = '2021'
  and d.doc_type = 'resultado';
