-- Import of Câmara dos Deputados 2026 official exam items for the career
-- "Técnico Legislativo – Especialidade: Policial Legislativo Federal"
-- (Edital nº 1 – CD/PLF, de 23 de janeiro de 2026, CEBRASPE, aplicação em
-- 26/4/2026). This is the FIRST import for this contest/career combination.
--
-- Source material read verbatim from Google Drive folder "CÂMARA DOS
-- DEPUTADOS 26 POLICIAL LEGISLATIVO FEDERAL" (fileId
-- 1YZ1v0qHKdm5tgrMbcBu888gA146wSn9L):
--   - Prova objetiva - Conhecimentos Gerais (fileId
--     1iIlZ8ULGoN80iffDX1jBRegWuNfKMaY2), itens 1 a 90.
--   - Prova objetiva - Conhecimentos Específicos (fileId
--     139uVVRFXKRgzQ4O_hIh1cfvIwWplinAz), itens 91 a 180.
--   - Gabarito definitivo - Conhecimentos Gerais (fileId
--     1LqdsTfgFDOkAc2Q-8XuGuVLKj5TeL-NP), itens 1 a 90.
--   - Gabarito definitivo - Conhecimentos Específicos (fileId
--     1aZPmGJkZ8bG8D19vdf8nU6kOQkyej45N), itens 91 a 180.
--   - Edital nº 1 - Abertura (fileId 1K56dLM4QovvYRO18mnc9RDHtl_AjJxzG),
--     used to confirm exact career wording, código de vaga (CDAL-015) and
--     banca (CEBRASPE).
-- Item counts cross-checked: prova objetiva (CG 1-90 + CE 91-180 = 180
-- itens) matches gabarito definitivo (CG 1-90 + CE 91-180 = 180 itens).
-- ( X ) no gabarito = item anulado -> content_status='annulled'.
--
-- Career/contest naming confirmed from the edital cover: cargo "Técnico
-- Legislativo – Especialidade: Policial Legislativo Federal", código
-- CDAL-015, órgão "Câmara dos Deputados", banca CEBRASPE, ano 2026.

insert into public.content_sources (source_type,title,issuer,url,status,notes) values
('outro','Prova objetiva - Conhecimentos Gerais - Câmara dos Deputados - Policial Legislativo Federal - 2026','Câmara dos Deputados / CEBRASPE','https://www.cebraspe.org.br/concursos/cd_26_policial_legislativo/prova_objetiva_conhecimentos_gerais.pdf/view','vigente','Caderno oficial usado para extração auditável de itens 1-90 (Google Drive fileId 1iIlZ8ULGoN80iffDX1jBRegWuNfKMaY2, texto lido verbatim nesta sessão). Edital nº 1 - CD/PLF, de 23/1/2026; aplicação 26/4/2026.'),
('outro','Prova objetiva - Conhecimentos Específicos - Câmara dos Deputados - Policial Legislativo Federal - 2026','Câmara dos Deputados / CEBRASPE','https://www.cebraspe.org.br/concursos/cd_26_policial_legislativo/prova_objetiva_conhecimentos_especificos.pdf/view','vigente','Caderno oficial usado para extração auditável de itens 91-180 (Google Drive fileId 139uVVRFXKRgzQ4O_hIh1cfvIwWplinAz, texto lido verbatim nesta sessão). Edital nº 1 - CD/PLF, de 23/1/2026; aplicação 26/4/2026.'),
('outro','Gabarito definitivo - Conhecimentos Gerais - Câmara dos Deputados - Policial Legislativo Federal - 2026','Câmara dos Deputados / CEBRASPE','https://www.cebraspe.org.br/concursos/cd_26_policial_legislativo/gabarito_definitivo_conhecimentos_gerais.pdf/view','vigente','Gabarito oficial definitivo itens 1-90, arquivo 175_CDPLF_CG1_01 (Google Drive fileId 1LqdsTfgFDOkAc2Q-8XuGuVLKj5TeL-NP); X identifica item anulado.'),
('outro','Gabarito definitivo - Conhecimentos Específicos - Câmara dos Deputados - Policial Legislativo Federal - 2026','Câmara dos Deputados / CEBRASPE','https://www.cebraspe.org.br/concursos/cd_26_policial_legislativo/gabarito_definitivo_conhecimentos_especificos.pdf/view','vigente','Gabarito oficial definitivo itens 91-180, arquivo 175_CDPLF_001_01 (Google Drive fileId 1aZPmGJkZ8bG8D19vdf8nU6kOQkyej45N); X identifica item anulado.'),
('outro','Edital nº 1 – CD/PLF, de 23 de janeiro de 2026 (Abertura)','Câmara dos Deputados / CEBRASPE','https://www.cebraspe.org.br/concursos/cd_26_policial_legislativo/edital_1_abertura.pdf/view','vigente','Edital de abertura do concurso; usado para confirmar denominação exata do cargo (Técnico Legislativo – Especialidade: Policial Legislativo Federal, código CDAL-015) e banca (Google Drive fileId 1K56dLM4QovvYRO18mnc9RDHtl_AjJxzG).')
on conflict (url) do update set checked_at=now(),status=excluded.status,notes=excluded.notes;

insert into public.syllabus_editions (contest_name,role_name,contest_year)
select 'Câmara dos Deputados','Técnico Legislativo – Especialidade: Policial Legislativo Federal',2026
where not exists (
  select 1 from public.syllabus_editions
  where contest_name='Câmara dos Deputados' and role_name='Técnico Legislativo – Especialidade: Policial Legislativo Federal' and contest_year=2026
);

with edition as (
  select id from public.syllabus_editions
  where contest_name='Câmara dos Deputados' and role_name='Técnico Legislativo – Especialidade: Policial Legislativo Federal' and contest_year=2026
)
insert into public.syllabus_topics (edition_id,block_name,discipline,topic_order,topic_text,content_status)
select edition.id,'Prova objetiva',d.discipline,1,d.topic_text,'current'
from edition cross join (values
  ('Língua Portuguesa','Compreensão e interpretação de textos, coesão e coerência, correção gramatical, sintaxe e classes de palavras.'),
  ('Língua Inglesa','Compreensão e interpretação de textos em língua inglesa sobre policiamento democrático e segurança parlamentar.'),
  ('Raciocínio Lógico-Matemático','Lógica proposicional, lógica de primeira ordem, análise combinatória, probabilidade e estatística (medidas de tendência central, dispersão e padronização).'),
  ('Direito Constitucional','Organização do Estado, princípios fundamentais, administração pública, segurança pública, Poder Legislativo, imunidades parlamentares e processo legislativo, à luz da Constituição Federal de 1988 e da jurisprudência do STF.'),
  ('Legislação Aplicável à Câmara dos Deputados','Regimento Interno da Câmara dos Deputados e Resolução da Câmara dos Deputados nº 18/2003, quanto à segurança institucional e à Polícia da Câmara dos Deputados.'),
  ('Direito Administrativo','Organização administrativa, atos e processos administrativos, agentes públicos, responsabilidade civil do Estado, Lei de Acesso à Informação, Lei Geral de Proteção de Dados, Lei nº 8.429/1992 (improbidade administrativa), bens públicos, licitações e contratos, e administração orçamentária e financeira.'),
  ('Noções de Informática','Sistemas operacionais, ferramentas de produtividade e nuvem, segurança da informação, redes, bancos de dados, Big Data, Android, malware e inteligência artificial generativa.'),
  ('Direito Penal','Crimes contra a administração pública (peculato), concurso de agentes, relação de causalidade, imputação penal, causas de extinção da punibilidade, lei penal no tempo e no espaço, imunidades, culpabilidade e exclusão da responsabilidade penal.'),
  ('Legislação Penal Especial - Juizados Especiais Criminais','Lei n.º 9.099/1995: atos processuais, termo circunstanciado de ocorrência e transação penal.'),
  ('Direito Processual Penal','Prisão em flagrante, prisão preventiva, liberdade provisória, mandado de prisão, interceptação telefônica (Lei n.º 9.296/1996) e prisão temporária (Lei n.º 7.960/1989).'),
  ('Lei de Abuso de Autoridade','Condutas tipificadas na Lei n.º 13.869/2019: ação penal, instauração de procedimento investigatório e condução coercitiva.'),
  ('Perícia Criminal','Exames periciais, prazos de laudo, exame documentoscópico e exame de corpo de delito.'),
  ('Criminologia','Modelos de reação ao delito, teorias sociológicas da criminologia (neutralização, identificação diferencial, subcultura delinquente), escolas criminológicas e controle social.'),
  ('Local de Crime e Cadeia de Custódia','Preservação do local de crime, vestígio, indício e evidência, etapas da cadeia de custódia e fraude processual.'),
  ('Direitos Humanos','Incorporação de tratados internacionais de direitos humanos na Constituição Federal, Convenção Americana sobre Direitos Humanos (Pacto de São José da Costa Rica) e Declaração Universal dos Direitos Humanos.'),
  ('Uso da Força e Atuação Policial','Princípios básicos sobre a utilização da força e de armas de fogo pelos funcionários responsáveis pela aplicação da lei.'),
  ('Atividade de Inteligência','Funções da atividade de inteligência, metodologia de produção de conhecimentos, contrainteligência, Política Nacional de Inteligência, análise de risco e controle da atividade de inteligência.')
) d(discipline,topic_text)
on conflict (edition_id,discipline,topic_order) do update set topic_text=excluded.topic_text;

with imported(exam_year,item_number,subject,question_text,raw_extraction,official_answer,source_page,content_status,legal_review_required,context_review_required,review_note) as (values
(2026,1,$q$Língua Portuguesa$q$,$q$No trecho "a história da ciência é menos uma sucessão de lampejos isolados e mais a de sincronizações oriundas de massas de dados e ideias que vão gradualmente se articulando" (último parágrafo), o vocábulo "a" substitui termo nominal já mencionado e contribui para a coesão sequencial do texto.$q$,$q$No trecho "a história da ciência é menos uma sucessão de lampejos isolados e mais a de sincronizações oriundas de massas de dados e ideias que vão gradualmente se articulando" (último parágrafo), o vocábulo "a" substitui termo nominal já mencionado e contribui para a coesão sequencial do texto.$q$,'X',1,'annulled',true,false,$q$Item anulado no gabarito oficial definitivo (Conhecimentos Gerais); não é exibido aos estudantes.$q$),
(2026,2,$q$Língua Portuguesa$q$,$q$De acordo com o texto, a simplicidade da descrição da ciência como uma sucessão de descobertas de uma mente brilhante confere conforto à sociedade e, ao mesmo tempo, opera apagamentos na história da construção do conhecimento.$q$,$q$De acordo com o texto, a simplicidade da descrição da ciência como uma sucessão de descobertas de uma mente brilhante confere conforto à sociedade e, ao mesmo tempo, opera apagamentos na história da construção do conhecimento.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,3,$q$Língua Portuguesa$q$,$q$Haveria prejuízo da correção gramatical do texto caso se inserisse vírgula após a palavra "controversas" (final do segundo parágrafo).$q$,$q$Haveria prejuízo da correção gramatical do texto caso se inserisse vírgula após a palavra "controversas" (final do segundo parágrafo).$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,4,$q$Língua Portuguesa$q$,$q$Da leitura do texto infere-se que a aproximação de uma teoria à verdade é fator menos decisivo que a existência de certa orientação vetorial de um sistema científico para a consagração dessa teoria e para o consequente surgimento de um paradigma científico.$q$,$q$Da leitura do texto infere-se que a aproximação de uma teoria à verdade é fator menos decisivo que a existência de certa orientação vetorial de um sistema científico para a consagração dessa teoria e para o consequente surgimento de um paradigma científico.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,5,$q$Língua Portuguesa$q$,$q$No segmento "é preciso haver, sobretudo, convergência" (final do primeiro parágrafo), a oração "haver, sobretudo, convergência" liga-se sintaticamente ao adjetivo "preciso".$q$,$q$No segmento "é preciso haver, sobretudo, convergência" (final do primeiro parágrafo), a oração "haver, sobretudo, convergência" liga-se sintaticamente ao adjetivo "preciso".$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,6,$q$Língua Portuguesa$q$,$q$De acordo com o texto, na história da ciência, as sincronizações provenientes de massas de dados e de ideias que, aos poucos, se vão articulando têm mais peso que a sucessão de lampejos.$q$,$q$De acordo com o texto, na história da ciência, as sincronizações provenientes de massas de dados e de ideias que, aos poucos, se vão articulando têm mais peso que a sucessão de lampejos.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,7,$q$Língua Portuguesa$q$,$q$O emprego do presente do indicativo em "Ideias científicas não emergem no vazio" (primeiro parágrafo) confere à ideia expressa no período valor de uma verdade absoluta.$q$,$q$O emprego do presente do indicativo em "Ideias científicas não emergem no vazio" (primeiro parágrafo) confere à ideia expressa no período valor de uma verdade absoluta.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,8,$q$Língua Portuguesa$q$,$q$Na oração "Uma nova ideia pode se aproximar mais da verdade" (segundo parágrafo), o emprego do pronome "se" entre as formas verbais "pode" e "aproximar" é típico de textos informais, de modo que, para garantir a formalidade e a correção gramatical do texto, tal pronome deveria ser deslocado para a posição enclítica à forma verbal "aproximar".$q$,$q$Na oração "Uma nova ideia pode se aproximar mais da verdade" (segundo parágrafo), o emprego do pronome "se" entre as formas verbais "pode" e "aproximar" é típico de textos informais, de modo que, para garantir a formalidade e a correção gramatical do texto, tal pronome deveria ser deslocado para a posição enclítica à forma verbal "aproximar".$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,9,$q$Língua Portuguesa$q$,$q$Na oração "para tornar mais rápido o atendimento telefônico em casos de emergência por engasgo" (primeiro parágrafo), a flexão da forma verbal "tornar" no plural — tornarem — prejudicaria tanto a correção gramatical quanto o sentido original do texto.$q$,$q$Na oração "para tornar mais rápido o atendimento telefônico em casos de emergência por engasgo" (primeiro parágrafo), a flexão da forma verbal "tornar" no plural — tornarem — prejudicaria tanto a correção gramatical quanto o sentido original do texto.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,10,$q$Língua Portuguesa$q$,$q$No último parágrafo do texto, os termos "do Voluntariado" e "Lucas" desempenham funções sintáticas distintas.$q$,$q$No último parágrafo do texto, os termos "do Voluntariado" e "Lucas" desempenham funções sintáticas distintas.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,11,$q$Língua Portuguesa$q$,$q$A substituição do termo preposicionado "de morte", em "risco de morte iminente" (segundo parágrafo), por mortal prejudicaria tanto as relações sintáticas estabelecidas no trecho quanto seu sentido original.$q$,$q$A substituição do termo preposicionado "de morte", em "risco de morte iminente" (segundo parágrafo), por mortal prejudicaria tanto as relações sintáticas estabelecidas no trecho quanto seu sentido original.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,12,$q$Língua Portuguesa$q$,$q$O texto caracteriza-se como predominantemente expositivo.$q$,$q$O texto caracteriza-se como predominantemente expositivo.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,13,$q$Língua Portuguesa$q$,$q$O período que inicia o primeiro parágrafo encerra a informação nuclear do texto.$q$,$q$O período que inicia o primeiro parágrafo encerra a informação nuclear do texto.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,14,$q$Língua Portuguesa$q$,$q$De acordo com o texto, os medos do ser humano permanecem os mesmos desde a época de seus ancestrais, mas passaram por processo gradativo de adaptação para a proteção da espécie contra novos perigos.$q$,$q$De acordo com o texto, os medos do ser humano permanecem os mesmos desde a época de seus ancestrais, mas passaram por processo gradativo de adaptação para a proteção da espécie contra novos perigos.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,15,$q$Língua Portuguesa$q$,$q$O fato de as pessoas reagirem de modos diferentes a diferentes estímulos atemorizantes é apresentado no terceiro parágrafo como um possível contra-argumento à tese de que medos e fobias compõem uma lista universal.$q$,$q$O fato de as pessoas reagirem de modos diferentes a diferentes estímulos atemorizantes é apresentado no terceiro parágrafo como um possível contra-argumento à tese de que medos e fobias compõem uma lista universal.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,16,$q$Língua Portuguesa$q$,$q$Embora reconheça que a falta de medo de certos elementos gera problema de segurança pública na sociedade urbana contemporânea, o autor opõe-se à ideia de que a tentativa de incutir medo "no coração dos cidadãos" constitua estratégia para resolver essa questão.$q$,$q$Embora reconheça que a falta de medo de certos elementos gera problema de segurança pública na sociedade urbana contemporânea, o autor opõe-se à ideia de que a tentativa de incutir medo "no coração dos cidadãos" constitua estratégia para resolver essa questão.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,17,$q$Língua Portuguesa$q$,$q$No segmento "quando se perguntou a estudantes de séries iniciais em Chicago o que eles mais temiam" (último parágrafo), o emprego do vocábulo "se" indica que o sujeito da primeira oração é indeterminado.$q$,$q$No segmento "quando se perguntou a estudantes de séries iniciais em Chicago o que eles mais temiam" (último parágrafo), o emprego do vocábulo "se" indica que o sujeito da primeira oração é indeterminado.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,18,$q$Língua Portuguesa$q$,$q$No segmento "Há pessoas que realmente desmaiam ao ver sangue" (terceiro parágrafo), a oração "Há pessoas" poderia ser reescrita como Existem pessoas, sem prejuízo dos sentidos e da correção gramatical do texto; entretanto as relações sintáticas estabelecidas na oração seriam alteradas, pois o termo "pessoas" deixaria de exercer a função de complemento verbal e passaria a funcionar como sujeito da oração.$q$,$q$No segmento "Há pessoas que realmente desmaiam ao ver sangue" (terceiro parágrafo), a oração "Há pessoas" poderia ser reescrita como Existem pessoas, sem prejuízo dos sentidos e da correção gramatical do texto; entretanto as relações sintáticas estabelecidas na oração seriam alteradas, pois o termo "pessoas" deixaria de exercer a função de complemento verbal e passaria a funcionar como sujeito da oração.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,19,$q$Língua Portuguesa$q$,$q$Diferentemente do medo de armas de fogo, o medo de cobra é caracterizado no texto como algo que independe de experiência prévia, é constante, ocorre em diferentes culturas e tem base biológica.$q$,$q$Diferentemente do medo de armas de fogo, o medo de cobra é caracterizado no texto como algo que independe de experiência prévia, é constante, ocorre em diferentes culturas e tem base biológica.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,20,$q$Língua Portuguesa$q$,$q$No trecho "as pessoas reagem de modos diferentes a diferentes estímulos atemorizantes" (terceiro parágrafo), o vocábulo "atemorizantes" é empregado com o mesmo sentido de temerários.$q$,$q$No trecho "as pessoas reagem de modos diferentes a diferentes estímulos atemorizantes" (terceiro parágrafo), o vocábulo "atemorizantes" é empregado com o mesmo sentido de temerários.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,21,$q$Língua Portuguesa$q$,$q$No texto, tanto a expressão "presumivelmente uma reação que minimizaria uma perda adicional de sangue" (final do terceiro parágrafo) quanto a expressão "perigos improváveis naquela cidade" (final do último parágrafo) exercem a função sintática de aposto.$q$,$q$No texto, tanto a expressão "presumivelmente uma reação que minimizaria uma perda adicional de sangue" (final do terceiro parágrafo) quanto a expressão "perigos improváveis naquela cidade" (final do último parágrafo) exercem a função sintática de aposto.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,22,$q$Língua Portuguesa$q$,$q$Seria mantida a correção gramatical do texto, embora sua coerência fosse prejudicada, caso a forma verbal presente no trecho "a maioria dos outros medos representa perigos evidentes" (segundo parágrafo) fosse flexionada no plural — representam.$q$,$q$Seria mantida a correção gramatical do texto, embora sua coerência fosse prejudicada, caso a forma verbal presente no trecho "a maioria dos outros medos representa perigos evidentes" (segundo parágrafo) fosse flexionada no plural — representam.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,23,$q$Língua Portuguesa$q$,$q$No primeiro parágrafo, os vocábulos "medo", em "São o que mais comumente provoca medo e asco em estudantes universitários cujas fobias foram estudadas", e "cautela", em "Mesmo nas culturas que veneram as serpentes, as pessoas as tratam com muita cautela", são empregados como sinônimos.$q$,$q$No primeiro parágrafo, os vocábulos "medo", em "São o que mais comumente provoca medo e asco em estudantes universitários cujas fobias foram estudadas", e "cautela", em "Mesmo nas culturas que veneram as serpentes, as pessoas as tratam com muita cautela", são empregados como sinônimos.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,24,$q$Língua Portuguesa$q$,$q$No último parágrafo, os vocábulos "são", em "medos são adaptações", e "vão", em "geralmente em vão", pertencem a classes de palavras distintas.$q$,$q$No último parágrafo, os vocábulos "são", em "medos são adaptações", e "vão", em "geralmente em vão", pertencem a classes de palavras distintas.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,25,$q$Língua Portuguesa$q$,$q$O termo "aterrorizados", em "chimpanzés nascidos em cativeiro gritam aterrorizados" (primeiro parágrafo), exerce a mesma função sintática que o termo "óbvia", em "A linha comum é óbvia" (segundo parágrafo).$q$,$q$O termo "aterrorizados", em "chimpanzés nascidos em cativeiro gritam aterrorizados" (primeiro parágrafo), exerce a mesma função sintática que o termo "óbvia", em "A linha comum é óbvia" (segundo parágrafo).$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,26,$q$Língua Portuguesa$q$,$q$No trecho "Deveríamos ter medo de armas de fogo, de dirigir em alta velocidade, de andar de carro sem cinto de segurança, de fluido de isqueiro e do secador de cabelo perto da banheira, e não de cobras" (último parágrafo), a substituição da vírgula empregada imediatamente após "banheira" por ponto e vírgula e a supressão do termo "e", em "e não de cobras", manteriam a correção gramatical e a coerência das ideias do texto.$q$,$q$No trecho "Deveríamos ter medo de armas de fogo, de dirigir em alta velocidade, de andar de carro sem cinto de segurança, de fluido de isqueiro e do secador de cabelo perto da banheira, e não de cobras" (último parágrafo), a substituição da vírgula empregada imediatamente após "banheira" por ponto e vírgula e a supressão do termo "e", em "e não de cobras", manteriam a correção gramatical e a coerência das ideias do texto.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,27,$q$Língua Inglesa$q$,$q$In the fragment "police have carefully circumscribed roles that require close and positive relations with ordinary citizens" (second paragraph), "ordinary citizens" are people who represent the average citizen in a democratic society.$q$,$q$In the fragment "police have carefully circumscribed roles that require close and positive relations with ordinary citizens" (second paragraph), "ordinary citizens" are people who represent the average citizen in a democratic society.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,28,$q$Língua Inglesa$q$,$q$The authors oppose two different roles of the police, each one related to a specific way political power can be exercised in a society.$q$,$q$The authors oppose two different roles of the police, each one related to a specific way political power can be exercised in a society.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,29,$q$Língua Inglesa$q$,$q$It is correct to infer from the first paragraph of the text that investigating common crimes committed against citizens is not part of the police's duties in autocratic nations.$q$,$q$It is correct to infer from the first paragraph of the text that investigating common crimes committed against citizens is not part of the police's duties in autocratic nations.$q$,'C',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
(2026,30,$q$Língua Inglesa$q$,$q$According to the text, the limitations imposed on police work in democratic societies are motivated by the fact that the use of arms almost never happens.$q$,$q$According to the text, the limitations imposed on police work in democratic societies are motivated by the fact that the use of arms almost never happens.$q$,'E',1,'under_review',true,false,$q$Transcrição verbatim do caderno de provas CD-PLF 2026 (Conhecimentos Gerais); gabarito conferido no gabarito oficial definitivo.$q$),
